"""Reusable stages, modules, and higher-level recipes."""

from ..modules import ModuleSpec, module_from_block, mount_module
from ..recipes import (
    arpeggio_quantized_stage,
    bypass_wrapper,
    convolver_controlled_stage,
    dial_label_cell,
    dry_wet_stage,
    euclidean_sequencer_stage,
    gain_controlled_stage,
    generative_midi_stage,
    grain_playback_controlled,
    lfo_matrix_distribute,
    mc_poly_spine,
    midi_learn_macro_assignment,
    midi_note_gate,
    parametric_eq_band_backend,
    poly_midi_gate,
    sample_drop_target,
    sidechain_compressor_recipe,
    spectral_gate_stage,
    stacked_panels,
    stereo_width_stage,
    switchable_bank,
    tempo_synced_delay,
    transport_sync_lfo_recipe,
    two_panel_strip,
)
from ..stages import Stage, StageResult, stage_result

__all__ = [
    "Stage",
    "StageResult",
    "stage_result",
    "ModuleSpec",
    "module_from_block",
    "mount_module",
    "gain_controlled_stage",
    "parametric_eq_band_backend",
    "dry_wet_stage",
    "stereo_width_stage",
    "tempo_synced_delay",
    "midi_note_gate",
    "convolver_controlled_stage",
    "sidechain_compressor_recipe",
    "lfo_matrix_distribute",
    "spectral_gate_stage",
    "arpeggio_quantized_stage",
    "grain_playback_controlled",
    "poly_midi_gate",
    "mc_poly_spine",
    "two_panel_strip",
    "dial_label_cell",
    "stacked_panels",
    "bypass_wrapper",
    "switchable_bank",
    "transport_sync_lfo_recipe",
    "midi_learn_macro_assignment",
    "generative_midi_stage",
    "euclidean_sequencer_stage",
    "sample_drop_target",
]
