"""Shared export metadata for lazy package namespaces."""

from __future__ import annotations


def _dedupe(*groups: list[str]) -> list[str]:
    seen: set[str] = set()
    items: list[str] = []
    for group in groups:
        for item in group:
            if item not in seen:
                seen.add(item)
                items.append(item)
    return items


CORE_EXPORTS = [
    "Device",
    "AudioEffect",
    "Instrument",
    "MidiEffect",
    "Subpatcher",
    "GraphContainer",
    "BoxRef",
    "OutletRef",
    "InletRef",
    "ParameterSpec",
    "PARAM_HIDDEN",
    "PARAM_VISIBLE",
    "LIVE_NATIVE_INT_MIN",
    "LIVE_NATIVE_INT_MAX",
    "Asset",
    "PatcherProfile",
    "DEFAULT_PATCHER_PROFILE",
    "JsuiContractError",
    "find_jsui_contract_issues",
    "validate_jsui_contract",
    "Stage",
    "StageResult",
    "stage_result",
    "ModuleSpec",
    "module_from_block",
    "mount_module",
    "ValidationIssue",
    "BuildValidationError",
    "format_validation_issues",
    "lint_graph",
    "Row",
    "Column",
    "Grid",
    "build_amxd",
    "write_amxd",
    "newobj",
    "patchline",
    "AUDIO_EFFECT",
    "INSTRUMENT",
    "MIDI_EFFECT",
    "user_library",
    "device_output_path",
]

UI_WIDGET_EXPORTS = [
    "panel",
    "dial",
    "tab",
    "toggle",
    "comment",
    "scope",
    "meter",
    "menu",
    "number_box",
    "slider",
    "button",
    "live_text",
    "fpic",
    "live_gain",
    "multislider",
    "jsui",
    "v8ui",
    "adsrui",
    "live_drop",
    "bpatcher",
    "swatch",
    "textedit",
    "live_step",
    "live_grid",
    "live_line",
    "live_arrows",
    "rslider",
    "kslider",
    "textbutton",
    "umenu",
    "radiogroup",
    "nodes",
    "matrixctrl",
    "ubutton",
    "nslider",
]

UI_THEME_EXPORTS = [
    "Theme",
    "MIDNIGHT",
    "WARM",
    "COOL",
    "LIGHT",
    "FOREST",
    "VIOLET",
    "SOLAR",
    "LOFI",
    "SYNTHWAVE",
    "INDUSTRIAL",
]

ENGINE_EXPORTS = [
    "xy_pad_js",
    "XY_PAD_INLETS",
    "XY_PAD_OUTLETS",
    "piano_roll_js",
    "PIANO_ROLL_INLETS",
    "PIANO_ROLL_OUTLETS",
    "velocity_curve_display_js",
    "VELOCITY_CURVE_INLETS",
    "VELOCITY_CURVE_OUTLETS",
    "wavetable_display_js",
    "WAVETABLE_DISPLAY_INLETS",
    "WAVETABLE_DISPLAY_OUTLETS",
    "resonance_bank_display_js",
    "RESONANCE_BANK_INLETS",
    "RESONANCE_BANK_OUTLETS",
    "sidechain_display_js",
    "SIDECHAIN_DISPLAY_INLETS",
    "SIDECHAIN_DISPLAY_OUTLETS",
    "spectral_display_js",
    "SPECTRAL_DISPLAY_INLETS",
    "SPECTRAL_DISPLAY_OUTLETS",
    "peaking_eq_display_js",
    "PEAKING_EQ_DISPLAY_INLETS",
    "PEAKING_EQ_DISPLAY_OUTLETS",
    "step_grid_display_js",
    "STEP_GRID_DISPLAY_INLETS",
    "STEP_GRID_DISPLAY_OUTLETS",
    "grain_display_js",
    "GRAIN_DISPLAY_INLETS",
    "GRAIN_DISPLAY_OUTLETS",
    "grid_sequencer_display_js",
    "GRID_SEQ_INLETS",
    "GRID_SEQ_OUTLETS",
    "wavetable_editor_js",
    "WAVETABLE_EDITOR_INLETS",
    "WAVETABLE_EDITOR_OUTLETS",
    "spectral_vocoder_display_js",
    "SPECTRAL_VOCODER_INLETS",
    "SPECTRAL_VOCODER_OUTLETS",
]

UI_EXPORTS = _dedupe(UI_WIDGET_EXPORTS, UI_THEME_EXPORTS, ENGINE_EXPORTS)

DSP_EXPORTS = [
    "stereo_io",
    "gain_stage",
    "dry_wet_mix",
    "ms_encode_decode",
    "dc_block",
    "saturation",
    "selector",
    "highpass_filter",
    "lowpass_filter",
    "onepole_filter",
    "signal_divide",
    "tilt_eq",
    "crossover_3band",
    "envelope_follower",
    "delay_line",
    "lfo",
    "comb_resonator",
    "feedback_delay",
    "tremolo",
    "param_smooth",
    "bandpass_filter",
    "notch_filter",
    "highshelf_filter",
    "lowshelf_filter",
    "compressor",
    "limiter",
    "noise_source",
    "tempo_sync",
    "live_remote",
    "live_param_signal",
    "adsr_envelope",
    "peaking_eq",
    "allpass_filter",
    "gate_expander",
    "sidechain_detect",
    "sample_and_hold",
    "multiband_compressor",
    "reverb_network",
    "notein",
    "noteout",
    "ctlin",
    "ctlout",
    "velocity_curve",
    "transpose",
    "midi_thru",
    "wavetable_osc",
    "buffer_load",
    "arpeggiator",
    "chord",
    "pitch_quantize",
    "lookahead_envelope_follower",
    "fdn_reverb",
    "spectral_gate",
    "spectral_gate_subpatcher",
    "vocoder",
    "mc_expand",
    "mc_collapse",
    "note_expression_decode",
    "transport_lfo",
    "pitchbend_in",
    "modwheel_in",
    "aftertouch_in",
    "xfade_matrix",
    "midi_learn_chain",
    "convolver",
    "program_change_in",
    "bank_select_in",
    "sample_and_hold_triggered",
    "bitcrusher",
    "poly_voices",
    "spectral_crossover",
    "spectral_crossover_subpatcher",
    "grain_cloud",
    "auto_gain",
    "midi_clock_out",
    "macromap",
    "stft_phase_vocoder",
    "phase_vocoder_subpatcher",
    "spectrum_band_extract",
    "morphing_lfo",
    "midi_clock_in",
    "sidechain_routing",
    "random_walk",
    "matrix_mixer",
    "cv_recorder",
    "quantize_time",
    "macro_modulation_matrix",
    "analog_oscillator_bank",
    "lfsr_generator",
    "cv_smooth_lag",
    "send_signal",
    "receive_signal",
    "send_msg",
    "receive_msg",
    "loadbang",
    "scale_range",
    "groove_player",
    "coll_store",
    "dict_store",
    "pattr_system",
    "midi_channel_filter",
    "gen_codebox",
    "mc_gain_stage",
    "mc_mixer",
    "mc_selector",
]

LIVE_API_EXPORTS = [
    "live_object_path",
    "live_parameter_probe",
    "live_observer",
    "live_state_observer",
    "live_set_control",
    "live_thisdevice",
    "device_active_state",
]

SHELL_EXPORTS = [
    "controller_surface_shell",
    "sequencer_dispatch_shell",
    "embedded_ui_shell",
    "embedded_ui_shell_v2",
    "named_bus_router",
    "init_dispatch_chain",
    "poly_shell",
    "poly_shell_bank",
]

PRESET_EXPORTS = [
    "preset_manager",
    "add_preset_buttons",
]

BRIDGE_EXPORTS = [
    "BRIDGE_PROTOCOL_VERSION",
    "DEFAULT_BRIDGE_PORT",
    "BRIDGE_RUNTIME_FILENAME",
    "BRIDGE_SERVER_FILENAME",
    "BRIDGE_SCHEMA_FILENAME",
    "BRIDGE_CAPABILITIES",
    "OBJECT_ATTR_ALLOWLIST",
    "BOX_ATTR_ALLOWLIST",
    "DISALLOWED_CREATE_CLASSES",
    "BRIDGE_COMMANDS",
    "bridge_schema",
    "bridge_runtime_js",
    "bridge_server_js",
    "enable_livemcp_bridge",
    "build_livemcp_bridge_demo",
]

LIVE_EXPORTS = _dedupe(
    ["user_library", "device_output_path"],
    LIVE_API_EXPORTS,
    SHELL_EXPORTS,
    PRESET_EXPORTS,
    BRIDGE_EXPORTS,
)

ROOT_RECIPE_EXPORTS = [
    "gain_controlled_stage",
    "dry_wet_stage",
    "tempo_synced_delay",
    "midi_note_gate",
    "convolver_controlled_stage",
    "sidechain_compressor_recipe",
    "lfo_matrix_distribute",
    "spectral_gate_stage",
    "arpeggio_quantized_stage",
    "grain_playback_controlled",
    "poly_midi_gate",
    "transport_sync_lfo_recipe",
    "midi_learn_macro_assignment",
]

BUILDER_RECIPE_EXPORTS = _dedupe(
    [
        "parametric_eq_band_backend",
    ],
    ROOT_RECIPE_EXPORTS,
)

REVERSE_EXPORTS = [
    "read_amxd",
    "snapshot_from_device",
    "snapshot_from_amxd",
    "snapshot_from_bridge_payload",
    "snapshot_to_json",
    "write_snapshot",
    "load_snapshot",
    "analyze_snapshot",
    "extract_embedded_patcher_snapshots",
    "extract_controller_shell_candidates",
    "extract_embedded_ui_shell_candidates",
    "extract_named_bus_router_candidates",
    "extract_init_dispatch_chain_candidates",
    "extract_state_bundle_router_candidates",
    "extract_sample_buffer_candidates",
    "extract_gen_processing_candidates",
    "extract_presentation_widget_cluster_candidates",
    "extract_poly_shell_candidates",
    "extract_poly_shell_bank_candidates",
    "extract_poly_editor_bank_candidates",
    "extract_behavior_hints",
    "extract_mapping_behavior_traces",
    "extract_mapping_semantic_candidates",
    "extract_mapping_workflow_candidates",
    "extract_first_party_api_rig_candidates",
    "extract_first_party_abstraction_host_candidates",
    "extract_first_party_abstraction_family_candidates",
    "extract_building_block_candidates",
    "extract_live_api_normalization_candidates",
    "detect_snapshot_patterns",
    "detect_snapshot_recipes",
    "detect_snapshot_motifs",
    "extract_parameter_specs",
    "extract_snapshot_knowledge",
    "generate_python_from_snapshot",
    "generate_python_from_amxd",
    "generate_python_from_device",
    "generate_python_from_bridge_payload",
    "generate_builder_python_from_snapshot",
    "generate_builder_python_from_amxd",
    "generate_builder_python_from_device",
    "generate_builder_python_from_bridge_payload",
    "generate_optimized_python_from_snapshot",
    "generate_optimized_python_from_amxd",
    "generate_optimized_python_from_device",
    "generate_optimized_python_from_bridge_payload",
    "generate_semantic_python_from_snapshot",
    "generate_semantic_python_from_amxd",
    "generate_semantic_python_from_device",
    "generate_semantic_python_from_bridge_payload",
]

ANALYSIS_EXPORTS = [
    "classify_corpus_source_metadata",
    "analyze_amxd_file",
    "analyze_amxd_corpus",
    "rank_reverse_candidates",
    "rank_reverse_candidate_families",
    "build_reverse_candidate_family_profile",
    "build_reverse_candidate_family_profiles",
    "build_source_lane_profiles",
    "source_lane_profiles_markdown",
    "build_reference_device_dossier",
    "build_reference_device_dossiers",
    "reference_device_dossiers_markdown",
    "rank_mapping_candidates",
    "build_mapping_lane_report",
    "mapping_lane_report_markdown",
    "write_mapping_lane_report",
    "build_mapping_product_brief",
    "build_mapping_product_brief_from_path",
    "build_mapping_product_briefs",
    "mapping_product_brief_markdown",
    "mapping_product_briefs_markdown",
    "write_mapping_product_brief",
    "write_mapping_product_briefs",
    "build_corpus_comparison",
    "corpus_comparison_markdown",
    "corpus_report_markdown",
    "family_profile_markdown",
    "write_corpus_report",
    "write_family_profile",
    "build_corpus_manifest",
    "load_corpus_manifest",
    "write_corpus_manifest",
    "select_corpus_manifest_entries",
    "run_corpus_fixture",
    "write_corpus_fixture_results",
]

ROOT_NAMESPACE_EXPORTS = [
    "builder",
    "reverse",
    "analysis",
    "bridge",
    "authoring",
    "live",
    "reverse_snapshot",
    "reverse_patterns",
    "reverse_analysis",
    "reverse_codegen",
]

ROOT_ALL = _dedupe(
    ROOT_NAMESPACE_EXPORTS,
    CORE_EXPORTS,
    UI_EXPORTS,
    DSP_EXPORTS,
    LIVE_EXPORTS,
    REVERSE_EXPORTS,
    ANALYSIS_EXPORTS,
    ROOT_RECIPE_EXPORTS,
)

BUILDER_ALL = _dedupe(
    ["core", "ui", "dsp", "live", "recipes"],
    CORE_EXPORTS,
    UI_EXPORTS,
    DSP_EXPORTS,
    LIVE_EXPORTS,
    BUILDER_RECIPE_EXPORTS,
)

AUTHORING_ALL = _dedupe(
    CORE_EXPORTS,
    UI_EXPORTS,
    DSP_EXPORTS,
    BUILDER_RECIPE_EXPORTS,
)

ROOT_NAMESPACE_MODULES = {
    "analysis": "m4l_builder.analysis",
    "bridge": "m4l_builder.bridge",
    "builder": "m4l_builder.builder",
    "reverse": "m4l_builder.reverse_api",
    "authoring": "m4l_builder.authoring",
    "live": "m4l_builder.live",
    "reverse_snapshot": "m4l_builder.reverse_snapshot",
    "reverse_patterns": "m4l_builder.reverse_patterns",
    "reverse_analysis": "m4l_builder.reverse_analysis",
    "reverse_codegen": "m4l_builder.reverse_codegen",
}

ROOT_EXPORT_GROUPS = (
    ("m4l_builder.builder.core", CORE_EXPORTS),
    ("m4l_builder.builder.ui", UI_EXPORTS),
    ("m4l_builder.builder.dsp", DSP_EXPORTS),
    ("m4l_builder.builder.live", LIVE_EXPORTS),
    ("m4l_builder.builder.recipes", ROOT_RECIPE_EXPORTS),
    ("m4l_builder.reverse_api", REVERSE_EXPORTS),
    ("m4l_builder.analysis_api", ANALYSIS_EXPORTS),
)

BUILDER_NAMESPACE_MODULES = {
    "core": "m4l_builder.builder.core",
    "ui": "m4l_builder.builder.ui",
    "dsp": "m4l_builder.builder.dsp",
    "live": "m4l_builder.builder.live",
    "recipes": "m4l_builder.builder.recipes",
}

BUILDER_EXPORT_GROUPS = (
    ("m4l_builder.builder.core", CORE_EXPORTS),
    ("m4l_builder.builder.ui", UI_EXPORTS),
    ("m4l_builder.builder.dsp", DSP_EXPORTS),
    ("m4l_builder.builder.live", LIVE_EXPORTS),
    ("m4l_builder.builder.recipes", BUILDER_RECIPE_EXPORTS),
)
