"""Reverse-engineering namespace."""

from .reverse import (
    analyze_snapshot,
    detect_snapshot_motifs,
    detect_snapshot_patterns,
    detect_snapshot_recipes,
    extract_behavior_hints,
    extract_building_block_candidates,
    extract_embedded_patcher_snapshots,
    extract_embedded_ui_shell_candidates,
    extract_first_party_abstraction_family_candidates,
    extract_first_party_abstraction_host_candidates,
    extract_first_party_api_rig_candidates,
    extract_gen_processing_candidates,
    extract_init_dispatch_chain_candidates,
    extract_live_api_normalization_candidates,
    extract_mapping_behavior_traces,
    extract_mapping_semantic_candidates,
    extract_mapping_workflow_candidates,
    extract_named_bus_router_candidates,
    extract_parameter_specs,
    extract_poly_editor_bank_candidates,
    extract_poly_shell_bank_candidates,
    extract_poly_shell_candidates,
    extract_presentation_widget_cluster_candidates,
    extract_sample_buffer_candidates,
    extract_snapshot_knowledge,
    extract_state_bundle_router_candidates,
    generate_builder_python_from_amxd,
    generate_builder_python_from_bridge_payload,
    generate_builder_python_from_device,
    generate_builder_python_from_snapshot,
    generate_optimized_python_from_amxd,
    generate_optimized_python_from_bridge_payload,
    generate_optimized_python_from_device,
    generate_optimized_python_from_snapshot,
    generate_python_from_amxd,
    generate_python_from_bridge_payload,
    generate_python_from_device,
    generate_python_from_snapshot,
    generate_semantic_python_from_amxd,
    generate_semantic_python_from_bridge_payload,
    generate_semantic_python_from_device,
    generate_semantic_python_from_snapshot,
    load_snapshot,
    read_amxd,
    snapshot_from_amxd,
    snapshot_from_bridge_payload,
    snapshot_from_device,
    snapshot_to_json,
    write_snapshot,
)

__all__ = [name for name in globals() if not name.startswith("_")]
