"""Ballistics curve — compressor attack/release step-response display.

A compact time-domain readout of the gain-reduction envelope: a step input
arrives, GR engages over the ATTACK time, holds, then the input drops and GR
recovers over the RELEASE time. The curve reshapes live as the knobs move —
fast attack = sharp entry, slow attack = gradual ramp; short release = quick
recovery, long release = long tail. Hold depth scales with RATIO and the
onset corner softens with KNEE. Display-only (no gestures, no outlets): the
inbound set_* messages drive redraws, so no Task/clock is needed.

Messages in (inlet 0):
    set_attack <ms>     attack time (one-pole tau), default 10
    set_release <ms>    release time (one-pole tau), default 120
    set_knee <db>       knee width — softens the onset corner, default 6
    set_ratio <r>       compression ratio — sets the hold depth, default 2

The envelope is a MODEL (not live audio): attack/release each settle over
~3 tau (95%), laid out on a proportional time axis so both phases are always
visible across the full knob ranges. Depth = 12 dB-over-threshold * (1 -
1/ratio), drawn against an 18 dB full-scale so it reads consistently.
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)

BALLISTICS_CURVE_INLETS = 1
BALLISTICS_CURVE_OUTLETS = 0

__all__ = [
    "BALLISTICS_CURVE_INLETS",
    "BALLISTICS_CURVE_OUTLETS",
    "ballistics_curve_js",
]


def ballistics_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    curve_color="0.95, 0.55, 0.25, 1.0",
    fill_color="0.95, 0.55, 0.25, 0.22",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    attack_ms=10.0,
    release_ms=120.0,
    knee_db=6.0,
    ratio=2.0,
    full_scale_db=18.0,
):
    """Return JavaScript source for the attack/release step-response display."""
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        curve_color=curve_color,
        fill_color=fill_color,
        grid_color=grid_color,
        text_color=text_color,
        attack_ms=attack_ms,
        release_ms=release_ms,
        knee_db=knee_db,
        ratio=ratio,
        full_scale_db=full_scale_db,
    )


_JS_TEMPLATE = Template("""\
// Ballistics Curve Display - generated by m4l-builder
// ES5 compatible; display-only (no gesture outlets).

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 0;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var CURVE_CLR  = [$curve_color];
var FILL_CLR   = [$fill_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];

var attack_ms = $attack_ms;
var release_ms = $release_ms;
var knee_db = $knee_db;
var ratio = $ratio;
var FULL_DB = $full_scale_db;

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

function plot_l() { return 5; }
function plot_r() { return mgraphics.size[0] - 5; }
function plot_t() { return 11; }
function plot_b() { return mgraphics.size[1] - 10; }
function plot_w() { var d = plot_r() - plot_l(); return d > 1 ? d : 1; }
function plot_h() { var d = plot_b() - plot_t(); return d > 1 ? d : 1; }

// Representative GR depth: a 12 dB-over-threshold step through the ratio.
function target_gr() {
    return 12.0 * (1.0 - 1.0 / Math.max(ratio, 1.0));
}

// Phase spans (ms): attack/release each settle in ~3 tau (95%); a
// proportional hold keeps both phases on screen across the full ranges.
function spans() {
    var a = Math.max(attack_ms, 0.05) * 3.0;
    var r = Math.max(release_ms, 5.0) * 3.0;
    var hold = 0.30 * (a + r);
    return { a: a, hold: hold, r: r, T: a + hold + r };
}

// Gain reduction (dB, >= 0) at time t (ms) along the modeled envelope.
function env_at(t, sp, tgt) {
    if (t < sp.a) {
        return tgt * (1.0 - Math.exp(-3.0 * t / sp.a));
    }
    var t2 = t - sp.a;
    if (t2 < sp.hold) return tgt;
    var t3 = t2 - sp.hold;
    return tgt * Math.exp(-3.0 * t3 / sp.r);
}

function gr_to_y(gr) {
    return plot_t() + clamp(gr, 0.0, FULL_DB) / FULL_DB * plot_h();
}

function fmt_ms(v) {
    if (v < 10.0) return (Math.round(v * 10) / 10) + "ms";
    return Math.round(v) + "ms";
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, y, gr;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    var sp = spans();
    var tgt = target_gr();

    // Horizontal GR gridlines every 6 dB.
    mgraphics.set_line_width(1.0);
    var gd;
    for (gd = 6; gd <= FULL_DB - 0.01; gd += 6) {
        y = gr_to_y(gd);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(plot_l(), y);
        mgraphics.line_to(plot_r(), y);
        mgraphics.stroke();
    }

    // Phase boundary ticks (attack end, release start) as faint verticals.
    var xa = plot_l() + (sp.a / sp.T) * plot_w();
    var xr = plot_l() + ((sp.a + sp.hold) / sp.T) * plot_w();
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.move_to(xa, plot_t()); mgraphics.line_to(xa, plot_b()); mgraphics.stroke();
    mgraphics.move_to(xr, plot_t()); mgraphics.line_to(xr, plot_b()); mgraphics.stroke();

    // Envelope: filled area from the 0-GR line down to the curve, + stroke.
    var N = 128;
    var y0 = gr_to_y(0.0);
    // Fill opacity scales with the GR depth: a light squeeze reads subtle,
    // a heavy one bold (the "intensity" cue).
    var fill_intensity = clamp(tgt / FULL_DB, 0.0, 1.0);
    mgraphics.set_source_rgba(FILL_CLR[0], FILL_CLR[1], FILL_CLR[2],
                              0.10 + fill_intensity * 0.34);
    mgraphics.move_to(plot_l(), y0);
    for (i = 0; i <= N; i++) {
        x = plot_l() + (i / N) * plot_w();
        gr = env_at((i / N) * sp.T, sp, tgt);
        mgraphics.line_to(x, gr_to_y(gr));
    }
    mgraphics.line_to(plot_r(), y0);
    mgraphics.close_path();
    mgraphics.fill();

    mgraphics.set_source_rgba(CURVE_CLR);
    mgraphics.set_line_width(1.6);
    for (i = 0; i <= N; i++) {
        x = plot_l() + (i / N) * plot_w();
        gr = env_at((i / N) * sp.T, sp, tgt);
        y = gr_to_y(gr);
        if (i === 0) mgraphics.move_to(x, y); else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    // Phase labels.
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(7.0);
    mgraphics.set_source_rgba(TEXT_CLR);
    var al = "ATK " + fmt_ms(attack_ms);
    mgraphics.move_to(plot_l() + 2, plot_b() - 2);
    mgraphics.show_text(al);
    var rl = "REL " + fmt_ms(release_ms);
    mgraphics.move_to(plot_r() - (rl.length * 4.4 + 2), plot_b() - 2);
    mgraphics.show_text(rl);
}

// ── Message handlers (display-only; each just restyles + redraws) ──────
function set_attack(v) { if (isFinite(v)) { attack_ms = v; mgraphics.redraw(); } }
function set_release(v) { if (isFinite(v)) { release_ms = v; mgraphics.redraw(); } }
function set_knee(v) { if (isFinite(v)) { knee_db = v; mgraphics.redraw(); } }
function set_ratio(v) { if (isFinite(v)) { ratio = v; mgraphics.redraw(); } }

function onresize(w, h) { mgraphics.redraw(); }
""")
