"""Ballistics curve — compressor attack/release step-response display.

A compact time-domain readout of the gain-reduction envelope: a step input
arrives, GR engages over the ATTACK time, holds, then the input drops and GR
recovers over the RELEASE time. The curve reshapes live as the knobs move —
fast attack = sharp entry, slow attack = gradual ramp; short release = quick
recovery, long release = long tail. Hold depth scales with RATIO and the
onset corner softens with KNEE. Inbound set_* messages drive redraws, so no
Task/clock is needed. With interactive=True it also becomes a 2-zone drag pad
(left half = attack, right half = release) emitting on outlet 0.

Messages in (inlet 0):
    set_attack <ms>     attack time (one-pole tau), default 10
    set_release <ms>    release time (one-pole tau), default 120
    set_knee <db>       knee width — softens the onset corner, default 6
    set_ratio <r>       compression ratio — sets the hold depth, default 2
    set_live_gr <db>    live gain reduction (>=0) — a cyan depth line rides the
                        modeled envelope, so the inset breathes with the signal

Messages out (outlet 0; interactive=True only, on user drag — no-echo):
    attack <ms>         left-half horizontal drag (log-mapped over [min,max])
    release <ms>        right-half horizontal drag

The envelope is a MODEL (not live audio): attack/release each settle over
~3 tau (95%), laid out on a proportional time axis so both phases are always
visible across the full knob ranges. Depth = 12 dB-over-threshold * (1 -
1/ratio), drawn against an 18 dB full-scale so it reads consistently.
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)

BALLISTICS_CURVE_INLETS = 1
BALLISTICS_CURVE_OUTLETS = 1

__all__ = [
    "BALLISTICS_CURVE_INLETS",
    "BALLISTICS_CURVE_OUTLETS",
    "ballistics_curve_js",
]


def ballistics_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    curve_color="0.95, 0.55, 0.25, 1.0",
    fill_color="0.95, 0.55, 0.25, 0.22",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    attack_ms=10.0,
    release_ms=120.0,
    knee_db=6.0,
    ratio=2.0,
    full_scale_db=18.0,
    interactive=False,
    attack_min_ms=0.05,
    attack_max_ms=250.0,
    release_min_ms=5.0,
    release_max_ms=2000.0,
    reset_attack_ms=None,
    reset_release_ms=None,
):
    """Return JavaScript source for the attack/release step-response display.

    With interactive=True the curve becomes a two-zone drag pad: dragging in
    the left half sets ATTACK, the right half sets RELEASE (matching the
    bottom-corner labels), log-mapped over [min,max] ms and emitted as
    ``attack <ms>`` / ``release <ms>`` on outlet 0 (no-echo: outlet fires only
    on user gestures; inbound set_* is ignored mid-drag). A double-click resets
    both to ``reset_attack_ms`` / ``reset_release_ms`` (default = the initial
    attack_ms / release_ms).
    """
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    if reset_attack_ms is None:
        reset_attack_ms = attack_ms
    if reset_release_ms is None:
        reset_release_ms = release_ms
    return _JS_TEMPLATE.substitute(
        reset_attack_ms=reset_attack_ms,
        reset_release_ms=reset_release_ms,
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        curve_color=curve_color,
        fill_color=fill_color,
        grid_color=grid_color,
        text_color=text_color,
        attack_ms=attack_ms,
        release_ms=release_ms,
        knee_db=knee_db,
        ratio=ratio,
        full_scale_db=full_scale_db,
        interactive=1 if interactive else 0,
        attack_min_ms=attack_min_ms,
        attack_max_ms=attack_max_ms,
        release_min_ms=release_min_ms,
        release_max_ms=release_max_ms,
    )


_JS_TEMPLATE = Template("""\
// Ballistics Curve Display - generated by m4l-builder
// ES5 compatible; interactive=True turns it into a 2-zone attack/release pad.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var CURVE_CLR  = [$curve_color];
var FILL_CLR   = [$fill_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];

var attack_ms = $attack_ms;
var release_ms = $release_ms;
var knee_db = $knee_db;
var ratio = $ratio;
var FULL_DB = $full_scale_db;

var INTERACTIVE = $interactive;
var ATK_MIN = $attack_min_ms, ATK_MAX = $attack_max_ms;
var REL_MIN = $release_min_ms, REL_MAX = $release_max_ms;
var RESET_ATK = $reset_attack_ms, RESET_REL = $reset_release_ms;
var dragging = 0;
var drag_zone = 0;     // 0 = attack (left half), 1 = release (right half)
var live_gr_db = 0.0;  // live gain reduction (dB, >=0) fed from the compressor
var live_gr_prev = -1.0;

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

function plot_l() { return 5; }
function plot_r() { return mgraphics.size[0] - 5; }
function plot_t() { return 11; }
function plot_b() { return mgraphics.size[1] - 10; }
function plot_w() { var d = plot_r() - plot_l(); return d > 1 ? d : 1; }
function plot_h() { var d = plot_b() - plot_t(); return d > 1 ? d : 1; }

// Representative GR depth: a 12 dB-over-threshold step through the ratio.
function target_gr() {
    return 12.0 * (1.0 - 1.0 / Math.max(ratio, 1.0));
}

// Phase spans (ms): attack/release each settle in ~3 tau (95%); a
// proportional hold keeps both phases on screen across the full ranges.
function spans() {
    var a = Math.max(attack_ms, 0.05) * 3.0;
    var r = Math.max(release_ms, 5.0) * 3.0;
    var hold = 0.30 * (a + r);
    return { a: a, hold: hold, r: r, T: a + hold + r };
}

// Gain reduction (dB, >= 0) at time t (ms) along the modeled envelope.
function env_at(t, sp, tgt) {
    if (t < sp.a) {
        return tgt * (1.0 - Math.exp(-3.0 * t / sp.a));
    }
    var t2 = t - sp.a;
    if (t2 < sp.hold) return tgt;
    var t3 = t2 - sp.hold;
    return tgt * Math.exp(-3.0 * t3 / sp.r);
}

function gr_to_y(gr) {
    return plot_t() + clamp(gr, 0.0, FULL_DB) / FULL_DB * plot_h();
}

function fmt_ms(v) {
    if (v < 10.0) return (Math.round(v * 10) / 10) + "ms";
    return Math.round(v) + "ms";
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, y, gr;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Active-zone tint while dragging — shows which knob (ATK left / REL right).
    if (dragging) {
        var hzx = plot_w() * 0.5;
        var zx = drag_zone === 0 ? plot_l() : plot_l() + hzx;
        mgraphics.set_source_rgba(CURVE_CLR[0], CURVE_CLR[1], CURVE_CLR[2], 0.09);
        mgraphics.rectangle(zx, plot_t(), hzx, plot_h());
        mgraphics.fill();
    }

    var sp = spans();
    var tgt = target_gr();

    // Horizontal GR gridlines every 6 dB.
    mgraphics.set_line_width(1.0);
    var gd;
    for (gd = 6; gd <= FULL_DB - 0.01; gd += 6) {
        y = gr_to_y(gd);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(plot_l(), y);
        mgraphics.line_to(plot_r(), y);
        mgraphics.stroke();
    }

    // Phase boundary ticks (attack end, release start) as faint verticals.
    var xa = plot_l() + (sp.a / sp.T) * plot_w();
    var xr = plot_l() + ((sp.a + sp.hold) / sp.T) * plot_w();
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.move_to(xa, plot_t()); mgraphics.line_to(xa, plot_b()); mgraphics.stroke();
    mgraphics.move_to(xr, plot_t()); mgraphics.line_to(xr, plot_b()); mgraphics.stroke();

    // Envelope: filled area from the 0-GR line down to the curve, + stroke.
    var N = 128;
    var y0 = gr_to_y(0.0);
    // Fill opacity scales with the GR depth: a light squeeze reads subtle,
    // a heavy one bold (the "intensity" cue).
    var fill_intensity = clamp(tgt / FULL_DB, 0.0, 1.0);
    mgraphics.set_source_rgba(FILL_CLR[0], FILL_CLR[1], FILL_CLR[2],
                              0.10 + fill_intensity * 0.34);
    mgraphics.move_to(plot_l(), y0);
    for (i = 0; i <= N; i++) {
        x = plot_l() + (i / N) * plot_w();
        gr = env_at((i / N) * sp.T, sp, tgt);
        mgraphics.line_to(x, gr_to_y(gr));
    }
    mgraphics.line_to(plot_r(), y0);
    mgraphics.close_path();
    mgraphics.fill();

    mgraphics.set_source_rgba(CURVE_CLR);
    mgraphics.set_line_width(1.6);
    for (i = 0; i <= N; i++) {
        x = plot_l() + (i / N) * plot_w();
        gr = env_at((i / N) * sp.T, sp, tgt);
        y = gr_to_y(gr);
        if (i === 0) mgraphics.move_to(x, y); else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    // Live GR indicator: a cyan line at the CURRENT gain-reduction depth that
    // rides against the modeled attack/release shape, so the static inset now
    // breathes with the signal (matching the transfer IO dot + level-history GR
    // stream — the last non-live hero comes alive). Ignites with depth: a soft
    // "current reduction" band from the 0-GR line down to the live depth, a
    // bright line, a glowing right-edge dot, and a numeric GR readout. Idle
    // (GR ~0) draws nothing so the envelope shape stays clean.
    if (live_gr_db > 0.1) {
        var lg = clamp(live_gr_db, 0.0, FULL_DB);
        var ly = gr_to_y(lg);
        var ign = clamp(lg / 9.0, 0.0, 1.0);   // brightness ramps to ~9 dB
        // Reduction band (0-GR line -> live depth).
        mgraphics.set_source_rgba(0.34, 0.82, 1.0, 0.06 + ign * 0.12);
        mgraphics.rectangle(plot_l(), y0, plot_w(), ly - y0);
        mgraphics.fill();
        // Live depth line.
        mgraphics.set_source_rgba(0.40, 0.85, 1.0, 0.45 + ign * 0.45);
        mgraphics.set_line_width(1.4);
        mgraphics.move_to(plot_l(), ly);
        mgraphics.line_to(plot_r(), ly);
        mgraphics.stroke();
        // Glowing right-edge dot (halo + core).
        mgraphics.set_source_rgba(0.40, 0.85, 1.0, 0.18 + ign * 0.22);
        mgraphics.arc(plot_r() - 4, ly, 5.0 + ign * 3.0, 0, Math.PI * 2);
        mgraphics.fill();
        mgraphics.set_source_rgba(0.65, 0.93, 1.0, 0.85);
        mgraphics.arc(plot_r() - 4, ly, 2.2, 0, Math.PI * 2);
        mgraphics.fill();
        // Numeric readout (top-right).
        mgraphics.select_font_face("Arial");
        mgraphics.set_font_size(7.5);
        mgraphics.set_source_rgba(0.55, 0.88, 1.0, 0.55 + ign * 0.45);
        var gl = "GR " + (Math.round(lg * 10) / 10).toFixed(1);
        mgraphics.move_to(plot_r() - (gl.length * 4.6 + 4), plot_t() + 9);
        mgraphics.show_text(gl);
    }

    // Phase labels.
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(7.0);
    mgraphics.set_source_rgba(TEXT_CLR);
    var al = "ATK " + fmt_ms(attack_ms);
    mgraphics.move_to(plot_l() + 2, plot_b() - 2);
    mgraphics.show_text(al);
    var rl = "REL " + fmt_ms(release_ms);
    mgraphics.move_to(plot_r() - (rl.length * 4.4 + 2), plot_b() - 2);
    mgraphics.show_text(rl);
}

// ── Message handlers (set_* restyle + redraw; ignored mid-drag) ────────
function set_attack(v) { if (dragging) return; if (isFinite(v)) { attack_ms = v; mgraphics.redraw(); } }
function set_release(v) { if (dragging) return; if (isFinite(v)) { release_ms = v; mgraphics.redraw(); } }
function set_knee(v) { if (isFinite(v)) { knee_db = v; mgraphics.redraw(); } }
function set_ratio(v) { if (isFinite(v)) { ratio = v; mgraphics.redraw(); } }
// Live gain reduction (dB, >=0) from the compressor's GR stream (~30 Hz). Guard
// against needless repaints when GR is pinned (e.g. parked at 0 when not
// compressing): only redraw when it moves by >=0.05 dB.
function set_live_gr(v) {
    if (!isFinite(v)) return;
    var nv = v < 0.0 ? 0.0 : v;
    if (Math.abs(nv - live_gr_prev) < 0.05) { live_gr_db = nv; return; }
    live_gr_prev = nv;
    live_gr_db = nv;
    mgraphics.redraw();
}

// ── Interaction: left half drags ATTACK, right half drags RELEASE ──────
// (matches the ATK/REL corner labels). Absolute + log-mapped, with the proven
// v8ui pointer resolver (.x/.localX/.offsetX/.clientX); outlet fires only on a
// user gesture (no-echo). The curve reshapes live as you drag.
function pointer_x(pe, fb) {
    if (!pe) return fb;
    if (pe.x !== undefined) return pe.x;
    if (pe.localX !== undefined) return pe.localX;
    if (pe.offsetX !== undefined) return pe.offsetX;
    if (pe.clientX !== undefined) return pe.clientX;
    return fb;
}
function pointer_buttons(pe, fb) {
    if (!pe) return fb;
    if (pe.buttons !== undefined) return pe.buttons;
    if (pe.button !== undefined) return pe.button === 2 ? 2 : 1;
    return fb;
}
function log_map(f, lo, hi) { return lo * Math.pow(hi / lo, clamp(f, 0.0, 1.0)); }

function apply_drag(x) {
    if (isNaN(x)) return;
    var half = plot_w() * 0.5;
    if (drag_zone === 0) {
        attack_ms = log_map((x - plot_l()) / half, ATK_MIN, ATK_MAX);
        outlet(0, "attack", attack_ms);
    } else {
        release_ms = log_map((x - plot_l() - half) / half, REL_MIN, REL_MAX);
        outlet(0, "release", release_ms);
    }
    mgraphics.redraw();
}

function start_drag(x) {
    if (!INTERACTIVE) return;
    dragging = 1;
    drag_zone = (x < plot_l() + plot_w() * 0.5) ? 0 : 1;
    apply_drag(x);
}
function drag_to(x) { if (dragging) apply_drag(x); }
function end_drag() { if (dragging) { dragging = 0; mgraphics.redraw(); } }

// Double-click resets BOTH attack + release to their defaults (consistency with
// the transfer/level-history displays). Emits on outlet 0 (no-echo).
function reset_ballistics() {
    if (!INTERACTIVE) return;
    dragging = 0;
    attack_ms = RESET_ATK;
    release_ms = RESET_REL;
    outlet(0, "attack", attack_ms);
    outlet(0, "release", release_ms);
    mgraphics.redraw();
}

function onpointerdown(pe) { start_drag(pointer_x(pe, plot_l())); }
function onpointermove(pe) {
    if (dragging && ((pointer_buttons(pe, 1) & 1) !== 0)) drag_to(pointer_x(pe, plot_l()));
    else if (dragging) end_drag();
}
function onpointerup(pe) { end_drag(); }
function onpointerleave(pe) { end_drag(); }
function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { start_drag(x); }
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) { if (but) drag_to(x); else end_drag(); }
function ondblclick(x, y, but, cmd, shift, caps, opt, ctrl) { reset_ballistics(); }

function onresize(w, h) { mgraphics.redraw(); }
""")
