"""Compressor transfer curve display engine for jsui.

Generates JavaScript code that renders a compression transfer curve with a
live gain reduction indicator inside Max's jsui object using mgraphics.

Inlets:
    0 -- Threshold in dB (float -60 to 0)
    1 -- Ratio (float 1 to 20)
    2 -- Gain reduction indicator (float 0-1, position riding the curve)
"""

COMPRESSOR_DISPLAY_INLETS = 3
COMPRESSOR_DISPLAY_OUTLETS = 0


def compressor_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                          curve_color="1.0, 1.0, 1.0, 0.9",
                          dot_color="0.9, 0.55, 0.2, 1.0",
                          grid_color="0.2, 0.2, 0.22, 0.5",
                          text_color="0.5, 0.5, 0.52, 1.0",
                          unity_color="0.3, 0.3, 0.32, 0.4"):
    """Return JavaScript source for a compressor transfer curve display (Max jsui).

    Draws a dB-in vs dB-out transfer curve showing the compression knee.
    A grid at -48, -36, -24, -12, 0 dB is drawn on both axes. The unity
    (1:1) line is shown dimmed. An orange dot rides the curve to show
    the current gain reduction amount.

    All color arguments are RGBA strings, e.g. ``"0.9, 0.55, 0.2, 1.0"``.

    Args:
        bg_color: Background color.
        curve_color: Transfer curve line color.
        dot_color: Gain reduction indicator dot color.
        grid_color: Grid line color.
        text_color: Axis label color.
        unity_color: Unity (1:1) diagonal line color.

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    return (
        "// Compressor Transfer Curve - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 3;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var threshold = -24; // dB, -60 to 0\n"
        "var ratio = 4;       // 1 to 20\n"
        "var gr_pos = 0;      // 0-1 gain reduction indicator\n"
        "\n"
        "// --- Constants ---\n"
        "var MIN_DB = -60;\n"
        "var MAX_DB = 0;\n"
        "var DB_RANGE = MAX_DB - MIN_DB;\n"
        "var MARGIN_LEFT = 24;\n"
        "var MARGIN_RIGHT = 6;\n"
        "var MARGIN_TOP = 6;\n"
        "var MARGIN_BOTTOM = 16;\n"
        "var NUM_POINTS = 128;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_float(v) {\n"
        "    if (inlet === 0) {\n"
        "        threshold = Math.max(-60, Math.min(0, v));\n"
        "    } else if (inlet === 1) {\n"
        "        ratio = Math.max(1, Math.min(20, v));\n"
        "    } else if (inlet === 2) {\n"
        "        gr_pos = Math.max(0, Math.min(1, v));\n"
        "    }\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "function msg_int(v) {\n"
        "    msg_float(v);\n"
        "}\n"
        "\n"
        "// --- Transfer function: input dB -> output dB ---\n"
        "function transfer(input_db) {\n"
        "    if (input_db <= threshold) {\n"
        "        return input_db;\n"
        "    }\n"
        "    return threshold + (input_db - threshold) / ratio;\n"
        "}\n"
        "\n"
        "// --- Mapping helpers ---\n"
        "function db_to_x(db, plot_x, plot_w) {\n"
        "    return plot_x + ((db - MIN_DB) / DB_RANGE) * plot_w;\n"
        "}\n"
        "\n"
        "function db_to_y(db, plot_y, plot_h) {\n"
        "    return plot_y + (1.0 - (db - MIN_DB) / DB_RANGE) * plot_h;\n"
        "}\n"
        "\n"
        "// --- Paint ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var plot_x = MARGIN_LEFT;\n"
        "    var plot_y = MARGIN_TOP;\n"
        "    var plot_w = w - MARGIN_LEFT - MARGIN_RIGHT;\n"
        "    var plot_h = h - MARGIN_TOP - MARGIN_BOTTOM;\n"
        "\n"
        "    // Background\n"
        "    mgraphics.set_source_rgba(" + bg_color + ");\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Grid lines at -48, -36, -24, -12, 0 dB\n"
        "    var db_ticks = [-48, -36, -24, -12, 0];\n"
        "    mgraphics.set_line_width(1);\n"
        "    for (var i = 0; i < db_ticks.length; i++) {\n"
        "        var db = db_ticks[i];\n"
        "        var gx = db_to_x(db, plot_x, plot_w);\n"
        "        var gy = db_to_y(db, plot_y, plot_h);\n"
        "\n"
        "        // Vertical grid line\n"
        "        mgraphics.set_source_rgba(" + grid_color + ");\n"
        "        mgraphics.move_to(Math.round(gx) + 0.5, plot_y);\n"
        "        mgraphics.line_to(Math.round(gx) + 0.5, plot_y + plot_h);\n"
        "        mgraphics.stroke();\n"
        "\n"
        "        // Horizontal grid line\n"
        "        mgraphics.move_to(plot_x, Math.round(gy) + 0.5);\n"
        "        mgraphics.line_to(plot_x + plot_w, Math.round(gy) + 0.5);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // dB labels on the left (output axis)\n"
        "    mgraphics.select_font_face(\"Ableton Sans Medium\");\n"
        "    mgraphics.set_font_size(8);\n"
        "    mgraphics.set_source_rgba(" + text_color + ");\n"
        "    for (var i = 0; i < db_ticks.length; i++) {\n"
        "        var db = db_ticks[i];\n"
        "        var gy = db_to_y(db, plot_y, plot_h);\n"
        "        mgraphics.move_to(1, gy + 3);\n"
        "        mgraphics.show_text(db + \"\");\n"
        "    }\n"
        "\n"
        "    // dB labels on the bottom (input axis)\n"
        "    for (var i = 0; i < db_ticks.length; i++) {\n"
        "        var db = db_ticks[i];\n"
        "        var gx = db_to_x(db, plot_x, plot_w);\n"
        "        mgraphics.move_to(gx - 6, h - 3);\n"
        "        mgraphics.show_text(db + \"\");\n"
        "    }\n"
        "\n"
        "    // Unity (1:1) diagonal\n"
        "    mgraphics.set_source_rgba(" + unity_color + ");\n"
        "    mgraphics.set_line_width(1);\n"
        "    mgraphics.move_to(db_to_x(MIN_DB, plot_x, plot_w), db_to_y(MIN_DB, plot_y, plot_h));\n"
        "    mgraphics.line_to(db_to_x(MAX_DB, plot_x, plot_w), db_to_y(MAX_DB, plot_y, plot_h));\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Transfer curve\n"
        "    mgraphics.set_source_rgba(" + curve_color + ");\n"
        "    mgraphics.set_line_width(2);\n"
        "    for (var i = 0; i <= NUM_POINTS; i++) {\n"
        "        var in_db = MIN_DB + (i / NUM_POINTS) * DB_RANGE;\n"
        "        var out_db = transfer(in_db);\n"
        "        var cx = db_to_x(in_db, plot_x, plot_w);\n"
        "        var cy = db_to_y(out_db, plot_y, plot_h);\n"
        "        if (i === 0) {\n"
        "            mgraphics.move_to(cx, cy);\n"
        "        } else {\n"
        "            mgraphics.line_to(cx, cy);\n"
        "        }\n"
        "    }\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Threshold marker (vertical dashed feel)\n"
        "    var thresh_x = db_to_x(threshold, plot_x, plot_w);\n"
        "    mgraphics.set_source_rgba(" + grid_color + ");\n"
        "    mgraphics.set_line_width(1);\n"
        "    mgraphics.move_to(Math.round(thresh_x) + 0.5, plot_y);\n"
        "    mgraphics.line_to(Math.round(thresh_x) + 0.5, plot_y + plot_h);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Gain reduction dot riding the curve\n"
        "    // gr_pos 0 = no signal (MIN_DB), 1 = full signal (MAX_DB)\n"
        "    var dot_in = MIN_DB + gr_pos * DB_RANGE;\n"
        "    var dot_out = transfer(dot_in);\n"
        "    var dot_x = db_to_x(dot_in, plot_x, plot_w);\n"
        "    var dot_y = db_to_y(dot_out, plot_y, plot_h);\n"
        "\n"
        "    // Dot glow\n"
        "    var dc = (\"" + dot_color + "\").split(\",\");\n"
        "    mgraphics.set_source_rgba(\n"
        "        parseFloat(dc[0]),\n"
        "        parseFloat(dc[1]),\n"
        "        parseFloat(dc[2]),\n"
        "        0.2\n"
        "    );\n"
        "    mgraphics.arc(dot_x, dot_y, 8, 0, Math.PI * 2);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Dot fill\n"
        "    mgraphics.set_source_rgba(" + dot_color + ");\n"
        "    mgraphics.arc(dot_x, dot_y, 4, 0, Math.PI * 2);\n"
        "    mgraphics.fill();\n"
        "}\n"
    )
