"""Delay tap-trail display (Timeless-style hero graph).

Two lanes (L top, R bottom) on a time ruler. Taps are drawn at each
feedback repeat with opacity decaying by the feedback amount and size
shrinking with damping; ping-pong alternates lanes. A live wet-level
glow pulses the first taps. Drag horizontally to set time; wheel adjusts
feedback. Outlets fire only on user gestures (no-echo rule).

Messages in (inlet 0):
    set_time <ms>          1..2000 (display + drag range)
    set_feedback <pct>     0..110
    set_damp <pct>         0..100 (visual: taps darken/shrink faster)
    set_pingpong <0|1>
    set_sync_label <text>  "FREE" or a division label for the readout
    wet_level <lin>        live wet level 0..1 (~30ms)
    set_duck <lin>         live duck depth 0..1 (dims the trail; lights DUCK badge)

Messages out (outlet 0):
    time <ms>              while dragging (only meaningful in FREE mode)
    feedback <pct>         on wheel
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)
from .design_system import design_system_js

DELAY_TRAIL_INLETS = 1
DELAY_TRAIL_OUTLETS = 1

__all__ = ["DELAY_TRAIL_INLETS", "DELAY_TRAIL_OUTLETS", "delay_trail_js"]


def delay_trail_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    tap_color="0.30, 0.75, 0.95, 1.0",
    lane_color="0.20, 0.23, 0.27, 0.55",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    accent_color="0.30, 0.75, 0.95, 1.0",
    max_ms=2000.0,
    reset_time_ms=350.0,
    reset_feedback_pct=35.0,
):
    """Return JavaScript source for the delay trail display.

    Drag is an absolute X/Y pad (x=time, y=feedback); double-click resets both
    to (reset_time_ms, reset_feedback_pct).
    """
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return design_system_js() + "\n" + _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        tap_color=tap_color,
        lane_color=lane_color,
        grid_color=grid_color,
        text_color=text_color,
        accent_color=accent_color,
        max_ms=max_ms,
        reset_time_ms=reset_time_ms,
        reset_feedback_pct=reset_feedback_pct,
    )


_JS_TEMPLATE = Template("""\
// Delay Trail Display - generated by m4l-builder
// ES5 compatible; full pointer handler set for v8ui drags.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var TAP_CLR    = [$tap_color];
var LANE_CLR   = [$lane_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];
var ACCENT_CLR = [$accent_color];
var MAX_MS     = $max_ms;
var RESET_TIME = $reset_time_ms;
var RESET_FB   = $reset_feedback_pct;

var time_ms = 350.0;
var feedback_pct = 45.0;
var damp_pct = 20.0;
var pingpong = 0;
var sync_label = "FREE";
var wet_lvl = 0.0;
var duck_lvl = 0.0;
var dragging = 0;
var hovering = 0;
var drag_start_x = 0;
var drag_start_y = 0;
var drag_start_time = 0.0;
var drag_start_feedback = 0.0;

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

function plot_l() { return 8; }
function plot_r() { return mgraphics.size[0] - 8; }
function plot_t() { return 8; }
function plot_b() { return mgraphics.size[1] - 16; }
function plot_w() { return plot_r() - plot_l(); }
function plot_h() { return plot_b() - plot_t(); }

function ms_to_x(ms) {
    return plot_l() + clamp(ms / MAX_MS, 0.0, 1.0) * plot_w();
}

function lane_y(is_right) {
    var third = plot_h() / 3.0;
    return plot_t() + (is_right ? third * 2.2 : third * 0.8);
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, ms;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Time ruler every 250 ms with labels at 500s.
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(7.0);
    for (ms = 250; ms < MAX_MS; ms += 250) {
        x = ms_to_x(ms);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.set_line_width(1.0);
        mgraphics.move_to(x, plot_t());
        mgraphics.line_to(x, plot_b());
        mgraphics.stroke();
        if (ms % 500 === 0) {
            mgraphics.set_source_rgba(TEXT_CLR);
            mgraphics.move_to(x - 8, h - 5);
            mgraphics.show_text((ms / 1000).toFixed(1) + "s");
        }
    }

    // Lane center lines.
    mgraphics.set_source_rgba(LANE_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(plot_l(), lane_y(0)); mgraphics.line_to(plot_r(), lane_y(0)); mgraphics.stroke();
    mgraphics.move_to(plot_l(), lane_y(1)); mgraphics.line_to(plot_r(), lane_y(1)); mgraphics.stroke();
    mgraphics.set_source_rgba(TEXT_CLR);
    mgraphics.set_font_size(7.5);
    mgraphics.move_to(plot_l() + 3, lane_y(0) - 7);
    mgraphics.show_text("L");
    mgraphics.move_to(plot_l() + 3, lane_y(1) - 7);
    mgraphics.show_text("R");

    // Input pulse at t=0 on both lanes — a real radial glow (design-system)
    // that swells with the live wet level, then a bright core dot on top.
    var wet = clamp(wet_lvl, 0, 1);
    var in_x = ms_to_x(0) + 2;
    var li0;
    for (li0 = 0; li0 < 2; li0++) {
        ds_node_glow(in_x, lane_y(li0), ACCENT_CLR, 6.0 + wet * 11.0, 0.30 + wet * 0.45);
        mgraphics.set_source_rgba(ACCENT_CLR[0], ACCENT_CLR[1], ACCENT_CLR[2], 0.55 + wet * 0.45);
        mgraphics.arc(in_x, lane_y(li0), 3.2, 0, Math.PI * 2); mgraphics.fill();
    }

    // Echo taps: amplitude decays by feedback per repeat; damping shrinks.
    // Ping-pong alternates L/R; a normal stereo delay echoes BOTH channels
    // equally, so each tap is drawn on both lanes (the R lane was dead in
    // non-ping-pong mode — both channels echo, so both lanes should show it).
    var fb = clamp(feedback_pct / 100.0, 0.0, 1.1);
    var amp = fb;
    // it177: the live DUCK depth recedes the WHOLE trail — when a dry transient
    // ducks the wet, every echo dims in lock-step (even a full duck keeps a faint
    // trail so the pattern stays readable). Makes the rail-only Duck knob visible.
    var duck = clamp(duck_lvl, 0, 1);
    var dim = 1.0 - duck * 0.72;
    var t = time_ms;
    var n = 0;
    var li, ly, stem, active_lane;
    while (amp > 0.02 && t <= MAX_MS && n < 24) {
        var size = (2.0 + amp * 5.0) * (1.0 - (damp_pct / 100.0) * 0.5 * (n / 8.0));
        if (size < 1.0) size = 1.0;
        x = ms_to_x(t);
        stem = amp * plot_h() * 0.16;
        active_lane = (n % 2 === 0) ? 1 : 0;  // ping-pong: which lane this repeat
        for (li = 0; li < 2; li++) {
            if (pingpong && li !== active_lane) continue;
            ly = lane_y(li);
            // Stem.
            mgraphics.set_source_rgba(TAP_CLR[0], TAP_CLR[1], TAP_CLR[2], amp * 0.35 * dim);
            mgraphics.set_line_width(1.0);
            mgraphics.move_to(x, ly - stem);
            mgraphics.line_to(x, ly + stem);
            mgraphics.stroke();
            // Glowing tap: a radial glow (design-system) that fades with the
            // echo amplitude, then a solid dot core — louder/earlier taps read
            // as brighter lights fading down the trail (and dim under ducking).
            ds_node_glow(x, ly, TAP_CLR, size + 5.0 + amp * 6.0,
                         (0.20 + clamp(amp, 0, 1) * 0.45) * dim);
            mgraphics.set_source_rgba(TAP_CLR[0], TAP_CLR[1], TAP_CLR[2], clamp(amp, 0, 1) * dim);
            mgraphics.arc(x, ly, size, 0, Math.PI * 2);
            mgraphics.fill();
        }
        n += 1;
        t += time_ms;
        amp *= fb;
    }

    // Border + readout.
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();

    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.set_font_size(8.0);
    mgraphics.move_to(plot_l() + 16, plot_t() + 11);
    var time_txt = sync_label === "FREE" ? (Math.round(time_ms) + " ms") : sync_label;
    mgraphics.show_text(time_txt + "   FB " + Math.round(feedback_pct) + "%");
    if (pingpong) {
        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.move_to(plot_l() + 16, plot_t() + 21);
        mgraphics.show_text("PING-PONG");
    }

    // it177: DUCK activity badge (top-right). An amber "DUCK ▾" + meter bar that
    // IGNITES with the live duck depth so the rail-only Duck knob has a hero
    // tell: idle = faint outline, ducking = bright amber. Pairs with the
    // whole-trail dim above (the echoes recede as this lights up).
    var dk = clamp(duck_lvl, 0, 1);
    var bx = plot_r() - 52;
    var by = plot_t() + 6;
    mgraphics.set_font_size(7.5);
    mgraphics.set_source_rgba(0.96, 0.66, 0.26, 0.28 + dk * 0.72);
    mgraphics.move_to(bx, by + 6);
    mgraphics.show_text("DUCK");
    // Downward chevron — brightens with the duck depth.
    mgraphics.set_source_rgba(0.96, 0.66, 0.26, 0.22 + dk * 0.78);
    mgraphics.move_to(bx + 27, by + 1);
    mgraphics.line_to(bx + 33, by + 1);
    mgraphics.line_to(bx + 30, by + 5.5);
    mgraphics.close_path();
    mgraphics.fill();
    // Thin meter: faint track + amber fill proportional to the live duck.
    mgraphics.set_source_rgba(0.96, 0.66, 0.26, 0.16);
    mgraphics.rectangle(bx, by + 9, 44, 2.5);
    mgraphics.fill();
    mgraphics.set_source_rgba(0.96, 0.66, 0.26, 0.88);
    mgraphics.rectangle(bx, by + 9, 44 * dk, 2.5);
    mgraphics.fill();
}

// ── Messages ─────────────────────────────────────────────────────────
function set_time(v)       { time_ms = clamp(v, 1.0, MAX_MS); mgraphics.redraw(); }
function set_feedback(v)   { feedback_pct = clamp(v, 0.0, 110.0); mgraphics.redraw(); }
function set_damp(v)       { damp_pct = clamp(v, 0.0, 100.0); mgraphics.redraw(); }
function set_pingpong(v)   { pingpong = v ? 1 : 0; mgraphics.redraw(); }
function set_sync_label(v) { sync_label = "" + v; mgraphics.redraw(); }
function wet_level(v) { wet_lvl = v; mgraphics.redraw(); }
function set_duck(v) { duck_lvl = clamp(v, 0.0, 1.0); mgraphics.redraw(); }

// ── Interaction: ABSOLUTE X/Y pad ────────────────────────────────────
// Robust pointer-coordinate resolution. Max's v8ui pointer events expose the
// object-local position under DIFFERENT property names across runtimes
// (.x / .localX / .offsetX / .clientX); reading only `.x` returned undefined
// in Live -> (undefined - plot_l()) = NaN -> time/feedback slammed to the rails
// (and the readout showed "NaN ms"). This is the exact helper set eq_curve uses
// (that engine drags reliably). The legacy onclick/ondrag path already passes
// real object-local pixels, so it needs no resolver.
function pointer_x(pe, fb) {
    if (!pe) return fb;
    if (pe.x !== undefined) return pe.x;
    if (pe.localX !== undefined) return pe.localX;
    if (pe.offsetX !== undefined) return pe.offsetX;
    if (pe.clientX !== undefined) return pe.clientX;
    return fb;
}
function pointer_y(pe, fb) {
    if (!pe) return fb;
    if (pe.y !== undefined) return pe.y;
    if (pe.localY !== undefined) return pe.localY;
    if (pe.offsetY !== undefined) return pe.offsetY;
    if (pe.clientY !== undefined) return pe.clientY;
    return fb;
}
function pointer_buttons(pe, fb) {
    if (!pe) return fb;
    if (pe.buttons !== undefined) return pe.buttons;
    if (pe.button !== undefined) return pe.button === 2 ? 2 : 1;
    return fb;
}

function start_drag(x, y) {
    dragging = 1;
    // Anchor for shift=fine (relative-to-press, clamped — cannot slam).
    drag_start_time = time_ms;
    drag_start_feedback = feedback_pct;
}

// ABSOLUTE X/Y pad: the pointer POSITION maps directly to time (x, along the
// ruler) and feedback (y, up = more) — not a relative start+delta. Bounded by
// the plot, so a stray pointer frame can never slam the values to the rails
// (the relative model did exactly that live). The isNaN guard is belt-and-
// suspenders: if every coordinate property is missing we leave state untouched
// rather than poisoning time_ms with NaN.
function drag_to(x, y, fine) {
    if (!dragging) return;
    if (isNaN(x) || isNaN(y)) return;
    var fx = clamp((x - plot_l()) / plot_w(), 0.0, 1.0);
    var fy = clamp((plot_b() - y) / plot_h(), 0.0, 1.0);
    var t_target = clamp(fx * MAX_MS, 1.0, MAX_MS);
    var f_target = clamp(fy * 110.0, 0.0, 110.0);
    // Shift = fine-adjust (suite-wide tactile grammar): move 1/5th of the cursor
    // distance from the press anchor — a stable 5x-finer drag for precise time /
    // feedback. Plain drag stays absolute (the pad follows the cursor).
    if (fine) {
        t_target = drag_start_time + (t_target - drag_start_time) * 0.20;
        f_target = drag_start_feedback + (f_target - drag_start_feedback) * 0.20;
    }
    time_ms = clamp(t_target, 1.0, MAX_MS);
    feedback_pct = clamp(f_target, 0.0, 110.0);
    outlet(0, "time", Math.round(time_ms));
    outlet(0, "feedback", Math.round(feedback_pct));
    mgraphics.redraw();
}

function end_drag() {
    if (!dragging) return;
    dragging = 0;
    mgraphics.redraw();
}

// Double-click resets the X/Y pad to its defaults (both time and feedback).
function reset_pad() {
    time_ms = clamp(RESET_TIME, 1.0, MAX_MS);
    feedback_pct = clamp(RESET_FB, 0.0, 110.0);
    outlet(0, "time", Math.round(time_ms));
    outlet(0, "feedback", Math.round(feedback_pct));
    mgraphics.redraw();
}

function pointer_alt_key(pe) { return (pe && pe.altKey) ? 1 : 0; }

// Opt-click toggles PING-PONG (the trail VISUALISES it — taps alternate L/R
// lanes), a direct-manipulation toggle right where the effect is shown. A bare
// click never moves the pad (start_drag only anchors; drag_to applies), so this
// does not disturb the time/feedback drag.
function toggle_pingpong() {
    pingpong = pingpong ? 0 : 1;
    outlet(0, "pingpong", pingpong);
    mgraphics.redraw();
}

function onpointerdown(pe) {
    if (pointer_alt_key(pe)) { toggle_pingpong(); return; }
    start_drag(pointer_x(pe, plot_l()), pointer_y(pe, plot_b()));
}
function onpointermove(pe) {
    var b = pointer_buttons(pe, 0);
    if (dragging && ((b & 1) !== 0)) {
        drag_to(pointer_x(pe, plot_l()), pointer_y(pe, plot_b()),
                pe && pe.shiftKey ? 1 : 0);
        return;
    }
    if (dragging && b === 0) { end_drag(); return; }
    if (!hovering) { hovering = 1; mgraphics.redraw(); }
}
function onpointerup(pe) { end_drag(); }
function onpointerleave(pe) { hovering = 0; end_drag(); mgraphics.redraw(); }
function ondblclick(x, y, but, cmd, shift, caps, opt, ctrl) { reset_pad(); }

function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { start_drag(x, y); }
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but) drag_to(x, y, shift);
    else end_drag();
}
function onidle(x, y) { if (!hovering) { hovering = 1; mgraphics.redraw(); } }
function onidleout() { hovering = 0; mgraphics.redraw(); }

function onwheel(x, y, scrollx, scrolly) {
    feedback_pct = clamp(feedback_pct + (scrolly > 0 ? 2 : -2), 0, 110);
    outlet(0, "feedback", Math.round(feedback_pct));
    mgraphics.redraw();
}

function onresize(w, h) { mgraphics.redraw(); }
""")
