"""Delay tap-trail display (a premium-delay-style hero graph).

Two lanes (L top, R bottom) on a time ruler. Taps are drawn at each
feedback repeat with opacity decaying by the feedback amount and size
shrinking with damping; ping-pong alternates lanes. A live wet-level
glow pulses the first taps. Drag horizontally to set time; wheel adjusts
feedback. Outlets fire only on user gestures (no-echo rule).

THE TIDE (D4 viz bus): when the device wires ``Device.add_viz_bus`` to a
2-channel ring buffer of per-bin peak |written| delay-line energy (256
bins across the 2 s window; slot 256 = head index, 257 = depth-scaled
wobble LFO), the display peeks it on a 33 ms Task and renders the REAL
delay-line contents marching along the ruler — a packet written now
drifts rightward in real time and IGNITES its tap (plus a re-injection
arc back to t=0) as the feedback consumes it. L/R render on their own
lanes so ping-pong shows as alternating wave packets. With no feed
wired, every tide feature is a clean no-op (geometric trail unchanged).

Messages in (inlet 0):
    set_time <ms>          1..2000 (display + drag range)
    set_feedback <pct>     0..110
    set_damp <pct>         0..100 (visual: taps darken/shrink faster)
    set_pingpong <0|1>
    set_sync_label <text>  "FREE" or a division label for the readout
    wet_level <lin>        live wet level 0..1 (~30ms)
    set_duck <lin>         live duck depth 0..1 (dims the trail; lights DUCK badge)
    set_freeze <0|1>       ice tint, gated input pulse, FROZEN badge
    set_reverse <0|1>      reverse-echo mode: ghost trails flip, REVERSE badge
    set_corr <lin>         live stereo correlation -1..1 (readout under DUCK)
    set_buffers <name>     resolved tide buffer~ name (Device.add_viz_bus) —
                           arms the 33 ms peek Task for the delay-line tide

Messages out (outlet 0):
    time <ms>              while dragging (only meaningful in FREE mode)
    feedback <pct>         on wheel
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)
from .design_system import design_system_js
from .interaction_core import (
    CLAMP_TERNARY_JS,
    ONRESIZE_JS,
    POINTER_BUTTONS_JS,
    POINTER_X_JS,
    POINTER_Y_JS,
    plot_geometry_short_js,
)

DELAY_TRAIL_INLETS = 1
DELAY_TRAIL_OUTLETS = 1

__all__ = ["DELAY_TRAIL_INLETS", "DELAY_TRAIL_OUTLETS", "delay_trail_js"]


def delay_trail_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    tap_color="0.30, 0.75, 0.95, 1.0",
    lane_color="0.20, 0.23, 0.27, 0.55",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    accent_color="0.30, 0.75, 0.95, 1.0",
    max_ms=2000.0,
    reset_time_ms=350.0,
    reset_feedback_pct=35.0,
):
    """Return JavaScript source for the delay trail display.

    Drag is an absolute X/Y pad (x=time, y=feedback); double-click resets both
    to (reset_time_ms, reset_feedback_pct).
    """
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return design_system_js() + "\n" + _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        tap_color=tap_color,
        lane_color=lane_color,
        grid_color=grid_color,
        text_color=text_color,
        accent_color=accent_color,
        max_ms=max_ms,
        reset_time_ms=reset_time_ms,
        reset_feedback_pct=reset_feedback_pct,
    ).replace("//__CLAMP_TERNARY__//", CLAMP_TERNARY_JS).replace(
        "//__PLOT_GEOMETRY__//",
        plot_geometry_short_js(
            "8", "mgraphics.size[0] - 8", "8", "mgraphics.size[1] - 16"
        ),
    ).replace("//__POINTER_X__//", POINTER_X_JS).replace(
        "//__POINTER_Y__//", POINTER_Y_JS
    ).replace("//__POINTER_BUTTONS__//", POINTER_BUTTONS_JS).replace(
        "//__ONRESIZE__//", ONRESIZE_JS
    )


_JS_TEMPLATE = Template("""\
// Delay Trail Display - generated by m4l-builder
// ES5 compatible; full pointer handler set for v8ui drags.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var TAP_CLR    = [$tap_color];
var LANE_CLR   = [$lane_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];
var ACCENT_CLR = [$accent_color];
var MAX_MS     = $max_ms;
var RESET_TIME = $reset_time_ms;
var RESET_FB   = $reset_feedback_pct;

var time_ms = 350.0;
var feedback_pct = 45.0;
var damp_pct = 20.0;
var mix_pct = 35.0;
var width_pct = 100.0;   // wet stereo width -> how far apart the L/R lanes sit
var spread_pct = 0.0;    // stereo spread -> L/R comets drift apart in time
var tone_pct = 0.0;      // echo tone tilt -> palette leans warm (-) / bright (+)
var sat_pct = 0.0;       // in-loop saturation -> gritty hot rim on the comets
var beat_ph = -1.0;      // live transport beat phase 0..1 (-1 = no feed) -> grid pulse
var pingpong = 0;
var sync_label = "FREE";
var wet_lvl = 0.0;
var duck_lvl = 0.0;
var character = 0;   // 0 DIGITAL (clean), 1 TAPE, 2 BBD -> warms/dims late repeats

// Transient value bezel for the modifier gestures (Cmd=mix / Alt=damp): shows the
// active param + value for a beat after a wheel/drag so the change is legible.
var gesture_label = "";
var gesture_ttl = 0;   // frames-to-live; decremented on idle redraws

// ── TIDE (D4 viz bus): the REAL delay-line contents ──────────────────
// The gen~ core pokes per-bin peak |written| (input + feedback) into a
// 2-channel ring buffer: 256 bins across the full time window, slot 256 =
// head index, slot 257 = depth-scaled wobble LFO. set_buffers (positional,
// from Device.add_viz_bus) delivers the resolved ---name; a 33 ms Task
// peeks it — zero patchcord traffic, the display cannot desync from the
// DSP. With no feed wired, tideL stays null and the tide is a no-op.
var TIDE_BINS  = 256;
var TIDE_SLOTS = 260;
var TIDE_H     = 0.155;   // bar half-height as a fraction of plot_h
var ICE_CLR    = [0.62, 0.86, 1.0];
var tide_name = "";
var tideL = null;
var tideR = null;
var tide_head = 0;
var wob_live = 0.0;       // depth-scaled wobble LFO, -1..1 (0 at Wobble 0)
var frozen = 0;
var reversed = 0;         // reverse-echo mode: comet ghost-trails flip direction
var corr_lvl = -2.0;      // live stereo correlation -1..1; -2 = no feed (hidden)
var tide_poll = null;

var dragging = 0;
var alt_pending = 0;   // an alt-press that hasn't yet resolved to click (ping-pong) vs drag (damp)
var hovering = 0;
var hover_x = 0.0;
var hover_y = 0.0;
var drag_start_x = 0;
var drag_start_y = 0;
var drag_start_time = 0.0;
var drag_start_feedback = 0.0;
var drag_start_mix = 35.0;
var drag_start_damp = 20.0;

//__CLAMP_TERNARY__//

//__PLOT_GEOMETRY__//

function ms_to_x(ms) {
    return plot_l() + clamp(ms / MAX_MS, 0.0, 1.0) * plot_w();
}

// Lane centres SPREAD with the wet WIDTH knob: 100% = the default spacing,
// 0% collapses toward a single mono line, 200% blooms them wide apart — you
// literally see the stereo image open and close.
function lane_y(is_right) {
    var w01 = clamp(width_pct / 200.0, 0.0, 1.0);   // 100% -> 0.5
    var half = plot_h() * (0.06 + 0.35 * w01);      // 100% -> ~0.235h (matches old)
    var cen = plot_t() + plot_h() * 0.5;
    return is_right ? cen + half : cen - half;
}

// ── Living-Delay render helpers ──────────────────────────────────────
// Energy = light = temperature. Real recirculating energy drives brightness,
// size and colour; the feedback decay is only the envelope/ceiling.
var REACT_FLOOR = 0.34;   // dim floor so the echo pattern still reads in silence
var REACT_GAIN  = 1.15;   // how hard live audio drives the nodes within the envelope
var REACT_CEIL  = 1.28;   // transient overshoot cap (>1 = a loud hit pops)
var COOL_CLR    = [0.16, 0.20, 0.52];   // rest / low energy: deep indigo
var _thc = [0.0, 0.0, 0.0];             // scratch thermal colour (avoid per-call GC)

// Thermal palette: energy e in 0..1 -> deep indigo -> accent cyan -> incandescent
// white. CHARACTER warms the hot anchor (TAPE amber / BBD deep amber); TONE tilts
// it on top (dark tone -> ember-warm, bright tone -> harder white); FREEZE remaps
// the whole ramp toward ice. Writes into the out array.
function thermal(e, out) {
    e = e < 0 ? 0 : (e > 1 ? 1 : e);
    var hr, hg, hb;
    if (character > 1.5)      { hr = 0.98; hg = 0.62; hb = 0.24; }   // BBD deep amber
    else if (character > 0.5) { hr = 1.00; hg = 0.74; hb = 0.34; }   // TAPE amber
    else                      { hr = 0.96; hg = 0.99; hb = 1.00; }   // DIGITAL white-hot
    // TONE = the echoes' dark<->bright tilt, painted onto the hot anchor: darker
    // tone pulls it toward a deep ember, brighter pushes it toward pure white.
    var tn = clamp(tone_pct / 100.0, -1.0, 1.0);
    if (tn < 0) {
        var wt = -tn * 0.65;
        hr = hr + (0.92 - hr) * wt;
        hg = hg + (0.44 - hg) * wt;
        hb = hb + (0.16 - hb) * wt;
    } else if (tn > 0) {
        var bt = tn * 0.6;
        hr = hr + (1.0 - hr) * bt;
        hg = hg + (1.0 - hg) * bt;
        hb = hb + (1.0 - hb) * bt;
    }
    var mr = ACCENT_CLR[0], mg = ACCENT_CLR[1], mb = ACCENT_CLR[2];
    if (e < 0.5) {
        var t = e * 2.0;
        out[0] = COOL_CLR[0] + (mr - COOL_CLR[0]) * t;
        out[1] = COOL_CLR[1] + (mg - COOL_CLR[1]) * t;
        out[2] = COOL_CLR[2] + (mb - COOL_CLR[2]) * t;
    } else {
        var t2 = (e - 0.5) * 2.0;
        out[0] = mr + (hr - mr) * t2;
        out[1] = mg + (hg - mg) * t2;
        out[2] = mb + (hb - mb) * t2;
    }
    if (frozen) {
        out[0] = out[0] + (ICE_CLR[0] - out[0]) * 0.78;
        out[1] = out[1] + (ICE_CLR[1] - out[1]) * 0.78;
        out[2] = out[2] + (ICE_CLR[2] - out[2]) * 0.78;
    }
    return out;
}

// A glowing bezier: wide low-alpha underlay (bloom) + crisp core (no real blur in
// v8ui — stacked alpha is the glow mechanism).
function glow_bezier(x0, y0, c1x, c1y, c2x, c2y, x1, y1, clr, lw, alpha) {
    mgraphics.set_source_rgba(clr[0], clr[1], clr[2], alpha * 0.30);
    mgraphics.set_line_width(lw + 3.0);
    mgraphics.move_to(x0, y0); mgraphics.curve_to(c1x, c1y, c2x, c2y, x1, y1); mgraphics.stroke();
    mgraphics.set_source_rgba(clr[0], clr[1], clr[2], alpha);
    mgraphics.set_line_width(lw);
    mgraphics.move_to(x0, y0); mgraphics.curve_to(c1x, c1y, c2x, c2y, x1, y1); mgraphics.stroke();
}

// THE ENERGY RIVER: a glowing thermal ribbon per lane whose thickness = the real
// per-bin recirculating energy, flowing along the delay ruler. Returns the lane's
// PEAK energy (feeds the feedback-loop glow). A closed ribbon filled with a
// vertical thermal gradient (eq_curve spectrum-river recipe).
function draw_river(arr, ly) {
    if (!arr) return 0.0;
    var bin_ms = MAX_MS / TIDE_BINS;
    var maxH = plot_h() * 0.17;
    var pr = plot_r();
    var peak = 0.0, any = 0;
    // Decimate the 256-bin ring to every RIVER_STEP-th point: at the trail's
    // pixel width one bin is sub-pixel, so this halves the vertex/roundcorners
    // cost with no visible change (perf).
    var STEP = 2;
    var i, idx, raw, ev, xr, last_i = TIDE_BINS;
    mgraphics.move_to(plot_l(), ly);
    for (i = 0; i < TIDE_BINS; i += STEP) {
        xr = ms_to_x(i * bin_ms);
        if (xr > pr) { last_i = i; break; }
        idx = ((tide_head - i) % TIDE_BINS + TIDE_BINS) % TIDE_BINS;
        raw = arr[idx];
        ev = (raw > 0.0) ? Math.pow(clamp(raw * 1.15, 0, 1), 0.55) : 0.0;
        if (ev > peak) peak = ev;
        mgraphics.line_to(xr, ly - ev * maxH);
        any = 1;
    }
    for (i = last_i - STEP; i >= 0; i -= STEP) {
        idx = ((tide_head - i) % TIDE_BINS + TIDE_BINS) % TIDE_BINS;
        raw = arr[idx];
        ev = (raw > 0.0) ? Math.pow(clamp(raw * 1.15, 0, 1), 0.55) : 0.0;
        mgraphics.line_to(ms_to_x(i * bin_ms), ly + ev * maxH);
    }
    mgraphics.close_path();
    if (!any) return 0.0;
    thermal(0.35 + 0.5 * peak, _thc);
    var g = mgraphics.pattern_create_linear(0, ly - maxH, 0, ly + maxH);
    var a = 0.08 + 0.38 * peak;
    g.add_color_stop_rgba(0.0, _thc[0], _thc[1], _thc[2], 0.0);
    g.add_color_stop_rgba(0.5, _thc[0], _thc[1], _thc[2], a);
    g.add_color_stop_rgba(1.0, _thc[0], _thc[1], _thc[2], 0.0);
    mgraphics.set_source(g);
    mgraphics.path_roundcorners(3.0);
    mgraphics.fill();
    return peak;
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, ms;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Time ruler. FREE mode: every 250 ms with second labels. SYNC mode: the
    // grid becomes MUSICAL — one line per division (= per echo), numbered, and
    // the whole grid breathes with the live transport beat (beat_ph from
    // plugsync~) so the delay's rhythm is visible on the graph itself.
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(7.0);
    var synced = sync_label !== "FREE";
    var pulse = (synced && beat_ph >= 0) ? (1.0 - beat_ph) * (1.0 - beat_ph) : 0.0;
    if (synced && time_ms > 30) {
        var k, kx;
        for (k = 1; k * time_ms < MAX_MS; k++) {
            kx = ms_to_x(k * time_ms);
            if (kx > plot_r() - 2) break;
            mgraphics.set_source_rgba(GRID_CLR[0], GRID_CLR[1], GRID_CLR[2],
                                      GRID_CLR[3] * (0.8 + pulse * 0.9));
            mgraphics.set_line_width(1.0);
            mgraphics.move_to(kx, plot_t());
            mgraphics.line_to(kx, plot_b());
            mgraphics.stroke();
            if (k <= 12) {
                mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2],
                                          0.6 + pulse * 0.4);
                mgraphics.move_to(kx - 3, h - 5);
                mgraphics.show_text("" + k);
            }
        }
    } else {
        for (ms = 250; ms < MAX_MS; ms += 250) {
            x = ms_to_x(ms);
            mgraphics.set_source_rgba(GRID_CLR);
            mgraphics.set_line_width(1.0);
            mgraphics.move_to(x, plot_t());
            mgraphics.line_to(x, plot_b());
            mgraphics.stroke();
            if (ms % 500 === 0) {
                mgraphics.set_source_rgba(TEXT_CLR);
                mgraphics.move_to(x - 8, h - 5);
                mgraphics.show_text((ms / 1000).toFixed(1) + "s");
            }
        }
    }

    // Lane center lines.
    mgraphics.set_source_rgba(LANE_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(plot_l(), lane_y(0)); mgraphics.line_to(plot_r(), lane_y(0)); mgraphics.stroke();
    mgraphics.move_to(plot_l(), lane_y(1)); mgraphics.line_to(plot_r(), lane_y(1)); mgraphics.stroke();
    mgraphics.set_source_rgba(TEXT_CLR);
    mgraphics.set_font_size(7.5);
    mgraphics.move_to(plot_l() + 3, lane_y(0) - 7);
    mgraphics.show_text("L");
    mgraphics.move_to(plot_l() + 3, lane_y(1) - 7);
    mgraphics.show_text("R");

    // ── THE ENERGY RIVER: the real per-lane recirculating energy flows down the
    // delay ruler as a glowing thermal ribbon (thickness + brightness = the live
    // signal). Peaks feed the recirculation-loop glow below.
    var peakL = draw_river(tideL, lane_y(0));
    var peakR = draw_river(tideR, lane_y(1));

    // ── FEEDBACK LOOP: a luminous recirculation arc from the tail back to the
    // source, brightening with feedback x live energy — faint when low, a bright
    // continuous loop near self-oscillation (a gorgeous, functional runaway cue).
    var fb_amt = clamp(feedback_pct / 110.0, 0, 1);
    var loop_pk = peakL > peakR ? peakL : peakR;
    var loop_a = fb_amt * (0.08 + 0.52 * loop_pk);
    if (loop_a > 0.02 && !frozen) {
        var tail_ms = clamp(time_ms * 3.0, time_ms, MAX_MS);
        var src_x = ms_to_x(0) + 2;
        var tail_x = ms_to_x(tail_ms);
        thermal(0.55 + 0.4 * fb_amt, _thc);
        var lli, lyy, lift;
        for (lli = 0; lli < 2; lli++) {
            lyy = lane_y(lli);
            lift = (lli === 0 ? -1 : 1) * plot_h() * 0.24;
            glow_bezier(tail_x, lyy,
                        tail_x * 0.5 + src_x * 0.5, lyy + lift,
                        tail_x * 0.2 + src_x * 0.8, lyy + lift,
                        src_x, lyy, _thc, 1.3, loop_a);
        }
    }

    // ── SOURCE BLOOM: the origin at t=0 flares white-hot with each transient —
    // the birthplace of every wave. FREEZE stills it to an ice-crystal ring.
    var wet = clamp(wet_lvl, 0, 1);
    var in_x = ms_to_x(0) + 2;
    var li0;
    for (li0 = 0; li0 < 2; li0++) {
        if (frozen) {
            mgraphics.set_source_rgba(ICE_CLR[0], ICE_CLR[1], ICE_CLR[2], 0.85);
            mgraphics.set_line_width(1.3);
            mgraphics.arc(in_x, lane_y(li0), 3.4, 0, Math.PI * 2); mgraphics.stroke();
            mgraphics.arc(in_x, lane_y(li0), 6.2, 0, Math.PI * 2); mgraphics.stroke();
            continue;
        }
        thermal(0.55 + 0.45 * wet, _thc);
        ds_node_glow(in_x, lane_y(li0), _thc, 7.0 + wet * 16.0, 0.30 + wet * 0.55);
        mgraphics.set_source_rgba(0.96, 0.99, 1.0, 0.5 + wet * 0.5);
        mgraphics.arc(in_x, lane_y(li0), 2.6 + wet * 1.6, 0, Math.PI * 2); mgraphics.fill();
    }

    // ── ECHO COMETS: each repeat is a comet sized + coloured by the REAL
    // recirculating energy at its delay position (audio-reactive), bounded by the
    // feedback-decay envelope; L/R react to their own channel; later echoes recede
    // into depth with a ghost trail for flow direction. No tide feed -> the
    // geometric envelope alone (backward compatible / Node harness).
    var fb = clamp(feedback_pct / 100.0, 0.0, 1.1);
    var amp = fb;
    var duck = clamp(duck_lvl, 0, 1);
    var dim = 1.0 - duck * 0.72;
    var has_tide = tideL ? 1 : 0;
    var tap_px = ms_to_x(time_ms) - ms_to_x(0);   // one delay in px (ghost spacing)
    var mid_y = plot_t() + plot_h() * 0.5;
    var t = time_ms;
    var n = 0;
    var li, active_lane;
    while (amp > 0.02 && t <= MAX_MS && n < 24) {
        x = ms_to_x(t) + wob_live * 4.0;             // tape-wobble sway
        active_lane = (n % 2 === 0) ? 1 : 0;         // ping-pong: which lane
        var depth = 1.0 - clamp(n / 26.0, 0, 0.5);   // 1.0 near -> 0.5 into the tail
        for (li = 0; li < 2; li++) {
            if (pingpong && li !== active_lane) continue;
            var ly = lane_y(li);
            ly = ly + (mid_y - ly) * (1.0 - depth) * 0.55;   // converge to a horizon
            // SPREAD drifts L/R apart, accumulating over the repeats (the DSP
            // diverges the channels each pass) — you see the stereo spread open.
            var cx = x + (li === 1 ? 1 : -1)
                     * clamp(spread_pct * 0.01 * (1.5 + n * 0.7), 0, 14);
            var real = has_tide ? tide_energy(li === 0 ? tideL : tideR, t) : -1.0;
            var ramp = (real < 0)
                ? amp
                : amp * clamp(REACT_FLOOR + REACT_GAIN * real, 0, REACT_CEIL);
            var lvl = clamp(ramp, 0, 1) * dim * depth;
            var size = (1.8 + ramp * 6.0) * depth
                       * (1.0 - (damp_pct / 100.0) * 0.4 * clamp(n / 8.0, 0, 1));
            if (size < 0.8) size = 0.8;
            thermal(clamp(ramp, 0, 1), _thc);
            // Ghost trail: two faded dots trailing back toward the previous tap
            // (skipped on dim echoes — invisible + saves fills). REVERSE flips
            // the trail forward: each grain plays backward, so the flow leads.
            if (lvl > 0.05) {
                var gt, gx;
                var tdir = reversed ? 1 : -1;
                for (gt = 1; gt <= 2; gt++) {
                    gx = cx + tdir * tap_px * 0.16 * gt;
                    if (tdir < 0 ? gx < in_x : gx > plot_r() - 2) break;
                    mgraphics.set_source_rgba(_thc[0], _thc[1], _thc[2], lvl * 0.16 / gt);
                    mgraphics.arc(gx, ly, size * (0.68 - gt * 0.16), 0, Math.PI * 2);
                    mgraphics.fill();
                }
            }
            // Bloom (radial gradient — the priciest per-comet op, so only for
            // comets bright enough to show it) + thermal core on top.
            if (lvl > 0.06) {
                ds_node_glow(cx, ly, _thc, size + 6.0 + ramp * 11.0, 0.18 + lvl * 0.55);
            }
            mgraphics.set_source_rgba(_thc[0], _thc[1], _thc[2], 0.42 + lvl * 0.58);
            mgraphics.arc(cx, ly, size, 0, Math.PI * 2);
            mgraphics.fill();
            // White-hot sparkle on a live transient (real energy above the floor).
            if (real > 0.46) {
                mgraphics.set_source_rgba(0.96, 0.99, 1.0, (real - 0.46) * 1.5 * dim);
                mgraphics.arc(cx, ly, size * 0.52, 0, Math.PI * 2);
                mgraphics.fill();
            }
            // SATURATION grit: the in-loop drive hardens each pass — drawn as a
            // hot rim ring around lit comets, growing with SAT x brightness.
            if (sat_pct > 1.0 && lvl > 0.12) {
                mgraphics.set_source_rgba(1.0, 0.72, 0.36,
                                          sat_pct * 0.01 * (0.25 + lvl * 0.55));
                mgraphics.set_line_width(1.1);
                mgraphics.arc(cx, ly, size + 1.6, 0, Math.PI * 2);
                mgraphics.stroke();
            }
        }
        n += 1;
        t += time_ms;
        amp *= fb;
    }

    // Border (skipped when the device passes an alpha-0 border for a
    // borderless, float-on-the-faceplate hero) + readout.
    if (BORDER_CLR.length < 4 || BORDER_CLR[3] > 0.01) {
        mgraphics.set_source_rgba(BORDER_CLR);
        mgraphics.set_line_width(1.0);
        mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
        mgraphics.stroke();
    }

    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.set_font_size(8.0);
    mgraphics.move_to(plot_l() + 16, plot_t() + 11);
    var time_txt = sync_label === "FREE" ? (Math.round(time_ms) + " ms") : sync_label;
    mgraphics.show_text(time_txt + "   FB " + Math.round(feedback_pct) + "%");
    if (pingpong) {
        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.move_to(plot_l() + 16, plot_t() + 21);
        mgraphics.show_text("PING-PONG");
    }
    if (frozen) {
        mgraphics.set_source_rgba(ICE_CLR[0], ICE_CLR[1], ICE_CLR[2], 0.9);
        mgraphics.set_font_size(7.5);
        mgraphics.move_to(plot_l() + 16, plot_t() + 21 + (pingpong ? 10 : 0));
        mgraphics.show_text("FROZEN");
    }
    if (reversed) {
        // Warm tape-amber badge + a wee left arrowhead: the line runs backward.
        var rv_y = plot_t() + 21 + (pingpong ? 10 : 0) + (frozen ? 10 : 0);
        mgraphics.set_source_rgba(0.98, 0.64, 0.30, 0.92);
        mgraphics.set_font_size(7.5);
        mgraphics.move_to(plot_l() + 16, rv_y);
        mgraphics.show_text("REVERSE");
        mgraphics.move_to(plot_l() + 14, rv_y - 6);
        mgraphics.line_to(plot_l() + 14, rv_y - 1);
        mgraphics.line_to(plot_l() + 9, rv_y - 3.5);
        mgraphics.close_path();
        mgraphics.fill();
    }

    // MIX readout — bottom-right, persistent (mix is not otherwise drawn on the
    // trail). While a Cmd=mix / Alt=damp gesture is active it brightens into a
    // value bezel showing the param being changed.
    var gr_x = plot_r() - 6;
    var gr_y = plot_b() - 5;
    mgraphics.set_font_size(7.5);
    if (gesture_ttl > 0 && gesture_label !== "") {
        var ga = clamp(gesture_ttl / 22.0, 0, 1);
        var gw = gesture_label.length * 4.7;
        mgraphics.set_source_rgba(0.05, 0.06, 0.09, 0.55 * ga);
        mgraphics.rectangle(gr_x - gw - 5, gr_y - 10, gw + 8, 13);
        mgraphics.fill();
        mgraphics.set_source_rgba(ACCENT_CLR[0], ACCENT_CLR[1], ACCENT_CLR[2], 0.62 + 0.38 * ga);
        mgraphics.move_to(gr_x - gw - 1, gr_y);
        mgraphics.show_text(gesture_label);
        gesture_ttl -= 1;
    } else if (!(hovering && !dragging)) {
        // Persistent MIX (hidden while the hover-preview owns the bottom edge).
        var mtxt = "MIX " + Math.round(mix_pct) + "%";
        mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.5);
        mgraphics.move_to(gr_x - mtxt.length * 4.7, gr_y);
        mgraphics.show_text(mtxt);
    }

    // it177: DUCK activity badge (top-right). An amber "DUCK ▾" + meter bar that
    // IGNITES with the live duck depth so the rail-only Duck knob has a hero
    // tell: idle = faint outline, ducking = bright amber. Pairs with the
    // whole-trail dim above (the echoes recede as this lights up).
    var dk = clamp(duck_lvl, 0, 1);
    var bx = plot_r() - 52;
    var by = plot_t() + 6;
    mgraphics.set_font_size(7.5);
    mgraphics.set_source_rgba(0.96, 0.66, 0.26, 0.28 + dk * 0.72);
    mgraphics.move_to(bx, by + 6);
    mgraphics.show_text("DUCK");
    // Downward chevron — brightens with the duck depth.
    mgraphics.set_source_rgba(0.96, 0.66, 0.26, 0.22 + dk * 0.78);
    mgraphics.move_to(bx + 27, by + 1);
    mgraphics.line_to(bx + 33, by + 1);
    mgraphics.line_to(bx + 30, by + 5.5);
    mgraphics.close_path();
    mgraphics.fill();
    // Thin meter: faint track + amber fill proportional to the live duck.
    mgraphics.set_source_rgba(0.96, 0.66, 0.26, 0.16);
    mgraphics.rectangle(bx, by + 9, 44, 2.5);
    mgraphics.fill();
    mgraphics.set_source_rgba(0.96, 0.66, 0.26, 0.88);
    mgraphics.rectangle(bx, by + 9, 44 * dk, 2.5);
    mgraphics.fill();

    // CORR readout (fed via set_corr; hidden until the first value arrives) —
    // lives under the DUCK badge. Dim while the image is healthy; warms toward
    // amber as the channels decorrelate (the phase-watch moment).
    if (corr_lvl > -1.5) {
        var cwarn = corr_lvl < 0.25 ? clamp((0.25 - corr_lvl) * 1.2, 0, 1) : 0;
        mgraphics.set_font_size(7.0);
        mgraphics.set_source_rgba(0.63 + 0.33 * cwarn, 0.64, 0.66 - 0.38 * cwarn,
                                  0.42 + 0.5 * cwarn);
        mgraphics.move_to(bx, by + 20);
        mgraphics.show_text("CORR " + corr_lvl.toFixed(2));
    }

    // Hover preview: a faint vertical crosshair at the cursor + the time/feedback
    // a click would set (the pad is absolute, X=time and Y=feedback). Time shows
    // only in FREE mode (in synced mode the X drag is overridden by the division).
    if (hovering && !dragging) {
        var hx = clamp(hover_x, plot_l(), plot_r());
        var hms = clamp((hx - plot_l()) / plot_w() * MAX_MS, 1.0, MAX_MS);
        var hfb = clamp((plot_b() - clamp(hover_y, plot_t(), plot_b())) / plot_h() * 110.0, 0.0, 110.0);
        mgraphics.set_source_rgba(ACCENT_CLR[0], ACCENT_CLR[1], ACCENT_CLR[2], 0.30);
        mgraphics.set_line_width(1.0);
        mgraphics.move_to(hx, plot_t()); mgraphics.line_to(hx, plot_b()); mgraphics.stroke();
        var lbl = (sync_label === "FREE" ? (Math.round(hms) + " ms · ") : "") + Math.round(hfb) + "%";
        var lx = hx + 4; if (lx > plot_r() - 70) lx = hx - 72;
        mgraphics.set_source_rgba(ACCENT_CLR[0], ACCENT_CLR[1], ACCENT_CLR[2], 0.9);
        mgraphics.set_font_size(7.5);
        mgraphics.move_to(lx, plot_b() - 4);
        mgraphics.show_text(lbl);
    }
}

// ── Messages ─────────────────────────────────────────────────────────
function set_time(v)       { time_ms = clamp(v, 1.0, MAX_MS); mgraphics.redraw(); }
function set_feedback(v)   { feedback_pct = clamp(v, 0.0, 110.0); mgraphics.redraw(); }
function set_damp(v)       { damp_pct = clamp(v, 0.0, 100.0); mgraphics.redraw(); }
function set_mix(v)        { mix_pct = clamp(v, 0.0, 100.0); mgraphics.redraw(); }
function set_width(v)      { width_pct = clamp(v, 0.0, 200.0); mgraphics.redraw(); }
function set_spread(v)     { spread_pct = clamp(v, 0.0, 100.0); mgraphics.redraw(); }
function set_tone(v)       { tone_pct = clamp(v, -100.0, 100.0); mgraphics.redraw(); }
function set_sat(v)        { sat_pct = clamp(v, 0.0, 100.0); mgraphics.redraw(); }
// Live transport beat phase (plugsync~, throttled device-side). NO redraw here —
// the tide poll's 30 Hz redraw carries the pulse animation for free.
function set_beat(v)       { beat_ph = clamp(v, 0.0, 1.0); }
function set_pingpong(v)   { pingpong = v ? 1 : 0; mgraphics.redraw(); }
function set_sync_label(v) { sync_label = "" + v; mgraphics.redraw(); }
function wet_level(v) { wet_lvl = v; mgraphics.redraw(); }
function set_duck(v) { duck_lvl = clamp(v, 0.0, 1.0); mgraphics.redraw(); }
// CHARACTER (DIGITAL/TAPE/BBD): tape + bucket-brigade lose top end each pass, so
// later repeats warm toward amber and dim. DIGITAL (0, default) leaves the taps
// the clean accent colour -> the trail is unchanged at the default.
function set_character(v) { character = clamp(Math.round(v), 0, 2); mgraphics.redraw(); }
// FREEZE: the loop holds (unity feedback, input gated) — tide turns ice, the
// input pulse hollows out, and a FROZEN badge joins the readout.
function set_freeze(v) { frozen = v ? 1 : 0; mgraphics.redraw(); }

// Reverse-echo mode: ghost trails lead forward + a REVERSE badge joins the
// readout stack (the DSP plays each grain backward).
function set_reverse(v) { reversed = v ? 1 : 0; mgraphics.redraw(); }

// Live output stereo correlation (+1 mono / 0 wide / -1 anti-phase) — drawn
// as a readout under the DUCK badge, warming amber as the image decorrelates.
function set_corr(v) { corr_lvl = clamp(v, -1.0, 1.0); mgraphics.redraw(); }

// ── TIDE feed (Device.add_viz_bus contract) ──────────────────────────
function set_buffers() {
    var args = arrayfromargs(arguments);
    if (args.length > 0) tide_name = "" + args[0];
    start_tide_poll();
}

function poll_tide() {
    if (tide_name === "") return;
    try {
        var b = new Buffer(tide_name);
        var l = b.peek(1, 0, TIDE_SLOTS);
        var r = b.peek(2, 0, TIDE_SLOTS);
        if (l && l.length >= TIDE_SLOTS && r && r.length >= TIDE_SLOTS) {
            tideL = l;
            tideR = r;
            tide_head = ((Math.round(l[TIDE_BINS]) % TIDE_BINS) + TIDE_BINS) % TIDE_BINS;
            wob_live = clamp(l[TIDE_BINS + 1], -1.0, 1.0);
            mgraphics.redraw();
        }
    } catch (e) { /* buffer~ not instantiated yet — retry next tick */ }
}

function start_tide_poll() {
    if (tide_poll !== null) return;
    if (typeof Task !== "undefined") {
        tide_poll = new Task(poll_tide);
        tide_poll.interval = 33;
        tide_poll.repeat();
    }
}

// Age (ms back from "now") -> perceptually-shaped 0..1 energy from one
// tide channel. Powers the real tap ignition + re-injection arcs.
function tide_energy(arr, age_ms) {
    if (!arr) return 0.0;
    var bin_ms = MAX_MS / TIDE_BINS;
    var age_bins = Math.floor(age_ms / bin_ms);
    if (age_bins < 0 || age_bins >= TIDE_BINS) return 0.0;
    var idx = ((tide_head - age_bins) % TIDE_BINS + TIDE_BINS) % TIDE_BINS;
    var raw = arr[idx];
    if (!(raw > 0.0)) return 0.0;
    var v = raw * 1.15;
    if (v > 1.0) v = 1.0;
    return Math.pow(v, 0.55);
}

// ── Interaction: ABSOLUTE X/Y pad ────────────────────────────────────
// Robust pointer-coordinate resolution. Max's v8ui pointer events expose the
// object-local position under DIFFERENT property names across runtimes
// (.x / .localX / .offsetX / .clientX); reading only '.x' returned undefined
// in Live -> (undefined - plot_l()) = NaN -> time/feedback slammed to the rails
// (and the readout showed "NaN ms"). This is the exact helper set eq_curve uses
// (that engine drags reliably). The legacy onclick/ondrag path already passes
// real object-local pixels, so it needs no resolver.
//__POINTER_X__//
//__POINTER_Y__//
//__POINTER_BUTTONS__//
// Cross-runtime modifier reads: v8ui pointer events expose .commandKey (NOT
// metaKey) and .altKey/.optionKey; the classic jsui path passes positional
// booleans. These prefer the pointerevent, fall back to the boolean.
function pointer_command_key(pe, cmd) {
    if (pe && (pe.commandKey || pe.controlKey)) return 1;
    return cmd ? 1 : 0;
}
function pointer_option_key(pe, opt) {
    if (pe && (pe.altKey || pe.optionKey)) return 1;
    return opt ? 1 : 0;
}
// Gesture mode from modifiers: 1 = mix (Cmd/Ctrl), 2 = damp (Alt/Opt), 0 =
// feedback (plain). Cmd wins if both are held.
function drag_mode_of(pe, cmd, opt) {
    if (pointer_command_key(pe, cmd)) return 1;
    if (pointer_option_key(pe, opt)) return 2;
    return 0;
}
function flash_bezel(label) { gesture_label = label; gesture_ttl = 22; }

function start_drag(x, y) {
    dragging = 1;
    // Anchor every axis for shift=fine (relative-to-press, clamped — cannot
    // slam), so any modifier pressed AFTER the press still fine-adjusts.
    drag_start_time = time_ms;
    drag_start_feedback = feedback_pct;
    drag_start_mix = mix_pct;
    drag_start_damp = damp_pct;
}

// ABSOLUTE X/Y pad: the pointer POSITION maps directly to time (x, along the
// ruler) and feedback (y, up = more) — not a relative start+delta. Bounded by
// the plot, so a stray pointer frame can never slam the values to the rails
// (the relative model did exactly that live). The isNaN guard is belt-and-
// suspenders: if every coordinate property is missing we leave state untouched
// rather than poisoning time_ms with NaN.
// ABSOLUTE X/Y pad with a modifier matrix. mode 0 = plain (X=time, Y=feedback,
// today's behaviour verbatim); mode 1 = Cmd (Y=mix, TIME LOCKED); mode 2 = Alt
// (Y=damp, TIME LOCKED). Modifier drags leave X/time untouched so you set
// mix/damp without disturbing the delay time (eq_curve "hold one axis, drive
// another"). Shift = fine (1/5 from the press anchor, per axis). isNaN guard
// keeps a missing-coordinate frame from poisoning state.
function drag_to(x, y, fine, mode) {
    if (!dragging) return;
    if (isNaN(x) || isNaN(y)) return;
    var fy = clamp((plot_b() - y) / plot_h(), 0.0, 1.0);
    if (mode === 1) {                 // Cmd -> MIX (time held)
        var m_target = clamp(fy * 100.0, 0.0, 100.0);
        if (fine) m_target = drag_start_mix + (m_target - drag_start_mix) * 0.20;
        mix_pct = clamp(m_target, 0.0, 100.0);
        outlet(0, "mix", Math.round(mix_pct));
        flash_bezel("MIX " + Math.round(mix_pct) + "%");
    } else if (mode === 2) {          // Alt -> DAMP (time held)
        var d_target = clamp(fy * 100.0, 0.0, 100.0);
        if (fine) d_target = drag_start_damp + (d_target - drag_start_damp) * 0.20;
        damp_pct = clamp(d_target, 0.0, 100.0);
        outlet(0, "damp", Math.round(damp_pct));
        flash_bezel("DAMP " + Math.round(damp_pct) + "%");
    } else {                          // plain -> X=time, Y=feedback
        var fx = clamp((x - plot_l()) / plot_w(), 0.0, 1.0);
        var t_target = clamp(fx * MAX_MS, 1.0, MAX_MS);
        var f_target = clamp(fy * 110.0, 0.0, 110.0);
        if (fine) {
            t_target = drag_start_time + (t_target - drag_start_time) * 0.20;
            f_target = drag_start_feedback + (f_target - drag_start_feedback) * 0.20;
        }
        time_ms = clamp(t_target, 1.0, MAX_MS);
        feedback_pct = clamp(f_target, 0.0, 110.0);
        outlet(0, "time", Math.round(time_ms));
        outlet(0, "feedback", Math.round(feedback_pct));
    }
    mgraphics.redraw();
}

function end_drag() {
    if (!dragging) return;
    dragging = 0;
    mgraphics.redraw();
}

// Double-click resets the X/Y pad to its defaults (both time and feedback).
function reset_pad() {
    time_ms = clamp(RESET_TIME, 1.0, MAX_MS);
    feedback_pct = clamp(RESET_FB, 0.0, 110.0);
    outlet(0, "time", Math.round(time_ms));
    outlet(0, "feedback", Math.round(feedback_pct));
    mgraphics.redraw();
}

function pointer_alt_key(pe) { return (pe && pe.altKey) ? 1 : 0; }

// Opt-click toggles PING-PONG (the trail VISUALISES it — taps alternate L/R
// lanes), a direct-manipulation toggle right where the effect is shown. A bare
// click never moves the pad (start_drag only anchors; drag_to applies), so this
// does not disturb the time/feedback drag.
function toggle_pingpong() {
    pingpong = pingpong ? 0 : 1;
    outlet(0, "pingpong", pingpong);
    mgraphics.redraw();
}

function onpointerdown(pe) {
    drag_start_x = pointer_x(pe, plot_l());
    drag_start_y = pointer_y(pe, plot_b());
    // Alt overloads: a bare alt-CLICK toggles ping-pong (it163); an alt-DRAG is
    // the DAMP axis of the gesture matrix. Arm a pending toggle; the move/up
    // handlers then decide (eq_curve's alt_drag_pending pattern).
    alt_pending = pointer_alt_key(pe) ? 1 : 0;
    start_drag(drag_start_x, drag_start_y);
}
function onpointermove(pe) {
    var b = pointer_buttons(pe, 0);
    if (dragging && ((b & 1) !== 0)) {
        var px = pointer_x(pe, plot_l()), py = pointer_y(pe, plot_b());
        if (alt_pending) {
            // Hold until it's clearly a drag (past a small dead-zone); a bare
            // alt-click stays a ping-pong toggle (resolved on release).
            if (Math.abs(px - drag_start_x) > 3 || Math.abs(py - drag_start_y) > 3) {
                alt_pending = 0;
            } else { return; }
        }
        drag_to(px, py, pe && pe.shiftKey ? 1 : 0, drag_mode_of(pe, 0, 0));
        return;
    }
    if (dragging && b === 0) { end_drag(); return; }
    // Track the hover position so paint() can draw a crosshair + a preview of the
    // time/feedback a click here would set (the X/Y pad is absolute). The
    // hovering flag was already set but never read; this wires that affordance.
    hover_x = pointer_x(pe, hover_x);
    hover_y = pointer_y(pe, hover_y);
    hovering = 1;
    mgraphics.redraw();
}
function onpointerup(pe) {
    // A bare alt-click (never dragged past the dead-zone) toggles ping-pong.
    if (alt_pending) { toggle_pingpong(); alt_pending = 0; }
    end_drag();
}
function onpointerleave(pe) { alt_pending = 0; hovering = 0; end_drag(); mgraphics.redraw(); }
function ondblclick(x, y, but, cmd, shift, caps, opt, ctrl) { reset_pad(); }

function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { start_drag(x, y); }
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but) drag_to(x, y, shift, drag_mode_of(null, cmd, opt));
    else end_drag();
}
function onidle(x, y) { hover_x = x; hover_y = y; hovering = 1; mgraphics.redraw(); }
function onidleout() { hovering = 0; mgraphics.redraw(); }

// Wheel modifier matrix (the fleet Para EQ grammar): plain = feedback, Cmd/Ctrl =
// mix, Alt/Opt = damp; Shift = fine. "Scroll up = more" throughout.
function onwheel(x, y, scrollx, scrolly, cmd, shift, caps, opt, ctrl) {
    var dir = scrolly > 0 ? 1 : -1;
    var step = (shift ? 0.5 : 2.0) * dir;
    if (pointer_command_key(null, cmd)) {
        mix_pct = clamp(mix_pct + step, 0, 100);
        outlet(0, "mix", Math.round(mix_pct));
        flash_bezel("MIX " + Math.round(mix_pct) + "%");
    } else if (pointer_option_key(null, opt)) {
        damp_pct = clamp(damp_pct + step, 0, 100);
        outlet(0, "damp", Math.round(damp_pct));
        flash_bezel("DAMP " + Math.round(damp_pct) + "%");
    } else {
        feedback_pct = clamp(feedback_pct + step, 0, 110);
        outlet(0, "feedback", Math.round(feedback_pct));
    }
    mgraphics.redraw();
}

//__ONRESIZE__//
""")
