"""Scrolling multi-band energy-history display (jsui).

A premium hero for layered / character effects: each inlet receives one band's
level (0..~1.3) as a float, and the display scrolls a stacked history so you can
watch every band's energy move over time. Bands are drawn back-to-front in the
order given (put the big filled layer first, accents last). Reusable across the
kit devices — e.g. an 808 knocker's KNOCK / SUB / PUNCH layers.

Wire a ``peakamp~`` (or any 0..1 level source) into each inlet; band ``i`` ->
inlet ``i``. ES5 jsui, no external dependencies.
"""

from string import Template

__all__ = ["energy_history_inlets", "energy_history_js"]


def energy_history_inlets(bands):
    """Number of inlets a display with these ``bands`` needs (one per band)."""
    return len(bands)


def _band_literal(b):
    color = b["color"]
    mode = 1 if b.get("mode", "fill") == "line" else 0
    line_width = float(b.get("line_width", 1.8))
    return "{c:[%s], m:%d, lw:%s}" % (color, mode, line_width)


def energy_history_js(
    bands,
    *,
    bg_color="0.09, 0.11, 0.09, 1.0",
    grid_color="0.22, 0.30, 0.22, 0.5",
    length=140,
    rate_hz=30.0,
    decay=0.55,
):
    """Return ES5 jsui source for a scrolling multi-band energy history.

    Args:
        bands: ordered (back-to-front) list of band dicts:
            ``{"color": "r, g, b, a", "mode": "fill"|"line",
               "line_width": float}``. ``mode`` defaults to ``"fill"``.
        bg_color / grid_color: ``"r, g, b, a"`` strings.
        length: number of history columns (older -> newer, left -> right).
        rate_hz: scroll / repaint rate.
        decay: per-tick multiplier applied to each band's latest value so a
            transient spikes then rings out (0..1).
    """
    if not bands:
        raise ValueError("energy_history_js needs at least one band")
    bands_js = ", ".join(_band_literal(b) for b in bands)
    return _JS_TEMPLATE.substitute(
        bg=bg_color,
        grid=grid_color,
        length=int(length),
        interval=int(round(1000.0 / float(rate_hz))),
        decay=decay,
        bands=bands_js,
    )


_JS_TEMPLATE = Template("""\
// energy_history -- scrolling multi-band energy display. generated by build.py.
mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

var BG = [$bg];
var GRID = [$grid];
var L = $length;
var DECAY = $decay;
var BANDS = [$bands];
var NB = BANDS.length;
inlets = NB;
outlets = 0;

var hist = [];
var cur = [];
var bi, ii;
for (bi = 0; bi < NB; bi++) {
    hist[bi] = [];
    for (ii = 0; ii < L; ii++) { hist[bi][ii] = 0.0; }
    cur[bi] = 0.0;
}

function clampv(v) { return v < 0 ? 0 : (v > 1.3 ? 1.3 : v); }
function msg_float(v) { cur[inlet] = clampv(v); }
function list() { cur[inlet] = clampv(arguments[0]); }

function paint() {
    var w = mgraphics.size[0], h = mgraphics.size[1];
    var b, i, g;

    mgraphics.set_source_rgba(BG[0], BG[1], BG[2], BG[3]);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();

    mgraphics.set_source_rgba(GRID[0], GRID[1], GRID[2], GRID[3]);
    mgraphics.set_line_width(1.0);
    for (g = 1; g <= 3; g++) {
        var gy = h * g / 4.0;
        mgraphics.move_to(0, gy);
        mgraphics.line_to(w, gy);
        mgraphics.stroke();
    }

    var colW = w / (L - 1);
    for (b = 0; b < NB; b++) {
        var c = BANDS[b];
        if (c.m === 0) {
            mgraphics.set_source_rgba(c.c[0], c.c[1], c.c[2], c.c[3]);
            mgraphics.move_to(0, h);
            for (i = 0; i < L; i++) {
                mgraphics.line_to(i * colW, h - hist[b][i] * h);
            }
            mgraphics.line_to(w, h);
            mgraphics.close_path();
            mgraphics.fill();
        } else {
            mgraphics.set_source_rgba(c.c[0], c.c[1], c.c[2], c.c[3]);
            mgraphics.set_line_width(c.lw);
            mgraphics.move_to(0, h - hist[b][0] * h);
            for (i = 1; i < L; i++) {
                mgraphics.line_to(i * colW, h - hist[b][i] * h);
            }
            mgraphics.stroke();
        }
    }
}

function tick() {
    var b;
    for (b = 0; b < NB; b++) {
        hist[b].shift();
        hist[b].push(cur[b]);
        cur[b] = cur[b] * DECAY;
    }
    mgraphics.redraw();
}
var _task = new Task(tick, this);
_task.interval = $interval;
_task.repeat();

mgraphics.redraw();
""")
