"""Selected-band control column engine for EQ-family devices.

Generates ES5 JavaScript for Max's jsui object. The display is intended to sit
beside a graph-based EQ and provide a compact, knob-first selected-band editor
that follows graph selection.

Communication uses 1 inlet and 1 outlet.

Inlet 0 messages:
    set_num_bands N
    set_band band_idx freq gain q type enabled [motion] [dynamic]
             [dynamic_amount] [motion_rate] [motion_depth] [motion_direction]
    set_motion band_idx enabled
    set_dynamic band_idx enabled
    set_motion_rate band_idx hz
    set_motion_depth band_idx percent
    set_motion_direction band_idx degrees
    set_selected band_idx

Outlet 0:
    band_freq band_idx freq
    band_gain band_idx gain
    band_q band_idx q
    band_type band_idx type
    band_slope band_idx slope
    band_enable band_idx enabled
    band_solo band_idx solo
    band_motion band_idx enabled
    band_dynamic band_idx enabled
    band_motion_rate band_idx hz
    band_motion_depth band_idx percent
    band_motion_direction band_idx degrees
"""

from __future__ import annotations

import json
from string import Template


EQ_BAND_COLUMN_INLETS = 1
EQ_BAND_COLUMN_OUTLETS = 1


def eq_band_column_js(
    *,
    title="SELECTED BAND",
    subtitle="Node-focused controls",
    type_names=None,
    type_short_names=None,
    gain_enabled_types=None,
    slope_enabled_types=None,
    show_slope=False,
    show_solo=False,
    show_motion=False,
    show_dynamic=False,
    show_type_controls=True,
    show_toggle_stack=True,
    show_header=True,
    show_frame=True,
    force_regular_layout=False,
    bg_color="0.09, 0.10, 0.12, 1.0",
    panel_color="0.08, 0.09, 0.11, 1.0",
    border_color="0.18, 0.20, 0.24, 1.0",
    text_color="0.92, 0.95, 1.0, 1.0",
    text_dim_color="0.46, 0.50, 0.58, 1.0",
    accent_color="0.86, 0.90, 0.98, 1.0",
    motion_accent_color="0.34, 0.86, 0.98, 1.0",
    knob_fill_color="0.12, 0.14, 0.18, 1.0",
    knob_track_color="0.21, 0.24, 0.30, 1.0",
    disabled_color="0.22, 0.24, 0.28, 1.0",
    enable_color="0.28, 0.82, 0.56, 1.0",
    solo_color="0.92, 0.76, 0.24, 1.0",
    font_name="Ableton Sans Medium",
    font_bold_name="Ableton Sans Bold",
):
    """Return JavaScript source for an EQ selected-band control column."""
    if type_names is None:
        type_names = ["Peak", "LShelf", "HShelf", "LP", "HP", "Notch", "BP", "AP"]
    if type_short_names is None:
        type_short_names = ["PK", "LS", "HS", "LP", "HP", "NT", "BP", "AP"]
    if gain_enabled_types is None:
        gain_enabled_types = [0, 1, 2]
    if slope_enabled_types is None:
        slope_enabled_types = []

    return _JS_TEMPLATE.substitute(
        title=json.dumps(title),
        subtitle=json.dumps(subtitle),
        type_names=json.dumps(type_names),
        type_short_names=json.dumps(type_short_names),
        gain_enabled_types=json.dumps(gain_enabled_types),
        slope_enabled_types=json.dumps(slope_enabled_types),
        show_slope="1" if show_slope else "0",
        show_solo="1" if show_solo else "0",
        show_motion="1" if show_motion else "0",
        show_dynamic="1" if show_dynamic else "0",
        show_type_controls="1" if show_type_controls else "0",
        show_toggle_stack="1" if show_toggle_stack else "0",
        show_header="1" if show_header else "0",
        show_frame="1" if show_frame else "0",
        force_regular_layout="1" if force_regular_layout else "0",
        bg_color=bg_color,
        panel_color=panel_color,
        border_color=border_color,
        text_color=text_color,
        text_dim_color=text_dim_color,
        accent_color=accent_color,
        motion_accent_color=motion_accent_color,
        knob_fill_color=knob_fill_color,
        knob_track_color=knob_track_color,
        disabled_color=disabled_color,
        enable_color=enable_color,
        solo_color=solo_color,
        font_name=json.dumps(font_name),
        font_bold_name=json.dumps(font_bold_name),
    )


_JS_TEMPLATE = Template("""\
// EQ Selected-Band Column - generated by m4l-builder
// ES5 compatible for Max jsui

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var TITLE = $title;
var SUBTITLE = $subtitle;
var TYPE_NAMES = $type_names;
var TYPE_SHORT_NAMES = $type_short_names;
var GAIN_ENABLED_TYPES = $gain_enabled_types;
var SLOPE_ENABLED_TYPES = $slope_enabled_types;
var SHOW_SLOPE = $show_slope;
var SHOW_SOLO = $show_solo;
var SHOW_MOTION = $show_motion;
var SHOW_DYNAMIC = $show_dynamic;
var SHOW_TYPE_CONTROLS = $show_type_controls;
var SHOW_TOGGLE_STACK = $show_toggle_stack;
var SHOW_HEADER = $show_header;
var SHOW_FRAME = $show_frame;
var FORCE_REGULAR_LAYOUT = $force_regular_layout;

var BG_COLOR = [$bg_color];
var PANEL_COLOR = [$panel_color];
var BORDER_COLOR = [$border_color];
var TEXT_COLOR = [$text_color];
var TEXT_DIM_COLOR = [$text_dim_color];
var ACCENT_COLOR = [$accent_color];
var MOTION_ACCENT_COLOR = [$motion_accent_color];
var KNOB_FILL_COLOR = [$knob_fill_color];
var KNOB_TRACK_COLOR = [$knob_track_color];
var DISABLED_COLOR = [$disabled_color];
var ENABLE_COLOR = [$enable_color];
var SOLO_COLOR = [$solo_color];
var FONT_NAME = $font_name;
var FONT_BOLD_NAME = $font_bold_name;

var MAX_BANDS = 8;
var MIN_FREQ = 20.0;
var MAX_FREQ = 20000.0;
var MIN_GAIN = -30.0;
var MAX_GAIN = 30.0;
var MIN_Q = 0.1;
var MAX_Q = 30.0;
var MIN_MOTION_RATE = 0.05;
var MAX_MOTION_RATE = 12.0;
var MIN_MOTION_DEPTH = 0.0;
var MAX_MOTION_DEPTH = 100.0;
var MIN_MOTION_DIRECTION = 0.0;
var MAX_MOTION_DIRECTION = 359.0;
var selected_band = -1;
var num_bands = 8;
var hover_control = "";
var drag_control = "";
var drag_start_y = 0;
var drag_start_value = 0.0;

var bands = [];
var i;

for (i = 0; i < MAX_BANDS; i++) {
    bands[i] = {
        freq: 1000.0,
        gain: 0.0,
        q: 1.0,
        type: 0,
        enabled: 1,
        slope: 0,
        solo: 0,
        motion: 0,
        dynamic: 0,
        dynamic_amount: 0.0,
        motion_rate: default_motion_rate(i),
        motion_depth: default_motion_depth(i),
        motion_direction: default_motion_direction(i)
    };
}

function clamp(v, lo, hi) {
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

function round_to(v, step) {
    if (step <= 0) return v;
    return Math.round(v / step) * step;
}

function has_index(list, idx) {
    var j;
    for (j = 0; j < list.length; j++) {
        if (list[j] === idx) return 1;
    }
    return 0;
}

function current_band() {
    if (selected_band < 0 || selected_band >= num_bands) return null;
    return bands[selected_band];
}

function motion_knobs_active(band) {
    return SHOW_MOTION && band && band.motion;
}

function uses_gain(type_idx) {
    return has_index(GAIN_ENABLED_TYPES, type_idx);
}

function uses_slope(type_idx) {
    return SHOW_SLOPE && has_index(SLOPE_ENABLED_TYPES, type_idx);
}

function supports_dynamic(type_idx) {
    return SHOW_DYNAMIC && uses_gain(type_idx);
}

function type_default_q(type_idx) {
    if (type_idx === 3 || type_idx === 4) return 0.707;
    return 1.0;
}

function default_motion_rate(idx) {
    var defaults = [0.18, 0.27, 0.39, 0.56, 0.80, 1.12, 1.48, 1.92];
    idx = Math.floor(idx);
    if (idx >= 0 && idx < defaults.length) return defaults[idx];
    return 0.56;
}

function default_motion_depth(idx) {
    var defaults = [18.0, 24.0, 30.0, 36.0, 44.0, 52.0, 60.0, 68.0];
    idx = Math.floor(idx);
    if (idx >= 0 && idx < defaults.length) return defaults[idx];
    return 36.0;
}

function default_motion_direction(idx) {
    var defaults = [0, 35, 70, 120, 165, 215, 285, 330];
    idx = Math.floor(idx);
    if (idx >= 0 && idx < defaults.length) return defaults[idx];
    return 0.0;
}

function clamp_motion_direction(value) {
    if (value === undefined || value !== value) return 0.0;
    while (value < 0.0) value += 360.0;
    while (value >= 360.0) value -= 360.0;
    return clamp(value, MIN_MOTION_DIRECTION, MAX_MOTION_DIRECTION);
}

function is_compact() {
    if (FORCE_REGULAR_LAYOUT) return 0;
    return mgraphics.size[0] <= 118 || mgraphics.size[1] <= 148;
}

function uses_minimal_rail_layout() {
    return FORCE_REGULAR_LAYOUT && !SHOW_HEADER && !SHOW_FRAME &&
        !SHOW_TYPE_CONTROLS && !SHOW_TOGGLE_STACK;
}

function knob_defs(band) {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var center_x = SHOW_TYPE_CONTROLS ? Math.floor(w * 0.5) : (SHOW_TOGGLE_STACK ? Math.floor(w * 0.41) : Math.floor(w * 0.5));
    var motion_pad = 0;
    if (uses_minimal_rail_layout()) {
        var slim_radius = Math.max(15, Math.min(17, Math.floor(Math.min(w * 0.27, h * 0.125))));
        var slim_top_y = 11 + slim_radius;
        var slim_middle_y = Math.floor(h * 0.50);
        var slim_lower_y = h - slim_radius - 12;
        return [
            {key: "freq",  label: "FREQ", cx: center_x, cy: slim_top_y, radius: slim_radius},
            {key: "gain",  label: "GAIN", cx: center_x, cy: slim_middle_y, radius: slim_radius},
            {key: "q_alt", label: "Q",    cx: center_x, cy: slim_lower_y, radius: slim_radius}
        ];
    }
    if (is_compact()) {
        var compact_radius = Math.max(10, Math.min(13, Math.floor(Math.min(w * 0.12, h * 0.085))));
        var top_y = 28 + compact_radius + motion_pad;
        var middle_y = Math.floor(h * 0.51);
        var lower_y = h - compact_radius - 16;
        return [
            {key: "freq",  label: "FREQ", cx: center_x, cy: top_y, radius: compact_radius},
            {key: "gain",  label: "GAIN", cx: center_x, cy: middle_y, radius: compact_radius},
            {key: "q_alt", label: "Q",    cx: center_x, cy: lower_y, radius: compact_radius}
        ];
    }
    var radius = Math.max(15, Math.min(18, Math.floor(Math.min(w * 0.16, h * 0.11))));
    var top_y = 26 + radius + motion_pad;
    var middle_y = Math.floor(h * 0.52);
    var lower_y = h - radius - 15;
    return [
        {key: "freq",  label: "FREQ", cx: center_x, cy: top_y, radius: radius},
        {key: "gain",  label: "GAIN", cx: center_x, cy: middle_y, radius: radius},
        {key: "q_alt", label: "Q",    cx: center_x, cy: lower_y, radius: radius}
    ];
}

function type_rects() {
    var w = mgraphics.size[0];
    var compact = is_compact();
    var rects = {};
    var toggle_x = w - (compact ? 19 : 22);
    var toggle_y = compact ? 8 : 10;
    var toggle_w = compact ? 12 : 14;
    var toggle_h = compact ? 12 : 14;
    var toggle_gap = compact ? 3 : 4;
    var x;
    var y;
    var h;
    var gap;
    var prev_w;
    var body_w;
    var next_w;

    function push_stack(key) {
        rects[key] = [toggle_x, toggle_y, toggle_w, toggle_h];
        toggle_y += toggle_h + toggle_gap;
    }

    if (SHOW_TYPE_CONTROLS) {
        y = compact ? 6 : 8;
        h = compact ? 12 : 16;
        gap = compact ? 2 : 3;
        prev_w = compact ? 9 : 10;
        body_w = compact ? 18 : 22;
        next_w = compact ? 9 : 10;
        x = compact ? 6 : 8;
        rects.prev = [x, y, prev_w, h];
        x += prev_w + gap;
        rects.body = [x, y, body_w, h];
        x += body_w + gap;
        rects.next = [x, y, next_w, h];
    }

    if (SHOW_TOGGLE_STACK) {
        push_stack("enable");
        if (SHOW_MOTION) push_stack("motion");
        if (SHOW_DYNAMIC) push_stack("dynamic");
        if (SHOW_SOLO) push_stack("solo");
    }
    return rects;
}

function knob_value_info(knob, band) {
    if (motion_knobs_active(band)) {
        if (knob.key === "freq") {
            return {
                key: "motion_rate",
                label: "RATE",
                value: band.motion_rate,
                min: MIN_MOTION_RATE,
                max: MAX_MOTION_RATE,
                log: 1,
                disabled: 0
            };
        }
        if (knob.key === "gain") {
            return {
                key: "motion_depth",
                label: "DEPTH",
                value: band.motion_depth,
                min: MIN_MOTION_DEPTH,
                max: MAX_MOTION_DEPTH,
                log: 0,
                disabled: 0
            };
        }
        return {
            key: "motion_direction",
            label: "DIR",
            value: band.motion_direction,
            min: MIN_MOTION_DIRECTION,
            max: MAX_MOTION_DIRECTION,
            log: 0,
            disabled: 0
        };
    }

    if (knob.key === "freq") {
        return {
            key: "freq",
            label: "FREQ",
            value: band.freq,
            min: MIN_FREQ,
            max: MAX_FREQ,
            log: 1,
            disabled: 0
        };
    }
    if (knob.key === "gain") {
        return {
            key: "gain",
            label: "GAIN",
            value: band.gain,
            min: MIN_GAIN,
            max: MAX_GAIN,
            log: 0,
            disabled: uses_gain(band.type) ? 0 : 1
        };
    }
    if (uses_slope(band.type)) {
        return {
            key: "slope",
            label: "SLOPE",
            value: band.slope,
            min: 0,
            max: 2,
            log: 0,
            disabled: 0
        };
    }
    return {
        key: "q",
        label: "Q",
        value: band.q,
        min: MIN_Q,
        max: MAX_Q,
        log: 1,
        disabled: 0
    };
}

function norm_for_info(info) {
    var v = clamp(info.value, info.min, info.max);
    if (info.max <= info.min) return 0.0;
    if (info.log) {
        return (Math.log(v) - Math.log(info.min)) / (Math.log(info.max) - Math.log(info.min));
    }
    return (v - info.min) / (info.max - info.min);
}

function value_from_norm(info, norm) {
    norm = clamp(norm, 0.0, 1.0);
    if (info.log) {
        return Math.exp(Math.log(info.min) + norm * (Math.log(info.max) - Math.log(info.min)));
    }
    return info.min + norm * (info.max - info.min);
}

function format_freq(v) {
    if (v >= 1000.0) {
        return (Math.round(v / 10.0) / 100.0).toFixed(v >= 10000.0 ? 1 : 2) + " kHz";
    }
    return Math.round(v) + " Hz";
}

function format_gain(v) {
    var sign = v > 0 ? "+" : "";
    return sign + v.toFixed(1) + " dB";
}

function format_q(v) {
    return v.toFixed(v >= 10.0 ? 1 : 2);
}

function format_motion_rate(v) {
    if (v < 1.0) return v.toFixed(2) + " Hz";
    return v.toFixed(v >= 10.0 ? 1 : 2) + " Hz";
}

function format_motion_depth(v) {
    return Math.round(v) + "%";
}

function format_motion_direction(v) {
    return Math.round(clamp_motion_direction(v)) + "°";
}

function format_slope(idx) {
    if (idx <= 0) return "12 dB";
    if (idx === 1) return "24 dB";
    return "48 dB";
}

function format_value(info) {
    if (info.key === "freq") return format_freq(info.value);
    if (info.key === "gain") return format_gain(info.value);
    if (info.key === "motion_rate") return format_motion_rate(info.value);
    if (info.key === "motion_depth") return format_motion_depth(info.value);
    if (info.key === "motion_direction") return format_motion_direction(info.value);
    if (info.key === "slope") return format_slope(Math.round(info.value));
    return format_q(info.value);
}

function compact_knob_label(info) {
    if (info.key === "freq") return "F";
    if (info.key === "gain") return "G";
    if (info.key === "motion_rate") return "RT";
    if (info.key === "motion_depth") return "DP";
    if (info.key === "motion_direction") return "DR";
    if (info.key === "slope") return "SL";
    return "Q";
}

function knob_label(info, compact) {
    if (compact) return compact_knob_label(info);
    return info.label;
}

function knob_accent_color(info) {
    if (info.key === "motion_rate" || info.key === "motion_depth" || info.key === "motion_direction") return MOTION_ACCENT_COLOR;
    return ACCENT_COLOR;
}

function type_short_name(type_idx) {
    return TYPE_SHORT_NAMES[type_idx] || TYPE_NAMES[type_idx] || "PK";
}

function draw_label(x, y, text, color, size, bold, center) {
    mgraphics.select_font_face(bold ? FONT_BOLD_NAME : FONT_NAME);
    mgraphics.set_font_size(size);
    mgraphics.set_source_rgba(color[0], color[1], color[2], color[3]);
    if (center) {
        var metrics = mgraphics.text_measure(text);
        mgraphics.move_to(x - metrics[0] * 0.5, y);
    } else {
        mgraphics.move_to(x, y);
    }
    mgraphics.show_text(text);
}

function mix_color(color_a, color_b, amount) {
    var inverse = 1.0 - amount;
    return [
        color_a[0] * inverse + color_b[0] * amount,
        color_a[1] * inverse + color_b[1] * amount,
        color_a[2] * inverse + color_b[2] * amount,
        color_a[3] * inverse + color_b[3] * amount
    ];
}

function draw_knob(knob, info) {
    var norm = norm_for_info(info);
    var start = Math.PI * 0.75;
    var end = Math.PI * 2.25;
    var angle = start + (end - start) * norm;
    var active = hover_control === info.key || drag_control === info.key;
    var accent = knob_accent_color(info);
    var compact = is_compact();
    var minimal = uses_minimal_rail_layout();
    var base = info.disabled ? mix_color(KNOB_FILL_COLOR, DISABLED_COLOR, 0.62) : KNOB_FILL_COLOR;
    var outer = info.disabled ? mix_color(PANEL_COLOR, DISABLED_COLOR, 0.45) : mix_color(PANEL_COLOR, BORDER_COLOR, 0.18);
    var inner = info.disabled ? mix_color(base, BG_COLOR, 0.20) : mix_color(base, TEXT_COLOR, 0.06);
    var track = info.disabled ? mix_color(KNOB_TRACK_COLOR, DISABLED_COLOR, 0.36) : KNOB_TRACK_COLOR;
    var pointer = info.disabled ? mix_color(TEXT_DIM_COLOR, DISABLED_COLOR, 0.60) : (active ? accent : mix_color(TEXT_COLOR, accent, 0.24));
    var label_color = info.disabled ? TEXT_DIM_COLOR : ((info.key === "motion_rate" || info.key === "motion_depth" || info.key === "motion_direction") ? accent : TEXT_DIM_COLOR);
    var ring_radius = knob.radius - (minimal ? 5.2 : (compact ? 4.3 : 5.2));
    var pointer_inner = minimal ? ring_radius * 0.18 : (compact ? ring_radius * 0.24 : ring_radius * 0.20);
    var pointer_outer = ring_radius - (minimal ? 2.7 : (compact ? 2.4 : 3.0));

    if (active) {
        mgraphics.set_source_rgba(accent[0], accent[1], accent[2], compact ? 0.12 : 0.16);
        mgraphics.arc(knob.cx, knob.cy, knob.radius + (minimal ? 4.0 : (compact ? 3.0 : 4.5)), 0, Math.PI * 2.0);
        mgraphics.fill();
    }

    mgraphics.set_source_rgba(outer[0], outer[1], outer[2], compact ? 0.96 : 1.0);
    mgraphics.arc(knob.cx, knob.cy, knob.radius, 0, Math.PI * 2.0);
    mgraphics.fill();

    mgraphics.set_source_rgba(BORDER_COLOR[0], BORDER_COLOR[1], BORDER_COLOR[2], info.disabled ? 0.30 : 0.72);
    mgraphics.set_line_width(compact ? 1.0 : 1.2);
    mgraphics.arc(knob.cx, knob.cy, knob.radius - 0.6, 0, Math.PI * 2.0);
    mgraphics.stroke();

    mgraphics.set_source_rgba(inner[0], inner[1], inner[2], compact ? 0.96 : 1.0);
    mgraphics.arc(knob.cx, knob.cy, knob.radius - (compact ? 2.2 : 2.8), 0, Math.PI * 2.0);
    mgraphics.fill();

    mgraphics.set_source_rgba(track[0], track[1], track[2], info.disabled ? 0.42 : 0.74);
    mgraphics.set_line_width(minimal ? 2.0 : (compact ? 1.8 : 2.2));
    mgraphics.arc(knob.cx, knob.cy, ring_radius, start, end);
    mgraphics.stroke();

    mgraphics.set_source_rgba(accent[0], accent[1], accent[2], info.disabled ? 0.18 : (active ? 0.96 : 0.84));
    mgraphics.set_line_width(minimal ? (active ? 3.0 : 2.6) : (compact ? (active ? 2.4 : 2.0) : (active ? 2.9 : 2.4)));
    mgraphics.arc(knob.cx, knob.cy, ring_radius, start, angle);
    mgraphics.stroke();

    mgraphics.set_source_rgba(pointer[0], pointer[1], pointer[2], info.disabled ? 0.28 : 0.96);
    mgraphics.set_line_width(minimal ? 2.1 : (compact ? 1.6 : 2.0));
    mgraphics.move_to(knob.cx + Math.cos(angle) * pointer_inner, knob.cy + Math.sin(angle) * pointer_inner);
    mgraphics.line_to(knob.cx + Math.cos(angle) * pointer_outer, knob.cy + Math.sin(angle) * pointer_outer);
    mgraphics.stroke();

    mgraphics.set_source_rgba(pointer[0], pointer[1], pointer[2], info.disabled ? 0.22 : 0.92);
    mgraphics.arc(knob.cx, knob.cy, minimal ? 1.5 : (compact ? 1.2 : 1.4), 0, Math.PI * 2.0);
    mgraphics.fill();

    draw_label(
        knob.cx,
        knob.cy - knob.radius - (minimal ? 1 : (compact ? 4 : 5)),
        knob_label(info, compact && !minimal),
        label_color,
        minimal ? 6.8 : (compact ? 5.1 : 5.8),
        1,
        1
    );
    draw_label(
        knob.cx,
        knob.cy + knob.radius + (minimal ? 7 : (compact ? 9 : 11)),
        format_value(info),
        info.disabled ? TEXT_DIM_COLOR : TEXT_COLOR,
        minimal ? 7.5 : (compact ? 5.2 : 6.4),
        0,
        1
    );
}

function fill_round_rect(x, y, w, h, r, color, alpha) {
    mgraphics.set_source_rgba(color[0], color[1], color[2], alpha === undefined ? color[3] : alpha);
    mgraphics.rectangle_rounded(x, y, w, h, r, r);
    mgraphics.fill();
}

function stroke_round_rect(x, y, w, h, r, color, alpha, width) {
    mgraphics.set_source_rgba(color[0], color[1], color[2], alpha === undefined ? color[3] : alpha);
    mgraphics.set_line_width(width === undefined ? 1.0 : width);
    mgraphics.rectangle_rounded(x, y, w, h, r, r);
    mgraphics.stroke();
}

function draw_type_and_toggles(band) {
    var rects = type_rects();
    var enabled_alpha = band.enabled ? 0.96 : 0.30;
    var solo_alpha = band.solo ? 0.96 : 0.26;
    var motion_alpha = band.motion ? 0.96 : 0.26;
    var dynamic_supported = supports_dynamic(band.type);
    var dynamic_alpha = dynamic_supported ? (band.dynamic ? 0.96 : 0.26) : 0.16;
    var compact = is_compact();

    if (SHOW_TYPE_CONTROLS) {
        fill_round_rect(rects.prev[0], rects.prev[1], rects.prev[2], rects.prev[3], compact ? 4 : 5, PANEL_COLOR, 1.0);
        fill_round_rect(rects.body[0], rects.body[1], rects.body[2], rects.body[3], compact ? 4 : 5, PANEL_COLOR, 1.0);
        fill_round_rect(rects.next[0], rects.next[1], rects.next[2], rects.next[3], compact ? 4 : 5, PANEL_COLOR, 1.0);
        stroke_round_rect(rects.prev[0], rects.prev[1], rects.prev[2], rects.prev[3], compact ? 4 : 5, BORDER_COLOR, 1.0, 1.0);
        stroke_round_rect(rects.body[0], rects.body[1], rects.body[2], rects.body[3], compact ? 4 : 5, BORDER_COLOR, 1.0, 1.0);
        stroke_round_rect(rects.next[0], rects.next[1], rects.next[2], rects.next[3], compact ? 4 : 5, BORDER_COLOR, 1.0, 1.0);
        draw_label(rects.prev[0] + rects.prev[2] * 0.5, rects.prev[1] + (compact ? 9 : 12), "<", TEXT_COLOR, compact ? 6.6 : 7.2, 1, 1);
        draw_label(rects.next[0] + rects.next[2] * 0.5, rects.next[1] + (compact ? 9 : 12), ">", TEXT_COLOR, compact ? 6.6 : 7.2, 1, 1);
        draw_label(rects.body[0] + rects.body[2] * 0.5, rects.body[1] + (compact ? 9 : 12), type_short_name(band.type), TEXT_COLOR, compact ? 5.8 : 7.0, 1, 1);
    }

    if (!SHOW_TOGGLE_STACK) return;

    fill_round_rect(rects.enable[0], rects.enable[1], rects.enable[2], rects.enable[3], compact ? 4 : 6, ENABLE_COLOR, enabled_alpha);
    stroke_round_rect(rects.enable[0], rects.enable[1], rects.enable[2], rects.enable[3], compact ? 4 : 6, BORDER_COLOR, 1.0, 1.0);
    draw_label(rects.enable[0] + rects.enable[2] * 0.5, rects.enable[1] + (compact ? 9 : 12), band.enabled ? "ON" : "BY", band.enabled ? BG_COLOR : TEXT_COLOR, compact ? 5.0 : 5.6, 1, 1);

    if (SHOW_MOTION && rects.motion) {
        fill_round_rect(rects.motion[0], rects.motion[1], rects.motion[2], rects.motion[3], compact ? 4 : 6, ACCENT_COLOR, motion_alpha);
        stroke_round_rect(rects.motion[0], rects.motion[1], rects.motion[2], rects.motion[3], compact ? 4 : 6, BORDER_COLOR, 1.0, 1.0);
        draw_label(rects.motion[0] + rects.motion[2] * 0.5, rects.motion[1] + (compact ? 9 : 12), compact ? "M" : "MOT", band.motion ? BG_COLOR : TEXT_COLOR, compact ? 5.0 : 5.2, 1, 1);
    }

    if (SHOW_DYNAMIC && rects.dynamic) {
        fill_round_rect(rects.dynamic[0], rects.dynamic[1], rects.dynamic[2], rects.dynamic[3], compact ? 4 : 6, dynamic_supported ? SOLO_COLOR : DISABLED_COLOR, dynamic_alpha);
        stroke_round_rect(rects.dynamic[0], rects.dynamic[1], rects.dynamic[2], rects.dynamic[3], compact ? 4 : 6, BORDER_COLOR, 1.0, 1.0);
        draw_label(rects.dynamic[0] + rects.dynamic[2] * 0.5, rects.dynamic[1] + (compact ? 9 : 12), compact ? "D" : "DYN", dynamic_supported && band.dynamic ? BG_COLOR : TEXT_COLOR, compact ? 5.0 : 5.0, 1, 1);
    }

    if (SHOW_SOLO && rects.solo) {
        fill_round_rect(rects.solo[0], rects.solo[1], rects.solo[2], rects.solo[3], compact ? 4 : 6, SOLO_COLOR, solo_alpha);
        stroke_round_rect(rects.solo[0], rects.solo[1], rects.solo[2], rects.solo[3], compact ? 4 : 6, BORDER_COLOR, 1.0, 1.0);
        draw_label(rects.solo[0] + rects.solo[2] * 0.5, rects.solo[1] + (compact ? 9 : 12), compact ? "S" : "SOLO", band.solo ? BG_COLOR : TEXT_COLOR, compact ? 5.0 : 5.4, 1, 1);
    }
}

function paint_empty() {
    var h = mgraphics.size[1];
    if (uses_minimal_rail_layout()) {
        draw_label(mgraphics.size[0] * 0.5, h * 0.47, "Select", TEXT_DIM_COLOR, 8.4, 1, 1);
        draw_label(mgraphics.size[0] * 0.5, h * 0.57, "a node", TEXT_DIM_COLOR, 6.6, 0, 1);
        return;
    }
    if (is_compact()) {
        draw_label(10, 16, "NO BAND", TEXT_DIM_COLOR, 8.0, 1, 0);
        draw_label(10, 28, "Select a node.", TEXT_DIM_COLOR, 5.6, 0, 0);
        return;
    }
    draw_label(12, 18, "NO BAND", TEXT_DIM_COLOR, 8.0, 1, 0);
    draw_label(12, 32, "Select a node.", TEXT_DIM_COLOR, 6.6, 0, 0);
    draw_label(mgraphics.size[0] * 0.5, h * 0.60, "No selected filter", TEXT_DIM_COLOR, 8.0, 1, 1);
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var band = current_band();
    var knobs;
    var k;
    var info;

    if (SHOW_FRAME) {
        fill_round_rect(0, 0, w, h, 8, BG_COLOR, 1.0);
        fill_round_rect(1, 1, w - 2, h - 2, 8, PANEL_COLOR, 1.0);
        stroke_round_rect(1, 1, w - 2, h - 2, 8, BORDER_COLOR, 1.0, 1.0);
    } else {
        fill_round_rect(0, 0, w, h, 0, BG_COLOR, 1.0);
    }

    if (!band) {
        paint_empty();
        return;
    }

    if (SHOW_HEADER) {
        if (is_compact()) {
            draw_label(9, 15, "B" + (selected_band + 1) + "  " + type_short_name(band.type), TEXT_COLOR, 5.9, 1, 0);
        } else {
            draw_label(12, 18, "B" + (selected_band + 1) + "  " + type_short_name(band.type), TEXT_COLOR, 6.8, 1, 0);
        }
    }

    knobs = knob_defs(band);
    for (k = 0; k < knobs.length; k++) {
        info = knob_value_info(knobs[k], band);
        draw_knob(knobs[k], info);
    }

    draw_type_and_toggles(band);
}

function hit_test(x, y) {
    var band = current_band();
    var knobs;
    var k;
    var dx;
    var dy;
    var rects;

    if (!band) return "";

    knobs = knob_defs(band);
    for (k = 0; k < knobs.length; k++) {
        dx = x - knobs[k].cx;
        dy = y - knobs[k].cy;
        if (dx * dx + dy * dy <= Math.pow(knobs[k].radius + 8, 2)) {
            return knob_value_info(knobs[k], band).key;
        }
    }

    rects = type_rects();
    if (SHOW_TYPE_CONTROLS) {
        if (x >= rects.prev[0] && x <= rects.prev[0] + rects.prev[2] &&
                y >= rects.prev[1] && y <= rects.prev[1] + rects.prev[3]) return "type_prev";
        if (x >= rects.body[0] && x <= rects.body[0] + rects.body[2] &&
                y >= rects.body[1] && y <= rects.body[1] + rects.body[3]) return "type_next";
        if (x >= rects.next[0] && x <= rects.next[0] + rects.next[2] &&
                y >= rects.next[1] && y <= rects.next[1] + rects.next[3]) return "type_next";
    }
    if (SHOW_TOGGLE_STACK && x >= rects.enable[0] && x <= rects.enable[0] + rects.enable[2] &&
            y >= rects.enable[1] && y <= rects.enable[1] + rects.enable[3]) return "enable";
    if (SHOW_TOGGLE_STACK && SHOW_MOTION && rects.motion &&
            x >= rects.motion[0] && x <= rects.motion[0] + rects.motion[2] &&
            y >= rects.motion[1] && y <= rects.motion[1] + rects.motion[3]) return "motion";
    if (SHOW_TOGGLE_STACK && SHOW_DYNAMIC && rects.dynamic &&
            x >= rects.dynamic[0] && x <= rects.dynamic[0] + rects.dynamic[2] &&
            y >= rects.dynamic[1] && y <= rects.dynamic[1] + rects.dynamic[3]) return "dynamic";
    if (SHOW_TOGGLE_STACK && SHOW_SOLO && x >= rects.solo[0] && x <= rects.solo[0] + rects.solo[2] &&
            y >= rects.solo[1] && y <= rects.solo[1] + rects.solo[3]) return "solo";

    return "";
}

function emit_value(control, value) {
    if (selected_band < 0 || selected_band >= num_bands) return;
    if (control === "freq") {
        outlet(0, "band_freq", selected_band, value);
        return;
    }
    if (control === "gain") {
        outlet(0, "band_gain", selected_band, value);
        return;
    }
    if (control === "motion_rate") {
        outlet(0, "band_motion_rate", selected_band, value);
        return;
    }
    if (control === "motion_depth") {
        outlet(0, "band_motion_depth", selected_band, value);
        return;
    }
    if (control === "motion_direction") {
        outlet(0, "band_motion_direction", selected_band, value);
        return;
    }
    if (control === "q") {
        outlet(0, "band_q", selected_band, value);
        return;
    }
    if (control === "slope") {
        outlet(0, "band_slope", selected_band, value);
        return;
    }
}

function apply_type_change(next_type) {
    var band = current_band();
    var q_changed = 0;
    var dynamic_was_active = 0;
    var dynamic_amount_was_active = 0;
    if (!band) return;
    next_type = clamp(Math.floor(next_type), 0, TYPE_NAMES.length - 1);
    if (band.type === next_type) return;

    dynamic_was_active = band.dynamic ? 1 : 0;
    dynamic_amount_was_active = Math.abs(band.dynamic_amount || 0.0) > 0.001;
    band.type = next_type;
    if (next_type === 3 || next_type === 4) {
        band.q = type_default_q(next_type);
        q_changed = 1;
    }
    if (!supports_dynamic(next_type)) {
        band.dynamic = 0;
        band.dynamic_amount = 0.0;
    }

    outlet(0, "band_type", selected_band, band.type);
    if (q_changed) {
        outlet(0, "band_q", selected_band, band.q);
    }
    if (!supports_dynamic(next_type) && (dynamic_was_active || dynamic_amount_was_active)) {
        outlet(0, "band_dynamic", selected_band, 0);
    }
}

function apply_drag_value(y) {
    var band = current_band();
    var info;
    var delta_norm;
    var norm;
    var next_value;

    if (!band || !drag_control) return;

    if (drag_control === "gain" && !motion_knobs_active(band) && !uses_gain(band.type)) return;
    if (drag_control === "slope" && !uses_slope(band.type)) return;

    if (drag_control === "freq") {
        info = {key: "freq", value: drag_start_value, min: MIN_FREQ, max: MAX_FREQ, log: 1};
    } else if (drag_control === "motion_rate") {
        info = {key: "motion_rate", value: drag_start_value, min: MIN_MOTION_RATE, max: MAX_MOTION_RATE, log: 1};
    } else if (drag_control === "motion_depth") {
        info = {key: "motion_depth", value: drag_start_value, min: MIN_MOTION_DEPTH, max: MAX_MOTION_DEPTH, log: 0};
    } else if (drag_control === "motion_direction") {
        info = {key: "motion_direction", value: drag_start_value, min: MIN_MOTION_DIRECTION, max: MAX_MOTION_DIRECTION, log: 0};
    } else if (drag_control === "gain") {
        info = {key: "gain", value: drag_start_value, min: MIN_GAIN, max: MAX_GAIN, log: 0};
    } else if (drag_control === "q") {
        info = {key: "q", value: drag_start_value, min: MIN_Q, max: MAX_Q, log: 1};
    } else if (drag_control === "slope") {
        info = {key: "slope", value: drag_start_value, min: 0, max: 2, log: 0};
    } else {
        return;
    }

    if (is_compact()) delta_norm = (drag_start_y - y) / (drag_control === "freq" ? 110.0 : 90.0);
    else delta_norm = (drag_start_y - y) / (drag_control === "freq" ? 170.0 : 140.0);
    norm = clamp(norm_for_info(info) + delta_norm, 0.0, 1.0);
    next_value = value_from_norm(info, norm);

    if (drag_control === "freq") {
        if (next_value < 100.0) next_value = Math.round(next_value);
        else if (next_value < 1000.0) next_value = Math.round(next_value);
        else next_value = Math.round(next_value / 10.0) * 10.0;
        if (next_value === band.freq) return;
        band.freq = next_value;
        emit_value("freq", next_value);
    } else if (drag_control === "motion_rate") {
        next_value = round_to(next_value, next_value < 1.0 ? 0.01 : 0.05);
        if (next_value === band.motion_rate) return;
        band.motion_rate = next_value;
        emit_value("motion_rate", next_value);
    } else if (drag_control === "motion_depth") {
        next_value = round_to(next_value, 1.0);
        if (next_value === band.motion_depth) return;
        band.motion_depth = next_value;
        emit_value("motion_depth", next_value);
    } else if (drag_control === "motion_direction") {
        next_value = round_to(next_value, 1.0);
        next_value = clamp_motion_direction(next_value);
        if (next_value === band.motion_direction) return;
        band.motion_direction = next_value;
        emit_value("motion_direction", next_value);
    } else if (drag_control === "gain") {
        next_value = round_to(next_value, 0.1);
        if (next_value === band.gain) return;
        band.gain = next_value;
        emit_value("gain", next_value);
    } else if (drag_control === "q") {
        next_value = round_to(next_value, next_value >= 10.0 ? 0.1 : 0.01);
        if (next_value === band.q) return;
        band.q = next_value;
        emit_value("q", next_value);
    } else if (drag_control === "slope") {
        next_value = Math.round(next_value);
        next_value = clamp(next_value, 0, 2);
        if (next_value === band.slope) return;
        band.slope = next_value;
        emit_value("slope", next_value);
    }
    mgraphics.redraw();
}

function onclick(x, y, but, cmd, shift, caps, opt, ctrl) {
    var band = current_band();
    if (!band) return;

    hover_control = hit_test(x, y);
    if (!hover_control) {
        drag_control = "";
        mgraphics.redraw();
        return;
    }

    if (hover_control === "type_prev") {
        apply_type_change((band.type + TYPE_NAMES.length - 1) % TYPE_NAMES.length);
        mgraphics.redraw();
        return;
    }
    if (hover_control === "type_next") {
        apply_type_change((band.type + 1) % TYPE_NAMES.length);
        mgraphics.redraw();
        return;
    }
    if (hover_control === "enable") {
        band.enabled = band.enabled ? 0 : 1;
        outlet(0, "band_enable", selected_band, band.enabled);
        mgraphics.redraw();
        return;
    }
    if (hover_control === "solo" && SHOW_SOLO) {
        band.solo = band.solo ? 0 : 1;
        outlet(0, "band_solo", selected_band, band.solo);
        mgraphics.redraw();
        return;
    }
    if (hover_control === "motion" && SHOW_MOTION) {
        band.motion = band.motion ? 0 : 1;
        if (band.motion && band.motion_depth < 1.0) band.motion_depth = default_motion_depth(selected_band);
        if (band.motion && band.motion_rate < MIN_MOTION_RATE) band.motion_rate = default_motion_rate(selected_band);
        outlet(0, "band_motion", selected_band, band.motion);
        outlet(0, "band_motion_rate", selected_band, band.motion_rate);
        outlet(0, "band_motion_depth", selected_band, band.motion_depth);
        mgraphics.redraw();
        return;
    }
    if (hover_control === "dynamic" && SHOW_DYNAMIC) {
        if (!supports_dynamic(band.type)) return;
        band.dynamic = band.dynamic ? 0 : 1;
        outlet(0, "band_dynamic", selected_band, band.dynamic);
        mgraphics.redraw();
        return;
    }

    drag_control = hover_control;
    drag_start_y = y;
    if (drag_control === "freq") drag_start_value = band.freq;
    else if (drag_control === "gain") drag_start_value = band.gain;
    else if (drag_control === "motion_rate") drag_start_value = band.motion_rate;
    else if (drag_control === "motion_depth") drag_start_value = band.motion_depth;
    else if (drag_control === "motion_direction") drag_start_value = band.motion_direction;
    else if (drag_control === "q") drag_start_value = band.q;
    else if (drag_control === "slope") drag_start_value = band.slope;
    else drag_control = "";
    mgraphics.redraw();
}

function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but === 0) {
        drag_control = "";
        mgraphics.redraw();
        return;
    }
    apply_drag_value(y);
}

function onwheel(x, y, scrollx, scrolly, cmd, shift, caps, opt, ctrl) {
    var band = current_band();
    var control;
    var next_q;
    var factor;
    if (!band) return;
    control = hit_test(x, y);
    if (!control) return;
    hover_control = control;
    if (!opt) {
        mgraphics.redraw();
        return;
    }
    if (control === "type_prev" || control === "type_next" ||
            control === "enable" || control === "motion" ||
            control === "dynamic" || control === "solo") {
        return;
    }
    factor = shift ? 0.02 : 0.08;
    next_q = band.q * (1.0 + scrolly * factor);
    next_q = clamp(next_q, MIN_Q, MAX_Q);
    next_q = round_to(next_q, next_q >= 10.0 ? 0.1 : 0.01);
    if (next_q === band.q) return;
    band.q = next_q;
    emit_value("q", next_q);
    mgraphics.redraw();
}

function onidle(x, y, but, cmd, shift, caps, opt, ctrl) {
    var next = hit_test(x, y);
    if (next !== hover_control) {
        hover_control = next;
        mgraphics.redraw();
    }
}

function onidleout(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (hover_control || drag_control) {
        hover_control = "";
        drag_control = "";
        mgraphics.redraw();
    }
}

function set_num_bands(v) {
    num_bands = Math.max(1, Math.min(MAX_BANDS, Math.floor(v)));
    if (selected_band >= num_bands) selected_band = num_bands - 1;
    mgraphics.redraw();
}

function set_selected(v) {
    selected_band = Math.floor(v);
    if (selected_band < 0 || selected_band >= num_bands) selected_band = -1;
    drag_control = "";
    mgraphics.redraw();
}

function set_band(idx, freq, gain, q, type, enabled, extra_a, extra_b, extra_c, extra_d, extra_e, extra_f) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].freq = clamp(freq, MIN_FREQ, MAX_FREQ);
    bands[idx].gain = clamp(gain, MIN_GAIN, MAX_GAIN);
    bands[idx].q = clamp(q, MIN_Q, MAX_Q);
    bands[idx].type = clamp(Math.floor(type), 0, TYPE_NAMES.length - 1);
    bands[idx].enabled = enabled ? 1 : 0;
    if (SHOW_SLOPE || SHOW_SOLO) {
        if (arguments.length > 6 && extra_a !== undefined) bands[idx].slope = clamp(Math.floor(extra_a), 0, 2);
        if (arguments.length > 7 && extra_b !== undefined) bands[idx].solo = extra_b ? 1 : 0;
    } else {
        if (arguments.length > 6 && extra_a !== undefined) bands[idx].motion = extra_a ? 1 : 0;
        if (arguments.length > 7 && extra_b !== undefined) bands[idx].dynamic = extra_b ? 1 : 0;
        if (arguments.length > 8 && extra_c !== undefined) bands[idx].dynamic_amount = extra_c;
        if (arguments.length > 9 && extra_d !== undefined) bands[idx].motion_rate = clamp(extra_d, MIN_MOTION_RATE, MAX_MOTION_RATE);
        if (arguments.length > 10 && extra_e !== undefined) bands[idx].motion_depth = clamp(extra_e, MIN_MOTION_DEPTH, MAX_MOTION_DEPTH);
        if (arguments.length > 11 && extra_f !== undefined) bands[idx].motion_direction = clamp_motion_direction(extra_f);
    }
    mgraphics.redraw();
}

function set_motion(idx, enabled) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].motion = enabled ? 1 : 0;
    mgraphics.redraw();
}

function set_dynamic(idx, enabled) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].dynamic = enabled ? 1 : 0;
    mgraphics.redraw();
}

function set_motion_rate(idx, value) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].motion_rate = clamp(value, MIN_MOTION_RATE, MAX_MOTION_RATE);
    mgraphics.redraw();
}

function set_motion_depth(idx, value) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].motion_depth = clamp(value, MIN_MOTION_DEPTH, MAX_MOTION_DEPTH);
    mgraphics.redraw();
}

function set_motion_direction(idx, value) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].motion_direction = clamp_motion_direction(value);
    mgraphics.redraw();
}

function list() {
    if (messagename === "set_band") {
        set_band.apply(this, arguments);
    }
}

function anything() {
    var args = arrayfromargs(arguments);
    switch (messagename) {
        case "set_num_bands":
            if (args.length > 0) set_num_bands(args[0]);
            return;
        case "set_selected":
            if (args.length > 0) set_selected(args[0]);
            return;
        case "set_band":
            set_band.apply(this, args);
            return;
        case "set_motion":
            if (args.length > 1) set_motion(args[0], args[1]);
            return;
        case "set_dynamic":
            if (args.length > 1) set_dynamic(args[0], args[1]);
            return;
        case "set_motion_rate":
            if (args.length > 1) set_motion_rate(args[0], args[1]);
            return;
        case "set_motion_depth":
            if (args.length > 1) set_motion_depth(args[0], args[1]);
            return;
        case "set_motion_direction":
            if (args.length > 1) set_motion_direction(args[0], args[1]);
            return;
    }
}
""")
