"""Parametric EQ curve display with draggable nodes for jsui.

Generates JavaScript (ES5) for Max's jsui object, drawing a Pro-Q/EQ Eight
style multi-band EQ with draggable nodes and composite response rendering.

Communication uses 3 inlets and 4 outlets.

Inlet 0 messages:
    set_band band_idx freq gain q type enabled [motion] [dynamic] [dynamic_amount]
             [motion_rate] [motion_depth] [motion_direction]
    set_num_bands N
    set_selected band_idx
    set_motion band_idx enabled
    set_dynamic band_idx enabled
    set_dynamic_amount band_idx amount
    set_motion_rate band_idx hz
    set_motion_depth band_idx percent
    set_motion_direction band_idx degrees
    set_analyzer_buffer name bins   (spectrum DISPLAY polls this buffer~)
    set_dyn_buffer name [bins]      (dynamic DETECTOR polls this pre-EQ buffer~;
                                     empty/none = fall back to the display buffer)

Inlet 1:
    sample-rate float (typically from dspstate~ outlet 1)

Inlet 2:
    analyzer magnitude list in dB (typically -72..0 dB, log-spaced bins)

Outlet 0:
    selected_band band_idx
    add_band band_idx freq gain q type enabled
    delete_band band_idx
    band_type band_idx type
    band_enable band_idx enabled
    band_motion band_idx enabled
    band_dynamic band_idx enabled
    band_dynamic_amount band_idx amount
    band_motion_rate band_idx hz
    band_motion_depth band_idx percent
    band_motion_direction band_idx degrees
Outlet 1: band_freq band_idx freq
Outlet 2: band_gain band_idx gain
Outlet 3: band_q band_idx q

Mouse interaction:
    Click node: select band
    Drag node: adjust frequency and gain for bell/shelf filters
    Drag cut/notch/BP nodes: frequency horizontal, Q vertical
    Drag dynamic handle: adjust per-band dynamic range
    Mouse wheel on node: adjust Q
    Shift + drag / wheel: fine tune
    Cmd/Ctrl + drag: lock the secondary parameter
    Right-click node: open node menu for type / Motion / Dynamic / bypass / delete
    Double-click empty graph: add first disabled band at cursor
    Opt/Alt + click node: disable that band
"""

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    band_palette_js,
    resolve_graph_panel_color,
)
from .design_system import design_system_js

EQ_CURVE_INLETS = 3
EQ_CURVE_OUTLETS = 4


def eq_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    composite_color="0.85, 0.88, 0.92, 1.0",
    fill_color="0.45, 0.75, 0.65, 0.12",
    analyzer_fill_color="0.24, 0.78, 0.92, 0.12",
    analyzer_line_color="0.32, 0.84, 0.96, 0.48",
    analyzer_peak_color="0.92, 0.96, 1.0, 0.9",
    grid_color="0.2, 0.2, 0.22, 0.5",
    text_color="0.5, 0.5, 0.52, 1.0",
    zero_line_color="0.3, 0.3, 0.32, 0.8",
    analyzer_trim_db=18.0,
):
    """Return JavaScript source for an interactive parametric EQ display.

    ``analyzer_trim_db`` lifts raw ``fft_frame`` magnitudes into the display's
    -72..0 dB window (2/N-normalized FFT bins of typical program material sit
    well below 0 dB). Ignored for the legacy dB-list analyzer path.
    """
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return design_system_js() + "\n" + _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        composite_color=composite_color,
        fill_color=fill_color,
        analyzer_fill_color=analyzer_fill_color,
        analyzer_line_color=analyzer_line_color,
        analyzer_peak_color=analyzer_peak_color,
        grid_color=grid_color,
        text_color=text_color,
        zero_line_color=zero_line_color,
        analyzer_trim_db=analyzer_trim_db,
        band_colors=band_palette_js(),
    )


_JS_TEMPLATE = Template("""\
// Parametric EQ Curve Display - generated by m4l-builder
// ES5 compatible, no let/const/arrow/template literals

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 3;
outlets = 4;

// ── Configurable colors ──────────────────────────────────────────────
var BG_COLOR       = [$bg_color];
var PANEL_CLR      = [$panel_color];
var PLOT_BORDER_CLR = [$plot_border_color];
var COMPOSITE_CLR  = [$composite_color];
var FILL_CLR       = [$fill_color];
var ANALYZER_FILL_CLR = [$analyzer_fill_color];
var ANALYZER_LINE_CLR = [$analyzer_line_color];
var ANALYZER_PEAK_CLR = [$analyzer_peak_color];
var GRID_CLR       = [$grid_color];
var TEXT_CLR       = [$text_color];
var ZERO_LINE_CLR  = [$zero_line_color];

var BAND_COLORS = $band_colors;
var MOTION_CLR = [0.34, 0.88, 0.96, 1.0];
var DYNAMIC_CLR = [0.98, 0.72, 0.26, 1.0];
var MENU_BG_CLR = [0.09, 0.10, 0.12, 0.96];
var MENU_SURFACE_CLR = [0.13, 0.14, 0.17, 0.98];
var MENU_BORDER_CLR = [0.24, 0.28, 0.34, 1.0];
var MENU_DISABLED_CLR = [0.14, 0.15, 0.17, 0.94];

// ── Filter types ─────────────────────────────────────────────────────
var TYPE_PEAK     = 0;
var TYPE_LOSHELF  = 1;
var TYPE_HISHELF  = 2;
var TYPE_LOWPASS  = 3;
var TYPE_HIGHPASS = 4;
var TYPE_NOTCH    = 5;
var TYPE_BANDPASS = 6;
var TYPE_ALLPASS  = 7;

var TYPE_NAMES = ["Peak", "LShelf", "HShelf", "LP", "HP", "Notch", "BP", "AllPass"];
var TYPE_SHORT_NAMES = ["PK", "LS", "HS", "LP", "HP", "NT", "BP", "AP"];
// ── Constants ────────────────────────────────────────────────────────
var MIN_FREQ      = 10;
var MAX_FREQ      = 22000;
var MIN_GAIN      = -30;
var MAX_GAIN      = 30;
var DISPLAY_FLOOR = -30;
var display_range = 15.0;
var MIN_Q         = 0.1;
var MAX_Q         = 30.0;
var NUM_POINTS    = 768;
var NODE_RADIUS     = 6.5;
var NODE_RADIUS_SEL = 8.5;
var HIT_RADIUS      = 18;
var DYNAMIC_HANDLE_RADIUS = 5.2;
var DYNAMIC_HIT_RADIUS = 15.0;
var MAX_DYNAMIC_RANGE = 18.0;
// When a band is dynamic-enabled but its range is ~0 the ring would sit exactly
// on the node, making node-vs-ring grabs ambiguous (the drag_mode flicker). Draw
// + hit-test the ring at this visible default offset (dB) from the node so it is
// reliably grabbable and visually distinct. Sign is opposite the node gain (a
// boost band previews a downward/compress ring; a cut previews an upward ring) —
// the same convention the menu's Dynamic-enable default uses.
var DYNAMIC_DEFAULT_OFFSET = 6.0;
// Ring vs node arbitration dead-zone (px^2). The ring only wins a press when it
// is hit AND it is at least this much closer (squared) than the node — small
// mouse jitter near the node can no longer flip drag_mode between gain and ring.
var DYNAMIC_GRAB_BIAS_SQ = 9.0;
var MAX_BANDS       = 8;
var DEFAULT_SR      = 48000.0;
var ANALYZER_MIN_DB = -72.0;
var ANALYZER_MAX_DB = 0.0;
var ANALYZER_BINS   = 256;        // fixed log-spaced display bins for fft_frame
var ANALYZER_TRIM_DB = $analyzer_trim_db;
// Spectrum Grab (Pro-Q): a plain press over an analyzer peak louder than this
// spawns a band right at that frequency and starts dragging it. The floor sits
// near ANALYZER_MIN_DB so this cleanly distinguishes a real resonance.
var SPECTRUM_GRAB_DB = -48.0;
var LOG_MIN         = Math.log(MIN_FREQ);
var LOG_MAX         = Math.log(MAX_FREQ);
var LOG_RANGE       = LOG_MAX - LOG_MIN;
var REDRAW_INTERVAL_MS = 33;
var DOUBLE_CLICK_MS = 320;

// ── Margin / padding for axis labels ─────────────────────────────────
var MARGIN_LEFT   = 20;
var MARGIN_RIGHT  = 8;
var MARGIN_TOP    = 6;
var MARGIN_BOTTOM = 12;

// ── State ────────────────────────────────────────────────────────────
var sample_rate = DEFAULT_SR;
var analyzer_enabled = 1;
// Display-domain spectrum tilt around a 1 kHz pivot (SPAN/Pro-Q style):
// +4.5 dB/oct makes pink noise read ~flat behind the curve. Pure render
// transform — never touches the audio path. Freeze halts the ballistics and
// holds the last frame (a snapshot to EQ against).
var analyzer_slope_db_oct = 0.0;
var analyzer_frozen = 0;
var num_bands = 0;
var selected_band = -1;
var hover_band = -1;
var hover_x = -1.0;
var hover_y = -1.0;
var hover_in_plot = 0;
// Cursor feedback + node glow come from the shared design-system snippet
// (ds_set_cursor / DS_CUR_* / ds_node_glow), prepended to this script.
var dragging = 0;
var drag_mode = 0;
var drag_start_freq = 0;
var drag_start_gain = 0;
var drag_start_q = 1.0;
var drag_start_dynamic = 0.0;
var menu_band = -1;
var menu_x = 0;
var menu_y = 0;
var menu_hover = "";
var redraw_task = null;
var redraw_task_running = 0;
var last_redraw_ms = 0;
var last_click_ms = 0;
var last_click_band = -1;
var last_pointer_press_ms = 0;
var last_pointer_press_x = 0;
var last_pointer_press_y = 0;
var suppress_next_click = 0;
var suppress_next_ondblclick_delete = 0;

var bands = [];
var band_cache = [];
var analyzer_display = [];
var analyzer_peaks = [];
var i;
for (i = 0; i < MAX_BANDS; i++) {
    bands[i] = {
        present: 0,
        freq: 1000,
        gain: 0,
        q: 1.0,
        type: TYPE_PEAK,
        enabled: 0,
        motion: 0,
        dynamic: 0,
        dynamic_amount: 0.0,
        dynamic_current: 0.0,
        dynamic_env: 0.0,
        motion_rate: default_motion_rate(i),
        motion_depth: default_motion_depth(i),
        motion_direction: default_motion_direction(i)
    };
    band_cache[i] = {
        idx: i,
        present: 0,
        enabled: 0,
        freq: 1000,
        gain: 0,
        q: 1.0,
        type: TYPE_PEAK,
        motion: 0,
        dynamic: 0,
        dynamic_amount: 0.0,
        motion_rate: default_motion_rate(i),
        motion_depth: default_motion_depth(i),
        motion_direction: default_motion_direction(i),
        node_gain: 0,
        uses_gain: 1,
        coeffs: [1, 0, 0, 1, 0, 0]
    };
}

// ── Coordinate helpers ───────────────────────────────────────────────
function plot_left()   { return MARGIN_LEFT; }
function plot_right()  { return mgraphics.size[0] - MARGIN_RIGHT; }
function plot_top()    { return MARGIN_TOP; }
function plot_bottom() { return mgraphics.size[1] - MARGIN_BOTTOM; }
function plot_w()      { return plot_right() - plot_left(); }
function plot_h()      { return plot_bottom() - plot_top(); }
function point_in_plot(x, y) {
    return x >= plot_left() && x <= plot_right() && y >= plot_top() && y <= plot_bottom();
}

function clamp(v, lo, hi) {
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

function safe_log10(v) {
    if (v <= 1.0e-20) v = 1.0e-20;
    return Math.log(v) / Math.log(10);
}

function default_motion_rate(idx) {
    var defaults = [0.18, 0.27, 0.39, 0.56, 0.80, 1.12, 1.48, 1.92];
    idx = Math.floor(idx);
    if (idx >= 0 && idx < defaults.length) return defaults[idx];
    return 0.56;
}

function default_motion_depth(idx) {
    var defaults = [18.0, 24.0, 30.0, 36.0, 44.0, 52.0, 60.0, 68.0];
    idx = Math.floor(idx);
    if (idx >= 0 && idx < defaults.length) return defaults[idx];
    return 36.0;
}

function default_motion_direction(idx) {
    var defaults = [0, 35, 70, 120, 165, 215, 285, 330];
    idx = Math.floor(idx);
    if (idx >= 0 && idx < defaults.length) return defaults[idx];
    return 0.0;
}

function clamp_motion_direction(value) {
    if (value === undefined || value !== value) return 0.0;
    while (value < 0.0) value += 360.0;
    while (value >= 360.0) value -= 360.0;
    return clamp(value, 0.0, 359.0);
}

function freq_to_x(f) {
    var norm = (Math.log(clamp(f, MIN_FREQ, MAX_FREQ)) - LOG_MIN) / LOG_RANGE;
    return plot_left() + norm * plot_w();
}

function x_to_freq(x) {
    var norm = (x - plot_left()) / plot_w();
    norm = clamp(norm, 0, 1);
    return Math.exp(LOG_MIN + norm * LOG_RANGE);
}

function gain_to_y(g) {
    var hi = display_range;
    var lo = -display_range;
    var norm = (clamp(g, lo, hi) - hi) / (lo - hi);
    return plot_top() + norm * plot_h();
}

function y_to_gain(y) {
    var norm = (y - plot_top()) / plot_h();
    norm = clamp(norm, 0, 1);
    var hi = display_range;
    var lo = -display_range;
    return hi + norm * (lo - hi);
}

function q_to_y(q) {
    var norm = (Math.log(clamp(q, MIN_Q, MAX_Q)) - Math.log(MIN_Q))
        / (Math.log(MAX_Q) - Math.log(MIN_Q));
    return plot_bottom() - norm * plot_h();
}

function y_to_q(y) {
    var norm = (plot_bottom() - y) / plot_h();
    norm = clamp(norm, 0, 1);
    return Math.exp(Math.log(MIN_Q) + norm * (Math.log(MAX_Q) - Math.log(MIN_Q)));
}

function analyzer_db_to_y(db) {
    var clamped = clamp(db, ANALYZER_MIN_DB, ANALYZER_MAX_DB);
    var norm = (clamped - ANALYZER_MIN_DB) / (ANALYZER_MAX_DB - ANALYZER_MIN_DB);
    return plot_bottom() - norm * plot_h();
}

function analyzer_bin_freq(idx, count) {
    var norm = idx / Math.max(count - 1, 1);
    return Math.exp(LOG_MIN + norm * LOG_RANGE);
}

// dB offset added to a bin at the draw stage for the display tilt. Zero is the
// fast path (no tilt). Pivot at 1 kHz so the slope rotates the spectrum about
// 1k: lows pulled down, highs lifted (or vice versa for a negative slope).
function analyzer_slope_at(freq) {
    if (analyzer_slope_db_oct === 0.0) return 0.0;
    return analyzer_slope_db_oct *
        (Math.log(clamp(freq, MIN_FREQ, MAX_FREQ) / 1000.0) / Math.LN2);
}

// Display dB for a bin: a bin at the noise floor (no signal) STAYS at the floor
// so the tilt can't lift the empty floor into a fake rising diagonal; a bin with
// real energy gets the display tilt added.
function analyzer_tilted_db(raw_db, tilt) {
    return (raw_db <= ANALYZER_MIN_DB + 0.5) ? ANALYZER_MIN_DB : raw_db + tilt;
}

// A real spectrum always has structure (peaks, rolloff); a PERFECTLY FLAT line
// across all bins is a no-signal artifact (digital-silence FFT or an unfed/
// uninitialized analyzer buffer) — drawn through the tilt it becomes a fake
// rising diagonal. Detect it (tiny bin-to-bin range) so the spectrum can be
// skipped entirely (reads empty, like Pro-Q with no audio).
function analyzer_is_flat() {
    var n = analyzer_display.length, i;
    if (n < 2) return 1;
    var lo = analyzer_display[0], hi = analyzer_display[0];
    for (i = 1; i < n; i++) {
        if (analyzer_display[i] < lo) lo = analyzer_display[i];
        if (analyzer_display[i] > hi) hi = analyzer_display[i];
    }
    return (hi - lo < 1.5) ? 1 : 0;
}

function now_ms() {
    return new Date().getTime();
}

function force_redraw() {
    last_redraw_ms = now_ms();
    mgraphics.redraw();
}

function request_redraw() {
    var now = now_ms();
    if (now - last_redraw_ms < REDRAW_INTERVAL_MS) return;
    last_redraw_ms = now;
    mgraphics.redraw();
}

function has_motion_animation() {
    var idx;
    for (idx = 0; idx < num_bands; idx++) {
        if (band_cache[idx].enabled && band_cache[idx].motion) return 1;
    }
    return 0;
}

function animation_tick() {
    // Driven by a repeating Task (interval+repeat — schedule() no-ops in Live).
    if (!has_motion_animation()) {
        if (redraw_task && redraw_task_running) redraw_task.cancel();
        redraw_task_running = 0;
        return;
    }
    request_redraw();
}

function refresh_animation_task() {
    if (!redraw_task && typeof Task !== "undefined") {
        redraw_task = new Task(animation_tick, this);
    }
    if (has_motion_animation()) {
        if (redraw_task && !redraw_task_running) {
            redraw_task_running = 1;
            redraw_task.interval = REDRAW_INTERVAL_MS;
            redraw_task.repeat();
        }
        return;
    }
    if (redraw_task && redraw_task_running) {
        redraw_task.cancel();
        redraw_task_running = 0;
    }
}

function update_analyzer_data(values) {
    var i, n, incoming;
    if (analyzer_frozen) return;   // hold the snapshot
    n = values.length;
    if (n < 2) {
        analyzer_display = [];
        analyzer_peaks = [];
        request_redraw();
        return;
    }

    if (analyzer_display.length !== n) {
        analyzer_display = [];
        analyzer_peaks = [];
        for (i = 0; i < n; i++) {
            analyzer_display[i] = ANALYZER_MIN_DB;
            analyzer_peaks[i] = ANALYZER_MIN_DB;
        }
    }

    for (i = 0; i < n; i++) {
        incoming = values[i];
        if (incoming !== incoming || incoming === undefined) incoming = ANALYZER_MIN_DB;
        incoming = clamp(incoming, ANALYZER_MIN_DB, ANALYZER_MAX_DB);
        analyzer_display[i] = analyzer_display[i] * 0.55 + incoming * 0.45;
        if (analyzer_display[i] > analyzer_peaks[i]) {
            analyzer_peaks[i] = analyzer_display[i];
        } else {
            analyzer_peaks[i] = Math.max(ANALYZER_MIN_DB, analyzer_peaks[i] - 0.38);
        }
    }
    request_redraw();
}

// Raw FFT magnitude frame (fft_frame): linear-spaced, linear-magnitude bins.
// Rebin into a fixed set of log-spaced display bins so the analyzer always has
// ANALYZER_BINS entries (no blank-out when the FFT size changes), and so the
// log frequency axis is correct (raw FFT bins are linear in Hz).
function ensure_analyzer_arrays() {
    var i;
    if (analyzer_display.length === ANALYZER_BINS) return;
    analyzer_display = [];
    analyzer_peaks = [];
    for (i = 0; i < ANALYZER_BINS; i++) {
        analyzer_display[i] = ANALYZER_MIN_DB;
        analyzer_peaks[i] = ANALYZER_MIN_DB;
    }
}

function update_analyzer_from_fft(mags) {
    if (analyzer_frozen) return;   // hold the snapshot
    var m = mags.length;
    if (m < 4) return;
    ensure_analyzer_arrays();
    var hz_per_bin = (sample_rate * 0.5) / m;   // mags = FFT_SIZE/2 bins -> Nyquist
    var half = 0.5 / (ANALYZER_BINS - 1);
    var i, k, klo, khi, norm, f_lo, f_hi, fc, kf, k0, fr, m0, m1, peak, sum, cnt, mag, energy, db, atk, rel;
    for (i = 0; i < ANALYZER_BINS; i++) {
        norm = i / (ANALYZER_BINS - 1);
        f_lo = Math.exp(LOG_MIN + (norm - half) * LOG_RANGE);
        f_hi = Math.exp(LOG_MIN + (norm + half) * LOG_RANGE);
        klo = Math.floor(f_lo / hz_per_bin);
        khi = Math.ceil(f_hi / hz_per_bin);
        if (klo < 0) klo = 0;
        if (khi >= m) khi = m - 1;
        if (khi < klo) khi = klo;
        if (khi - klo <= 1) {
            // Sparse low-freq cell: interpolate the magnitude at the cell
            // centre between the two nearest FFT bins so the log low end
            // is a smooth curve, not blocky stair-steps (bins are far
            // apart down here). Dense high cells stay peak-dominant.
            fc = Math.exp(LOG_MIN + norm * LOG_RANGE);
            kf = fc / hz_per_bin;
            k0 = Math.floor(kf);
            if (k0 < 0) k0 = 0;
            if (k0 > m - 2) k0 = m - 2;
            fr = kf - k0;
            m0 = mags[k0]; if (m0 < 0.0) m0 = -m0; if (m0 !== m0) m0 = 0.0;
            m1 = mags[k0 + 1]; if (m1 < 0.0) m1 = -m1; if (m1 !== m1) m1 = 0.0;
            energy = m0 * (1.0 - fr) + m1 * fr;
            db = energy > 1e-9 ? (20.0 * Math.log(energy) / Math.LN10) : ANALYZER_MIN_DB;
            db += ANALYZER_TRIM_DB;
            db = clamp(db, ANALYZER_MIN_DB, ANALYZER_MAX_DB);
            if (db > analyzer_display[i]) {
                analyzer_display[i] = analyzer_display[i] * 0.35 + db * 0.65;
            } else {
                analyzer_display[i] = analyzer_display[i] * 0.82 + db * 0.18;
            }
            if (analyzer_display[i] > analyzer_peaks[i]) {
                analyzer_peaks[i] = analyzer_display[i];
            } else {
                analyzer_peaks[i] = Math.max(ANALYZER_MIN_DB, analyzer_peaks[i] - 0.22);
            }
            continue;
        }
        peak = 0.0; sum = 0.0; cnt = 0;
        for (k = klo; k <= khi; k++) {
            mag = mags[k];
            if (mag < 0.0) mag = -mag;
            if (mag !== mag) mag = 0.0;       // NaN guard
            if (mag > peak) peak = mag;
            sum += mag; cnt++;
        }
        // Peak-dominant so tonal spikes stay sharp and narrow (a heavy mean
        // weight smears them into a blob); tiny mean term tames noise jitter.
        energy = cnt > 0 ? (0.88 * peak + 0.12 * (sum / cnt)) : 0.0;
        db = energy > 1e-9 ? (20.0 * Math.log(energy) / Math.LN10) : ANALYZER_MIN_DB;
        db += ANALYZER_TRIM_DB;
        db = clamp(db, ANALYZER_MIN_DB, ANALYZER_MAX_DB);
        // Frame-rate-independent enough at ~30fps: fast attack, slow release.
        if (db > analyzer_display[i]) {
            analyzer_display[i] = analyzer_display[i] * 0.35 + db * 0.65;
        } else {
            analyzer_display[i] = analyzer_display[i] * 0.82 + db * 0.18;
        }
        if (analyzer_display[i] > analyzer_peaks[i]) {
            analyzer_peaks[i] = analyzer_display[i];
        } else {
            analyzer_peaks[i] = Math.max(ANALYZER_MIN_DB, analyzer_peaks[i] - 0.22);
        }
    }
    request_redraw();
}

function fft_frame() {
    update_analyzer_from_fft(arrayfromargs(arguments));
}

function set_samplerate(hz) {
    if (hz > 1000.0 && hz < 768000.0) {
        sample_rate = hz;
        rebuild_band_cache();
        request_redraw();
    }
}

// Buffer-polling analyzer source: the fft_analyzer backend pokes magnitudes
// into a named buffer~ every spectral frame; we read it on a ~30fps clock.
// (Scheduler-message frames proved unreliable in Live — see fft_analyzer.py.)
var analyzer_buffer_name = "";
var analyzer_buffer_bins = 0;
var analyzer_poll_task = null;

// Optional DEDICATED detector buffer (a pre-EQ tap). When set via
// set_dyn_buffer, the dynamic detector reads THIS buffer instead of the
// post-EQ display buffer, so a dynamic cut does not pull down the level it
// reacts to. Empty = fall back to the display buffer (other devices unchanged).
var dyn_buffer_name = "";
var dyn_buffer_bins = 0;

// Read fft_size/2 linear magnitudes from a named buffer~. Returns null if the
// name is empty or the buffer~ is not instantiated yet (retry next tick).
function read_buffer_frame(nm, bins) {
    if (nm === "") return null;
    try {
        var b = new Buffer(nm);
        var n = bins > 0 ? bins : 1024;
        return b.peek(1, 0, n);
    } catch (e) {
        return null;
    }
}

function poll_analyzer_buffer() {
    if (analyzer_buffer_name === "" && dyn_buffer_name === "") return;
    var vals = read_buffer_frame(analyzer_buffer_name, analyzer_buffer_bins);
    // Spectrum display reads ONLY the (post-EQ) display buffer, gated by enable.
    if (vals && vals.length >= 4 && analyzer_enabled) update_analyzer_from_fft(vals);
    // Dynamic detector: read the DEDICATED pre-EQ buffer when one is set, else
    // fall back to the display buffer so other eq_curve devices are unchanged.
    var dyn_vals = dyn_buffer_name !== "" ? read_buffer_frame(dyn_buffer_name, dyn_buffer_bins) : null;
    if (dyn_vals === null) dyn_vals = vals;
    if (dyn_vals && dyn_vals.length >= 4) {
        if (update_dynamic_from_fft(dyn_vals)) request_redraw();
    }
}

function start_analyzer_poll() {
    if (analyzer_poll_task !== null) return;
    if (typeof Task !== "undefined") {
        analyzer_poll_task = new Task(poll_analyzer_buffer);
        analyzer_poll_task.interval = 33;
        analyzer_poll_task.repeat();
    } else if (typeof setInterval !== "undefined") {
        analyzer_poll_task = setInterval(poll_analyzer_buffer, 33);
    }
}

function set_analyzer_buffer(name, bins) {
    analyzer_buffer_name = "" + name;
    analyzer_buffer_bins = bins ? Math.floor(bins) : 0;
    start_analyzer_poll();
}

// Point the DYNAMIC detector at its own (pre-EQ) buffer~, separate from the
// post-EQ spectrum display buffer. Send with no name (or 'none'/'0') to clear
// it and fall back to the display buffer. Shares the one analyzer poll Task.
function set_dyn_buffer(name, bins) {
    var nm = (name === undefined) ? "" : "" + name;
    if (nm === "none" || nm === "0") nm = "";
    dyn_buffer_name = nm;
    dyn_buffer_bins = bins ? Math.floor(bins) : 0;
    start_analyzer_poll();
}

// Display tilt (dB/oct around 1 kHz). Render-only; no outlet, no audio effect.
function set_analyzer_slope(v) {
    if (v === undefined || v !== v) return;
    analyzer_slope_db_oct = clamp(v, -12.0, 12.0);
    request_redraw();
}

// Freeze/thaw the analyzer. Frozen holds the last frame (the update guards
// no-op) so you can EQ against a captured spectrum; thaw resumes ballistics.
function set_analyzer_freeze(v) {
    analyzer_frozen = v ? 1 : 0;
    force_redraw();
}

function band_uses_gain(type) {
    return type === TYPE_PEAK || type === TYPE_LOSHELF || type === TYPE_HISHELF;
}

function band_supports_dynamic(type) {
    return band_uses_gain(type);
}

// ── Dynamic EQ detector ─────────────────────────────────────────────────
// For each dynamic-enabled gain band, derive a gain OFFSET that tracks the
// level in the band's frequency region from the FFT magnitudes (a dedicated
// pre-EQ detector buffer when set via set_dyn_buffer, else the spectrum buffer):
// offset = dynamic_amount * envelope(level). Negative amount
// = compress (cut when loud), positive = expand (boost when loud). The offset
// is emitted as "band_dyngain idx offset" on outlet 0 for the product to ADD
// to the band's filter gain — kept separate from the static Gain param so the
// modulation never writes the param. Runs at the analyzer poll rate; biquad
// coefficient interpolation downstream smooths the steps.
var DYN_TRIGGER_FLOOR = -42.0;
var DYN_TRIGGER_RANGE = 24.0;
var DYN_ATTACK = 0.24;
var DYN_RELEASE = 0.10;
var DYN_TRIM_DB = 18.0;
var DYN_MIN_DB = -72.0;

// Peak dB of the raw FFT magnitudes in the band's region (freq +/- ~1/4 oct).
function dyn_probe_db(freq, mags) {
    var m = mags.length;
    if (m < 4) return DYN_MIN_DB;
    var hz_per_bin = (sample_rate * 0.5) / m;
    var klo = Math.floor((freq * 0.84) / hz_per_bin);
    var khi = Math.ceil((freq * 1.19) / hz_per_bin);
    if (klo < 0) klo = 0;
    if (khi >= m) khi = m - 1;
    if (khi < klo) khi = klo;
    var peak = 0.0, k, mag;
    for (k = klo; k <= khi; k++) {
        mag = mags[k]; if (mag < 0.0) mag = -mag; if (mag !== mag) mag = 0.0;
        if (mag > peak) peak = mag;
    }
    var db = peak > 1e-9 ? (20.0 * Math.log(peak) / Math.LN10) + DYN_TRIM_DB : DYN_MIN_DB;
    if (db < DYN_MIN_DB) db = DYN_MIN_DB;
    if (db > 0.0) db = 0.0;
    return db;
}

// Update every dynamic band's offset from one raw FFT frame; emit + redraw on
// change. Returns 1 if any band changed (so the caller can refresh the curve).
function update_dynamic_from_fft(mags) {
    var i, b, level, norm, coeff, target;
    var changed = 0;
    for (i = 0; i < num_bands; i++) {
        b = bands[i];
        if (!b || !b.present) continue;
        if (!b.enabled || !b.dynamic || !band_supports_dynamic(b.type) ||
                Math.abs(b.dynamic_amount) < 0.001) {
            if (Math.abs(b.dynamic_current) > 0.01 || Math.abs(b.dynamic_env) > 0.01) {
                b.dynamic_env = b.dynamic_env * 0.82;
                b.dynamic_current = b.dynamic_current * 0.82;
                outlet(0, "band_dyngain", i, b.dynamic_current);
                apply_dyn_to_cache(i);
                changed = 1;
            }
            continue;
        }
        level = dyn_probe_db(b.freq, mags);
        norm = clamp((level - DYN_TRIGGER_FLOOR) / DYN_TRIGGER_RANGE, 0.0, 1.0);
        coeff = norm > b.dynamic_env ? DYN_ATTACK : DYN_RELEASE;
        b.dynamic_env = b.dynamic_env * (1.0 - coeff) + norm * coeff;
        target = Math.round(b.dynamic_amount * b.dynamic_env * 10.0) / 10.0;
        if (Math.abs(target - b.dynamic_current) >= 0.05) {
            b.dynamic_current = target;
            outlet(0, "band_dyngain", i, target);
            apply_dyn_to_cache(i);
            changed = 1;
        }
    }
    return changed;
}

// Reflect a band's live dynamic offset in the DRAWN curve: recompute its biquad
// response at the effective gain (static + dynamic_current). The node dot stays
// at the static gain (Pro-Q style — the ring shows the range, the curve moves).
function apply_dyn_to_cache(i) {
    var bc = band_cache[i];
    if (!bc || !bc.present || !bc.enabled || !bc.uses_gain) return;
    bc.coeffs = biquad_coeffs(bc.type, bc.freq,
        clamp(bc.gain + bands[i].dynamic_current, MIN_GAIN, MAX_GAIN), bc.q);
}

// Re-sweep a motion-enabled band's DRAWN coeffs at the LFO-swept frequency (and
// gain), so the curve bump visibly moves in time with the audio LFO. Called
// every paint and recomputed from the static cache each rebuild; folds in any
// dynamic offset so motion + dynamic compose. Returns 1 if it swept (so the
// caller knows a band is animating).
function apply_motion_to_cache(i) {
    var bc = band_cache[i];
    if (!bc || !bc.present || !bc.enabled || !bc.motion || bc.motion_depth < 0.5) return 0;
    var dir = motion_direction_components(bc.motion_direction);
    var swing = Math.sin(motion_phase(i, bc));
    var f = bc.freq;
    var g = bc.gain;
    if (bands[i] && bands[i].dynamic) g = g + bands[i].dynamic_current;
    if (Math.abs(dir[0]) > 0.001) {
        f = clamp(bc.freq * Math.pow(2.0, swing * (bc.motion_depth / 100.0) * 1.25 * dir[0]),
                  MIN_FREQ, MAX_FREQ);
    }
    if (Math.abs(dir[1]) > 0.001 && bc.uses_gain) {
        g = g + swing * (bc.motion_depth / 100.0) * 12.0 * dir[1];
    }
    bc.coeffs = biquad_coeffs(bc.type, f, clamp(g, MIN_GAIN, MAX_GAIN), bc.q);
    return 1;
}

function type_default_q(type) {
    if (type === TYPE_LOWPASS || type === TYPE_HIGHPASS) return 0.707;
    return 1.0;
}

function apply_band_type(idx, type_idx) {
    var next_type;
    var prev_type;
    var prev_dynamic;
    var prev_dynamic_amount;
    var q_changed;

    idx = Math.floor(idx);
    next_type = Math.floor(type_idx);
    if (idx < 0 || idx >= num_bands) return 0;
    if (next_type < 0 || next_type >= TYPE_NAMES.length) return 0;

    prev_type = bands[idx].type;
    prev_dynamic = bands[idx].dynamic ? 1 : 0;
    prev_dynamic_amount = Math.abs(bands[idx].dynamic_amount || 0.0) > 0.001;
    q_changed = 0;

    bands[idx].type = next_type;
    if ((next_type === TYPE_LOWPASS || next_type === TYPE_HIGHPASS) && prev_type !== next_type) {
        bands[idx].q = type_default_q(next_type);
        q_changed = 1;
    }
    if (!band_supports_dynamic(next_type)) {
        bands[idx].dynamic = 0;
        bands[idx].dynamic_amount = 0.0;
    }

    rebuild_band_cache();
    outlet(0, "band_type", idx, next_type);
    if (q_changed) {
        outlet(3, "band_q", idx, band_cache[idx].q);
    }
    if (!band_supports_dynamic(next_type) && (prev_dynamic || prev_dynamic_amount)) {
        outlet(0, "band_dynamic", idx, 0);
        outlet(0, "band_dynamic_amount", idx, 0.0);
    }
    return 1;
}

function band_node_gain(b) {
    if (band_uses_gain(b.type)) return clamp(b.gain, MIN_GAIN, MAX_GAIN);
    return 0.0;
}

// Effective ring offset (dB) used for drawing AND hit-testing. With a real
// non-zero range it is the range itself; at ~0 it falls back to a signed visible
// default so the ring never overlaps the node (which is what made the grab
// ambiguous). Direction defaults opposite the node gain so a boost previews a
// compress ring and a cut previews an expand ring.
function dynamic_handle_offset(cache) {
    var amt = cache.dynamic_amount;
    // Mid-drag the ring must follow the cursor continuously through 0 (the
    // default-offset snap would make it jump at the sign flip).
    if (cache.idx !== undefined && is_active_ring_drag(cache.idx)) return amt;
    if (Math.abs(amt) >= 0.05) return amt;
    return cache.node_gain >= 0.0 ? -DYNAMIC_DEFAULT_OFFSET : DYNAMIC_DEFAULT_OFFSET;
}

function dynamic_handle_gain(cache) {
    return clamp(cache.node_gain + dynamic_handle_offset(cache), MIN_GAIN, MAX_GAIN);
}

// True while a ring-drag (drag_mode 2) is in flight on this band, so the ring
// stays visible/hittable across the amount==0 sign flip.
function is_active_ring_drag(idx) {
    return dragging && drag_mode === 2 && idx === selected_band;
}

function find_free_band() {
    var i;
    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].present) return i;
    }
    return -1;
}

function next_enabled_band(preferred_idx) {
    var i;
    if (preferred_idx >= 0 && preferred_idx < num_bands && band_cache[preferred_idx].present) {
        return preferred_idx;
    }
    for (i = 0; i < num_bands; i++) {
        if (band_cache[i].present) return i;
    }
    return -1;
}

function close_node_menu() {
    menu_band = -1;
    menu_x = 0;
    menu_y = 0;
    menu_hover = "";
}

function open_node_menu_for(idx, x, y) {
    if (idx < 0 || idx >= num_bands || !band_cache[idx].present) {
        close_node_menu();
        return;
    }
    menu_band = idx;
    menu_x = x;
    menu_y = y;
    menu_hover = "";
}

function delete_band_at(idx) {
    var next_idx;
    if (idx < 0 || idx >= num_bands) return;
    if (!bands[idx].present) return;

    bands[idx].present = 0;
    bands[idx].enabled = 0;
    bands[idx].motion = 0;
    bands[idx].dynamic = 0;
    bands[idx].dynamic_amount = 0.0;
    rebuild_band_cache();
    next_idx = next_enabled_band(idx === selected_band ? idx + 1 : selected_band);
    selected_band = next_idx;
    outlet(0, "delete_band", idx);
    outlet(0, "selected_band", next_idx);
    dragging = 0;
    close_node_menu();
    mgraphics.redraw();
}

function create_band_at(x, y) {
    var created_idx;
    var created_freq;
    var created_gain;
    created_idx = find_free_band();
    if (created_idx < 0) return 0;

    created_freq = x_to_freq(x);
    created_gain = y_to_gain(y);
    created_gain = Math.round(created_gain * 10.0) / 10.0;
    bands[created_idx].freq = clamp(created_freq, MIN_FREQ, MAX_FREQ);
    bands[created_idx].gain = clamp(created_gain, MIN_GAIN, MAX_GAIN);
    bands[created_idx].q = 1.0;
    bands[created_idx].type = TYPE_PEAK;
    bands[created_idx].present = 1;
    bands[created_idx].enabled = 1;
    bands[created_idx].motion = 0;
    bands[created_idx].dynamic = 0;
    bands[created_idx].dynamic_amount = 0.0;
    bands[created_idx].motion_rate = default_motion_rate(created_idx);
    bands[created_idx].motion_depth = default_motion_depth(created_idx);
    bands[created_idx].motion_direction = default_motion_direction(created_idx);
    selected_band = created_idx;
    dragging = 0;
    drag_mode = 0;
    rebuild_band_cache();
    close_node_menu();
    outlet(
        0,
        "add_band",
        created_idx,
        bands[created_idx].freq,
        bands[created_idx].gain,
        bands[created_idx].q,
        bands[created_idx].type,
        1
    );
    outlet(1, "band_freq", created_idx, bands[created_idx].freq);
    outlet(2, "band_gain", created_idx, bands[created_idx].gain);
    outlet(3, "band_q", created_idx, bands[created_idx].q);
    outlet(0, "band_type", created_idx, bands[created_idx].type);
    outlet(0, "band_enable", created_idx, 1);
    outlet(0, "band_motion", created_idx, 0);
    outlet(0, "band_dynamic", created_idx, 0);
    outlet(0, "band_dynamic_amount", created_idx, 0.0);
    outlet(0, "band_motion_rate", created_idx, bands[created_idx].motion_rate);
    outlet(0, "band_motion_depth", created_idx, bands[created_idx].motion_depth);
    outlet(0, "band_motion_direction", created_idx, bands[created_idx].motion_direction);
    outlet(0, "selected_band", created_idx);
    force_redraw();
    return 1;
}

// ── Filter coefficients / response ───────────────────────────────────
function biquad_coeffs(type, freq, gain, q) {
    var sr = clamp(sample_rate, 22050.0, 384000.0);
    var fc = clamp(freq, MIN_FREQ, Math.min(MAX_FREQ, sr * 0.49));
    var Q = clamp(q, MIN_Q, MAX_Q);
    var w0 = 2.0 * Math.PI * fc / sr;
    var cosw0 = Math.cos(w0);
    var sinw0 = Math.sin(w0);
    var alpha = sinw0 / (2.0 * Q);
    var A = Math.pow(10.0, gain / 40.0);
    var shelf_s = clamp(Q, 0.1, 4.0);
    var shelf_alpha = sinw0 * 0.5 * Math.sqrt((A + 1.0 / A) * (1.0 / shelf_s - 1.0) + 2.0);
    var two_sqrt_A_alpha = 2.0 * Math.sqrt(A) * shelf_alpha;
    var b0, b1, b2, a0, a1, a2;

    switch (type) {
        case TYPE_PEAK:
            b0 = 1.0 + alpha * A;
            b1 = -2.0 * cosw0;
            b2 = 1.0 - alpha * A;
            a0 = 1.0 + alpha / A;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha / A;
            break;

        case TYPE_LOSHELF:
            b0 = A * ((A + 1.0) - (A - 1.0) * cosw0 + two_sqrt_A_alpha);
            b1 = 2.0 * A * ((A - 1.0) - (A + 1.0) * cosw0);
            b2 = A * ((A + 1.0) - (A - 1.0) * cosw0 - two_sqrt_A_alpha);
            a0 = (A + 1.0) + (A - 1.0) * cosw0 + two_sqrt_A_alpha;
            a1 = -2.0 * ((A - 1.0) + (A + 1.0) * cosw0);
            a2 = (A + 1.0) + (A - 1.0) * cosw0 - two_sqrt_A_alpha;
            break;

        case TYPE_HISHELF:
            b0 = A * ((A + 1.0) + (A - 1.0) * cosw0 + two_sqrt_A_alpha);
            b1 = -2.0 * A * ((A - 1.0) + (A + 1.0) * cosw0);
            b2 = A * ((A + 1.0) + (A - 1.0) * cosw0 - two_sqrt_A_alpha);
            a0 = (A + 1.0) - (A - 1.0) * cosw0 + two_sqrt_A_alpha;
            a1 = 2.0 * ((A - 1.0) - (A + 1.0) * cosw0);
            a2 = (A + 1.0) - (A - 1.0) * cosw0 - two_sqrt_A_alpha;
            break;

        case TYPE_LOWPASS:
            b0 = (1.0 - cosw0) * 0.5;
            b1 = 1.0 - cosw0;
            b2 = (1.0 - cosw0) * 0.5;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_HIGHPASS:
            b0 = (1.0 + cosw0) * 0.5;
            b1 = -(1.0 + cosw0);
            b2 = (1.0 + cosw0) * 0.5;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_NOTCH:
            b0 = 1.0;
            b1 = -2.0 * cosw0;
            b2 = 1.0;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_BANDPASS:
            b0 = alpha;
            b1 = 0.0;
            b2 = -alpha;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_ALLPASS:
            b0 = 1.0 - alpha;
            b1 = -2.0 * cosw0;
            b2 = 1.0 + alpha;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        default:
            return [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
    }

    if (Math.abs(a0) < 1.0e-12) return [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
    return [b0 / a0, b1 / a0, b2 / a0, 1.0, a1 / a0, a2 / a0];
}

function response_db(coeffs, freq) {
    var sr = clamp(sample_rate, 22050.0, 384000.0);
    var fc = clamp(freq, MIN_FREQ, Math.min(MAX_FREQ, sr * 0.49));
    var w = 2.0 * Math.PI * fc / sr;
    var c1 = Math.cos(w);
    var s1 = Math.sin(w);
    var c2 = Math.cos(2.0 * w);
    var s2 = Math.sin(2.0 * w);

    var b0 = coeffs[0];
    var b1 = coeffs[1];
    var b2 = coeffs[2];
    var a0 = coeffs[3];
    var a1 = coeffs[4];
    var a2 = coeffs[5];

    var nr = b0 + b1 * c1 + b2 * c2;
    var ni = -b1 * s1 - b2 * s2;
    var dr = a0 + a1 * c1 + a2 * c2;
    var di = -a1 * s1 - a2 * s2;

    var num = nr * nr + ni * ni;
    var den = dr * dr + di * di;
    var mag = num / Math.max(den, 1.0e-20);
    var db = 10.0 * safe_log10(mag);
    if (db < DISPLAY_FLOOR) db = DISPLAY_FLOOR;
    if (db > MAX_GAIN) db = MAX_GAIN;
    return db;
}

function rebuild_band_cache() {
    var i;
    for (i = 0; i < MAX_BANDS; i++) {
        band_cache[i].present = bands[i].present ? 1 : 0;
        band_cache[i].enabled = bands[i].enabled ? 1 : 0;
        band_cache[i].freq = clamp(bands[i].freq, MIN_FREQ, MAX_FREQ);
        band_cache[i].gain = clamp(bands[i].gain, MIN_GAIN, MAX_GAIN);
        band_cache[i].q = clamp(bands[i].q, MIN_Q, MAX_Q);
        band_cache[i].type = Math.floor(bands[i].type);
        band_cache[i].motion = bands[i].motion ? 1 : 0;
        // While the ring of this band is actively being dragged, keep it
        // "dynamic" even as the live amount sweeps through 0 — otherwise the
        // ring would vanish mid-drag at the sign flip and the gesture glitches
        // (the reported bug). Drag owns the band; the flag is restored on release.
        band_cache[i].dynamic = (bands[i].dynamic || is_active_ring_drag(i)) ? 1 : 0;
        band_cache[i].dynamic_amount = clamp(bands[i].dynamic_amount || 0.0, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE);
        band_cache[i].motion_rate = clamp(bands[i].motion_rate || default_motion_rate(i), 0.05, 12.0);
        band_cache[i].motion_depth = clamp(bands[i].motion_depth || 0.0, 0.0, 100.0);
        band_cache[i].motion_direction = clamp_motion_direction(bands[i].motion_direction);
        band_cache[i].uses_gain = band_uses_gain(band_cache[i].type) ? 1 : 0;
        band_cache[i].node_gain = band_node_gain(band_cache[i]);
        if (!band_supports_dynamic(band_cache[i].type)) {
            band_cache[i].dynamic = 0;
            band_cache[i].dynamic_amount = 0.0;
        }

        if (!band_cache[i].present || !band_cache[i].enabled) {
            band_cache[i].coeffs = [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
        } else if (!band_cache[i].uses_gain && band_cache[i].type === TYPE_BANDPASS) {
            band_cache[i].coeffs = biquad_coeffs(
                band_cache[i].type, band_cache[i].freq, 0.0, band_cache[i].q
            );
        } else {
            band_cache[i].coeffs = biquad_coeffs(
                band_cache[i].type, band_cache[i].freq, band_cache[i].gain, band_cache[i].q
            );
        }
    }
    refresh_animation_task();
}

// ── Build frequency table (logarithmic spacing) ─────────────────────
var freq_table = [];
(function() {
    var i;
    for (i = 0; i < NUM_POINTS; i++) {
        var norm = i / (NUM_POINTS - 1);
        freq_table[i] = Math.exp(LOG_MIN + norm * LOG_RANGE);
    }
    rebuild_band_cache();
})();

// ── Drawing ──────────────────────────────────────────────────────────
function draw_plot_background() {
    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, mgraphics.size[0], mgraphics.size[1]);
    mgraphics.fill();

    mgraphics.set_source_rgba(BG_COLOR);
    mgraphics.rectangle(plot_left(), plot_top(), plot_w(), plot_h());
    mgraphics.fill_preserve();
    mgraphics.set_source_rgba(PLOT_BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.stroke();
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];

    draw_plot_background();

    draw_grid();
    draw_analyzer();
    // Re-sweep each motion band's drawn coeffs so the curve moves with the LFO.
    var _mi;
    for (_mi = 0; _mi < num_bands; _mi++) apply_motion_to_cache(_mi);
    draw_band_curves();
    draw_composite_curve();
    draw_motion_guides();
    draw_hover_crosshair();
    draw_dynamic_handles();
    draw_nodes();
    draw_tooltip();
    draw_node_menu();
}

// ── Grid ─────────────────────────────────────────────────────────────
var FREQ_LINES  = [10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 22000];
var FREQ_LABELS = ["10", "20", "50", "100", "200", "500", "1k", "2k", "5k", "10k", "22k"];
function gain_grid_step() {
    if (display_range <= 15.0) return 3.0;
    if (display_range <= 18.0) return 3.0;
    if (display_range <= 24.0) return 6.0;
    return 6.0;
}

function gain_grid_values() {
    var vals = [];
    var step = gain_grid_step();
    var g = -display_range;
    while (g <= display_range + 0.0001) {
        vals.push(Math.round(g * 100.0) / 100.0);
        g += step;
    }
    return vals;
}

function draw_grid() {
    var i, x, y, label, metrics;
    var gain_lines = gain_grid_values();

    mgraphics.set_line_width(0.5);
    for (i = 0; i < FREQ_LINES.length; i++) {
        x = freq_to_x(FREQ_LINES[i]);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(x, plot_top());
        mgraphics.line_to(x, plot_bottom());
        mgraphics.stroke();

        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.select_font_face("Arial");
        mgraphics.set_font_size(8);
        label = FREQ_LABELS[i];
        metrics = mgraphics.text_measure(label);
        mgraphics.move_to(x - metrics[0] * 0.5, plot_bottom() - 2);
        mgraphics.show_text(label);
    }

    for (i = 0; i < gain_lines.length; i++) {
        y = gain_to_y(gain_lines[i]);
        if (Math.abs(gain_lines[i]) < 0.0001) {
            mgraphics.set_source_rgba(ZERO_LINE_CLR);
            mgraphics.set_line_width(1.0);
        } else {
            mgraphics.set_source_rgba(GRID_CLR);
            mgraphics.set_line_width(0.5);
        }
        mgraphics.move_to(plot_left(), y);
        mgraphics.line_to(plot_right(), y);
        mgraphics.stroke();

        if (Math.abs(gain_lines[i] % gain_grid_step()) < 0.0001 || Math.abs(gain_lines[i]) < 0.0001) {
            mgraphics.set_source_rgba(TEXT_CLR);
            mgraphics.select_font_face("Arial");
            mgraphics.set_font_size(8);
            label = gain_lines[i] > 0 ? "+" + gain_lines[i] : "" + gain_lines[i];
            if (Math.abs(gain_lines[i]) < 0.0001) label = " 0";
            mgraphics.move_to(2, y + 3);
            mgraphics.show_text(label);
        }
    }
}

function draw_analyzer() {
    var i, n, freq;
    var xs = [];
    var ys = [];
    var py = [];
    if (!analyzer_enabled) return;
    n = analyzer_display.length;
    if (n < 2) return;
    if (analyzer_is_flat()) return;   // no real signal -> draw nothing (empty)

    var left = plot_left();
    var right = plot_right();
    var bottom = plot_bottom();
    var top = plot_top();

    var tilt;
    // Floor bins (no real signal) stay at the floor (analyzer_tilted_db) so the
    // tilt can't lift the empty floor into a fake rising diagonal.
    for (i = 0; i < n; i++) {
        freq = analyzer_bin_freq(i, n);
        tilt = analyzer_slope_at(freq);
        xs[i] = freq_to_x(freq);
        ys[i] = analyzer_db_to_y(analyzer_tilted_db(analyzer_display[i], tilt));
        py[i] = analyzer_db_to_y(analyzer_tilted_db(analyzer_peaks[i], tilt));
    }

    // Filled area under the spectrum, with a vertical gradient that fades
    // toward the floor. One pattern fill for the whole shape (cheap; avoids
    // per-slice fills).
    var grad = mgraphics.pattern_create_linear(left, top, left, bottom);
    grad.add_color_stop_rgba(0.0,
        ANALYZER_FILL_CLR[0], ANALYZER_FILL_CLR[1], ANALYZER_FILL_CLR[2],
        ANALYZER_FILL_CLR[3]);
    grad.add_color_stop_rgba(1.0,
        ANALYZER_FILL_CLR[0], ANALYZER_FILL_CLR[1], ANALYZER_FILL_CLR[2], 0.0);
    mgraphics.set_source(grad);
    mgraphics.move_to(xs[0], bottom);
    for (i = 0; i < n; i++) mgraphics.line_to(xs[i], ys[i]);
    mgraphics.line_to(xs[n - 1], bottom);
    mgraphics.close_path();
    mgraphics.fill();

    // Spectrum line on top of the fill.
    mgraphics.set_source_rgba(ANALYZER_LINE_CLR);
    mgraphics.set_line_width(1.4);
    for (i = 0; i < n; i++) {
        if (i === 0) mgraphics.move_to(xs[i], ys[i]);
        else mgraphics.line_to(xs[i], ys[i]);
    }
    mgraphics.stroke();

    // Peak-hold line (slow-decaying), drawn thin above the live spectrum.
    if (ANALYZER_PEAK_CLR[3] > 0.001) {
        mgraphics.set_source_rgba(ANALYZER_PEAK_CLR);
        mgraphics.set_line_width(1.0);
        var started = 0;
        for (i = 0; i < n; i++) {
            if (analyzer_peaks[i] <= ANALYZER_MIN_DB + 1.0) { started = 0; continue; }
            if (!started) { mgraphics.move_to(xs[i], py[i]); started = 1; }
            else mgraphics.line_to(xs[i], py[i]);
        }
        mgraphics.stroke();
    }

    // FROZEN badge — top-right of the plot while the spectrum is held.
    if (analyzer_frozen) {
        mgraphics.select_font_face("Arial");
        mgraphics.set_font_size(8.0);
        mgraphics.set_source_rgba(ANALYZER_PEAK_CLR[0], ANALYZER_PEAK_CLR[1],
                                  ANALYZER_PEAK_CLR[2], 0.92);
        mgraphics.move_to(right - 44, top + 11);
        mgraphics.show_text("FROZEN");
    }
}

function format_freq_text(freq) {
    if (freq >= 10000) return (freq / 1000.0).toFixed(1) + "k";
    if (freq >= 1000) return (freq / 1000.0).toFixed(2) + "k";
    return Math.round(freq) + " Hz";
}

function band_response_db(idx, freq) {
    if (!band_cache[idx].enabled) return 0.0;
    return response_db(band_cache[idx].coeffs, freq);
}

function curve_db_is_visible(db) {
    return db > DISPLAY_FLOOR + 0.05;
}

// ── Individual band curves ───────────────────────────────────────────
// Pro-Q-style band shading: every active gain band tints its own
// contribution with its band color so the EQ reads at a glance and is
// distinct from the analyzer behind it. The selected/hovered band gets a
// stronger fill plus its colored outline.
function draw_band_curves() {
    var i, j, f, x, y, db, clr, zero_y, started, is_active, fill_a;
    zero_y = gain_to_y(0);

    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].present) continue;
        if (!band_cache[i].enabled) continue;
        if (!band_cache[i].uses_gain) continue;
        if (Math.abs(band_cache[i].gain) < 0.01) continue;

        clr = BAND_COLORS[i % BAND_COLORS.length];
        is_active = (i === selected_band || i === hover_band);
        fill_a = is_active ? 0.22 : 0.12;

        // Filled colored region from the 0 dB line to this band's response
        // (boost fills upward, cut fills downward — both tinted).
        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], fill_a);
        mgraphics.move_to(freq_to_x(freq_table[0]), zero_y);
        for (j = 0; j < NUM_POINTS; j++) {
            f = freq_table[j];
            db = band_response_db(i, f);
            mgraphics.line_to(freq_to_x(f), gain_to_y(db));
        }
        mgraphics.line_to(freq_to_x(freq_table[NUM_POINTS - 1]), zero_y);
        mgraphics.close_path();
        mgraphics.fill();

        // Colored outline only on the active band (keeps the rest clean).
        if (!is_active) continue;
        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.55);
        mgraphics.set_line_width(1.0);
        started = 0;
        for (j = 0; j < NUM_POINTS; j++) {
            f = freq_table[j];
            db = band_response_db(i, f);
            if (!curve_db_is_visible(db)) {
                started = 0;
                continue;
            }
            x = freq_to_x(f);
            y = gain_to_y(db);
            if (!started) {
                mgraphics.move_to(x, y);
                started = 1;
            } else {
                mgraphics.line_to(x, y);
            }
        }
        if (started) mgraphics.stroke();
    }
}

// ── Composite curve + fill ───────────────────────────────────────────
function draw_composite_curve() {
    var j, f, x, y, total_db, started;
    var zero_y = gain_to_y(0);
    var xs = [];
    var ys = [];
    var i;

    for (j = 0; j < NUM_POINTS; j++) {
        f = freq_table[j];
        total_db = 0.0;
        for (i = 0; i < num_bands; i++) {
            if (band_cache[i].enabled) {
                total_db += band_response_db(i, f);
            }
        }
        x = freq_to_x(f);
        if (curve_db_is_visible(total_db)) {
            y = gain_to_y(total_db);
            xs[j] = x;
            ys[j] = y;
        } else {
            xs[j] = x;
            ys[j] = null;
        }
    }

    if (num_bands > 0) {
        mgraphics.set_source_rgba(FILL_CLR);
        mgraphics.move_to(xs[0], zero_y);
        for (j = 0; j < NUM_POINTS; j++) {
            if (ys[j] !== null) mgraphics.line_to(xs[j], ys[j]);
        }
        mgraphics.line_to(xs[NUM_POINTS - 1], zero_y);
        mgraphics.close_path();
        mgraphics.fill();
    }

    if (num_bands > 0) {
        mgraphics.set_source_rgba(COMPOSITE_CLR);
        mgraphics.set_line_width(2.0);
        started = 0;
        for (j = 0; j < NUM_POINTS; j++) {
            if (ys[j] === null) {
                started = 0;
                continue;
            }
            if (!started) {
                mgraphics.move_to(xs[j], ys[j]);
                started = 1;
            } else {
                mgraphics.line_to(xs[j], ys[j]);
            }
        }
        if (started) mgraphics.stroke();
    }
}

function motion_phase(idx, cache) {
    return now_ms() * 0.001 * cache.motion_rate * Math.PI * 2.0 + idx * 0.85;
}

function motion_direction_components(direction) {
    var radians = clamp_motion_direction(direction) * Math.PI / 180.0;
    return [Math.cos(radians), Math.sin(radians)];
}

function draw_motion_guides() {
    var i, cache, clr, alpha, phase, swing, direction;
    var x0, x1, y0, y1, mx, my;
    var freq_octaves, gain_span, low_freq, high_freq;

    for (i = 0; i < num_bands; i++) {
        cache = band_cache[i];
        if (!cache.present) continue;
        if (!cache.enabled || !cache.motion || cache.motion_depth < 0.5) continue;

        clr = BAND_COLORS[i % BAND_COLORS.length];
        alpha = 0.40;
        phase = motion_phase(i, cache);
        swing = Math.sin(phase);
        direction = motion_direction_components(cache.motion_direction);
        x0 = freq_to_x(cache.freq);
        y0 = node_y_for_band(i);
        x1 = x0;
        y1 = y0;
        mx = x0;
        my = y0;

        if (Math.abs(direction[0]) > 0.001) {
            freq_octaves = (cache.motion_depth / 100.0) * 1.25 * Math.abs(direction[0]);
            low_freq = clamp(cache.freq * Math.pow(2.0, -freq_octaves), MIN_FREQ, MAX_FREQ);
            high_freq = clamp(cache.freq * Math.pow(2.0, freq_octaves), MIN_FREQ, MAX_FREQ);
            x0 = freq_to_x(low_freq);
            x1 = freq_to_x(high_freq);
            mx = freq_to_x(clamp(cache.freq * Math.pow(2.0, swing * freq_octaves * direction[0]), MIN_FREQ, MAX_FREQ));
        }

        if (Math.abs(direction[1]) > 0.001 && cache.uses_gain) {
            gain_span = (cache.motion_depth / 100.0) * 12.0 * Math.abs(direction[1]);
            y0 = gain_to_y(clamp(cache.node_gain - gain_span, MIN_GAIN, MAX_GAIN));
            y1 = gain_to_y(clamp(cache.node_gain + gain_span, MIN_GAIN, MAX_GAIN));
            my = gain_to_y(clamp(cache.node_gain + swing * gain_span * direction[1], MIN_GAIN, MAX_GAIN));
        }

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], alpha);
        mgraphics.set_line_width(1.4);
        mgraphics.move_to(x0, y0);
        mgraphics.line_to(x1, y1);
        mgraphics.stroke();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.20);
        mgraphics.arc(mx, my, 5.0, 0, Math.PI * 2.0);
        mgraphics.fill();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.92);
        mgraphics.arc(mx, my, 1.9, 0, Math.PI * 2.0);
        mgraphics.fill();
    }
}

function node_y_for_band(idx) {
    if (band_cache[idx].uses_gain) return gain_to_y(band_cache[idx].node_gain);
    return gain_to_y(0.0);
}

// ── Draggable nodes ──────────────────────────────────────────────────
function draw_nodes() {
    var i, x, y, r, clr, enabled_alpha, ring_alpha, core_alpha, center_alpha;

    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].present) continue;
        x = freq_to_x(band_cache[i].freq);
        y = node_y_for_band(i);

        clr = BAND_COLORS[i % BAND_COLORS.length];
        r = (i === selected_band) ? NODE_RADIUS_SEL : NODE_RADIUS;
        enabled_alpha = band_cache[i].enabled ? 1.0 : 0.26;
        ring_alpha = band_cache[i].enabled ? 1.0 : 0.44;
        core_alpha = band_cache[i].enabled ? 0.92 : 0.18;
        center_alpha = band_cache[i].enabled ? 0.75 : 0.0;

        // Radial glow: a soft ambient halo on every enabled node + a brighter
        // one on the selected/hovered node (replaces the old flat disc).
        if (band_cache[i].enabled) ds_node_glow(x, y, clr, r + 6.0, 0.13);
        if (i === selected_band || i === hover_band) {
            ds_node_glow(x, y, clr, r + 11.0, band_cache[i].enabled ? 0.42 : 0.16);
        }

        mgraphics.set_source_rgba(0.02, 0.02, 0.03, band_cache[i].enabled ? (i === selected_band ? 0.78 : 0.58) : 0.28);
        mgraphics.arc(x, y, r + 1.7, 0, Math.PI * 2);
        mgraphics.fill();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], core_alpha);
        mgraphics.arc(x, y, r, 0, Math.PI * 2);
        mgraphics.fill();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], ring_alpha);
        mgraphics.set_line_width(i === selected_band ? 2.4 : 1.9);
        mgraphics.arc(x, y, r, 0, Math.PI * 2);
        mgraphics.stroke();

        if (band_cache[i].dynamic) {
            mgraphics.set_source_rgba(DYNAMIC_CLR[0], DYNAMIC_CLR[1], DYNAMIC_CLR[2], i === selected_band ? 0.94 : 0.72);
            mgraphics.set_line_width(1.6);
            mgraphics.move_to(x - (r + 4), y + (r + 4));
            mgraphics.line_to(x - 1, y + (r + 1));
            mgraphics.line_to(x - (r + 4), y + (r - 1));
            mgraphics.close_path();
            mgraphics.fill();
        }

        if (center_alpha > 0.0) {
            mgraphics.set_source_rgba(1.0, 1.0, 1.0, center_alpha);
            mgraphics.arc(x, y, 2.1, 0, Math.PI * 2);
            mgraphics.fill();
        }

        mgraphics.set_source_rgba(1.0, 1.0, 1.0, band_cache[i].enabled ? 0.88 : 0.42);
        mgraphics.select_font_face("Arial");
        mgraphics.set_font_size(i === selected_band ? 9.0 : 8.0);
        mgraphics.move_to(x + r + 3, y - r + 1);
        mgraphics.show_text("" + (i + 1));
    }
}

function draw_dynamic_handles() {
    var x, base_y, target_y, clr, alpha, size;

    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].present) continue;
        if (!band_cache[i].enabled) continue;
        if (!band_cache[i].dynamic) continue;
        if (!band_supports_dynamic(band_cache[i].type)) continue;

        x = freq_to_x(band_cache[i].freq);
        base_y = node_y_for_band(i);
        target_y = gain_to_y(dynamic_handle_gain(band_cache[i]));
        clr = BAND_COLORS[i % BAND_COLORS.length];
        alpha = i === selected_band ? 0.92 : (i === hover_band ? 0.78 : 0.58);
        size = i === selected_band ? (DYNAMIC_HANDLE_RADIUS + 1.6) : DYNAMIC_HANDLE_RADIUS;

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], i === selected_band ? 0.34 : 0.20);
        mgraphics.set_line_width(i === selected_band ? 1.9 : 1.2);
        mgraphics.move_to(x, base_y);
        mgraphics.line_to(x, target_y);
        mgraphics.stroke();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], alpha);
        mgraphics.set_line_width(i === selected_band ? 1.8 : 1.2);
        mgraphics.rectangle(x - size * 0.5, target_y - size * 0.5, size, size);
        mgraphics.stroke();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], i === selected_band ? 0.30 : 0.18);
        mgraphics.rectangle(x - size * 0.5 - 2, target_y - size * 0.5 - 2, size + 4, size + 4);
        mgraphics.fill();
    }
}

function node_menu_rect(idx) {
    var anchor_x = menu_x;
    var anchor_y = menu_y;
    var x;
    var y;
    var w = 126;
    var h = 74;
    if (anchor_x <= 0 && anchor_y <= 0) {
        anchor_x = freq_to_x(band_cache[idx].freq);
        anchor_y = node_y_for_band(idx);
    }
    x = anchor_x + 8;
    y = anchor_y - 10;
    if (x + w > plot_right()) x = freq_to_x(band_cache[idx].freq) - w - 18;
    if (x < plot_left() + 4) x = plot_left() + 4;
    if (y < plot_top() + 28) y = plot_top() + 28;
    if (y + h > plot_bottom()) y = plot_bottom() - h;
    return [x, y, w, h];
}

function menu_chip_hit(mx, my, x, y, w, h) {
    return mx >= x && mx <= x + w && my >= y && my <= y + h;
}

function node_menu_hit_test(mx, my) {
    var idx = menu_band;
    var rect;
    var col;
    var row;
    var chip_x;
    var chip_y;
    var type_idx;
    var action_x;
    var action_rects = [
        ["motion", 6, 26],
        ["dynamic", 36, 26],
        ["bypass", 66, 24],
        ["delete", 94, 24]
    ];
    var i;

    if (idx < 0 || idx >= num_bands) return "";
    rect = node_menu_rect(idx);
    if (!menu_chip_hit(mx, my, rect[0], rect[1], rect[2], rect[3])) return "";

    for (type_idx = 0; type_idx < TYPE_NAMES.length; type_idx++) {
        col = type_idx % 4;
        row = Math.floor(type_idx / 4);
        chip_x = rect[0] + 6 + col * 28;
        chip_y = rect[1] + 6 + row * 14;
        if (menu_chip_hit(mx, my, chip_x, chip_y, 24, 12)) {
            return "type:" + type_idx;
        }
    }

    for (i = 0; i < action_rects.length; i++) {
        action_x = rect[0] + action_rects[i][1];
        if (menu_chip_hit(mx, my, action_x, rect[1] + 36, action_rects[i][2], 14)) {
            return action_rects[i][0];
        }
    }
    return "panel";
}

function draw_menu_chip(x, y, w, h, label, active, color) {
    var fill = color || MENU_SURFACE_CLR;
    mgraphics.set_source_rgba(fill[0], fill[1], fill[2], active ? 0.96 : 0.82);
    mgraphics.rectangle_rounded(x, y, w, h, 3, 3);
    mgraphics.fill();

    mgraphics.set_source_rgba(active ? 0.04 : MENU_BORDER_CLR[0], active ? 0.04 : MENU_BORDER_CLR[1], active ? 0.05 : MENU_BORDER_CLR[2], active ? 0.0 : 1.0);
    if (!active) {
        mgraphics.set_line_width(1.0);
        mgraphics.rectangle_rounded(x + 0.5, y + 0.5, w - 1.0, h - 1.0, 3, 3);
        mgraphics.stroke();
    }

    mgraphics.set_source_rgba(active ? 0.05 : 0.92, active ? 0.05 : 0.94, active ? 0.06 : 0.98, 1.0);
    mgraphics.select_font_face("Arial Bold");
    mgraphics.set_font_size(7.0);
    var metrics = mgraphics.text_measure(label);
    mgraphics.move_to(x + (w - metrics[0]) * 0.5, y + 8.5);
    mgraphics.show_text(label);
}

function draw_node_menu() {
    var idx = menu_band;
    var rect;
    var type_idx;
    var col;
    var row;
    var chip_x;
    var chip_y;
    var motion_active;
    var dynamic_active;
    var menu_motion = menu_hover === "motion";
    var menu_dynamic = menu_hover === "dynamic";
    var menu_bypass = menu_hover === "bypass";
    var menu_delete = menu_hover === "delete";
    var dynamic_supported;
    if (idx < 0 || idx >= num_bands || !band_cache[idx].present) return;
    rect = node_menu_rect(idx);

    mgraphics.set_source_rgba(MENU_BG_CLR[0], MENU_BG_CLR[1], MENU_BG_CLR[2], MENU_BG_CLR[3]);
    mgraphics.rectangle_rounded(rect[0], rect[1], rect[2], rect[3], 5, 5);
    mgraphics.fill();

    mgraphics.set_source_rgba(MENU_BORDER_CLR[0], MENU_BORDER_CLR[1], MENU_BORDER_CLR[2], 1.0);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle_rounded(rect[0] + 0.5, rect[1] + 0.5, rect[2] - 1.0, rect[3] - 1.0, 5, 5);
    mgraphics.stroke();

    for (type_idx = 0; type_idx < TYPE_NAMES.length; type_idx++) {
        col = type_idx % 4;
        row = Math.floor(type_idx / 4);
        chip_x = rect[0] + 6 + col * 28;
        chip_y = rect[1] + 6 + row * 14;
        draw_menu_chip(
            chip_x,
            chip_y,
            24,
            12,
            TYPE_SHORT_NAMES[type_idx],
            band_cache[idx].type === type_idx || menu_hover === ("type:" + type_idx),
            band_cache[idx].type === type_idx ? BAND_COLORS[idx % BAND_COLORS.length] : MENU_SURFACE_CLR
        );
    }

    motion_active = band_cache[idx].enabled && band_cache[idx].motion ? 1 : 0;
    dynamic_active = band_cache[idx].enabled && band_cache[idx].dynamic ? 1 : 0;
    dynamic_supported = band_supports_dynamic(band_cache[idx].type) ? 1 : 0;
    draw_menu_chip(rect[0] + 6, rect[1] + 36, 26, 14, "MOT", motion_active || menu_motion, motion_active ? MOTION_CLR : MENU_SURFACE_CLR);
    draw_menu_chip(rect[0] + 36, rect[1] + 36, 26, 14, "DYN", dynamic_supported && (dynamic_active || menu_dynamic), dynamic_supported ? (dynamic_active ? DYNAMIC_CLR : MENU_SURFACE_CLR) : MENU_DISABLED_CLR);
    draw_menu_chip(rect[0] + 66, rect[1] + 36, 24, 14, band_cache[idx].enabled ? "BYP" : "ON", menu_bypass || !band_cache[idx].enabled, menu_bypass ? BAND_COLORS[idx % BAND_COLORS.length] : MENU_SURFACE_CLR);
    draw_menu_chip(rect[0] + 94, rect[1] + 36, 24, 14, "DEL", menu_delete, menu_delete ? BAND_COLORS[idx % BAND_COLORS.length] : MENU_SURFACE_CLR);
}

function apply_menu_action(action) {
    var idx = menu_band;
    var type_idx;
    var dynamic_was_active;
    var dynamic_amount_was_active;
    if (idx < 0 || idx >= num_bands) return;

    if (action.indexOf("type:") === 0) {
        type_idx = Math.floor(action.split(":")[1]);
        if (type_idx >= 0 && type_idx < TYPE_NAMES.length && bands[idx].type !== type_idx) {
            dynamic_was_active = bands[idx].dynamic ? 1 : 0;
            dynamic_amount_was_active = Math.abs(bands[idx].dynamic_amount || 0.0) > 0.001;
            apply_band_type(idx, type_idx);
        }
        close_node_menu();
        mgraphics.redraw();
        return;
    }

    if (action === "motion") {
        if (!bands[idx].enabled) {
            close_node_menu();
            mgraphics.redraw();
            return;
        }
        bands[idx].motion = bands[idx].motion ? 0 : 1;
        if (bands[idx].motion && (!bands[idx].motion_depth || bands[idx].motion_depth < 1.0)) {
            bands[idx].motion_depth = default_motion_depth(idx);
        }
        if (bands[idx].motion && (!bands[idx].motion_rate || bands[idx].motion_rate < 0.05)) {
            bands[idx].motion_rate = default_motion_rate(idx);
        }
        rebuild_band_cache();
        outlet(0, "band_motion", idx, bands[idx].motion ? 1 : 0);
        outlet(0, "band_motion_rate", idx, band_cache[idx].motion_rate);
        outlet(0, "band_motion_depth", idx, band_cache[idx].motion_depth);
        close_node_menu();
        mgraphics.redraw();
        return;
    }

    if (action === "dynamic") {
        if (!bands[idx].enabled) {
            close_node_menu();
            mgraphics.redraw();
            return;
        }
        if (!band_supports_dynamic(bands[idx].type)) {
            close_node_menu();
            mgraphics.redraw();
            return;
        }
        bands[idx].dynamic = bands[idx].dynamic ? 0 : 1;
        if (!bands[idx].dynamic) {
            bands[idx].dynamic_amount = 0.0;
        } else if (Math.abs(bands[idx].dynamic_amount || 0.0) < 0.01) {
            bands[idx].dynamic_amount = bands[idx].gain >= 0.0 ? -6.0 : 6.0;
        }
        rebuild_band_cache();
        outlet(0, "band_dynamic", idx, bands[idx].dynamic ? 1 : 0);
        outlet(0, "band_dynamic_amount", idx, band_cache[idx].dynamic_amount);
        close_node_menu();
        mgraphics.redraw();
        return;
    }

    if (action === "bypass") {
        bands[idx].enabled = bands[idx].enabled ? 0 : 1;
        rebuild_band_cache();
        outlet(0, "band_enable", idx, bands[idx].enabled ? 1 : 0);
        close_node_menu();
        mgraphics.redraw();
        return;
    }

    if (action === "delete") {
        delete_band_at(idx);
    }
}

// ── Tooltip on hover ────────────────────────────────────────────────
function draw_tooltip() {
    // Hover/drag only — a persistent tooltip for the selected band occludes
    // the curve (the left strip already shows the selection's values).
    var target = -1;
    if (menu_band >= 0) {
        target = -1;
    } else if (dragging && selected_band >= 0) {
        target = selected_band;
    } else if (hover_band >= 0) {
        target = hover_band;
    }
    if (target < 0 || target >= num_bands) return;

    var b = band_cache[target];
    var nx = freq_to_x(b.freq);
    var ny = node_y_for_band(target);
    var line1;
    var line2;
    var line3 = "";

    var freq_str = format_freq_text(b.freq);

    if (b.uses_gain) {
        var gain_str = (b.gain >= 0 ? "+" : "") + b.gain.toFixed(1) + " dB";
        line1 = freq_str + "  " + gain_str;
        line2 = "Q " + b.q.toFixed(2) + "  " + (TYPE_NAMES[b.type] || "Peak");
    } else {
        line1 = freq_str + "  " + (TYPE_NAMES[b.type] || "Filter");
        line2 = "Q " + b.q.toFixed(2);
    }
    if (!b.enabled) {
        line2 += "  BYPASSED";
    }
    if (b.dynamic && b.enabled) {
        line3 += "DYN " + format_dynamic_amount(b.dynamic_amount);
    }
    if (b.motion && b.enabled) {
        if (line3) line3 += "   ";
        line3 += "MOT " + format_motion_rate(b.motion_rate) + "  " + format_motion_depth(b.motion_depth) + "  DIR " + Math.round(clamp_motion_direction(b.motion_direction)) + "°";
    }

    var tx = nx + 16;
    var ty = ny - 32;
    var tw = line3 ? 214 : 104;
    var th = line3 ? 54 : 40;

    if (tx + tw > plot_right()) tx = nx - tw - 16;
    if (ty < plot_top()) ty = ny + 8;
    if (ty + th > plot_bottom()) ty = plot_bottom() - th;

    mgraphics.set_source_rgba(0.12, 0.12, 0.14, 0.92);
    mgraphics.rectangle_rounded(tx, ty, tw, th, 3, 3);
    mgraphics.fill();

    var clr = BAND_COLORS[target % BAND_COLORS.length];
    mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.42);
    mgraphics.set_line_width(1);
    mgraphics.rectangle_rounded(tx + 0.5, ty + 0.5, tw - 1, th - 1, 3, 3);
    mgraphics.stroke();

    mgraphics.set_source_rgba(0.92, 0.92, 0.94, 1.0);
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(9);
    mgraphics.move_to(tx + 5, ty + 13);
    mgraphics.show_text(line1);
    mgraphics.set_source_rgba(0.65, 0.65, 0.68, 1.0);
    mgraphics.move_to(tx + 5, ty + 26);
    mgraphics.show_text(line2);
    if (line3) {
        mgraphics.set_source_rgba(0.72, 0.85, 0.92, 1.0);
        mgraphics.move_to(tx + 5, ty + 39);
        mgraphics.show_text(line3);
    }
}

function ring_is_grabbable(i) {
    if (!band_cache[i].present) return 0;
    if (!band_cache[i].enabled) return 0;
    if (!band_cache[i].dynamic) return 0;
    if (!band_supports_dynamic(band_cache[i].type)) return 0;
    return 1;
}

// Squared pixel distance from (mx,my) to band i's ring handle (or a large
// sentinel when the band has no grabbable ring).
function ring_dist_sq(i, mx, my) {
    var x, y, dx, dy;
    if (!ring_is_grabbable(i)) return 1.0e12;
    x = freq_to_x(band_cache[i].freq);
    y = gain_to_y(dynamic_handle_gain(band_cache[i]));
    dx = mx - x;
    dy = my - y;
    return dx * dx + dy * dy;
}

// Closest grabbable ring within the hit radius (was first-match — now nearest,
// so two nearby rings resolve deterministically).
function dynamic_hit_test(mx, my) {
    var i, d, best = -1, best_d = DYNAMIC_HIT_RADIUS * DYNAMIC_HIT_RADIUS;
    for (i = 0; i < num_bands; i++) {
        d = ring_dist_sq(i, mx, my);
        if (d <= best_d) {
            best_d = d;
            best = i;
        }
    }
    return best;
}

// ── Hit-testing ──────────────────────────────────────────────────────
function hit_test(mx, my) {
    var i, x, y, dx, dy, dist;
    var best = -1;
    var best_dist = HIT_RADIUS + 1;

    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].present) continue;
        x = freq_to_x(band_cache[i].freq);
        y = node_y_for_band(i);
        dx = mx - x;
        dy = my - y;
        dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < best_dist) {
            best_dist = dist;
            best = i;
        }
    }
    return best;
}

// Squared pixel distance from (mx,my) to band idx's node dot (large sentinel
// when the band is absent). Used to arbitrate ring-vs-node presses.
function node_dist_sq(idx, mx, my) {
    var x, y, dx, dy;
    if (idx < 0 || idx >= num_bands || !band_cache[idx].present) return 1.0e12;
    x = freq_to_x(band_cache[idx].freq);
    y = node_y_for_band(idx);
    dx = mx - x;
    dy = my - y;
    return dx * dx + dy * dy;
}

// ── Message handlers (inlet 0 messages, inlet 1 sample rate) ────────
function set_band(idx, freq, gain, q, type, enabled, motion, dynamic, dynamic_amount, motion_rate, motion_depth, motion_direction) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    // Drag ownership: while the user drags this band the graph is the source
    // of truth. Parameter echoes of our own outlet values would fight the
    // gesture and force a rebuild+redraw per tick.
    if (dragging && idx === selected_band) return;
    // Echo guard: the shell routes our outlets into live.* params whose
    // changes come straight back here. Skip exact no-ops (6-arg form only —
    // the extended motion/dynamic form always applies).
    if (arguments.length <= 6) {
        var bb = bands[idx];
        var en_g = enabled ? 1 : 0;
        if ((en_g ? bb.present : 1) &&
            bb.enabled === en_g &&
            bb.type === Math.floor(type) &&
            Math.abs(bb.freq - freq) < 0.05 &&
            Math.abs(bb.gain - gain) < 0.01 &&
            Math.abs(bb.q - q) < 0.005) {
            return;
        }
    }
    if (enabled) {
        bands[idx].present = 1;
    }
    bands[idx].freq    = freq;
    bands[idx].gain    = gain;
    bands[idx].q       = q;
    bands[idx].type    = Math.floor(type);
    bands[idx].enabled = enabled ? 1 : 0;
    if (arguments.length >= 7 && motion !== undefined) {
        bands[idx].motion = motion ? 1 : 0;
    }
    if (arguments.length >= 8 && dynamic !== undefined) {
        bands[idx].dynamic = dynamic ? 1 : 0;
    }
    if (arguments.length >= 9 && dynamic_amount !== undefined) {
        bands[idx].dynamic_amount = clamp(dynamic_amount, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE);
    }
    if (arguments.length >= 10 && motion_rate !== undefined) {
        bands[idx].motion_rate = clamp(motion_rate, 0.05, 12.0);
    }
    if (arguments.length >= 11 && motion_depth !== undefined) {
        bands[idx].motion_depth = clamp(motion_depth, 0.0, 100.0);
    }
    if (arguments.length >= 12 && motion_direction !== undefined) {
        bands[idx].motion_direction = clamp_motion_direction(motion_direction);
    }
    rebuild_band_cache();
    // Message-driven updates coalesce through the 33ms throttle; direct
    // gestures redraw synchronously in their own handlers.
    request_redraw();
}

function set_num_bands(n) {
    n = Math.floor(n);
    if (n < 0) n = 0;
    if (n > MAX_BANDS) n = MAX_BANDS;
    num_bands = n;
    if (selected_band >= num_bands) selected_band = -1;
    if (menu_band >= num_bands) close_node_menu();
    rebuild_band_cache();
    force_redraw();
}

function set_selected(idx) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands || !band_cache[idx].present) {
        selected_band = -1;
    } else {
        selected_band = idx;
    }
    force_redraw();
}

function set_motion(idx, enabled) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) return;
    bands[idx].motion = enabled ? 1 : 0;
    if (bands[idx].motion && (!bands[idx].motion_depth || bands[idx].motion_depth < 1.0)) {
        bands[idx].motion_depth = default_motion_depth(idx);
    }
    if (bands[idx].motion && (!bands[idx].motion_rate || bands[idx].motion_rate < 0.05)) {
        bands[idx].motion_rate = default_motion_rate(idx);
    }
    rebuild_band_cache();
    refresh_animation_task();
    force_redraw();
}

function set_dynamic(idx, enabled) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) return;
    bands[idx].dynamic = enabled ? 1 : 0;
    if (!bands[idx].dynamic) {
        bands[idx].dynamic_amount = 0.0;
    } else if (Math.abs(bands[idx].dynamic_amount || 0.0) < 0.01) {
        bands[idx].dynamic_amount = bands[idx].gain >= 0.0 ? -6.0 : 6.0;
    }
    rebuild_band_cache();
    force_redraw();
}

function set_dynamic_amount(idx, amount) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) return;
    bands[idx].dynamic_amount = clamp(amount, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE);
    // A non-zero range turns dynamic mode ON. A zero range does NOT force it
    // back OFF: a band the user explicitly put into Dynamic mode keeps its
    // grabbable ring (drawn at a visible default offset) even at amount 0, so
    // dragging the ring through 0 doesn't make the handle disappear. The load
    // default is amount 0 with dynamic already 0, so no rings show on load.
    if (Math.abs(bands[idx].dynamic_amount) > 0.001) {
        bands[idx].dynamic = 1;
    } else {
        bands[idx].dynamic_current = 0.0;
        bands[idx].dynamic_env = 0.0;
    }
    rebuild_band_cache();
    force_redraw();
}

function set_motion_rate(idx, value) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) return;
    // Echo-safe: rate/depth NEVER toggle the enable flag. set_motion owns it.
    // (When the graph disables motion it also emits the band's current
    // rate/depth; if those re-enabled motion here the disable would bounce back
    // through the product's reverse route — an echo fight.)
    bands[idx].motion_rate = clamp(value, 0.05, 12.0);
    rebuild_band_cache();
    force_redraw();
}

function set_motion_depth(idx, value) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) return;
    bands[idx].motion_depth = clamp(value, 0.0, 100.0);
    rebuild_band_cache();
    force_redraw();
}

function set_motion_direction(idx, value) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) return;
    bands[idx].motion_direction = clamp_motion_direction(value);
    rebuild_band_cache();
    force_redraw();
}

function set_analyzer_enabled(v) {
    analyzer_enabled = v ? 1 : 0;
    force_redraw();
}

function set_display_range(v) {
    var next = Math.abs(v);
    if (next <= 16.5) {
        display_range = 15.0;
    } else if (next <= 21) {
        display_range = 18.0;
    } else if (next <= 27) {
        display_range = 24.0;
    } else {
        display_range = 30.0;
    }
    force_redraw();
}

function list() {
    if (inlet === 2) {
        update_analyzer_data(arrayfromargs(arguments));
    }
}

function msg_float(v) {
    if (inlet === 1) {
        sample_rate = clamp(v, 22050.0, 384000.0);
        rebuild_band_cache();
        mgraphics.redraw();
    }
}

function msg_int(v) {
    if (inlet === 1) {
        msg_float(v);
    }
}

function pointer_middle_click(pointerevent, but) {
    if (pointerevent) {
        if (pointerevent.button !== undefined && pointerevent.button === 1) return 1;
        if (pointerevent.buttons !== undefined && (pointerevent.buttons & 4) !== 0) return 1;
    }
    if (but !== undefined && but !== null) {
        if ((but & 4) !== 0) return 1;
    }
    return 0;
}

function pointer_context_click(pointerevent, but, ctrl) {
    if (pointerevent) {
        if (pointerevent.button !== undefined && pointerevent.button === 2) return 1;
        if (pointerevent.buttons !== undefined && (pointerevent.buttons & 2) !== 0) return 1;
    }
    if (but !== undefined && but !== null) {
        if ((but & 2) !== 0) return 1;
    }
    // In classic jsui mouse callbacks, mod2/ctrl carries right-click on Windows
    // and control-click on macOS, which should open the context menu here.
    return ctrl ? 1 : 0;
}

function pointer_option_key(pointerevent, opt) {
    if (pointerevent) {
        if (pointerevent.altKey) return 1;
        if (pointerevent.optionKey) return 1;
    }
    return opt ? 1 : 0;
}

function pointer_shift_key(pointerevent, shift) {
    if (pointerevent && pointerevent.shiftKey) return 1;
    return shift ? 1 : 0;
}

function pointer_command_key(pointerevent, cmd) {
    if (pointerevent && pointerevent.commandKey) return 1;
    return cmd ? 1 : 0;
}

function pointer_control_key(pointerevent, ctrl) {
    if (pointerevent && pointerevent.contextModifier) return 1;
    return ctrl ? 1 : 0;
}

function pointer_x(pointerevent, fallback) {
    if (!pointerevent) return fallback;
    if (pointerevent.x !== undefined) return pointerevent.x;
    if (pointerevent.localX !== undefined) return pointerevent.localX;
    if (pointerevent.offsetX !== undefined) return pointerevent.offsetX;
    if (pointerevent.clientX !== undefined) return pointerevent.clientX;
    return fallback;
}

function pointer_y(pointerevent, fallback) {
    if (!pointerevent) return fallback;
    if (pointerevent.y !== undefined) return pointerevent.y;
    if (pointerevent.localY !== undefined) return pointerevent.localY;
    if (pointerevent.offsetY !== undefined) return pointerevent.offsetY;
    if (pointerevent.clientY !== undefined) return pointerevent.clientY;
    return fallback;
}

function pointer_buttons(pointerevent, fallback) {
    if (!pointerevent) return fallback;
    if (pointerevent.buttons !== undefined) return pointerevent.buttons;
    if (pointerevent.button !== undefined) {
        if (pointerevent.button === 2) return 2;
        return 1;
    }
    return fallback;
}

function note_pointer_press(x, y) {
    last_pointer_press_ms = new Date().getTime();
    last_pointer_press_x = x;
    last_pointer_press_y = y;
    suppress_next_click = 1;
}

function should_ignore_pointer_click(x, y) {
    var now_ms;
    if (!suppress_next_click) return 0;
    now_ms = new Date().getTime();
    if ((now_ms - last_pointer_press_ms) > 300) {
        suppress_next_click = 0;
        return 0;
    }
    if (Math.abs(x - last_pointer_press_x) > 4 || Math.abs(y - last_pointer_press_y) > 4) {
        suppress_next_click = 0;
        return 0;
    }
    suppress_next_click = 0;
    return 1;
}

// Analyzer magnitude (dB) under a plot x — the display bins are log-spaced over
// [MIN_FREQ, MAX_FREQ] with the same norm as freq_to_x, so x maps straight to a
// bin. Used by Spectrum Grab to detect a peak under the cursor.
function analyzer_db_at_x(x) {
    var n = analyzer_display.length;
    if (n < 2) return ANALYZER_MIN_DB;
    var norm = (x - plot_left()) / Math.max(1.0, plot_right() - plot_left());
    if (norm < 0.0 || norm > 1.0) return ANALYZER_MIN_DB;
    var bin = Math.round(norm * (n - 1));
    if (bin < 0) bin = 0;
    else if (bin >= n) bin = n - 1;
    return analyzer_display[bin];
}

// ── Mouse interaction ────────────────────────────────────────────────
function handle_press(x, y, but, cmd, shift, opt, ctrl, pointerevent) {
    var hit = hit_test(x, y);
    var dynamic_hit = dynamic_hit_test(x, y);
    // Deterministic ring-vs-node arbitration. The ring only wins a drag-start
    // when it is genuinely closer than its band's node by a dead-zone margin
    // (DYNAMIC_GRAB_BIAS_SQ) — so tiny mouse jitter near a node that has its
    // dynamic ring nearby (e.g. a small/zero range) can no longer flip the
    // drag_mode between a gain edit and a ring edit. A ring with no competing
    // node (hit < 0) is always grabbable.
    var ring_wins = 0;
    if (dynamic_hit >= 0) {
        if (hit < 0) {
            ring_wins = 1;
        } else {
            ring_wins = ring_dist_sq(dynamic_hit, x, y) + DYNAMIC_GRAB_BIAS_SQ
                <= node_dist_sq(hit, x, y) ? 1 : 0;
        }
    }
    if (!ring_wins) dynamic_hit = -1;
    var clicked_band = dynamic_hit >= 0 ? dynamic_hit : hit;
    var menu_hit = node_menu_hit_test(x, y);
    var now_ms = new Date().getTime();
    var middle_click = pointer_middle_click(pointerevent, but);
    var context_click = pointer_context_click(pointerevent, but, ctrl);
    var option_click = pointer_option_key(pointerevent, opt);
    var command_click = pointer_command_key(pointerevent, cmd);
    var control_click = pointer_control_key(pointerevent, ctrl);
    var is_delete_double_click = (
        clicked_band >= 0 &&
        clicked_band === last_click_band &&
        (now_ms - last_click_ms) <= DOUBLE_CLICK_MS &&
        !option_click &&
        !control_click &&
        !command_click &&
        !context_click &&
        but <= 1
    );

    last_click_ms = now_ms;
    last_click_band = clicked_band;

    if (middle_click) {
        dragging = 0;
        drag_mode = 0;
        mgraphics.redraw();
        return;
    }

    if (is_delete_double_click) {
        close_node_menu();
        reset_band_at(clicked_band);
        suppress_next_ondblclick_delete = 1;
        last_click_ms = 0;
        last_click_band = -1;
        return;
    }

    if (menu_band >= 0) {
        if (menu_hit && menu_hit !== "panel") {
            apply_menu_action(menu_hit);
            return;
        }
        if (!menu_hit) {
            close_node_menu();
        } else {
            mgraphics.redraw();
            return;
        }
    }

    if (option_click) {
        if (dynamic_hit >= 0 || hit >= 0) {
            var opt_idx = dynamic_hit >= 0 ? dynamic_hit : hit;
            bands[opt_idx].enabled = bands[opt_idx].enabled ? 0 : 1;
            selected_band = opt_idx;
            rebuild_band_cache();
            outlet(0, "band_enable", opt_idx, bands[opt_idx].enabled);
            outlet(0, "selected_band", opt_idx);
            mgraphics.redraw();
            return;
        }
    }

    if (context_click) {
        if (dynamic_hit >= 0 || hit >= 0) {
            selected_band = dynamic_hit >= 0 ? dynamic_hit : hit;
            dragging = 0;
            drag_mode = 0;
            outlet(0, "selected_band", selected_band);
            open_node_menu_for(selected_band, x, y);
            mgraphics.redraw();
            return;
        }
        dragging = 0;
        drag_mode = 0;
        mgraphics.redraw();
        return;
    }

    if (hit < 0 && dynamic_hit < 0) {
        // Spectrum Grab: a plain press on a prominent analyzer peak (behind the
        // curve) spawns a band right at that frequency and immediately drags it
        // — grab the resonance and pull it down to cut. Plain presses on empty
        // space just deselect (below).
        if (!option_click && !context_click && !command_click && !control_click &&
                x >= plot_left() && x <= plot_right() &&
                y >= plot_top() && y <= plot_bottom() &&
                analyzer_db_at_x(x) > SPECTRUM_GRAB_DB &&
                find_free_band() >= 0) {
            if (create_band_at(x, y)) {
                dragging = 1;
                drag_mode = 1;
                drag_start_freq = bands[selected_band].freq;
                drag_start_gain = bands[selected_band].gain;
                drag_start_q = bands[selected_band].q;
                return;
            }
        }
        selected_band = -1;
        dragging = 0;
        drag_mode = 0;
        close_node_menu();
        mgraphics.redraw();
        return;
    }

    if (dynamic_hit >= 0) {
        selected_band = dynamic_hit;
        dragging = 1;
        drag_mode = 2;
        close_node_menu();
        drag_start_dynamic = bands[dynamic_hit].dynamic_amount || 0.0;
        outlet(0, "selected_band", dynamic_hit);
        mgraphics.redraw();
        return;
    }

    if (hit >= 0) {
        selected_band = hit;
        dragging = 1;
        drag_mode = 1;
        close_node_menu();
        drag_start_freq = bands[hit].freq;
        drag_start_gain = bands[hit].gain;
        drag_start_q = bands[hit].q;
        outlet(0, "selected_band", hit);
    } else {
        selected_band = -1;
        dragging = 0;
        drag_mode = 0;
        close_node_menu();
    }
    mgraphics.redraw();
}

function reset_band_at(idx) {
    // Pro-Q semantics: double-click resets the band (gain bands -> 0 dB,
    // gain-less types -> default Q). Delete stays on the context menu.
    if (idx < 0 || idx >= num_bands) return;
    if (!bands[idx].present) return;
    selected_band = idx;
    if (band_cache[idx].uses_gain) {
        if (bands[idx].gain !== 0.0) {
            bands[idx].gain = 0.0;
            rebuild_band_cache();
            outlet(2, "band_gain", idx, 0.0);
        }
    } else if (bands[idx].q !== 1.0) {
        bands[idx].q = 1.0;
        rebuild_band_cache();
        outlet(3, "band_q", idx, 1.0);
    }
    outlet(0, "selected_band", idx);
    mgraphics.redraw();
}

function handle_double_click(x, y) {
    if (suppress_next_ondblclick_delete) {
        suppress_next_ondblclick_delete = 0;
        return;
    }

    var hit = hit_test(x, y);
    var dynamic_hit = dynamic_hit_test(x, y);

    if (dynamic_hit >= 0 || hit >= 0) {
        reset_band_at(dynamic_hit >= 0 ? dynamic_hit : hit);
        return;
    }
    if (!point_in_plot(x, y)) return;
    create_band_at(x, y);
}

function handle_drag_at(x, y, but, cmd, shift) {
    if (but === 0) {
        dragging = 0;
        drag_mode = 0;
        mgraphics.redraw();
        return;
    }
    if (!dragging || selected_band < 0 || selected_band >= num_bands) return;

    var b = bands[selected_band];
    var cache = band_cache[selected_band];
    var new_dynamic;
    var new_freq = x_to_freq(x);
    var new_gain = b.gain;
    var new_q = b.q;
    var uses_gain = cache.uses_gain ? 1 : 0;
    var target_y;

    if (menu_band >= 0) {
        close_node_menu();
    }

    if (drag_mode === 2) {
        new_dynamic = y_to_gain(y) - cache.node_gain;
        if (shift) {
            new_dynamic = b.dynamic_amount + (new_dynamic - b.dynamic_amount) * 0.15;
        }
        new_dynamic = Math.round(clamp(new_dynamic, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE) * 10.0) / 10.0;
        if (new_dynamic === b.dynamic_amount) return;
        bands[selected_band].dynamic = 1;
        bands[selected_band].dynamic_amount = new_dynamic;
        rebuild_band_cache();
        outlet(0, "band_dynamic", selected_band, 1);
        outlet(0, "band_dynamic_amount", selected_band, new_dynamic);
        mgraphics.redraw();
        return;
    }

    if (uses_gain) {
        target_y = y;
        new_gain = y_to_gain(target_y);
        if (cmd) {
            new_gain = drag_start_gain;
        }
        if (shift) {
            new_gain = b.gain + (new_gain - b.gain) * 0.15;
        }
        new_gain = Math.round(new_gain * 10.0) / 10.0;
        new_gain = clamp(new_gain, MIN_GAIN, MAX_GAIN);
    } else {
        target_y = y;
        new_q = y_to_q(target_y);
        if (cmd) {
            new_q = drag_start_q;
        }
        if (shift) {
            new_q = b.q + (new_q - b.q) * 0.15;
        }
        new_q = Math.round(new_q * 100.0) / 100.0;
        new_q = clamp(new_q, MIN_Q, MAX_Q);
    }

    if (shift) {
        new_freq = b.freq + (new_freq - b.freq) * 0.15;
    }

    // Continuous frequency (0.1 Hz resolution) — the old 10 Hz snap above
    // 1 kHz made the node stutter against the visual drag position. Display
    // formatting handles presentation rounding.
    new_freq = Math.round(new_freq * 10.0) / 10.0;
    new_freq = clamp(new_freq, MIN_FREQ, MAX_FREQ);

    if (uses_gain && new_freq === b.freq && new_gain === b.gain) return;
    if (!uses_gain && new_freq === b.freq && new_q === b.q) return;

    bands[selected_band].freq = new_freq;
    if (uses_gain) {
        bands[selected_band].gain = new_gain;
    } else {
        bands[selected_band].q = new_q;
    }

    rebuild_band_cache();
    outlet(1, "band_freq", selected_band, new_freq);
    if (uses_gain) {
        outlet(2, "band_gain", selected_band, new_gain);
    } else {
        outlet(3, "band_q", selected_band, new_q);
    }
    mgraphics.redraw();
}

function handle_hover(x, y) {
    var prev = hover_band;
    var dynamic_hover;
    var prev_menu = menu_hover;
    dynamic_hover = dynamic_hit_test(x, y);
    hover_band = dynamic_hover >= 0 ? dynamic_hover : hit_test(x, y);
    if (menu_band >= 0) {
        menu_hover = node_menu_hit_test(x, y);
        if (menu_hover === "panel") menu_hover = "";
    } else {
        menu_hover = "";
    }
    var prev_in = hover_in_plot;
    hover_x = x;
    hover_y = y;
    hover_in_plot = (!dragging && x >= plot_left() && x <= plot_right() &&
                     y >= plot_top() && y <= plot_bottom()) ? 1 : 0;
    // Cursor: pointing hand over a grabbable node/ring/menu-chip, crosshair over
    // the open plot, default arrow otherwise. (Drag uses the grab hand, set at
    // press/drag time since onpointermove skips hover while a button is down.)
    ds_set_cursor((hover_band >= 0 || menu_hover) ? DS_CUR_HAND
               : (hover_in_plot ? DS_CUR_CROSS : DS_CUR_ARROW));
    if (hover_band !== prev || menu_hover !== prev_menu ||
            hover_in_plot || prev_in) {
        request_redraw();
    }
}

function clear_hover_state() {
    ds_set_cursor(DS_CUR_ARROW);
    if (hover_band >= 0 || menu_hover || hover_in_plot) {
        hover_band = -1;
        menu_hover = "";
        hover_in_plot = 0;
        mgraphics.redraw();
    }
}

// Pro-Q-style hover crosshair: faint guides from the cursor to the axes,
// with the exact frequency in the bottom gutter and gain in the left gutter.
function draw_hover_crosshair() {
    if (!hover_in_plot) return;
    var x = clamp(hover_x, plot_left(), plot_right());
    var y = clamp(hover_y, plot_top(), plot_bottom());
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.46);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(x, plot_top()); mgraphics.line_to(x, plot_bottom()); mgraphics.stroke();
    mgraphics.move_to(plot_left(), y); mgraphics.line_to(plot_right(), y); mgraphics.stroke();

    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(8.0);
    // Frequency under the cursor (bottom gutter).
    var ftxt = format_freq_text(x_to_freq(x));
    var fw = ftxt.length * 4.6 + 4;
    var fx = clamp(x - fw * 0.5, 0.0, mgraphics.size[0] - fw);
    mgraphics.set_source_rgba(0.05, 0.06, 0.08, 0.92);
    mgraphics.rectangle(fx, plot_bottom() + 1.0, fw, 10.0);
    mgraphics.fill();
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.98);
    mgraphics.move_to(fx + 2.0, plot_bottom() + 8.5);
    mgraphics.show_text(ftxt);
    // Gain at the cursor (left gutter).
    var gv = y_to_gain(y);
    var gtxt = (gv >= 0 ? "+" : "") + gv.toFixed(1);
    mgraphics.set_source_rgba(0.05, 0.06, 0.08, 0.92);
    mgraphics.rectangle(0.0, y - 5.0, MARGIN_LEFT - 1.0, 10.0);
    mgraphics.fill();
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.98);
    mgraphics.move_to(1.0, y + 2.5);
    mgraphics.show_text(gtxt);
}

function onpointerdown(pointerevent) {
    var x = pointer_x(pointerevent, 0);
    var y = pointer_y(pointerevent, 0);
    note_pointer_press(x, y);
    handle_press(
        x,
        y,
        pointer_buttons(pointerevent, 1),
        pointer_command_key(pointerevent, 0),
        pointer_shift_key(pointerevent, 0),
        pointer_option_key(pointerevent, 0),
        pointer_control_key(pointerevent, 0),
        pointerevent
    );
    if (dragging) ds_set_cursor(DS_CUR_GRAB);
}

function onpointermove(pointerevent) {
    var buttons = pointer_buttons(pointerevent, 0);
    var x = pointer_x(pointerevent, 0);
    var y = pointer_y(pointerevent, 0);
    if (dragging && ((buttons & 1) !== 0)) {
        ds_set_cursor(DS_CUR_GRAB);
        handle_drag_at(
            x,
            y,
            buttons,
            pointer_command_key(pointerevent, 0),
            pointer_shift_key(pointerevent, 0)
        );
        return;
    }
    if (dragging && buttons === 0) {
        dragging = 0;
        drag_mode = 0;
    }
    handle_hover(x, y);
}

function onpointerup(pointerevent) {
    var x = pointer_x(pointerevent, 0);
    var y = pointer_y(pointerevent, 0);
    if (dragging) {
        dragging = 0;
        drag_mode = 0;
        mgraphics.redraw();
    } else {
        handle_hover(x, y);
    }
}

function onpointerleave(pointerevent) {
    if (dragging && pointerevent && pointerevent.buttons === 0) {
        dragging = 0;
        drag_mode = 0;
    }
    clear_hover_state();
}

function onclick(x, y, but, cmd, shift, caps, opt, ctrl, pointerevent) {
    if (should_ignore_pointer_click(x, y)) return;
    handle_press(x, y, but, cmd, shift, opt, ctrl, pointerevent);
}

function ondblclick(x, y, but, cmd, shift, caps, opt, ctrl) {
    handle_double_click(x, y);
}

function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    handle_drag_at(x, y, but, cmd, shift);
}

function onidle(x, y, but, cmd, shift, caps, opt, ctrl) {
    handle_hover(x, y);
}

function onidleout(x, y, but, cmd, shift, caps, opt, ctrl) {
    clear_hover_state();
}

function onwheel(x, y, scrollx, scrolly, cmd, shift, caps, opt, ctrl) {
    var target = hover_band >= 0 ? hover_band : selected_band;
    if (target < 0 || target >= num_bands) return;
    if (!bands[target].enabled) return;

    var q = bands[target].q;
    var factor = shift ? 0.02 : 0.08;
    q = q * (1.0 + scrolly * factor);
    q = clamp(q, MIN_Q, MAX_Q);
    q = Math.round(q * 100.0) / 100.0;
    if (q === bands[target].q) return;

    bands[target].q = q;
    rebuild_band_cache();
    outlet(3, "band_q", target, q);
    mgraphics.redraw();
}

function format_dynamic_amount(v) {
    var prefix = v > 0 ? "+" : "";
    return prefix + v.toFixed(1) + " dB";
}
""")
