"""Parametric EQ curve display with draggable nodes for jsui.

Generates JavaScript (ES5) code that runs inside Max's jsui object,
drawing a multi-band parametric EQ with interactive draggable nodes.
Communication uses 1 inlet and 4 outlets — see EQ_CURVE_INLETS / EQ_CURVE_OUTLETS.

Inlet 0 messages:
    set_band band_idx freq gain q type enabled
    set_num_bands N
    set_selected band_idx

Outlet 0: selected_band band_idx
Outlet 1: band_freq band_idx freq
Outlet 2: band_gain band_idx gain
Outlet 3: band_q band_idx q

Mouse interaction (Pro-Q style):
    Click node: select band
    Drag node: adjust freq (horizontal) and gain (vertical)
    Mouse wheel on node: adjust Q (bandwidth)
    Shift + drag: fine-tune mode (higher precision)
    Cmd/Ctrl + drag: lock gain (horizontal-only frequency change)
    Hover: tooltip showing freq/gain/Q values
"""

EQ_CURVE_INLETS = 1
EQ_CURVE_OUTLETS = 4


def eq_curve_js(
    *,
    bg_color="0.07, 0.07, 0.08, 1.0",
    composite_color="0.85, 0.88, 0.92, 1.0",
    fill_color="0.45, 0.75, 0.65, 0.12",
    grid_color="0.2, 0.2, 0.22, 0.5",
    text_color="0.5, 0.5, 0.52, 1.0",
    zero_line_color="0.3, 0.3, 0.32, 0.8",
):
    """Return JavaScript source for an interactive parametric EQ display.

    The returned code is ES5-compatible and uses Max's mgraphics (Cairo)
    API to render a FabFilter Pro-Q style EQ curve with draggable band
    nodes, logarithmic frequency grid, and composite magnitude response.

    Features:
        - Click-and-drag band nodes to adjust frequency and gain
        - Mouse wheel to adjust Q (bandwidth) on hovered/selected band
        - Shift+drag for fine-tune mode
        - Cmd+drag to lock gain (horizontal-only)
        - Hover tooltip showing freq/gain/Q values
        - ±30 dB gain range (matches Pro-Q 3)
        - Filled composite curve with per-band colored curves
        - Band number labels and glow effects

    Args:
        bg_color: RGBA background color.
        composite_color: RGBA color for the composite EQ curve.
        fill_color: RGBA color for the fill between composite curve and 0 dB.
        grid_color: RGBA color for grid lines.
        text_color: RGBA color for axis labels.
        zero_line_color: RGBA color for the 0 dB reference line.
    """
    return _JS_TEMPLATE.format(
        bg_color=bg_color,
        composite_color=composite_color,
        fill_color=fill_color,
        grid_color=grid_color,
        text_color=text_color,
        zero_line_color=zero_line_color,
    )


_JS_TEMPLATE = """\
// Parametric EQ Curve Display — generated by m4l-builder
// ES5 compatible — no let/const/arrow/template literals

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 4;

// ── Configurable colors ──────────────────────────────────────────────
var BG_COLOR       = [{bg_color}];
var COMPOSITE_CLR  = [{composite_color}];
var FILL_CLR       = [{fill_color}];
var GRID_CLR       = [{grid_color}];
var TEXT_CLR       = [{text_color}];
var ZERO_LINE_CLR  = [{zero_line_color}];

var BAND_COLORS = [
    [0.90, 0.35, 0.35, 1.0],
    [0.90, 0.65, 0.25, 1.0],
    [0.85, 0.85, 0.30, 1.0],
    [0.35, 0.80, 0.45, 1.0],
    [0.35, 0.75, 0.85, 1.0],
    [0.40, 0.55, 0.90, 1.0],
    [0.65, 0.45, 0.85, 1.0],
    [0.85, 0.45, 0.65, 1.0]
];

// ── Filter types ─────────────────────────────────────────────────────
var TYPE_PEAK     = 0;
var TYPE_LOSHELF  = 1;
var TYPE_HISHELF  = 2;
var TYPE_LOWPASS  = 3;
var TYPE_HIGHPASS = 4;
var TYPE_NOTCH    = 5;
var TYPE_BANDPASS = 6;

var TYPE_NAMES = ["Peak", "LShelf", "HShelf", "LP", "HP", "Notch", "BP"];

// ── Constants ────────────────────────────────────────────────────────
var MIN_FREQ   = 20;
var MAX_FREQ   = 20000;
var MIN_GAIN   = -30;
var MAX_GAIN   = 30;
var MIN_Q      = 0.1;
var MAX_Q      = 30.0;
var NUM_POINTS = 512;
var NODE_RADIUS     = 7;
var NODE_RADIUS_SEL = 10;
var HIT_RADIUS      = 14;
var MAX_BANDS  = 8;
var LOG_MIN    = Math.log(MIN_FREQ);
var LOG_MAX    = Math.log(MAX_FREQ);
var LOG_RANGE  = LOG_MAX - LOG_MIN;

// ── Margin / padding for axis labels ─────────────────────────────────
var MARGIN_LEFT   = 30;
var MARGIN_RIGHT  = 8;
var MARGIN_TOP    = 6;
var MARGIN_BOTTOM = 16;

// ── State ────────────────────────────────────────────────────────────
var num_bands = 0;
var selected_band = -1;
var hover_band = -1;
var dragging = 0;
var drag_start_freq = 0;
var drag_start_gain = 0;

var bands = [];
var i;
for (i = 0; i < MAX_BANDS; i++) {{
    bands[i] = {{
        freq: 1000,
        gain: 0,
        q: 1.0,
        type: TYPE_PEAK,
        enabled: 1
    }};
}}

// ── Coordinate helpers ───────────────────────────────────────────────
function plot_left()   {{ return MARGIN_LEFT; }}
function plot_right()  {{ return mgraphics.size[0] - MARGIN_RIGHT; }}
function plot_top()    {{ return MARGIN_TOP; }}
function plot_bottom() {{ return mgraphics.size[1] - MARGIN_BOTTOM; }}
function plot_w()      {{ return plot_right() - plot_left(); }}
function plot_h()      {{ return plot_bottom() - plot_top(); }}

function freq_to_x(f) {{
    var norm = (Math.log(f) - LOG_MIN) / LOG_RANGE;
    return plot_left() + norm * plot_w();
}}

function x_to_freq(x) {{
    var norm = (x - plot_left()) / plot_w();
    if (norm < 0) norm = 0;
    if (norm > 1) norm = 1;
    var f = Math.exp(LOG_MIN + norm * LOG_RANGE);
    if (f < MIN_FREQ) f = MIN_FREQ;
    if (f > MAX_FREQ) f = MAX_FREQ;
    return f;
}}

function gain_to_y(g) {{
    var norm = (g - MAX_GAIN) / (MIN_GAIN - MAX_GAIN);
    return plot_top() + norm * plot_h();
}}

function y_to_gain(y) {{
    var norm = (y - plot_top()) / plot_h();
    if (norm < 0) norm = 0;
    if (norm > 1) norm = 1;
    var g = MAX_GAIN + norm * (MIN_GAIN - MAX_GAIN);
    if (g < MIN_GAIN) g = MIN_GAIN;
    if (g > MAX_GAIN) g = MAX_GAIN;
    return g;
}}

// ── Filter magnitude (dB at frequency f for band b) ──────────────────
function band_db(b, f) {{
    if (!b.enabled) return 0;
    var fc = b.freq;
    var gain = b.gain;
    var Q = b.q;
    if (Q < 0.1) Q = 0.1;
    var ratio, s, denom;

    switch (b.type) {{
        case TYPE_PEAK:
            ratio = f / fc - fc / f;
            denom = 1 + (ratio * Q) * (ratio * Q);
            return gain / denom;

        case TYPE_LOSHELF:
            s = 1.0;
            return gain * 0.5 * (1 - tanh_approx(s * Q * Math.log(f / fc)));

        case TYPE_HISHELF:
            s = 1.0;
            return gain * 0.5 * (1 + tanh_approx(s * Q * Math.log(f / fc)));

        case TYPE_LOWPASS:
            if (f <= fc) return 0;
            return -12.0 * Math.log(f / fc) / Math.log(2);

        case TYPE_HIGHPASS:
            if (f >= fc) return 0;
            return -12.0 * Math.log(fc / f) / Math.log(2);

        case TYPE_NOTCH:
            ratio = f / fc - fc / f;
            denom = 1 + (ratio * Q) * (ratio * Q);
            return -48.0 / denom;

        case TYPE_BANDPASS:
            ratio = f / fc - fc / f;
            denom = 1 + (ratio * Q) * (ratio * Q);
            return gain - gain / denom;

        default:
            return 0;
    }}
}}

function tanh_approx(x) {{
    if (x > 4)  return 1;
    if (x < -4) return -1;
    var x2 = x * x;
    return x * (27 + x2) / (27 + 9 * x2);
}}

// ── Build frequency table (logarithmic spacing) ─────────────────────
var freq_table = [];
(function() {{
    var i;
    for (i = 0; i < NUM_POINTS; i++) {{
        var norm = i / (NUM_POINTS - 1);
        freq_table[i] = Math.exp(LOG_MIN + norm * LOG_RANGE);
    }}
}})();

// ── Drawing ──────────────────────────────────────────────────────────
function paint() {{
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];

    // background
    mgraphics.set_source_rgba(BG_COLOR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();

    draw_grid();
    draw_band_curves();
    draw_composite_curve();
    draw_nodes();
    draw_tooltip();
}}

// ── Grid ─────────────────────────────────────────────────────────────
var FREQ_LINES  = [20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000];
var FREQ_LABELS = ["20", "50", "100", "200", "500", "1k", "2k", "5k", "10k", "20k"];
var GAIN_LINES  = [-30, -24, -18, -12, -6, 0, 6, 12, 18, 24, 30];

function draw_grid() {{
    var i, x, y, label;

    // frequency grid lines
    mgraphics.set_line_width(0.5);
    for (i = 0; i < FREQ_LINES.length; i++) {{
        x = freq_to_x(FREQ_LINES[i]);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(x, plot_top());
        mgraphics.line_to(x, plot_bottom());
        mgraphics.stroke();

        // label
        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.select_font_face("Ableton Sans Medium");
        mgraphics.set_font_size(8);
        mgraphics.move_to(x - 6, plot_bottom() + 12);
        mgraphics.show_text(FREQ_LABELS[i]);
    }}

    // gain grid lines
    for (i = 0; i < GAIN_LINES.length; i++) {{
        y = gain_to_y(GAIN_LINES[i]);
        if (GAIN_LINES[i] === 0) {{
            mgraphics.set_source_rgba(ZERO_LINE_CLR);
            mgraphics.set_line_width(1.0);
        }} else {{
            mgraphics.set_source_rgba(GRID_CLR);
            mgraphics.set_line_width(0.5);
        }}
        mgraphics.move_to(plot_left(), y);
        mgraphics.line_to(plot_right(), y);
        mgraphics.stroke();

        // label (skip some for density)
        if (GAIN_LINES[i] % 6 === 0) {{
            mgraphics.set_source_rgba(TEXT_CLR);
            mgraphics.select_font_face("Ableton Sans Medium");
            mgraphics.set_font_size(8);
            label = GAIN_LINES[i] > 0 ? "+" + GAIN_LINES[i] : "" + GAIN_LINES[i];
            if (GAIN_LINES[i] === 0) label = " 0";
            mgraphics.move_to(2, y + 3);
            mgraphics.show_text(label);
        }}
    }}
}}

// ── Individual band curves ───────────────────────────────────────────
function draw_band_curves() {{
    var i, j, f, x, y, db, clr;

    for (i = 0; i < num_bands; i++) {{
        if (!bands[i].enabled) continue;
        if (bands[i].gain === 0 && bands[i].type !== TYPE_LOWPASS
            && bands[i].type !== TYPE_HIGHPASS && bands[i].type !== TYPE_NOTCH) continue;

        clr = BAND_COLORS[i % BAND_COLORS.length];

        // Selected band gets filled area
        if (i === selected_band || i === hover_band) {{
            var zero_y = gain_to_y(0);
            mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.08);
            mgraphics.move_to(freq_to_x(freq_table[0]), zero_y);
            for (j = 0; j < NUM_POINTS; j++) {{
                f = freq_table[j];
                db = band_db(bands[i], f);
                x = freq_to_x(f);
                y = gain_to_y(db);
                if (y < plot_top()) y = plot_top();
                if (y > plot_bottom()) y = plot_bottom();
                mgraphics.line_to(x, y);
            }}
            mgraphics.line_to(freq_to_x(freq_table[NUM_POINTS - 1]), zero_y);
            mgraphics.close_path();
            mgraphics.fill();
        }}

        // Band curve line
        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.45);
        mgraphics.set_line_width(1.0);
        for (j = 0; j < NUM_POINTS; j++) {{
            f = freq_table[j];
            db = band_db(bands[i], f);
            x = freq_to_x(f);
            y = gain_to_y(db);
            if (y < plot_top()) y = plot_top();
            if (y > plot_bottom()) y = plot_bottom();
            if (j === 0) {{
                mgraphics.move_to(x, y);
            }} else {{
                mgraphics.line_to(x, y);
            }}
        }}
        mgraphics.stroke();
    }}
}}

// ── Composite curve + fill ───────────────────────────────────────────
function draw_composite_curve() {{
    var j, f, x, y, db, total_db;
    var zero_y = gain_to_y(0);
    var xs = [];
    var ys = [];

    for (j = 0; j < NUM_POINTS; j++) {{
        f = freq_table[j];
        total_db = 0;
        var i;
        for (i = 0; i < num_bands; i++) {{
            if (bands[i].enabled) {{
                total_db += band_db(bands[i], f);
            }}
        }}
        x = freq_to_x(f);
        y = gain_to_y(total_db);
        if (y < plot_top()) y = plot_top();
        if (y > plot_bottom()) y = plot_bottom();
        xs[j] = x;
        ys[j] = y;
    }}

    // fill to 0 dB
    if (num_bands > 0) {{
        mgraphics.set_source_rgba(FILL_CLR);
        mgraphics.move_to(xs[0], zero_y);
        for (j = 0; j < NUM_POINTS; j++) {{
            mgraphics.line_to(xs[j], ys[j]);
        }}
        mgraphics.line_to(xs[NUM_POINTS - 1], zero_y);
        mgraphics.close_path();
        mgraphics.fill();
    }}

    // composite stroke
    if (num_bands > 0) {{
        mgraphics.set_source_rgba(COMPOSITE_CLR);
        mgraphics.set_line_width(2.0);
        for (j = 0; j < NUM_POINTS; j++) {{
            if (j === 0) {{
                mgraphics.move_to(xs[j], ys[j]);
            }} else {{
                mgraphics.line_to(xs[j], ys[j]);
            }}
        }}
        mgraphics.stroke();
    }}
}}

// ── Draggable nodes ──────────────────────────────────────────────────
function draw_nodes() {{
    var i, x, y, r, clr;

    for (i = 0; i < num_bands; i++) {{
        if (!bands[i].enabled) continue;
        x = freq_to_x(bands[i].freq);
        y = gain_to_y(bands[i].gain);

        clr = BAND_COLORS[i % BAND_COLORS.length];
        r = (i === selected_band) ? NODE_RADIUS_SEL : NODE_RADIUS;

        // outer glow for selected / hovered
        if (i === selected_band || i === hover_band) {{
            mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.18);
            mgraphics.arc(x, y, r + 6, 0, Math.PI * 2);
            mgraphics.fill();
        }}

        // filled circle
        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.9);
        mgraphics.arc(x, y, r, 0, Math.PI * 2);
        mgraphics.fill();

        // bright outline
        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 1.0);
        mgraphics.set_line_width(1.5);
        mgraphics.arc(x, y, r, 0, Math.PI * 2);
        mgraphics.stroke();

        // center dot
        mgraphics.set_source_rgba(1, 1, 1, 0.7);
        mgraphics.arc(x, y, 2, 0, Math.PI * 2);
        mgraphics.fill();

        // band number label
        mgraphics.set_source_rgba(1, 1, 1, 0.85);
        mgraphics.select_font_face("Ableton Sans Medium");
        mgraphics.set_font_size(9);
        mgraphics.move_to(x + r + 4, y - r - 2);
        mgraphics.show_text("" + (i + 1));
    }}
}}

// ── Tooltip on hover ────────────────────────────────────────────────
function draw_tooltip() {{
    var target = hover_band >= 0 ? hover_band : (dragging ? selected_band : -1);
    if (target < 0 || target >= num_bands) return;
    if (!bands[target].enabled) return;

    var b = bands[target];
    var nx = freq_to_x(b.freq);
    var ny = gain_to_y(b.gain);

    // Format values
    var freq_str;
    if (b.freq >= 10000) {{
        freq_str = (b.freq / 1000).toFixed(1) + "k";
    }} else if (b.freq >= 1000) {{
        freq_str = (b.freq / 1000).toFixed(2) + "k";
    }} else {{
        freq_str = Math.round(b.freq) + " Hz";
    }}
    var gain_str = (b.gain >= 0 ? "+" : "") + b.gain.toFixed(1) + " dB";
    var q_str = "Q " + b.q.toFixed(2);
    var type_str = TYPE_NAMES[b.type] || "Peak";

    // Tooltip position (offset to avoid cursor)
    var tx = nx + 16;
    var ty = ny - 32;
    var tw = 82;
    var th = 40;

    // Keep tooltip within plot area
    if (tx + tw > plot_right()) tx = nx - tw - 16;
    if (ty < plot_top()) ty = ny + 8;
    if (ty + th > plot_bottom()) ty = plot_bottom() - th;

    // Background pill
    mgraphics.set_source_rgba(0.12, 0.12, 0.14, 0.92);
    mgraphics.rectangle_rounded(tx, ty, tw, th, 3, 3);
    mgraphics.fill();

    // Border
    var clr = BAND_COLORS[target % BAND_COLORS.length];
    mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.4);
    mgraphics.set_line_width(1);
    mgraphics.rectangle_rounded(tx + 0.5, ty + 0.5, tw - 1, th - 1, 3, 3);
    mgraphics.stroke();

    // Text
    mgraphics.set_source_rgba(0.92, 0.92, 0.94, 1.0);
    mgraphics.select_font_face("Ableton Sans Medium");
    mgraphics.set_font_size(9);
    mgraphics.move_to(tx + 5, ty + 13);
    mgraphics.show_text(freq_str + "  " + gain_str);
    mgraphics.set_source_rgba(0.65, 0.65, 0.68, 1.0);
    mgraphics.move_to(tx + 5, ty + 26);
    mgraphics.show_text(q_str + "  " + type_str);
}}

// ── Hit-testing ──────────────────────────────────────────────────────
function hit_test(mx, my) {{
    var i, x, y, dx, dy, dist;
    var best = -1;
    var best_dist = HIT_RADIUS + 1;

    for (i = 0; i < num_bands; i++) {{
        if (!bands[i].enabled) continue;
        x = freq_to_x(bands[i].freq);
        y = gain_to_y(bands[i].gain);
        dx = mx - x;
        dy = my - y;
        dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < best_dist) {{
            best_dist = dist;
            best = i;
        }}
    }}
    return best;
}}

// ── Message handlers (inlet 0) ───────────────────────────────────────
function set_band(idx, freq, gain, q, type, enabled) {{
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].freq    = freq;
    bands[idx].gain    = gain;
    bands[idx].q       = q;
    bands[idx].type    = Math.floor(type);
    bands[idx].enabled = enabled ? 1 : 0;
    mgraphics.redraw();
}}

function set_num_bands(n) {{
    n = Math.floor(n);
    if (n < 0) n = 0;
    if (n > MAX_BANDS) n = MAX_BANDS;
    num_bands = n;
    if (selected_band >= num_bands) selected_band = -1;
    mgraphics.redraw();
}}

function set_selected(idx) {{
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) {{
        selected_band = -1;
    }} else {{
        selected_band = idx;
    }}
    mgraphics.redraw();
}}

// Ignore stray floats/ints on inlet 0
function msg_float(v) {{}}
function msg_int(v) {{}}

// ── Mouse interaction ────────────────────────────────────────────────
function onclick(x, y, but, cmd, shift, caps, opt, ctrl) {{
    var hit = hit_test(x, y);
    if (hit >= 0) {{
        selected_band = hit;
        dragging = 1;
        drag_start_freq = bands[hit].freq;
        drag_start_gain = bands[hit].gain;
        outlet(0, "selected_band", hit);
    }} else {{
        selected_band = -1;
        dragging = 0;
    }}
    mgraphics.redraw();
}}

function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {{
    // but === 0 means mouse was released
    if (but === 0) {{
        dragging = 0;
        mgraphics.redraw();
        return;
    }}
    if (!dragging || selected_band < 0 || selected_band >= num_bands) return;

    var new_freq = x_to_freq(x);
    var new_gain = y_to_gain(y);

    // Cmd/Ctrl: lock gain (horizontal-only frequency drag)
    if (cmd) {{
        new_gain = drag_start_gain;
    }}

    // Shift: fine-tune mode (reduce sensitivity)
    if (shift) {{
        var cur_freq = bands[selected_band].freq;
        var cur_gain = bands[selected_band].gain;
        new_freq = cur_freq + (new_freq - cur_freq) * 0.15;
        new_gain = cur_gain + (new_gain - cur_gain) * 0.15;
    }}

    // Round gain to 0.1 dB
    new_gain = Math.round(new_gain * 10) / 10;
    // Round freq
    if (new_freq < 100) {{
        new_freq = Math.round(new_freq);
    }} else if (new_freq < 1000) {{
        new_freq = Math.round(new_freq);
    }} else {{
        new_freq = Math.round(new_freq / 10) * 10;
    }}

    // Clamp
    if (new_freq < MIN_FREQ) new_freq = MIN_FREQ;
    if (new_freq > MAX_FREQ) new_freq = MAX_FREQ;
    if (new_gain < MIN_GAIN) new_gain = MIN_GAIN;
    if (new_gain > MAX_GAIN) new_gain = MAX_GAIN;

    bands[selected_band].freq = new_freq;
    bands[selected_band].gain = new_gain;

    outlet(1, "band_freq", selected_band, new_freq);
    outlet(2, "band_gain", selected_band, new_gain);
    mgraphics.redraw();
}}

function onidle(x, y, but, cmd, shift, caps, opt, ctrl) {{
    var prev = hover_band;
    hover_band = hit_test(x, y);
    if (hover_band !== prev) {{
        mgraphics.redraw();
    }}
}}

function onidleout(x, y, but, cmd, shift, caps, opt, ctrl) {{
    if (hover_band >= 0) {{
        hover_band = -1;
        mgraphics.redraw();
    }}
}}

function onwheel(x, y, scrollx, scrolly, cmd, shift, caps, opt, ctrl) {{
    // Mouse wheel adjusts Q of hovered or selected band
    var target = hover_band >= 0 ? hover_band : selected_band;
    if (target < 0 || target >= num_bands) return;
    if (!bands[target].enabled) return;

    var q = bands[target].q;

    // Scale Q logarithmically
    var factor = shift ? 0.02 : 0.08;
    q = q * (1.0 + scrolly * factor);

    // Clamp
    if (q < MIN_Q) q = MIN_Q;
    if (q > MAX_Q) q = MAX_Q;

    // Round to 2 decimal places
    q = Math.round(q * 100) / 100;

    bands[target].q = q;
    outlet(3, "band_q", target, q);
    mgraphics.redraw();
}}
"""
