"""Parametric EQ curve display with draggable nodes for jsui.

Generates JavaScript (ES5) for Max's jsui object, drawing a Pro-Q/EQ Eight
style multi-band EQ with draggable nodes and composite response rendering.

Communication uses 3 inlets and 4 outlets.

Inlet 0 messages:
    set_band band_idx freq gain q type enabled
    set_num_bands N
    set_selected band_idx

Inlet 1:
    sample-rate float (typically from dspstate~ outlet 1)

Inlet 2:
    analyzer magnitude list in dB (typically -72..0 dB, log-spaced bins)

Outlet 0:
    selected_band band_idx
    add_band band_idx freq gain q type enabled
    delete_band band_idx
Outlet 1: band_freq band_idx freq
Outlet 2: band_gain band_idx gain
Outlet 3: band_q band_idx q

Mouse interaction:
    Click node: select band
    Drag node: adjust frequency and gain for bell/shelf filters
    Drag cut/notch/BP nodes: frequency horizontal, Q vertical
    Mouse wheel on node: adjust Q
    Shift + drag / wheel: fine tune
    Cmd/Ctrl + drag: lock the secondary parameter
    Click empty graph: add first disabled band at cursor
    Opt/Alt + click node: disable that band
"""

from string import Template

EQ_CURVE_INLETS = 3
EQ_CURVE_OUTLETS = 4


def eq_curve_js(
    *,
    bg_color="0.07, 0.07, 0.08, 1.0",
    composite_color="0.85, 0.88, 0.92, 1.0",
    fill_color="0.45, 0.75, 0.65, 0.12",
    analyzer_fill_color="0.24, 0.78, 0.92, 0.12",
    analyzer_line_color="0.32, 0.84, 0.96, 0.48",
    analyzer_peak_color="0.92, 0.96, 1.0, 0.9",
    grid_color="0.2, 0.2, 0.22, 0.5",
    text_color="0.5, 0.5, 0.52, 1.0",
    zero_line_color="0.3, 0.3, 0.32, 0.8",
):
    """Return JavaScript source for an interactive parametric EQ display."""
    return _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        composite_color=composite_color,
        fill_color=fill_color,
        analyzer_fill_color=analyzer_fill_color,
        analyzer_line_color=analyzer_line_color,
        analyzer_peak_color=analyzer_peak_color,
        grid_color=grid_color,
        text_color=text_color,
        zero_line_color=zero_line_color,
    )


_JS_TEMPLATE = Template("""\
// Parametric EQ Curve Display - generated by m4l-builder
// ES5 compatible, no let/const/arrow/template literals

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 3;
outlets = 4;

// ── Configurable colors ──────────────────────────────────────────────
var BG_COLOR       = [$bg_color];
var COMPOSITE_CLR  = [$composite_color];
var FILL_CLR       = [$fill_color];
var ANALYZER_FILL_CLR = [$analyzer_fill_color];
var ANALYZER_LINE_CLR = [$analyzer_line_color];
var ANALYZER_PEAK_CLR = [$analyzer_peak_color];
var GRID_CLR       = [$grid_color];
var TEXT_CLR       = [$text_color];
var ZERO_LINE_CLR  = [$zero_line_color];

var BAND_COLORS = [
    [0.92, 0.36, 0.34, 1.0],
    [0.94, 0.62, 0.24, 1.0],
    [0.88, 0.84, 0.28, 1.0],
    [0.36, 0.80, 0.46, 1.0],
    [0.32, 0.76, 0.86, 1.0],
    [0.38, 0.56, 0.92, 1.0],
    [0.66, 0.46, 0.88, 1.0],
    [0.90, 0.42, 0.66, 1.0]
];

// ── Filter types ─────────────────────────────────────────────────────
var TYPE_PEAK     = 0;
var TYPE_LOSHELF  = 1;
var TYPE_HISHELF  = 2;
var TYPE_LOWPASS  = 3;
var TYPE_HIGHPASS = 4;
var TYPE_NOTCH    = 5;
var TYPE_BANDPASS = 6;
var TYPE_ALLPASS  = 7;

var TYPE_NAMES = ["Peak", "LShelf", "HShelf", "LP", "HP", "Notch", "BP", "AllPass"];

// ── Constants ────────────────────────────────────────────────────────
var MIN_FREQ      = 20;
var MAX_FREQ      = 20000;
var MIN_GAIN      = -30;
var MAX_GAIN      = 30;
var DISPLAY_FLOOR = -30;
var display_range = 12.0;
var MIN_Q         = 0.1;
var MAX_Q         = 30.0;
var NUM_POINTS    = 768;
var NODE_RADIUS     = 10;
var NODE_RADIUS_SEL = 14;
var HIT_RADIUS      = 22;
var MAX_BANDS       = 8;
var DEFAULT_SR      = 48000.0;
var ANALYZER_MIN_DB = -72.0;
var ANALYZER_MAX_DB = 0.0;
var LOG_MIN         = Math.log(MIN_FREQ);
var LOG_MAX         = Math.log(MAX_FREQ);
var LOG_RANGE       = LOG_MAX - LOG_MIN;

// ── Margin / padding for axis labels ─────────────────────────────────
var MARGIN_LEFT   = 30;
var MARGIN_RIGHT  = 8;
var MARGIN_TOP    = 6;
var MARGIN_BOTTOM = 16;

// ── State ────────────────────────────────────────────────────────────
var sample_rate = DEFAULT_SR;
var analyzer_enabled = 1;
var num_bands = 0;
var selected_band = -1;
var hover_band = -1;
var dragging = 0;
var drag_start_freq = 0;
var drag_start_gain = 0;
var drag_start_q = 1.0;

var bands = [];
var band_cache = [];
var analyzer_display = [];
var analyzer_peaks = [];
var i;
for (i = 0; i < MAX_BANDS; i++) {
    bands[i] = {
        freq: 1000,
        gain: 0,
        q: 1.0,
        type: TYPE_PEAK,
        enabled: 1
    };
    band_cache[i] = {
        enabled: 1,
        freq: 1000,
        gain: 0,
        q: 1.0,
        type: TYPE_PEAK,
        node_gain: 0,
        uses_gain: 1,
        coeffs: [1, 0, 0, 1, 0, 0]
    };
}

// ── Coordinate helpers ───────────────────────────────────────────────
function plot_left()   { return MARGIN_LEFT; }
function plot_right()  { return mgraphics.size[0] - MARGIN_RIGHT; }
function plot_top()    { return MARGIN_TOP; }
function plot_bottom() { return mgraphics.size[1] - MARGIN_BOTTOM; }
function plot_w()      { return plot_right() - plot_left(); }
function plot_h()      { return plot_bottom() - plot_top(); }

function clamp(v, lo, hi) {
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

function safe_log10(v) {
    if (v <= 1.0e-20) v = 1.0e-20;
    return Math.log(v) / Math.log(10);
}

function freq_to_x(f) {
    var norm = (Math.log(clamp(f, MIN_FREQ, MAX_FREQ)) - LOG_MIN) / LOG_RANGE;
    return plot_left() + norm * plot_w();
}

function x_to_freq(x) {
    var norm = (x - plot_left()) / plot_w();
    norm = clamp(norm, 0, 1);
    return Math.exp(LOG_MIN + norm * LOG_RANGE);
}

function gain_to_y(g) {
    var hi = display_range;
    var lo = -display_range;
    var norm = (clamp(g, lo, hi) - hi) / (lo - hi);
    return plot_top() + norm * plot_h();
}

function y_to_gain(y) {
    var norm = (y - plot_top()) / plot_h();
    norm = clamp(norm, 0, 1);
    var hi = display_range;
    var lo = -display_range;
    return hi + norm * (lo - hi);
}

function q_to_y(q) {
    var norm = (Math.log(clamp(q, MIN_Q, MAX_Q)) - Math.log(MIN_Q))
        / (Math.log(MAX_Q) - Math.log(MIN_Q));
    return plot_bottom() - norm * plot_h();
}

function y_to_q(y) {
    var norm = (plot_bottom() - y) / plot_h();
    norm = clamp(norm, 0, 1);
    return Math.exp(Math.log(MIN_Q) + norm * (Math.log(MAX_Q) - Math.log(MIN_Q)));
}

function analyzer_db_to_y(db) {
    var clamped = clamp(db, ANALYZER_MIN_DB, ANALYZER_MAX_DB);
    var norm = (clamped - ANALYZER_MIN_DB) / (ANALYZER_MAX_DB - ANALYZER_MIN_DB);
    return plot_bottom() - norm * plot_h();
}

function analyzer_bin_freq(idx, count) {
    var norm = idx / Math.max(count - 1, 1);
    return Math.exp(LOG_MIN + norm * LOG_RANGE);
}

function update_analyzer_data(values) {
    var i, n, incoming;
    n = values.length;
    if (n < 2) {
        analyzer_display = [];
        analyzer_peaks = [];
        mgraphics.redraw();
        return;
    }

    if (analyzer_display.length !== n) {
        analyzer_display = [];
        analyzer_peaks = [];
        for (i = 0; i < n; i++) {
            analyzer_display[i] = ANALYZER_MIN_DB;
            analyzer_peaks[i] = ANALYZER_MIN_DB;
        }
    }

    for (i = 0; i < n; i++) {
        incoming = values[i];
        if (incoming !== incoming || incoming === undefined) incoming = ANALYZER_MIN_DB;
        incoming = clamp(incoming, ANALYZER_MIN_DB, ANALYZER_MAX_DB);
        analyzer_display[i] = analyzer_display[i] * 0.74 + incoming * 0.26;
        if (analyzer_display[i] > analyzer_peaks[i]) {
            analyzer_peaks[i] = analyzer_display[i];
        } else {
            analyzer_peaks[i] = Math.max(ANALYZER_MIN_DB, analyzer_peaks[i] - 0.38);
        }
    }
    mgraphics.redraw();
}

function band_uses_gain(type) {
    return type === TYPE_PEAK || type === TYPE_LOSHELF || type === TYPE_HISHELF;
}

function band_node_gain(b) {
    if (band_uses_gain(b.type)) return clamp(b.gain, MIN_GAIN, MAX_GAIN);
    return 0.0;
}

function find_free_band() {
    var i;
    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].enabled) return i;
    }
    return -1;
}

function next_enabled_band(preferred_idx) {
    var i;
    if (preferred_idx >= 0 && preferred_idx < num_bands && band_cache[preferred_idx].enabled) {
        return preferred_idx;
    }
    for (i = 0; i < num_bands; i++) {
        if (band_cache[i].enabled) return i;
    }
    return -1;
}

// ── Filter coefficients / response ───────────────────────────────────
function biquad_coeffs(type, freq, gain, q) {
    var sr = clamp(sample_rate, 22050.0, 384000.0);
    var fc = clamp(freq, MIN_FREQ, Math.min(MAX_FREQ, sr * 0.49));
    var Q = clamp(q, MIN_Q, MAX_Q);
    var w0 = 2.0 * Math.PI * fc / sr;
    var cosw0 = Math.cos(w0);
    var sinw0 = Math.sin(w0);
    var alpha = sinw0 / (2.0 * Q);
    var A = Math.pow(10.0, gain / 40.0);
    var shelf_s = clamp(Q, 0.1, 4.0);
    var shelf_alpha = sinw0 * 0.5 * Math.sqrt((A + 1.0 / A) * (1.0 / shelf_s - 1.0) + 2.0);
    var two_sqrt_A_alpha = 2.0 * Math.sqrt(A) * shelf_alpha;
    var b0, b1, b2, a0, a1, a2;

    switch (type) {
        case TYPE_PEAK:
            b0 = 1.0 + alpha * A;
            b1 = -2.0 * cosw0;
            b2 = 1.0 - alpha * A;
            a0 = 1.0 + alpha / A;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha / A;
            break;

        case TYPE_LOSHELF:
            b0 = A * ((A + 1.0) - (A - 1.0) * cosw0 + two_sqrt_A_alpha);
            b1 = 2.0 * A * ((A - 1.0) - (A + 1.0) * cosw0);
            b2 = A * ((A + 1.0) - (A - 1.0) * cosw0 - two_sqrt_A_alpha);
            a0 = (A + 1.0) + (A - 1.0) * cosw0 + two_sqrt_A_alpha;
            a1 = -2.0 * ((A - 1.0) + (A + 1.0) * cosw0);
            a2 = (A + 1.0) + (A - 1.0) * cosw0 - two_sqrt_A_alpha;
            break;

        case TYPE_HISHELF:
            b0 = A * ((A + 1.0) + (A - 1.0) * cosw0 + two_sqrt_A_alpha);
            b1 = -2.0 * A * ((A - 1.0) + (A + 1.0) * cosw0);
            b2 = A * ((A + 1.0) + (A - 1.0) * cosw0 - two_sqrt_A_alpha);
            a0 = (A + 1.0) - (A - 1.0) * cosw0 + two_sqrt_A_alpha;
            a1 = 2.0 * ((A - 1.0) - (A + 1.0) * cosw0);
            a2 = (A + 1.0) - (A - 1.0) * cosw0 - two_sqrt_A_alpha;
            break;

        case TYPE_LOWPASS:
            b0 = (1.0 - cosw0) * 0.5;
            b1 = 1.0 - cosw0;
            b2 = (1.0 - cosw0) * 0.5;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_HIGHPASS:
            b0 = (1.0 + cosw0) * 0.5;
            b1 = -(1.0 + cosw0);
            b2 = (1.0 + cosw0) * 0.5;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_NOTCH:
            b0 = 1.0;
            b1 = -2.0 * cosw0;
            b2 = 1.0;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_BANDPASS:
            b0 = alpha;
            b1 = 0.0;
            b2 = -alpha;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_ALLPASS:
            b0 = 1.0 - alpha;
            b1 = -2.0 * cosw0;
            b2 = 1.0 + alpha;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        default:
            return [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
    }

    if (Math.abs(a0) < 1.0e-12) return [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
    return [b0 / a0, b1 / a0, b2 / a0, 1.0, a1 / a0, a2 / a0];
}

function response_db(coeffs, freq) {
    var sr = clamp(sample_rate, 22050.0, 384000.0);
    var fc = clamp(freq, MIN_FREQ, Math.min(MAX_FREQ, sr * 0.49));
    var w = 2.0 * Math.PI * fc / sr;
    var c1 = Math.cos(w);
    var s1 = Math.sin(w);
    var c2 = Math.cos(2.0 * w);
    var s2 = Math.sin(2.0 * w);

    var b0 = coeffs[0];
    var b1 = coeffs[1];
    var b2 = coeffs[2];
    var a0 = coeffs[3];
    var a1 = coeffs[4];
    var a2 = coeffs[5];

    var nr = b0 + b1 * c1 + b2 * c2;
    var ni = -b1 * s1 - b2 * s2;
    var dr = a0 + a1 * c1 + a2 * c2;
    var di = -a1 * s1 - a2 * s2;

    var num = nr * nr + ni * ni;
    var den = dr * dr + di * di;
    var mag = num / Math.max(den, 1.0e-20);
    var db = 10.0 * safe_log10(mag);
    if (db < DISPLAY_FLOOR) db = DISPLAY_FLOOR;
    if (db > MAX_GAIN) db = MAX_GAIN;
    return db;
}

function rebuild_band_cache() {
    var i;
    for (i = 0; i < MAX_BANDS; i++) {
        band_cache[i].enabled = bands[i].enabled ? 1 : 0;
        band_cache[i].freq = clamp(bands[i].freq, MIN_FREQ, MAX_FREQ);
        band_cache[i].gain = clamp(bands[i].gain, MIN_GAIN, MAX_GAIN);
        band_cache[i].q = clamp(bands[i].q, MIN_Q, MAX_Q);
        band_cache[i].type = Math.floor(bands[i].type);
        band_cache[i].uses_gain = band_uses_gain(band_cache[i].type) ? 1 : 0;
        band_cache[i].node_gain = band_node_gain(band_cache[i]);

        if (!band_cache[i].enabled) {
            band_cache[i].coeffs = [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
        } else if (!band_cache[i].uses_gain && band_cache[i].type === TYPE_BANDPASS) {
            band_cache[i].coeffs = biquad_coeffs(
                band_cache[i].type, band_cache[i].freq, 0.0, band_cache[i].q
            );
        } else {
            band_cache[i].coeffs = biquad_coeffs(
                band_cache[i].type, band_cache[i].freq, band_cache[i].gain, band_cache[i].q
            );
        }
    }
}

// ── Build frequency table (logarithmic spacing) ─────────────────────
var freq_table = [];
(function() {
    var i;
    for (i = 0; i < NUM_POINTS; i++) {
        var norm = i / (NUM_POINTS - 1);
        freq_table[i] = Math.exp(LOG_MIN + norm * LOG_RANGE);
    }
    rebuild_band_cache();
})();

// ── Drawing ──────────────────────────────────────────────────────────
function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];

    mgraphics.set_source_rgba(BG_COLOR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();

    draw_grid();
    draw_analyzer();
    draw_band_curves();
    draw_composite_curve();
    draw_nodes();
    draw_hud();
    draw_tooltip();
}

// ── Grid ─────────────────────────────────────────────────────────────
var FREQ_LINES  = [20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000];
var FREQ_LABELS = ["20", "50", "100", "200", "500", "1k", "2k", "5k", "10k", "20k"];
function gain_grid_step() {
    if (display_range <= 3.0) return 1.0;
    if (display_range <= 6.0) return 1.5;
    if (display_range <= 12.0) return 3.0;
    return 6.0;
}

function gain_grid_values() {
    var vals = [];
    var step = gain_grid_step();
    var g = -display_range;
    while (g <= display_range + 0.0001) {
        vals.push(Math.round(g * 100.0) / 100.0);
        g += step;
    }
    return vals;
}

function draw_grid() {
    var i, x, y, label;
    var gain_lines = gain_grid_values();

    mgraphics.set_line_width(0.5);
    for (i = 0; i < FREQ_LINES.length; i++) {
        x = freq_to_x(FREQ_LINES[i]);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(x, plot_top());
        mgraphics.line_to(x, plot_bottom());
        mgraphics.stroke();

        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.select_font_face("Ableton Sans Medium");
        mgraphics.set_font_size(8);
        mgraphics.move_to(x - 6, plot_bottom() + 12);
        mgraphics.show_text(FREQ_LABELS[i]);
    }

    for (i = 0; i < gain_lines.length; i++) {
        y = gain_to_y(gain_lines[i]);
        if (Math.abs(gain_lines[i]) < 0.0001) {
            mgraphics.set_source_rgba(ZERO_LINE_CLR);
            mgraphics.set_line_width(1.0);
        } else {
            mgraphics.set_source_rgba(GRID_CLR);
            mgraphics.set_line_width(0.5);
        }
        mgraphics.move_to(plot_left(), y);
        mgraphics.line_to(plot_right(), y);
        mgraphics.stroke();

        if (Math.abs(gain_lines[i] % gain_grid_step()) < 0.0001 || Math.abs(gain_lines[i]) < 0.0001) {
            mgraphics.set_source_rgba(TEXT_CLR);
            mgraphics.select_font_face("Ableton Sans Medium");
            mgraphics.set_font_size(8);
            label = gain_lines[i] > 0 ? "+" + gain_lines[i] : "" + gain_lines[i];
            if (Math.abs(gain_lines[i]) < 0.0001) label = " 0";
            mgraphics.move_to(2, y + 3);
            mgraphics.show_text(label);
        }
    }
}

function draw_analyzer() {
    var i, n, freq, x0, x1, bw, bx;
    var xs = [];
    var ys = [];
    if (!analyzer_enabled) return;
    n = analyzer_display.length;
    if (n < 2) return;

    for (i = 0; i < n; i++) {
        freq = analyzer_bin_freq(i, n);
        xs[i] = freq_to_x(freq);
        ys[i] = analyzer_db_to_y(analyzer_display[i]);
    }

    for (i = 0; i < n; i++) {
        if (i === 0) {
            x0 = plot_left();
        } else {
            x0 = (xs[i - 1] + xs[i]) * 0.5;
        }
        if (i === n - 1) {
            x1 = plot_right();
        } else {
            x1 = (xs[i] + xs[i + 1]) * 0.5;
        }
        bw = Math.max(1.0, x1 - x0 - (x1 - x0 > 8.0 ? 2.2 : 1.2));
        bx = x0 + ((x1 - x0) - bw) * 0.5;
        mgraphics.set_source_rgba(ANALYZER_FILL_CLR);
        mgraphics.rectangle(bx, ys[i], bw, plot_bottom() - ys[i]);
        mgraphics.fill();
    }

    mgraphics.set_source_rgba(ANALYZER_LINE_CLR);
    mgraphics.set_line_width(1.2);
    for (i = 0; i < n; i++) {
        if (i === 0) {
            mgraphics.move_to(xs[i], ys[i]);
        } else {
            mgraphics.line_to(xs[i], ys[i]);
        }
    }
    mgraphics.stroke();

    mgraphics.set_source_rgba(ANALYZER_PEAK_CLR);
    mgraphics.set_line_width(1.0);
    for (i = 0; i < n; i += 2) {
        x = xs[i];
        y = analyzer_db_to_y(analyzer_peaks[i]);
        mgraphics.move_to(x - 1.5, y);
        mgraphics.line_to(x + 1.5, y);
    }
    mgraphics.stroke();
}

function format_freq_text(freq) {
    if (freq >= 10000) return (freq / 1000.0).toFixed(1) + "k";
    if (freq >= 1000) return (freq / 1000.0).toFixed(2) + "k";
    return Math.round(freq) + " Hz";
}

function band_response_db(idx, freq) {
    if (!band_cache[idx].enabled) return 0.0;
    return response_db(band_cache[idx].coeffs, freq);
}

function curve_db_is_visible(db) {
    return db > DISPLAY_FLOOR + 0.05;
}

// ── Individual band curves ───────────────────────────────────────────
function draw_band_curves() {
    var i, j, f, x, y, db, clr, zero_y, started;

    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].enabled) continue;
        if (band_cache[i].uses_gain && Math.abs(band_cache[i].gain) < 0.01) continue;

        clr = BAND_COLORS[i % BAND_COLORS.length];
        zero_y = gain_to_y(0);

        if ((i === selected_band || i === hover_band) && band_cache[i].uses_gain) {
            mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.08);
            mgraphics.move_to(freq_to_x(freq_table[0]), zero_y);
            for (j = 0; j < NUM_POINTS; j++) {
                f = freq_table[j];
                db = band_response_db(i, f);
                x = freq_to_x(f);
                y = gain_to_y(db);
                if (j === 0) {
                    mgraphics.line_to(x, y);
                } else {
                    mgraphics.line_to(x, y);
                }
            }
            mgraphics.line_to(freq_to_x(freq_table[NUM_POINTS - 1]), zero_y);
            mgraphics.close_path();
            mgraphics.fill();
        }

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.45);
        mgraphics.set_line_width(1.0);
        started = 0;
        for (j = 0; j < NUM_POINTS; j++) {
            f = freq_table[j];
            db = band_response_db(i, f);
            if (!curve_db_is_visible(db)) {
                started = 0;
                continue;
            }
            x = freq_to_x(f);
            y = gain_to_y(db);
            if (!started) {
                mgraphics.move_to(x, y);
                started = 1;
            } else {
                mgraphics.line_to(x, y);
            }
        }
        if (started) mgraphics.stroke();
    }
}

// ── Composite curve + fill ───────────────────────────────────────────
function draw_composite_curve() {
    var j, f, x, y, total_db, started;
    var zero_y = gain_to_y(0);
    var xs = [];
    var ys = [];
    var i;

    for (j = 0; j < NUM_POINTS; j++) {
        f = freq_table[j];
        total_db = 0.0;
        for (i = 0; i < num_bands; i++) {
            if (band_cache[i].enabled) {
                total_db += band_response_db(i, f);
            }
        }
        x = freq_to_x(f);
        if (curve_db_is_visible(total_db)) {
            y = gain_to_y(total_db);
            xs[j] = x;
            ys[j] = y;
        } else {
            xs[j] = x;
            ys[j] = null;
        }
    }

    if (num_bands > 0) {
        mgraphics.set_source_rgba(FILL_CLR);
        mgraphics.move_to(xs[0], zero_y);
        for (j = 0; j < NUM_POINTS; j++) {
            if (ys[j] !== null) mgraphics.line_to(xs[j], ys[j]);
        }
        mgraphics.line_to(xs[NUM_POINTS - 1], zero_y);
        mgraphics.close_path();
        mgraphics.fill();
    }

    if (num_bands > 0) {
        mgraphics.set_source_rgba(COMPOSITE_CLR);
        mgraphics.set_line_width(2.0);
        started = 0;
        for (j = 0; j < NUM_POINTS; j++) {
            if (ys[j] === null) {
                started = 0;
                continue;
            }
            if (!started) {
                mgraphics.move_to(xs[j], ys[j]);
                started = 1;
            } else {
                mgraphics.line_to(xs[j], ys[j]);
            }
        }
        if (started) mgraphics.stroke();
    }
}

function node_y_for_band(idx) {
    if (band_cache[idx].uses_gain) return gain_to_y(band_cache[idx].node_gain);
    return gain_to_y(0.0);
}

// ── Draggable nodes ──────────────────────────────────────────────────
function draw_nodes() {
    var i, x, y, r, clr;

    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].enabled) continue;
        x = freq_to_x(band_cache[i].freq);
        y = node_y_for_band(i);

        clr = BAND_COLORS[i % BAND_COLORS.length];
        r = (i === selected_band) ? NODE_RADIUS_SEL : NODE_RADIUS;

        if (i === selected_band || i === hover_band) {
            mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.18);
            mgraphics.arc(x, y, r + 10, 0, Math.PI * 2);
            mgraphics.fill();
        }

        mgraphics.set_source_rgba(0.02, 0.02, 0.03, i === selected_band ? 0.78 : 0.58);
        mgraphics.arc(x, y, r + 2.4, 0, Math.PI * 2);
        mgraphics.fill();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.92);
        mgraphics.arc(x, y, r, 0, Math.PI * 2);
        mgraphics.fill();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 1.0);
        mgraphics.set_line_width(i === selected_band ? 2.4 : 1.9);
        mgraphics.arc(x, y, r, 0, Math.PI * 2);
        mgraphics.stroke();

        mgraphics.set_source_rgba(1.0, 1.0, 1.0, 0.75);
        mgraphics.arc(x, y, 3.0, 0, Math.PI * 2);
        mgraphics.fill();

        mgraphics.set_source_rgba(1.0, 1.0, 1.0, 0.88);
        mgraphics.select_font_face("Ableton Sans Medium");
        mgraphics.set_font_size(i === selected_band ? 10.5 : 9.4);
        mgraphics.move_to(x + r + 4, y - r - 2);
        mgraphics.show_text("" + (i + 1));
    }
}

function draw_hud() {
    var target = hover_band >= 0 ? hover_band : selected_band;
    var pill_x = plot_left() + 8;
    var pill_y = plot_top() + 8;
    var pill_w = 228;
    var pill_h = 24;
    var label;
    var detail;
    var b;
    var clr;
    var range_text = "+/- " + Math.round(display_range) + " dB";
    var info_x = plot_right() - 120;

    if (target >= 0 && target < num_bands && band_cache[target].enabled) {
        b = band_cache[target];
        clr = BAND_COLORS[target % BAND_COLORS.length];
        label = "B" + (target + 1) + "  " + (TYPE_NAMES[b.type] || "Peak");
        detail = format_freq_text(b.freq);
        if (b.uses_gain) {
            detail += "  " + (b.gain >= 0 ? "+" : "") + b.gain.toFixed(1) + " dB";
        }
        detail += "  Q " + b.q.toFixed(2);

        mgraphics.set_source_rgba(0.11, 0.12, 0.14, 0.92);
        mgraphics.rectangle_rounded(pill_x, pill_y, pill_w, pill_h, 4, 4);
        mgraphics.fill();

        mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.95);
        mgraphics.rectangle_rounded(pill_x, pill_y, 56, pill_h, 4, 4);
        mgraphics.fill();

        mgraphics.set_source_rgba(0.04, 0.04, 0.05, 1.0);
        mgraphics.select_font_face("Ableton Sans Bold");
        mgraphics.set_font_size(9);
        mgraphics.move_to(pill_x + 10, pill_y + 15);
        mgraphics.show_text("B" + (target + 1));

        mgraphics.set_source_rgba(0.92, 0.92, 0.94, 1.0);
        mgraphics.select_font_face("Ableton Sans Medium");
        mgraphics.set_font_size(9);
        mgraphics.move_to(pill_x + 64, pill_y + 10);
        mgraphics.show_text(label);
        mgraphics.set_source_rgba(0.68, 0.70, 0.74, 1.0);
        mgraphics.set_font_size(8);
        mgraphics.move_to(pill_x + 64, pill_y + 19);
        mgraphics.show_text(detail);
    }

    mgraphics.set_source_rgba(0.11, 0.12, 0.14, 0.86);
    mgraphics.rectangle_rounded(info_x, pill_y, 112, pill_h, 4, 4);
    mgraphics.fill();

    mgraphics.set_source_rgba(0.70, 0.73, 0.78, 1.0);
    mgraphics.select_font_face("Ableton Sans Medium");
    mgraphics.set_font_size(8);
    mgraphics.move_to(info_x + 8, pill_y + 10);
    mgraphics.show_text(analyzer_enabled ? "POST ANALYZER" : "ANALYZER OFF");

    mgraphics.set_source_rgba(0.92, 0.92, 0.94, 1.0);
    mgraphics.set_font_size(9);
    mgraphics.move_to(info_x + 8, pill_y + 19);
    mgraphics.show_text(range_text);
}

// ── Tooltip on hover ────────────────────────────────────────────────
function draw_tooltip() {
    var target = hover_band >= 0 ? hover_band : (dragging ? selected_band : -1);
    if (target < 0 || target >= num_bands) return;
    if (!band_cache[target].enabled) return;

    var b = band_cache[target];
    var nx = freq_to_x(b.freq);
    var ny = node_y_for_band(target);
    var line1;
    var line2;

    var freq_str = format_freq_text(b.freq);

    if (b.uses_gain) {
        var gain_str = (b.gain >= 0 ? "+" : "") + b.gain.toFixed(1) + " dB";
        line1 = freq_str + "  " + gain_str;
        line2 = "Q " + b.q.toFixed(2) + "  " + (TYPE_NAMES[b.type] || "Peak");
    } else {
        line1 = freq_str + "  " + (TYPE_NAMES[b.type] || "Filter");
        line2 = "Q " + b.q.toFixed(2);
    }

    var tx = nx + 16;
    var ty = ny - 32;
    var tw = 88;
    var th = 40;

    if (tx + tw > plot_right()) tx = nx - tw - 16;
    if (ty < plot_top()) ty = ny + 8;
    if (ty + th > plot_bottom()) ty = plot_bottom() - th;

    mgraphics.set_source_rgba(0.12, 0.12, 0.14, 0.92);
    mgraphics.rectangle_rounded(tx, ty, tw, th, 3, 3);
    mgraphics.fill();

    var clr = BAND_COLORS[target % BAND_COLORS.length];
    mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 0.42);
    mgraphics.set_line_width(1);
    mgraphics.rectangle_rounded(tx + 0.5, ty + 0.5, tw - 1, th - 1, 3, 3);
    mgraphics.stroke();

    mgraphics.set_source_rgba(0.92, 0.92, 0.94, 1.0);
    mgraphics.select_font_face("Ableton Sans Medium");
    mgraphics.set_font_size(9);
    mgraphics.move_to(tx + 5, ty + 13);
    mgraphics.show_text(line1);
    mgraphics.set_source_rgba(0.65, 0.65, 0.68, 1.0);
    mgraphics.move_to(tx + 5, ty + 26);
    mgraphics.show_text(line2);
}

// ── Hit-testing ──────────────────────────────────────────────────────
function hit_test(mx, my) {
    var i, x, y, dx, dy, dist;
    var best = -1;
    var best_dist = HIT_RADIUS + 1;

    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].enabled) continue;
        x = freq_to_x(band_cache[i].freq);
        y = node_y_for_band(i);
        dx = mx - x;
        dy = my - y;
        dist = Math.sqrt(dx * dx + dy * dy);
        if (dist < best_dist) {
            best_dist = dist;
            best = i;
        }
    }
    return best;
}

// ── Message handlers (inlet 0 messages, inlet 1 sample rate) ────────
function set_band(idx, freq, gain, q, type, enabled) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].freq    = freq;
    bands[idx].gain    = gain;
    bands[idx].q       = q;
    bands[idx].type    = Math.floor(type);
    bands[idx].enabled = enabled ? 1 : 0;
    rebuild_band_cache();
    mgraphics.redraw();
}

function set_num_bands(n) {
    n = Math.floor(n);
    if (n < 0) n = 0;
    if (n > MAX_BANDS) n = MAX_BANDS;
    num_bands = n;
    if (selected_band >= num_bands) selected_band = -1;
    rebuild_band_cache();
    mgraphics.redraw();
}

function set_selected(idx) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) {
        selected_band = -1;
    } else {
        selected_band = idx;
    }
    mgraphics.redraw();
}

function set_analyzer_enabled(v) {
    analyzer_enabled = v ? 1 : 0;
    mgraphics.redraw();
}

function set_display_range(v) {
    var next = Math.abs(v);
    if (next <= 4) {
        display_range = 3.0;
    } else if (next <= 9) {
        display_range = 6.0;
    } else if (next <= 21) {
        display_range = 12.0;
    } else {
        display_range = 30.0;
    }
    mgraphics.redraw();
}

function list() {
    if (inlet === 2) {
        update_analyzer_data(arrayfromargs(arguments));
    }
}

function msg_float(v) {
    if (inlet === 1) {
        sample_rate = clamp(v, 22050.0, 384000.0);
        rebuild_band_cache();
        mgraphics.redraw();
    }
}

function msg_int(v) {
    if (inlet === 1) {
        msg_float(v);
    }
}

// ── Mouse interaction ────────────────────────────────────────────────
function onclick(x, y, but, cmd, shift, caps, opt, ctrl) {
    var hit = hit_test(x, y);
    var created_idx;
    var created_freq;
    var created_gain;
    var next_idx;

    if (opt) {
        if (hit >= 0) {
            bands[hit].enabled = 0;
            rebuild_band_cache();
            next_idx = next_enabled_band(hit === selected_band ? hit + 1 : selected_band);
            selected_band = next_idx;
            outlet(0, "delete_band", hit);
            if (next_idx >= 0) {
                outlet(0, "selected_band", next_idx);
            }
            dragging = 0;
            mgraphics.redraw();
            return;
        }
    }

    if (hit < 0) {
        created_idx = find_free_band();
        if (created_idx >= 0) {
            created_freq = x_to_freq(x);
            created_gain = y_to_gain(y);
            created_gain = Math.round(created_gain * 10.0) / 10.0;
            bands[created_idx].freq = clamp(created_freq, MIN_FREQ, MAX_FREQ);
            bands[created_idx].gain = clamp(created_gain, MIN_GAIN, MAX_GAIN);
            bands[created_idx].q = 1.0;
            bands[created_idx].type = TYPE_PEAK;
            bands[created_idx].enabled = 1;
            selected_band = created_idx;
            dragging = 0;
            rebuild_band_cache();
            outlet(
                0,
                "add_band",
                created_idx,
                bands[created_idx].freq,
                bands[created_idx].gain,
                bands[created_idx].q,
                bands[created_idx].type,
                1
            );
            outlet(0, "selected_band", created_idx);
            mgraphics.redraw();
            return;
        }
    }

    if (hit >= 0) {
        selected_band = hit;
        dragging = 1;
        drag_start_freq = bands[hit].freq;
        drag_start_gain = bands[hit].gain;
        drag_start_q = bands[hit].q;
        outlet(0, "selected_band", hit);
    } else {
        selected_band = -1;
        dragging = 0;
    }
    mgraphics.redraw();
}

function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but === 0) {
        dragging = 0;
        mgraphics.redraw();
        return;
    }
    if (!dragging || selected_band < 0 || selected_band >= num_bands) return;

    var b = bands[selected_band];
    var cache = band_cache[selected_band];
    var new_freq = x_to_freq(x);
    var new_gain = b.gain;
    var new_q = b.q;
    var uses_gain = cache.uses_gain ? 1 : 0;
    var target_y;

    if (uses_gain) {
        target_y = y;
        new_gain = y_to_gain(target_y);
        if (cmd) {
            new_gain = drag_start_gain;
        }
        if (shift) {
            new_gain = b.gain + (new_gain - b.gain) * 0.15;
        }
        new_gain = Math.round(new_gain * 10.0) / 10.0;
        new_gain = clamp(new_gain, MIN_GAIN, MAX_GAIN);
    } else {
        target_y = y;
        new_q = y_to_q(target_y);
        if (cmd) {
            new_q = drag_start_q;
        }
        if (shift) {
            new_q = b.q + (new_q - b.q) * 0.15;
        }
        new_q = Math.round(new_q * 100.0) / 100.0;
        new_q = clamp(new_q, MIN_Q, MAX_Q);
    }

    if (shift) {
        new_freq = b.freq + (new_freq - b.freq) * 0.15;
    }

    if (new_freq < 100) {
        new_freq = Math.round(new_freq);
    } else if (new_freq < 1000) {
        new_freq = Math.round(new_freq);
    } else {
        new_freq = Math.round(new_freq / 10.0) * 10.0;
    }
    new_freq = clamp(new_freq, MIN_FREQ, MAX_FREQ);

    bands[selected_band].freq = new_freq;
    if (uses_gain) {
        bands[selected_band].gain = new_gain;
    } else {
        bands[selected_band].q = new_q;
    }

    rebuild_band_cache();
    outlet(1, "band_freq", selected_band, new_freq);
    if (uses_gain) {
        outlet(2, "band_gain", selected_band, new_gain);
    } else {
        outlet(3, "band_q", selected_band, new_q);
    }
    mgraphics.redraw();
}

function onidle(x, y, but, cmd, shift, caps, opt, ctrl) {
    var prev = hover_band;
    hover_band = hit_test(x, y);
    if (hover_band !== prev) {
        mgraphics.redraw();
    }
}

function onidleout(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (hover_band >= 0) {
        hover_band = -1;
        mgraphics.redraw();
    }
}

function onwheel(x, y, scrollx, scrolly, cmd, shift, caps, opt, ctrl) {
    var target = hover_band >= 0 ? hover_band : selected_band;
    if (target < 0 || target >= num_bands) return;
    if (!bands[target].enabled) return;

    var q = bands[target].q;
    var factor = shift ? 0.02 : 0.08;
    q = q * (1.0 + scrolly * factor);
    q = clamp(q, MIN_Q, MAX_Q);
    q = Math.round(q * 100.0) / 100.0;

    bands[target].q = q;
    rebuild_band_cache();
    outlet(3, "band_q", target, q);
    mgraphics.redraw();
}
""")
