"""Harmonic-exciter band display (harmonic-exciter-style hero graph).

A log-frequency response plot (20 Hz .. 20 kHz) of the two exciter bands — a LOW
"body/warmth" band that lifts below its tune frequency and a HIGH "air/sparkle"
band that lifts above its tune frequency — drawn as a filled "added-harmonics"
envelope. Each band has a draggable handle: drag horizontally to set its TUNE
(crossover) frequency, vertically to set its AMOUNT. A live output-level glow
rides the curve. Outlets fire only on user gestures (no-echo rule: an inbound
``set_*`` never triggers an outlet).

This is a *representative* envelope (the perceived spectral lift), not the exact
per-sample transfer — the DSP adds band-filtered harmonics in parallel; the
curve communicates which part of the spectrum each band energizes and how hard.

Messages in (inlet 0):
    set_lo_amount <pct>     0..100  (LOW band drive amount)
    set_hi_amount <pct>     0..100  (HIGH band drive amount)
    set_lo_tune <hz>        30..1000   (LOW band crossover)
    set_hi_tune <hz>        800..18000 (HIGH band crossover)
    set_character <idx>     0 WARM / 1 CLASSIC / 2 CLEAR (tints the fill)
    set_listen <idx>        0 OFF / 1 ALL / 2 HIGH / 3 LOW (delta-solo badge)
    io_level <env_lin>      live |output| 0..1 (~30 ms) — drives the glow

Messages out (outlet 0):
    lo_amount <pct>         while dragging the LOW handle vertically
    hi_amount <pct>         while dragging the HIGH handle vertically
    lo_tune <hz>            while dragging the LOW handle horizontally
    hi_tune <hz>            while dragging the HIGH handle horizontally
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)
from .design_system import design_system_js
from .interaction_core import (
    CLAMP_TERNARY_JS,
    ONRESIZE_JS,
    POINTER_BUTTONS_JS,
    POINTER_X_JS,
    POINTER_Y_JS,
    plot_geometry_short_js,
)

EXCITER_CURVE_INLETS = 1
EXCITER_CURVE_OUTLETS = 1

__all__ = ["EXCITER_CURVE_INLETS", "EXCITER_CURVE_OUTLETS", "exciter_curve_js"]


def exciter_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    lo_color="0.96, 0.55, 0.22, 1.0",
    hi_color="0.36, 0.78, 0.96, 1.0",
    curve_color="0.95, 0.97, 0.99, 0.95",
    accent_color="0.95, 0.62, 0.28, 1.0",
    spec_fill_color="0.46, 0.62, 0.72, 0.16",
    spec_line_color="0.58, 0.76, 0.86, 0.42",
):
    """Return JavaScript source for the harmonic-exciter band display.

    ``lo_color`` / ``hi_color`` tint the LOW and HIGH band fills/handles.
    ``spec_fill_color`` / ``spec_line_color`` tint the live FFT spectrum drawn
    behind the band curves (a dim neutral so the colored bands stay dominant).
    All color arguments are RGBA strings, e.g. ``"0.96, 0.55, 0.22, 1.0"``.
    """
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return design_system_js() + "\n" + _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        grid_color=grid_color,
        text_color=text_color,
        lo_color=lo_color,
        hi_color=hi_color,
        curve_color=curve_color,
        accent_color=accent_color,
        spec_fill_color=spec_fill_color,
        spec_line_color=spec_line_color,
    ).replace("//__CLAMP_TERNARY__//", CLAMP_TERNARY_JS).replace(
        "//__PLOT_GEOMETRY__//",
        plot_geometry_short_js(
            "MARGIN_L",
            "mgraphics.size[0] - MARGIN_R",
            "MARGIN_T",
            "mgraphics.size[1] - MARGIN_B",
        ),
    ).replace("//__POINTER_X__//", POINTER_X_JS).replace(
        "//__POINTER_Y__//", POINTER_Y_JS
    ).replace("//__POINTER_BUTTONS__//", POINTER_BUTTONS_JS).replace(
        "//__ONRESIZE__//", ONRESIZE_JS
    )


_JS_TEMPLATE = Template("""\
// Harmonic Exciter Band Display - generated by m4l-builder
// ES5 compatible; full pointer handler set for v8ui drags.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];
var LO_CLR     = [$lo_color];
var HI_CLR     = [$hi_color];
var CURVE_CLR  = [$curve_color];
var ACCENT_CLR = [$accent_color];
var SPEC_FILL_CLR = [$spec_fill_color];
var SPEC_LINE_CLR = [$spec_line_color];

var MARGIN_L = 6, MARGIN_R = 6, MARGIN_T = 6, MARGIN_B = 16;
var MIN_FREQ = 20.0, MAX_FREQ = 20000.0;
var MAX_LIFT = 18.0;            // dB top of the lift axis
var SLOPE_K  = 1.45;            // logistic steepness per octave of the shelf
var LO_MIN = 30.0,  LO_MAX = 1000.0;
var HI_MIN = 800.0, HI_MAX = 18000.0;

var LOG_MIN = Math.log(MIN_FREQ) / Math.LN10;
var LOG_MAX = Math.log(MAX_FREQ) / Math.LN10;
var LOG_RANGE = LOG_MAX - LOG_MIN;
var LN2 = Math.LN2;

var MAJOR_FREQS = [20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000];

// State (mirrors the params; set_* updates these, never emits).
var lo_amount = 0.0, hi_amount = 0.0;
var lo_tune = 150.0, hi_tune = 3500.0;
var listen = 0;   // 0 OFF / 1 ALL / 2 HIGH / 3 LOW (delta-solo of the harmonics)
var character = 1;
var env = 0.0;

var dragging = 0;     // 0 none, 1 LOW handle, 2 HIGH handle
var hovering = 0;

// ── Live FFT spectrum: magnitudes poked into a buffer~ by the fft_analyzer
// backend, polled here ~30 fps and drawn behind the band curves so you SEE the
// harmonics each band is adding (premium-exciter-style). Absolute-level backdrop;
// its own dB axis, independent of the band-lift axis the curves use.
var SPEC_BINS    = 160;          // log-spaced display bins (20 Hz .. 20 kHz)
var SPEC_MIN_DB  = -72.0;
var SPEC_MAX_DB  = 6.0;
var SPEC_TRIM_DB = 12.0;          // lift so a typical mix sits mid-graph
var sample_rate = 44100.0;
var analyzer_buffer_name = "";
var analyzer_buffer_bins = 0;
var analyzer_poll_task = null;
var analyzer_display = [];        // smoothed dB per display bin (fast atk/slow rel)

//__CLAMP_TERNARY__//

//__PLOT_GEOMETRY__//

function freq_to_x(f) {
    var lv = Math.log(clamp(f, MIN_FREQ, MAX_FREQ)) / Math.LN10;
    return plot_l() + ((lv - LOG_MIN) / LOG_RANGE) * plot_w();
}
function x_to_freq(x) {
    var n = clamp((x - plot_l()) / plot_w(), 0.0, 1.0);
    return Math.pow(10, LOG_MIN + n * LOG_RANGE);
}
function lift_to_y(db) {
    return plot_b() - (clamp(db, 0.0, MAX_LIFT) / MAX_LIFT) * plot_h();
}

// Per-band lift (dB) at a frequency: a logistic shelf around the tune freq.
// HIGH rises ABOVE hi_tune, LOW rises BELOW lo_tune. Peak = amount% of MAX_LIFT.
function hi_lift(f) {
    var oct = (Math.log(clamp(f, MIN_FREQ, MAX_FREQ)) - Math.log(hi_tune)) / LN2;
    var s = 1.0 / (1.0 + Math.exp(-SLOPE_K * oct));
    return (hi_amount / 100.0) * MAX_LIFT * s;
}
function lo_lift(f) {
    var oct = (Math.log(lo_tune) - Math.log(clamp(f, MIN_FREQ, MAX_FREQ))) / LN2;
    var s = 1.0 / (1.0 + Math.exp(-SLOPE_K * oct));
    return (lo_amount / 100.0) * MAX_LIFT * s;
}
function total_lift(f) { return lo_lift(f) + hi_lift(f); }

// Handles sit at the tune freq, at half the band's peak lift (the shelf knee) —
// or pinned near the baseline when the band is off, so they stay grabbable.
function hi_handle_y() {
    var amt = (hi_amount / 100.0) * MAX_LIFT;
    return lift_to_y(Math.max(amt * 0.5, 1.2));
}
function lo_handle_y() {
    var amt = (lo_amount / 100.0) * MAX_LIFT;
    return lift_to_y(Math.max(amt * 0.5, 1.2));
}

function fill_clr(t) {
    // WARM leans to LO color, CLEAR to HI color, CLASSIC blends.
    var k = character === 0 ? 0.18 : (character === 2 ? 0.82 : 0.5);
    return [LO_CLR[0] + (HI_CLR[0] - LO_CLR[0]) * k,
            LO_CLR[1] + (HI_CLR[1] - LO_CLR[1]) * k,
            LO_CLR[2] + (HI_CLR[2] - LO_CLR[2]) * k];
}

function band_curve(fn, alpha_fill) {
    var i, N = 96, f, x, y;
    var bottom = plot_b();
    mgraphics.move_to(plot_l(), bottom);
    for (i = 0; i <= N; i++) {
        f = Math.pow(10, LOG_MIN + (i / N) * LOG_RANGE);
        x = plot_l() + (i / N) * plot_w();
        y = lift_to_y(fn(f));
        mgraphics.line_to(x, y);
    }
    mgraphics.line_to(plot_r(), bottom);
    mgraphics.close_path();
}

function stroke_curve(fn, width) {
    var i, N = 96, f, x, y;
    mgraphics.set_line_width(width);
    for (i = 0; i <= N; i++) {
        f = Math.pow(10, LOG_MIN + (i / N) * LOG_RANGE);
        x = plot_l() + (i / N) * plot_w();
        y = lift_to_y(fn(f));
        if (i === 0) mgraphics.move_to(x, y);
        else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();
}

function draw_handle(x, y, clr, active) {
    ds_node_glow(x, y, clr, active ? 11.0 : 7.0, active ? 0.55 : 0.34);
    mgraphics.set_source_rgba(clr[0], clr[1], clr[2], 1.0);
    mgraphics.arc(x, y, active ? 5.0 : 4.0, 0, Math.PI * 2);
    mgraphics.fill();
    mgraphics.set_source_rgba(0.04, 0.05, 0.06, 0.85);
    mgraphics.arc(x, y, 1.7, 0, Math.PI * 2);
    mgraphics.fill();
}

function paint() {
    var w = mgraphics.size[0], h = mgraphics.size[1];
    var i, x, y;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Live FFT spectrum backdrop (behind the grid + band curves).
    draw_spectrum();

    // Frequency grid + labels.
    mgraphics.set_line_width(1.0);
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(7.0);
    for (i = 0; i < MAJOR_FREQS.length; i++) {
        x = freq_to_x(MAJOR_FREQS[i]);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(x, plot_t());
        mgraphics.line_to(x, plot_b());
        mgraphics.stroke();
        mgraphics.set_source_rgba(TEXT_CLR);
        var lbl = MAJOR_FREQS[i] >= 1000 ? ((MAJOR_FREQS[i] / 1000) + "k") : ("" + MAJOR_FREQS[i]);
        mgraphics.move_to(x - 6, h - 5);
        mgraphics.show_text(lbl);
    }
    // 0 dB baseline.
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.move_to(plot_l(), plot_b());
    mgraphics.line_to(plot_r(), plot_b());
    mgraphics.stroke();

    // Per-band tints (so each band reads where it lives) then the combined fill.
    mgraphics.set_source_rgba(LO_CLR[0], LO_CLR[1], LO_CLR[2], 0.12);
    band_curve(lo_lift, 0.12);
    mgraphics.fill();
    mgraphics.set_source_rgba(HI_CLR[0], HI_CLR[1], HI_CLR[2], 0.12);
    band_curve(hi_lift, 0.12);
    mgraphics.fill();

    var fc = fill_clr(0.0);
    var grad = mgraphics.pattern_create_linear(0, plot_t(), 0, plot_b());
    grad.add_color_stop_rgba(0.0, fc[0], fc[1], fc[2], 0.34);
    grad.add_color_stop_rgba(1.0, fc[0], fc[1], fc[2], 0.04);
    mgraphics.set_source(grad);
    band_curve(total_lift, 0.34);
    mgraphics.fill();

    // Combined response curve.
    mgraphics.set_source_rgba(CURVE_CLR);
    stroke_curve(total_lift, (dragging || hovering) ? 2.0 : 1.6);

    // Tune markers (faint verticals) + handles.
    mgraphics.set_source_rgba(LO_CLR[0], LO_CLR[1], LO_CLR[2], 0.4);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(freq_to_x(lo_tune), plot_t());
    mgraphics.line_to(freq_to_x(lo_tune), plot_b());
    mgraphics.stroke();
    mgraphics.set_source_rgba(HI_CLR[0], HI_CLR[1], HI_CLR[2], 0.4);
    mgraphics.move_to(freq_to_x(hi_tune), plot_t());
    mgraphics.line_to(freq_to_x(hi_tune), plot_b());
    mgraphics.stroke();
    draw_handle(freq_to_x(lo_tune), lo_handle_y(), LO_CLR, dragging === 1);
    draw_handle(freq_to_x(hi_tune), hi_handle_y(), HI_CLR, dragging === 2);

    // Live output glow riding the curve crest (the louder the output, the hotter).
    if (env > 0.0005) {
        var hot = clamp(env, 0.0, 1.0);
        var cx = freq_to_x(hi_tune);
        var cy = lift_to_y(total_lift(hi_tune));
        ds_node_glow(cx, cy, CURVE_CLR, 6.0 + hot * 10.0, 0.18 + hot * 0.4);
    }

    // Readout: per-band amount + tune.
    mgraphics.set_font_size(8.0);
    mgraphics.set_source_rgba(LO_CLR[0], LO_CLR[1], LO_CLR[2], 1.0);
    mgraphics.move_to(plot_l() + 5, plot_t() + 11);
    mgraphics.show_text("LOW " + Math.round(lo_amount) + "%  " + fmt_hz(lo_tune));
    mgraphics.set_source_rgba(HI_CLR[0], HI_CLR[1], HI_CLR[2], 1.0);
    var t2 = "HIGH " + Math.round(hi_amount) + "%  " + fmt_hz(hi_tune);
    mgraphics.move_to(plot_r() - (t2.length * 4.6) - 5, plot_t() + 11);
    mgraphics.show_text(t2);

    // DELTA / Listen indicator (top-centre): when soloing just the added
    // harmonics, show WHICH band you are auditioning. The menu had no display
    // sync before -- you could not see the delta state on the hero.
    if (listen > 0) {
        var dlbl = listen === 1 ? "DELTA ALL" : (listen === 2 ? "DELTA HIGH" : "DELTA LOW");
        mgraphics.select_font_face("Arial Bold");
        mgraphics.set_font_size(8.5);
        mgraphics.set_source_rgba(CURVE_CLR[0], CURVE_CLR[1], CURVE_CLR[2], 0.96);
        mgraphics.move_to(plot_l() + plot_w() * 0.5 - dlbl.length * 2.5, plot_t() + 12);
        mgraphics.show_text(dlbl);
    }

    // Border.
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();
}

function fmt_hz(f) {
    return f >= 1000 ? ((Math.round(f / 100) / 10) + "k") : (Math.round(f) + "Hz");
}

// ── Messages (no-echo: update state + redraw, never emit) ────────────────
function set_lo_amount(v) { lo_amount = clamp(v, 0.0, 100.0); mgraphics.redraw(); }
function set_hi_amount(v) { hi_amount = clamp(v, 0.0, 100.0); mgraphics.redraw(); }
function set_lo_tune(v)   { lo_tune = clamp(v, LO_MIN, LO_MAX); mgraphics.redraw(); }
function set_hi_tune(v)   { hi_tune = clamp(v, HI_MIN, HI_MAX); mgraphics.redraw(); }
function set_character(v) { character = clamp(Math.round(v), 0, 2); mgraphics.redraw(); }
function set_listen(v)    { listen = clamp(Math.round(v), 0, 3); mgraphics.redraw(); }
function io_level(e) { env = (e === e) ? clamp(e, 0.0, 1.0) : 0.0; mgraphics.redraw(); }

// ── Live FFT spectrum: poll the analyzer buffer~, smooth into display bins ─
// The fft_analyzer backend (set_analyzer_buffer <name> <bins>) pokes
// fft_size/2 linear magnitudes into a named buffer~ every spectral frame; we
// read it on a ~30 fps Task (scheduler-message frames proved unreliable in
// Live — see fft_analyzer.py). set_samplerate maps bins -> Hz.
function spec_ensure() {
    if (analyzer_display.length === SPEC_BINS) return;
    analyzer_display = [];
    var i;
    for (i = 0; i < SPEC_BINS; i++) analyzer_display[i] = SPEC_MIN_DB;
}

function read_buffer_frame(nm, bins) {
    if (nm === "") return null;
    try {
        var b = new Buffer(nm);
        var n = bins > 0 ? bins : 1024;
        return b.peek(1, 0, n);
    } catch (e) { return null; }
}

function update_spectrum(mags) {
    var m = mags.length;
    if (m < 4) return;
    spec_ensure();
    var hz_per_bin = (sample_rate * 0.5) / m;   // mags = FFT_SIZE/2 bins -> Nyquist
    var half = 0.0065;
    var i, k, klo, khi, norm, f_lo, f_hi, peak, sum, cnt, mag, energy, db;
    for (i = 0; i < SPEC_BINS; i++) {
        norm = i / (SPEC_BINS - 1);
        f_lo = Math.pow(10, LOG_MIN + (norm - half) * LOG_RANGE);
        f_hi = Math.pow(10, LOG_MIN + (norm + half) * LOG_RANGE);
        klo = Math.floor(f_lo / hz_per_bin);
        khi = Math.ceil(f_hi / hz_per_bin);
        if (klo < 0) klo = 0;
        if (khi >= m) khi = m - 1;
        if (khi < klo) khi = klo;
        peak = 0.0; sum = 0.0; cnt = 0;
        for (k = klo; k <= khi; k++) {
            mag = mags[k];
            if (mag < 0.0) mag = -mag;
            if (mag !== mag) mag = 0.0;          // NaN guard
            if (mag > peak) peak = mag;
            sum += mag; cnt++;
        }
        // peak-dominant so a tone reads as a tight spike; mean lifts valleys
        // so harmonics stay connected (same recipe as the EQ spectrum).
        energy = cnt > 0 ? (0.6 * peak + 0.4 * (sum / cnt)) : 0.0;
        db = energy > 1e-9 ? (20.0 * Math.log(energy) / Math.LN10) : SPEC_MIN_DB;
        db += SPEC_TRIM_DB;
        db = clamp(db, SPEC_MIN_DB, SPEC_MAX_DB);
        if (db > analyzer_display[i]) {
            analyzer_display[i] = analyzer_display[i] * 0.4 + db * 0.6;   // fast attack
        } else {
            analyzer_display[i] = analyzer_display[i] * 0.82 + db * 0.18; // slow release
        }
    }
    mgraphics.redraw();
}

function poll_analyzer_buffer() {
    if (analyzer_buffer_name === "") return;
    var vals = read_buffer_frame(analyzer_buffer_name, analyzer_buffer_bins);
    if (vals && vals.length >= 4) update_spectrum(vals);
}

function start_analyzer_poll() {
    if (analyzer_poll_task !== null) return;
    if (typeof Task !== "undefined") {
        analyzer_poll_task = new Task(poll_analyzer_buffer);
        analyzer_poll_task.interval = 33;
        analyzer_poll_task.repeat();
    } else if (typeof setInterval !== "undefined") {
        analyzer_poll_task = setInterval(poll_analyzer_buffer, 33);
    }
}

function set_analyzer_buffer(name, bins) {
    analyzer_buffer_name = "" + name;
    analyzer_buffer_bins = bins ? Math.floor(bins) : 0;
    spec_ensure();
    start_analyzer_poll();
}

function set_samplerate(hz) {
    if (hz > 1000.0 && hz < 768000.0) sample_rate = hz;
}

function spec_y(db) {
    var nrm = (clamp(db, SPEC_MIN_DB, SPEC_MAX_DB) - SPEC_MIN_DB) / (SPEC_MAX_DB - SPEC_MIN_DB);
    return plot_b() - nrm * plot_h();
}

function draw_spectrum() {
    if (analyzer_display.length !== SPEC_BINS) return;
    var i, x, y, bottom = plot_b();
    mgraphics.set_source_rgba(SPEC_FILL_CLR);
    mgraphics.move_to(plot_l(), bottom);
    for (i = 0; i < SPEC_BINS; i++) {
        x = plot_l() + (i / (SPEC_BINS - 1)) * plot_w();
        y = spec_y(analyzer_display[i]);
        mgraphics.line_to(x, y);
    }
    mgraphics.line_to(plot_r(), bottom);
    mgraphics.close_path();
    mgraphics.fill();
    mgraphics.set_source_rgba(SPEC_LINE_CLR);
    mgraphics.set_line_width(1.0);
    for (i = 0; i < SPEC_BINS; i++) {
        x = plot_l() + (i / (SPEC_BINS - 1)) * plot_w();
        y = spec_y(analyzer_display[i]);
        if (i === 0) mgraphics.move_to(x, y);
        else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();
}

// ── Interaction: grab the nearest handle, drag X = tune, Y = amount ───────
//__POINTER_X__//
//__POINTER_Y__//
//__POINTER_BUTTONS__//

function pick_handle(px, py) {
    var lx = freq_to_x(lo_tune), ly = lo_handle_y();
    var hx = freq_to_x(hi_tune), hy = hi_handle_y();
    var dlo = Math.abs(px - lx) + Math.abs(py - ly) * 0.25;
    var dhi = Math.abs(px - hx) + Math.abs(py - hy) * 0.25;
    // Bias by which half of the plot the press is in so an empty-band press still
    // grabs the intuitive handle (LOW left, HIGH right).
    if (px < freq_to_x(Math.sqrt(lo_tune * hi_tune))) return 1;
    if (dlo < dhi - 24) return 1;
    if (dhi < dlo - 24) return 2;
    return px < (lx + hx) * 0.5 ? 1 : 2;
}

function apply_drag(px, py) {
    var amt = clamp(((plot_b() - py) / plot_h()) * 100.0, 0.0, 100.0);
    var f = x_to_freq(px);
    if (dragging === 1) {
        lo_tune = clamp(f, LO_MIN, LO_MAX);
        lo_amount = amt;
        outlet(0, "lo_tune", Math.round(lo_tune));
        outlet(0, "lo_amount", Math.round(lo_amount * 10) / 10);
    } else if (dragging === 2) {
        hi_tune = clamp(f, HI_MIN, HI_MAX);
        hi_amount = amt;
        outlet(0, "hi_tune", Math.round(hi_tune));
        outlet(0, "hi_amount", Math.round(hi_amount * 10) / 10);
    }
    mgraphics.redraw();
}

function start(px, py) {
    dragging = pick_handle(px, py);
    ds_set_cursor(DS_CUR_GRAB);
    apply_drag(px, py);
}
function end_drag() {
    if (!dragging) return;
    dragging = 0;
    ds_set_cursor(DS_CUR_ARROW);
    mgraphics.redraw();
}

function onpointerdown(pe) { start(pointer_x(pe, plot_l()), pointer_y(pe, plot_b())); }
function onpointermove(pe) {
    if (dragging && ((pointer_buttons(pe, 1) & 1) !== 0)) {
        apply_drag(pointer_x(pe, plot_l()), pointer_y(pe, plot_b())); return;
    }
    if (dragging) { end_drag(); return; }
    if (!hovering) { hovering = 1; mgraphics.redraw(); }
    ds_set_cursor(DS_CUR_HAND);
}
function onpointerup(pe) { end_drag(); }
function onpointerleave(pe) { hovering = 0; end_drag(); ds_set_cursor(DS_CUR_ARROW); mgraphics.redraw(); }

// Legacy mouse fallbacks (some Live builds route these instead of pointer*).
function onclick(x, y, but, cmd, shift) { start(x, y); }
function ondrag(x, y, but, cmd, shift) { if (but) apply_drag(x, y); else end_drag(); }
function onidle(x, y) { if (!hovering) { hovering = 1; mgraphics.redraw(); } ds_set_cursor(DS_CUR_HAND); }
function onidleout() { hovering = 0; ds_set_cursor(DS_CUR_ARROW); mgraphics.redraw(); }
//__ONRESIZE__//
""")
