"""Transparent graticule overlay for a compiled ``scope~`` X-Y goniometer.

A goniometer plots the stereo signal as a Lissajous figure: a compiled ``scope~``
in X-Y mode renders the dense dot cloud in native C++ (Side on X, Mid on Y, so a
MONO signal collapses to a vertical line — the pro convention). This v8ui sits
transparently ON TOP and draws only the reference graticule: the bounding circle,
the centre cross, the two 45° diagonals, and the L / R / M / S labels. No fill, so
the live dot cloud shows through.

Pair with ``Device.add_compiled_display(..., overlay_js=...)`` (compiled box added
first → behind; this overlay second → in front).

Inlets:
    0 -- bang (redraw); display-only, no data.

Outlets:
    (none)
"""

GONIOMETER_GRATICULE_INLETS = 1
GONIOMETER_GRATICULE_OUTLETS = 0


def goniometer_graticule_js(
    *,
    bg_color="0.05, 0.052, 0.060, 1.0",
    grid_color="0.34, 0.38, 0.44, 0.55",
    diag_color="0.30, 0.34, 0.40, 0.40",
    text_color="0.62, 0.67, 0.74, 0.85",
    accent="1.0, 0.64, 0.30, 0.85",
    fontname="Ableton Sans Medium",
    fontsize=8.0,
) -> str:
    """Return v8ui source for a goniometer's reference graticule.

    Mono (Side = 0) reads as a VERTICAL line, so ``M`` is at top/bottom, ``S`` at
    the horizontal extremes, and ``L``/``R`` on the upper diagonals. All colors
    are ``"r, g, b, a"`` strings; ``accent`` tints the M (mono) markers.
    """
    return (
        "// Goniometer graticule - generated by m4l-builder (v8ui, lines + labels)\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 1;\n"
        "outlets = 0;\n"
        "\n"
        f"var BG_CLR = [{bg_color}];\n"
        f"var GRID_CLR = [{grid_color}];\n"
        f"var DIAG_CLR = [{diag_color}];\n"
        f"var TEXT_CLR = [{text_color}];\n"
        f"var ACCENT_CLR = [{accent}];\n"
        f'var FONT_NAME = "{fontname}";\n'
        f"var FONT_SIZE = {float(fontsize)};\n"
        "\n"
        "function gono_label(text, x, y, clr) {\n"
        "    mgraphics.set_source_rgba(clr[0], clr[1], clr[2], clr[3]);\n"
        "    mgraphics.move_to(x, y);\n"
        "    mgraphics.show_text(text);\n"
        "}\n"
        "\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var cx = w * 0.5;\n"
        "    var cy = h * 0.5;\n"
        "    var r = Math.min(w, h) * 0.5 - 10;\n"
        "    var dr = r * 0.7071;   // 45-degree reach\n"
        "\n"
        "    // Opaque backdrop (this overlay sits BEHIND a transparent scope~).\n"
        "    mgraphics.set_source_rgba(BG_CLR[0], BG_CLR[1], BG_CLR[2], BG_CLR[3]);\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // 45-degree diagonals (L upper-left .. R upper-right Lissajous axes)\n"
        "    mgraphics.set_source_rgba(DIAG_CLR[0], DIAG_CLR[1], DIAG_CLR[2], DIAG_CLR[3]);\n"
        "    mgraphics.set_line_width(1.0);\n"
        "    mgraphics.move_to(cx - dr, cy - dr); mgraphics.line_to(cx + dr, cy + dr); mgraphics.stroke();\n"
        "    mgraphics.move_to(cx + dr, cy - dr); mgraphics.line_to(cx - dr, cy + dr); mgraphics.stroke();\n"
        "\n"
        "    // Centre cross (vertical = mono axis, horizontal = side axis)\n"
        "    mgraphics.set_source_rgba(GRID_CLR[0], GRID_CLR[1], GRID_CLR[2], GRID_CLR[3]);\n"
        "    mgraphics.move_to(cx, cy - r); mgraphics.line_to(cx, cy + r); mgraphics.stroke();\n"
        "    mgraphics.move_to(cx - r, cy); mgraphics.line_to(cx + r, cy); mgraphics.stroke();\n"
        "\n"
        "    // Bounding circle\n"
        "    mgraphics.arc(cx, cy, r, 0, Math.PI * 2);\n"
        "    mgraphics.stroke();\n"
        "    // Inner reference circle (half-scale)\n"
        "    mgraphics.set_source_rgba(GRID_CLR[0], GRID_CLR[1], GRID_CLR[2], GRID_CLR[3] * 0.6);\n"
        "    mgraphics.arc(cx, cy, r * 0.5, 0, Math.PI * 2);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Labels\n"
        "    mgraphics.select_font_face(FONT_NAME);\n"
        "    mgraphics.set_font_size(FONT_SIZE);\n"
        "    gono_label('M', cx - 3, cy - r - 1, ACCENT_CLR);      // mono, top\n"
        "    gono_label('L', cx - dr - 9, cy - dr - 1, TEXT_CLR);  // upper-left\n"
        "    gono_label('R', cx + dr + 3, cy - dr - 1, TEXT_CLR);  // upper-right\n"
        "    gono_label('+S', cx + r - 12, cy - 3, TEXT_CLR);      // side, right\n"
        "    gono_label('-S', cx - r + 2, cy - 3, TEXT_CLR);       // side, left\n"
        "}\n"
        "\n"
        "function bang() { mgraphics.redraw(); }\n"
        "function msg_int(v) { mgraphics.redraw(); }\n"
    )
