"""Granular synthesis display engine for jsui.

Generates JavaScript code that renders a waveform buffer with a movable
playhead marker inside Max's jsui object using mgraphics. Clicking the
display sets the playhead position and outputs it.

Inlets:
    0 -- Waveform samples (list of floats -1.0 to 1.0)
    1 -- Playhead position (float 0.0-1.0)

Outlets:
    0 -- Playhead position (float 0.0-1.0) on click
"""

GRAIN_DISPLAY_INLETS = 2
GRAIN_DISPLAY_OUTLETS = 1


def grain_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                      wave_color="0.35, 0.60, 0.90, 0.7",
                      playhead_color="1.0, 0.85, 0.4, 0.9",
                      grain_color="0.45, 0.75, 0.65, 0.5"):
    """Return JavaScript source for a granular display (Max jsui).

    Inlet 0 receives a list of waveform samples (-1.0 to 1.0). Inlet 1
    receives the playhead position (0.0-1.0). Clicking the display moves
    the playhead and outputs the position on outlet 0.

    Args:
        bg_color: Background color (RGBA string).
        wave_color: Waveform fill color (RGBA string).
        playhead_color: Playhead marker color (RGBA string).
        grain_color: Grain scatter dot color (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    wc = [s.strip() for s in wave_color.split(",")]
    wave_line = wc[0] + ", " + wc[1] + ", " + wc[2] + ", 0.9"
    wave_fill = wc[0] + ", " + wc[1] + ", " + wc[2] + ", 0.2"

    return (
        "// Grain Display — generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 1;\n"
        "\n"
        "// --- State ---\n"
        "var samples = [];\n"
        "var playhead = 0.0;\n"
        "\n"
        "// --- Constants ---\n"
        "var PADDING = 2;\n"
        "var PLAYHEAD_WIDTH = 1.5;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_list() {\n"
        "    if (inlet === 0) {\n"
        "        samples = arrayfromargs(arguments);\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_float(v) {\n"
        "    if (inlet === 1) {\n"
        "        playhead = Math.max(0, Math.min(1, v));\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_int(v) {\n"
        "    msg_float(v);\n"
        "}\n"
        "\n"
        "// --- Mouse handling ---\n"
        "function onclick(x, y, but, cmd, shift, capslock, option, ctrl) {\n"
        "    var w = mgraphics.size[0];\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    playhead = Math.max(0, Math.min(1, (x - PADDING) / area_w));\n"
        "    outlet(0, playhead);\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "function ondrag(x, y, but, cmd, shift, capslock, option, ctrl) {\n"
        "    if (but === 0) return;\n"
        "    var w = mgraphics.size[0];\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    playhead = Math.max(0, Math.min(1, (x - PADDING) / area_w));\n"
        "    outlet(0, playhead);\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_x = PADDING;\n"
        "    var area_y = PADDING;\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "    var mid_y = area_y + area_h * 0.5;\n"
        "    var n = samples.length;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Center line\n"
        "    mgraphics.set_source_rgba(0.2, 0.2, 0.22, 0.5);\n"
        "    mgraphics.set_line_width(0.5);\n"
        "    mgraphics.move_to(area_x, mid_y);\n"
        "    mgraphics.line_to(area_x + area_w, mid_y);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Waveform\n"
        "    if (n > 1) {\n"
        "        // Filled waveform shape\n"
        f"        mgraphics.set_source_rgba({wave_fill});\n"
        "        mgraphics.move_to(area_x, mid_y);\n"
        "        var k;\n"
        "        for (k = 0; k < n; k++) {\n"
        "            var sx = area_x + (k / (n - 1)) * area_w;\n"
        "            var sample = samples[k];\n"
        "            if (sample != sample) sample = 0;\n"
        "            if (sample < -1) sample = -1;\n"
        "            if (sample > 1) sample = 1;\n"
        "            var sy = mid_y - sample * area_h * 0.5;\n"
        "            mgraphics.line_to(sx, sy);\n"
        "        }\n"
        "        mgraphics.line_to(area_x + area_w, mid_y);\n"
        "        mgraphics.close_path();\n"
        "        mgraphics.fill();\n"
        "\n"
        "        // Waveform stroke\n"
        f"        mgraphics.set_source_rgba({wave_line});\n"
        "        mgraphics.set_line_width(1.0);\n"
        "        var sx0 = area_x;\n"
        "        var sy0 = mid_y - samples[0] * area_h * 0.5;\n"
        "        mgraphics.move_to(sx0, sy0);\n"
        "        for (k = 1; k < n; k++) {\n"
        "            var sxk = area_x + (k / (n - 1)) * area_w;\n"
        "            var sampleK = samples[k];\n"
        "            if (sampleK != sampleK) sampleK = 0;\n"
        "            if (sampleK < -1) sampleK = -1;\n"
        "            if (sampleK > 1) sampleK = 1;\n"
        "            var syk = mid_y - sampleK * area_h * 0.5;\n"
        "            mgraphics.line_to(sxk, syk);\n"
        "        }\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // Playhead marker\n"
        "    var ph_x = area_x + playhead * area_w;\n"
        f"    mgraphics.set_source_rgba({playhead_color});\n"
        "    mgraphics.set_line_width(PLAYHEAD_WIDTH);\n"
        "    mgraphics.move_to(ph_x, area_y);\n"
        "    mgraphics.line_to(ph_x, area_y + area_h);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Triangle marker at top\n"
        f"    mgraphics.set_source_rgba({playhead_color});\n"
        "    mgraphics.move_to(ph_x - 4, area_y);\n"
        "    mgraphics.line_to(ph_x + 4, area_y);\n"
        "    mgraphics.line_to(ph_x, area_y + 6);\n"
        "    mgraphics.close_path();\n"
        "    mgraphics.fill();\n"
        "}\n"
    )
