"""Grid sequencer display engine for jsui.

Generates JavaScript code that renders an interactive 2D grid sequencer inside
Max's jsui object using mgraphics. X axis = time (columns), Y axis = pitch (rows).
Cells are clickable to toggle notes with velocity, and a playhead column is highlighted.

Inlets:
    0 -- Note grid data: flat list [active, velocity, active, velocity...] row by row
    1 -- Playhead column position (int)

Outlets:
    0 -- Column index (int)
    1 -- Row index (int)
    2 -- Active state (int 0 or 1)
    3 -- Velocity (float 0.0-1.0)
"""

GRID_SEQ_INLETS = 2
GRID_SEQ_OUTLETS = 4


def grid_sequencer_display_js(rows=12, cols=16, *,
                               bg_color="0.07, 0.07, 0.08, 1.0",
                               active_color="0.45, 0.75, 0.65, 1.0",
                               inactive_color="0.15, 0.15, 0.17, 1.0",
                               playhead_color="1.0, 1.0, 1.0, 0.2"):
    """Return JavaScript source for a 2D grid sequencer display (Max jsui).

    Each cell stores active flag and velocity. Inlet 0 accepts a flat array
    [active, velocity, ...] row by row. Inlet 1 sets the playhead column.
    Clicking a cell toggles it and outputs col, row, active, velocity on
    outlets 0-3.

    Args:
        rows: Number of pitch rows (default 12).
        cols: Number of time columns (default 16).
        bg_color: Background color (RGBA string).
        active_color: Active cell color (RGBA string).
        inactive_color: Inactive cell color (RGBA string).
        playhead_color: Playhead column highlight color (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    ac = [s.strip() for s in active_color.split(",")]
    active_rgb = ac[0] + ", " + ac[1] + ", " + ac[2]

    return (
        "// Grid Sequencer Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 4;\n"
        "\n"
        "// --- Configuration ---\n"
        f"var NUM_ROWS = {rows};\n"
        f"var NUM_COLS = {cols};\n"
        "var PADDING = 1;\n"
        "var GAP = 1;\n"
        "\n"
        "// --- State ---\n"
        "var playhead_col = -1;\n"
        "var grid_active = [];\n"
        "var grid_velocity = [];\n"
        "var r, c;\n"
        "for (r = 0; r < NUM_ROWS; r++) {\n"
        "    grid_active[r] = [];\n"
        "    grid_velocity[r] = [];\n"
        "    for (c = 0; c < NUM_COLS; c++) {\n"
        "        grid_active[r][c] = 0;\n"
        "        grid_velocity[r][c] = 0.75;\n"
        "    }\n"
        "}\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_list() {\n"
        "    if (inlet === 0) {\n"
        "        var args = arrayfromargs(arguments);\n"
        "        var i;\n"
        "        for (i = 0; i < NUM_ROWS * NUM_COLS; i++) {\n"
        "            var row = Math.floor(i / NUM_COLS);\n"
        "            var col = i % NUM_COLS;\n"
        "            var base = i * 2;\n"
        "            if (base + 1 < args.length) {\n"
        "                grid_active[row][col] = args[base] ? 1 : 0;\n"
        "                grid_velocity[row][col] = Math.max(0, Math.min(1, args[base + 1]));\n"
        "            }\n"
        "        }\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_int(v) {\n"
        "    if (inlet === 1) {\n"
        "        playhead_col = v;\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_float(v) {\n"
        "    msg_int(Math.round(v));\n"
        "}\n"
        "\n"
        "// --- Mouse handling ---\n"
        "function onclick(x, y, but, cmd, shift, capslock, option, ctrl) {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "    var cell_w = (area_w - GAP * (NUM_COLS - 1)) / NUM_COLS;\n"
        "    var cell_h = (area_h - GAP * (NUM_ROWS - 1)) / NUM_ROWS;\n"
        "    var col = Math.floor((x - PADDING) / (cell_w + GAP));\n"
        "    var row = Math.floor((y - PADDING) / (cell_h + GAP));\n"
        "    if (col < 0) col = 0;\n"
        "    if (col >= NUM_COLS) col = NUM_COLS - 1;\n"
        "    if (row < 0) row = 0;\n"
        "    if (row >= NUM_ROWS) row = NUM_ROWS - 1;\n"
        "    grid_active[row][col] = grid_active[row][col] ? 0 : 1;\n"
        "    outlet(0, col);\n"
        "    outlet(1, row);\n"
        "    outlet(2, grid_active[row][col]);\n"
        "    outlet(3, grid_velocity[row][col]);\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_x = PADDING;\n"
        "    var area_y = PADDING;\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "    var cell_w = (area_w - GAP * (NUM_COLS - 1)) / NUM_COLS;\n"
        "    var cell_h = (area_h - GAP * (NUM_ROWS - 1)) / NUM_ROWS;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    var row, col;\n"
        "    for (row = 0; row < NUM_ROWS; row++) {\n"
        "        for (col = 0; col < NUM_COLS; col++) {\n"
        "            var cx = area_x + col * (cell_w + GAP);\n"
        "            var cy = area_y + row * (cell_h + GAP);\n"
        "\n"
        "            // Playhead column highlight\n"
        "            if (col === playhead_col) {\n"
        f"                mgraphics.set_source_rgba({playhead_color});\n"
        "                mgraphics.rectangle(cx, cy, cell_w, cell_h);\n"
        "                mgraphics.fill();\n"
        "            }\n"
        "\n"
        "            if (grid_active[row][col]) {\n"
        "                var alpha = 0.35 + grid_velocity[row][col] * 0.65;\n"
        f"                mgraphics.set_source_rgba({active_rgb}, alpha);\n"
        "            } else {\n"
        f"                mgraphics.set_source_rgba({inactive_color});\n"
        "            }\n"
        "            mgraphics.rectangle(cx, cy, cell_w, cell_h);\n"
        "            mgraphics.fill();\n"
        "        }\n"
        "    }\n"
        "\n"
        "    // Beat grouping lines (every 4 columns)\n"
        "    for (col = 4; col < NUM_COLS; col += 4) {\n"
        "        var lx = area_x + col * (cell_w + GAP) - GAP * 0.5;\n"
        "        mgraphics.set_source_rgba(1.0, 1.0, 1.0, 0.12);\n"
        "        mgraphics.set_line_width(1.0);\n"
        "        mgraphics.move_to(lx, area_y);\n"
        "        mgraphics.line_to(lx, area_y + area_h);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "}\n"
    )
