"""Integrated loudness accumulator (ITU-R BS.1770-4 / EBU R128 gated).

A non-UI ``js`` object that turns a stream of 400 ms momentary-loudness
blocks into the gated INTEGRATED loudness ("I", the whole-programme number
a master is judged by). Feed it the device's existing momentary-LUFS value
(sampled every 100 ms — a BS.1770 gating block at 75 % overlap) and it emits
the running integrated value; send it ``reset`` to start a fresh measurement.

This is the third leg of the loudness trinity (Momentary / Short-term /
Integrated) shown on the Spectrum Analyzer + Ceiling meters.

Gating (BS.1770-4):
  1. ABSOLUTE gate — drop blocks below -70 LUFS (silence).
  2. RELATIVE gate — drop blocks below (mean of the absolute-gated blocks)
     minus 10 LU, then average what remains.
The relative gate is applied via a 0.1 LU histogram of block loudness (the
reference real-time method): each bin keeps its exact summed mean-square so
the final average is not loudness-quantised — only the gate *decision* is.

Messages in (inlet 0):
    <float>     one momentary-LUFS gating block (already clipped to [-70, 0])
    reset       clear the measurement (I -> -inf)

Messages out (outlet 0):
    <float>     the current integrated LUFS (-70.0 sentinel == "no measurement")

Pure + deterministic — Node-tested in tests/test_js_behavior.py. The Max
``outlet`` / ``mgraphics`` globals are mocked by the harness, so the same
source runs headless.
"""

from __future__ import annotations

INTEGRATED_LUFS_INLETS = 1
INTEGRATED_LUFS_OUTLETS = 1

__all__ = [
    "INTEGRATED_LUFS_INLETS",
    "INTEGRATED_LUFS_OUTLETS",
    "integrated_lufs_js",
]

_JS = r"""// Integrated loudness (ITU-R BS.1770-4 gated) — generated by
// m4l_builder.engines.integrated_lufs. Non-UI js object.
autowatch = 0;
inlets = 1;
outlets = 1;

var ABS_GATE = -70.0;   // absolute gate / "no measurement" sentinel (LUFS)
var REL_LU = 10.0;      // relative gate offset (LU below the gated mean)
var OFF = -0.691;       // BS.1770 loudness offset

// Histogram of block loudness for the relative gate: 0.1 LU bins over
// [-70, 0]. hist[i] = block count in the bin; hsum[i] = exact summed
// mean-square (so the averaged result is not loudness-quantised).
var H_LO = -70.0, H_HI = 0.0, H_STEP = 0.1;
var H_N = Math.round((H_HI - H_LO) / H_STEP) + 1;
var hist = [];
var hsum = [];
var n_abs = 0;          // count of absolute-gated blocks
var sum_ms = 0.0;       // summed mean-square of absolute-gated blocks
var ilufs = ABS_GATE;   // current integrated value

function lufs_to_ms(l) { return Math.pow(10.0, (l - OFF) / 10.0); }
function ms_to_lufs(m) {
    return (m <= 0.0) ? ABS_GATE : (OFF + 10.0 * Math.log(m) / Math.LN10);
}

function reset() {
    hist = [];
    hsum = [];
    for (var i = 0; i < H_N; i++) { hist[i] = 0; hsum[i] = 0.0; }
    n_abs = 0;
    sum_ms = 0.0;
    ilufs = ABS_GATE;
    outlet(0, ilufs);
}

function recompute() {
    if (n_abs <= 0) { ilufs = ABS_GATE; return; }
    var mean_abs = sum_ms / n_abs;                  // absolute-gated mean (ms)
    var rel_lufs = ms_to_lufs(mean_abs) - REL_LU;   // relative gate threshold
    var rsum = 0.0, rcount = 0;
    for (var i = 0; i < H_N; i++) {
        if (hist[i] <= 0) continue;
        var bin_l = H_LO + i * H_STEP;              // bin's representative loudness
        if (bin_l >= rel_lufs) { rsum += hsum[i]; rcount += hist[i]; }
    }
    // If the relative gate excluded everything (can't happen — the mean's own
    // bins sit above mean-10 — but guard anyway) fall back to the absolute mean.
    ilufs = (rcount > 0) ? ms_to_lufs(rsum / rcount) : ms_to_lufs(mean_abs);
}

// One gating block. m = momentary LUFS (already clipped to [-70, 0]).
function block(m) {
    if (typeof m !== "number" || m !== m) { outlet(0, ilufs); return; }  // NaN guard
    if (m > ABS_GATE) {
        var ms = lufs_to_ms(m);
        var bi = Math.round((m - H_LO) / H_STEP);
        if (bi < 0) bi = 0; else if (bi >= H_N) bi = H_N - 1;
        hist[bi] += 1;
        hsum[bi] += ms;
        n_abs += 1;
        sum_ms += ms;
        recompute();
    }
    outlet(0, ilufs);
}

// Max entry points: a bare float is a block; "reset" clears the measurement.
function msg_float(f) { block(f); }
function msg_int(i) { block(i); }
function anything() {
    if (messagename == "reset") reset();
}
function bang() { reset(); }

reset();
"""


def integrated_lufs_js() -> str:
    """Return the integrated-loudness accumulator JS (non-UI ``js`` object)."""
    return _JS
