"""Scrolling level + gain-reduction history display (Pro-C 2 / Pro-L 2 style).

The signature dynamics view: input level scrolls right-to-left as a filled
area from the bottom while gain reduction hangs from the top as a filled
band on its own scale. A peak-GR readout tracks the deepest reduction of
the last ~1.5 s. Display-only in V1 (no gestures, no outlets fired) — the
inbound ~30 Hz `levels` stream drives redraws, so no Task/clock is needed
(legacy js Task.schedule silently no-ops in Live).

Messages in (inlet 0):
    levels <env_db> <gr_db>   push one frame (detector level dB, GR dB <= 0)
    set_range <lo> <hi>       vertical level window in dB (default -60..6)
    set_gr_scale <db>         full-scale GR band depth in dB (default 24)
    set_seconds <s>           history length in seconds (default 6)
    set_rate <hz>             expected frame rate, sizes the ring (default 30)
    set_ref_db <db>           draw a reference level line (ceiling/threshold);
                              values outside the window hide it
    clear                     wipe history

With interactive=True the reference line becomes draggable (Pro-C/Pro-L
style: threshold/ceiling on the main view): click or drag and the line
follows the cursor's level (ABSOLUTE mapping), emitting "threshold <db>"
on outlet 0, clamped to [lo_db, min(hi_db, 0)]. Coordinates resolve via a
.y/.localY/.offsetY/.clientY fallback (raw pointerevent.y is undefined in
Live's v8ui). While dragging, inbound set_ref_db is ignored (drag owns the
line).

Messages out (outlet 0): none in V1 (reserved for threshold drag later).
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)

LEVEL_HISTORY_INLETS = 1
LEVEL_HISTORY_OUTLETS = 1

__all__ = ["LEVEL_HISTORY_INLETS", "LEVEL_HISTORY_OUTLETS", "level_history_js"]


def level_history_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    level_fill_color="0.30, 0.75, 0.95, 0.18",
    level_line_color="0.30, 0.75, 0.95, 0.85",
    gr_fill_color="0.95, 0.55, 0.25, 0.30",
    gr_line_color="0.95, 0.55, 0.25, 1.0",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    ref_color="0.95, 0.55, 0.25, 0.9",
    lo_db=-60.0,
    hi_db=6.0,
    gr_scale_db=24.0,
    seconds=6.0,
    rate_hz=30.0,
    ref_db=None,
    interactive=False,
    reset_db=0.0,
):
    """Return JavaScript source for the scrolling level/GR history display.

    interactive=True makes the reference line draggable (emits ``threshold``);
    double-click resets it to ``reset_db``.
    """
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        level_fill_color=level_fill_color,
        level_line_color=level_line_color,
        gr_fill_color=gr_fill_color,
        gr_line_color=gr_line_color,
        grid_color=grid_color,
        text_color=text_color,
        ref_color=ref_color,
        lo_db=lo_db,
        hi_db=hi_db,
        gr_scale_db=gr_scale_db,
        seconds=seconds,
        rate_hz=rate_hz,
        ref_db="null" if ref_db is None else ref_db,
        interactive=1 if interactive else 0,
        reset_db=reset_db,
    )


_JS_TEMPLATE = Template("""\
// Level History Display - generated by m4l-builder
// ES5 compatible; display-only (no gesture outlets in V1).

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR      = [$bg_color];
var PANEL_CLR   = [$panel_color];
var BORDER_CLR  = [$plot_border_color];
var LVL_FILL    = [$level_fill_color];
var LVL_LINE    = [$level_line_color];
var GR_FILL     = [$gr_fill_color];
var GR_LINE     = [$gr_line_color];
var GRID_CLR    = [$grid_color];
var TEXT_CLR    = [$text_color];
var REF_CLR     = [$ref_color];

var ref_db = $ref_db;
var INTERACTIVE = $interactive;
var RESET_DB = $reset_db;
var dragging = 0;
var drag_start_y = 0.0;
var drag_start_ref = 0.0;
var lo_db = $lo_db;
var hi_db = $hi_db;
var gr_scale_db = $gr_scale_db;
var seconds = $seconds;
var rate_hz = $rate_hz;

// Ring buffers (fixed size; resized only by set_seconds/set_rate).
var cap = 0;
var env_ring = [];
var gr_ring = [];
var head = 0;     // next write slot
var count = 0;    // valid frames (<= cap)

function rebuild_ring() {
    cap = Math.round(seconds * rate_hz);
    if (cap < 16) cap = 16;
    if (cap > 1024) cap = 1024;
    env_ring = new Array(cap);
    gr_ring = new Array(cap);
    var i;
    for (i = 0; i < cap; i++) { env_ring[i] = lo_db; gr_ring[i] = 0.0; }
    head = 0;
    count = 0;
}
rebuild_ring();

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

function plot_l() { return 24; }
function plot_r() { return mgraphics.size[0] - 22; }
function plot_t() { return 6; }
function plot_b() { return mgraphics.size[1] - 6; }
function plot_w() { return plot_r() - plot_l(); }
function plot_h() { return plot_b() - plot_t(); }

function db_to_y(db) {
    var n = (clamp(db, lo_db, hi_db) - lo_db) / (hi_db - lo_db);
    return plot_b() - n * plot_h();
}

// GR band hangs from the top on its own scale (0..gr_scale_db of depth
// mapped onto the upper 45% of the plot).
function gr_to_depth(grdb) {
    var n = clamp(-grdb, 0.0, gr_scale_db) / gr_scale_db;
    return n * plot_h() * 0.45;
}

function frame_at(i) {
    // i = 0 is oldest of the valid frames.
    return (head - count + i + cap * 2) % cap;
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, idx, x, y;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Level gridlines every 12 dB, labeled on the left.
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(6.5);
    var db;
    for (db = Math.ceil(lo_db / 12) * 12; db <= hi_db; db += 12) {
        y = db_to_y(db);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.set_line_width(1.0);
        mgraphics.move_to(plot_l(), y);
        mgraphics.line_to(plot_r(), y);
        mgraphics.stroke();
        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.move_to(2, y + 2);
        mgraphics.show_text("" + db);
    }
    // GR scale ticks on the right (every 6 dB of reduction).
    var grd;
    for (grd = 6; grd <= gr_scale_db; grd += 6) {
        y = plot_t() + gr_to_depth(-grd);
        mgraphics.set_source_rgba(GR_LINE[0], GR_LINE[1], GR_LINE[2], 0.35);
        mgraphics.move_to(plot_r() - 4, y);
        mgraphics.line_to(plot_r(), y);
        mgraphics.stroke();
        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.move_to(plot_r() + 2, y + 2);
        mgraphics.show_text("" + grd);
    }

    if (count > 1) {
        var px = plot_w() / (cap - 1);
        var x0 = plot_r() - (count - 1) * px;

        // Input level: filled area from the bottom + line.
        mgraphics.set_source_rgba(LVL_FILL);
        mgraphics.move_to(x0, plot_b());
        for (i = 0; i < count; i++) {
            idx = frame_at(i);
            mgraphics.line_to(x0 + i * px, db_to_y(env_ring[idx]));
        }
        mgraphics.line_to(x0 + (count - 1) * px, plot_b());
        mgraphics.close_path();
        mgraphics.fill();

        mgraphics.set_source_rgba(LVL_LINE);
        mgraphics.set_line_width(1.2);
        for (i = 0; i < count; i++) {
            idx = frame_at(i);
            x = x0 + i * px;
            y = db_to_y(env_ring[idx]);
            if (i === 0) mgraphics.move_to(x, y);
            else mgraphics.line_to(x, y);
        }
        mgraphics.stroke();

        // Gain reduction: filled band hanging from the top + edge line.
        mgraphics.set_source_rgba(GR_FILL);
        mgraphics.move_to(x0, plot_t());
        for (i = 0; i < count; i++) {
            idx = frame_at(i);
            mgraphics.line_to(x0 + i * px, plot_t() + gr_to_depth(gr_ring[idx]));
        }
        mgraphics.line_to(x0 + (count - 1) * px, plot_t());
        mgraphics.close_path();
        mgraphics.fill();

        mgraphics.set_source_rgba(GR_LINE);
        mgraphics.set_line_width(1.3);
        for (i = 0; i < count; i++) {
            idx = frame_at(i);
            x = x0 + i * px;
            y = plot_t() + gr_to_depth(gr_ring[idx]);
            if (i === 0) mgraphics.move_to(x, y);
            else mgraphics.line_to(x, y);
        }
        mgraphics.stroke();
    }

    // Reference level line (ceiling/threshold) on the level scale, with a dB
    // readout pill. While DRAGGING the line the pill brightens + enlarges and
    // rides the cursor's level (Pro-C/Pro-L threshold feedback); idle it's a
    // subtle tag so the value is always legible.
    if (ref_db !== null && ref_db >= lo_db && ref_db <= hi_db) {
        y = db_to_y(ref_db);
        var big = (INTERACTIVE && dragging) ? 1 : 0;
        mgraphics.set_source_rgba(REF_CLR[0], REF_CLR[1], REF_CLR[2],
            (REF_CLR.length > 3 ? REF_CLR[3] : 1.0) * (big ? 1.0 : 0.85));
        mgraphics.set_line_width(big ? 1.8 : 1.2);
        var dash_x = plot_l();
        var dash_len = big ? 7 : 5, dash_gap = big ? 11 : 9;
        while (dash_x < plot_r()) {
            mgraphics.move_to(dash_x, y);
            mgraphics.line_to(Math.min(dash_x + dash_len, plot_r()), y);
            mgraphics.stroke();
            dash_x += dash_gap;
        }
        // The readout pill.
        var rtxt = ((ref_db >= 0 ? "+" : "") + ref_db.toFixed(1)) + " dB";
        var fs = big ? 9.5 : 7.0;
        var pw = rtxt.length * (big ? 5.8 : 4.0) + (big ? 12 : 6);
        var ph = big ? 15 : 10;
        var pxx = plot_r() - pw - 2;
        var pyy = clamp(y - ph * 0.5, plot_t() + 1, plot_b() - ph - 1);
        mgraphics.set_source_rgba(REF_CLR[0], REF_CLR[1], REF_CLR[2], big ? 0.96 : 0.20);
        mgraphics.rectangle_rounded(pxx, pyy, pw, ph, 3, 3);
        mgraphics.fill();
        if (big) mgraphics.set_source_rgba(0.05, 0.06, 0.08, 0.97);
        else mgraphics.set_source_rgba(REF_CLR[0], REF_CLR[1], REF_CLR[2], 0.96);
        mgraphics.set_font_size(fs);
        mgraphics.move_to(pxx + (big ? 6 : 3), pyy + (big ? 10.8 : 7.6));
        mgraphics.show_text(rtxt);
    }

    // Peak GR over the most recent ~1.5 s, as a readout.
    var look = Math.min(count, Math.round(rate_hz * 1.5));
    var peak_gr = 0.0;
    for (i = count - look; i < count; i++) {
        if (i < 0) continue;
        idx = frame_at(i);
        if (gr_ring[idx] < peak_gr) peak_gr = gr_ring[idx];
    }
    if (peak_gr < -0.05) {
        mgraphics.set_source_rgba(GR_LINE);
        mgraphics.set_font_size(8.0);
        mgraphics.move_to(plot_l() + 6, plot_t() + 12);
        // GR as a positive magnitude ("GR 10.8 dB") to match the transfer
        // inset + Pro-L/Pro-C convention (peak_gr is the deepest, negative).
        mgraphics.show_text("GR " + (-peak_gr).toFixed(1) + " dB");
    }

    // Border.
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();
}

// ── Messages ─────────────────────────────────────────────────────────
function levels(env_db, gr_db) {
    // Guard: a per-frame TypeError flood wedges Max's UI thread Live-wide.
    var e = parseFloat(env_db);
    var g = parseFloat(gr_db);
    if (!isFinite(e)) e = lo_db;
    if (!isFinite(g) || g > 0.0) g = 0.0;
    env_ring[head] = e;
    gr_ring[head] = g;
    head = (head + 1) % cap;
    if (count < cap) count += 1;
    mgraphics.redraw();
}

function set_range(lo, hi) {
    lo = parseFloat(lo); hi = parseFloat(hi);
    if (!isFinite(lo) || !isFinite(hi) || hi - lo < 6.0) return;
    lo_db = lo; hi_db = hi;
    mgraphics.redraw();
}

function set_gr_scale(v) {
    v = parseFloat(v);
    if (!isFinite(v) || v < 3.0) return;
    gr_scale_db = v;
    mgraphics.redraw();
}

function set_seconds(s) {
    s = parseFloat(s);
    if (!isFinite(s) || s < 1.0 || s > 30.0) return;
    seconds = s;
    rebuild_ring();
    mgraphics.redraw();
}

function set_rate(hz) {
    hz = parseFloat(hz);
    if (!isFinite(hz) || hz < 5.0 || hz > 120.0) return;
    rate_hz = hz;
    rebuild_ring();
    mgraphics.redraw();
}

function set_ref_db(v) {
    if (dragging) return;  // drag owns the line
    v = parseFloat(v);
    if (!isFinite(v)) { ref_db = null; }
    else { ref_db = v; }
    mgraphics.redraw();
}

// ── Interaction (interactive=True): drag the reference line ──────────
// Robust pointer-coordinate resolver: v8ui exposes the object-local position
// under different property names (.y / .localY / .offsetY / .clientY); reading
// only `.y` returned undefined in Live -> NaN -> the line mis-scaled and jumped
// (the it38 bug). Mirrors eq_curve / delay_trail. The mapping is ABSOLUTE — the
// line follows the cursor's level on the dB scale (robust to any v8ui frame
// quirk), not a relative start+delta.
function pointer_y(pe, fb) {
    if (!pe) return fb;
    if (pe.y !== undefined) return pe.y;
    if (pe.localY !== undefined) return pe.localY;
    if (pe.offsetY !== undefined) return pe.offsetY;
    if (pe.clientY !== undefined) return pe.clientY;
    return fb;
}
function pointer_buttons(pe, fb) {
    if (!pe) return fb;
    if (pe.buttons !== undefined) return pe.buttons;
    if (pe.button !== undefined) return pe.button === 2 ? 2 : 1;
    return fb;
}

function y_to_db(y) {
    return lo_db + ((plot_b() - y) / plot_h()) * (hi_db - lo_db);
}

function apply_ref(y) {
    if (isNaN(y)) return;
    ref_db = clamp(y_to_db(y), lo_db, Math.min(hi_db, 0.0));
    outlet(0, "threshold", Math.round(ref_db * 10) / 10);
    mgraphics.redraw();
}

function start_drag(y) {
    if (!INTERACTIVE) return;
    dragging = 1;
    // Arm only (don't apply on press) so the first click of a double-click
    // doesn't jump the line before reset_ref() runs. The drag sets it on move.
}

function drag_to(y, fine) {
    if (!dragging) return;
    apply_ref(y);
}

function end_drag() {
    if (!dragging) return;
    dragging = 0;
    mgraphics.redraw();
}

// Double-click resets the reference line to its default (RESET_DB).
function reset_ref() {
    if (!INTERACTIVE) return;
    ref_db = clamp(RESET_DB, lo_db, Math.min(hi_db, 0.0));
    outlet(0, "threshold", Math.round(ref_db * 10) / 10);
    mgraphics.redraw();
}

function onpointerdown(pe) { start_drag(pointer_y(pe, plot_b())); }
function onpointermove(pe) {
    if (dragging && ((pointer_buttons(pe, 1) & 1) !== 0)) {
        drag_to(pointer_y(pe, plot_b()), 0);
    } else if (dragging) {
        end_drag();
    }
}
function onpointerup(pe) { end_drag(); }
function onpointerleave(pe) { end_drag(); }
function ondblclick(x, y, but, cmd, shift, caps, opt, ctrl) { reset_ref(); }

function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { start_drag(y); }
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but) drag_to(y, shift);
    else end_drag();
}

function clear() {
    rebuild_ring();
    mgraphics.redraw();
}

function onresize(w, h) { mgraphics.redraw(); }
""")
