"""Compact stereo output level meter (reusable v8ui widget).

A small L/R peak meter for plugins that have an output but no meter (the EQs,
Pressure, Heat all lack one vs a premium EQ's prominent output meter). Two vertical
bars on a dB scale with a decaying peak-hold tick and a latching clip flag;
click to reset the peak-hold/clip. Display-only (no gestures leave the box).

Messages in (inlet 0):
    levels <l_lin> <r_lin>   live linear amplitudes (~30 Hz), 0..~2
    set_range <lo_db> <hi_db> override the dB scale (default -54 .. +6)
    reset_clip                clear the latched clip flag + peak-hold

Feed it from ``peakamp~ L`` / ``peakamp~ R`` -> ``snapshot~`` -> ``pak 0. 0.``
-> ``prepend levels``. No outlet (no-echo; a display-only meter).
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)
from .design_system import design_system_js
from .interaction_core import CLAMP_TERNARY_JS, ONRESIZE_JS

LEVEL_METER_INLETS = 1
LEVEL_METER_OUTLETS = 0

__all__ = ["LEVEL_METER_INLETS", "LEVEL_METER_OUTLETS", "level_meter_js"]


def level_meter_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    text_color="0.55, 0.58, 0.63, 1.0",
    lo_db=-54.0,
    hi_db=6.0,
):
    """Return JavaScript source for the stereo level-meter display."""
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return design_system_js() + "\n" + _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        text_color=text_color,
        lo_db=lo_db,
        hi_db=hi_db,
    ).replace("//__CLAMP_TERNARY__//", CLAMP_TERNARY_JS).replace(
        "//__ONRESIZE__//", ONRESIZE_JS
    )


_JS_TEMPLATE = Template("""\
// Level Meter Display - generated by m4l-builder
// ES5 compatible; display-only stereo peak meter.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 0;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var TEXT_CLR   = [$text_color];
var LO_DB = $lo_db;
var HI_DB = $hi_db;

var lvlL = 0.0, lvlR = 0.0;     // live amplitude (dB)
var peakL = -200.0, peakR = -200.0;  // decaying peak-hold (dB)
var clip = 0;                    // latched clip flag

//__CLAMP_TERNARY__//

function lin_to_db(x) {
    if (x <= 0.0000001) return -200.0;
    return 20.0 * Math.log(x) / Math.LN10;
}

function db_to_frac(db) {
    return clamp((db - LO_DB) / (HI_DB - LO_DB), 0.0, 1.0);
}

function plot_l() { return 4; }
function plot_t() { return 4; }
function plot_r() { return mgraphics.size[0] - 4; }
function plot_b() { return mgraphics.size[1] - 4; }
function plot_w() { return plot_r() - plot_l(); }
function plot_h() { return plot_b() - plot_t(); }

// Bar color by dB: green below -12, amber to -3, red near/over 0.
function bar_rgb(db) {
    if (db >= -1.5) return [0.92, 0.30, 0.26];
    if (db >= -9.0) return [0.92, 0.72, 0.28];
    return [0.32, 0.80, 0.52];
}

function draw_bar(x, w, db, peak_db) {
    var b = plot_b();
    var h = plot_h();
    // track
    mgraphics.set_source_rgba(BG_CLR[0], BG_CLR[1], BG_CLR[2], 0.5);
    mgraphics.rectangle(x, plot_t(), w, h);
    mgraphics.fill();
    // fill from bottom up to the level
    var f = db_to_frac(db);
    if (f > 0.0) {
        var c = bar_rgb(db);
        var fh = f * h;
        mgraphics.set_source_rgba(c[0], c[1], c[2], 0.92);
        mgraphics.rectangle(x, b - fh, w, fh);
        mgraphics.fill();
    }
    // peak-hold tick
    if (peak_db > LO_DB) {
        var py = b - db_to_frac(peak_db) * h;
        var pc = bar_rgb(peak_db);
        mgraphics.set_source_rgba(pc[0], pc[1], pc[2], 1.0);
        mgraphics.rectangle(x, py - 1.0, w, 1.5);
        mgraphics.fill();
    }
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();

    // 0 dB reference line.
    var zy = plot_b() - db_to_frac(0.0) * plot_h();
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.30);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(plot_l(), zy); mgraphics.line_to(plot_r(), zy); mgraphics.stroke();

    var gap = 3.0;
    var bw = (plot_w() - gap) / 2.0;
    draw_bar(plot_l(), bw, lvlL, peakL);
    draw_bar(plot_l() + bw + gap, bw, lvlR, peakR);

    // clip flag (latched red cap at the very top).
    if (clip) {
        mgraphics.set_source_rgba(0.95, 0.25, 0.22, 1.0);
        mgraphics.rectangle(plot_l(), plot_t(), plot_w(), 2.5);
        mgraphics.fill();
    }

    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();
}

// ── Messages ─────────────────────────────────────────────────────────
function levels(l, r) {
    if (l > 1.0 || r > 1.0) clip = 1;
    lvlL = lin_to_db(l);
    lvlR = lin_to_db(r);
    // peak-hold rises instantly, decays ~12 dB/s at 30 Hz (0.4 dB/frame).
    peakL = lvlL > peakL ? lvlL : peakL - 0.4;
    peakR = lvlR > peakR ? lvlR : peakR - 0.4;
    mgraphics.redraw();
}
function set_range(lo, hi) { LO_DB = lo; HI_DB = hi; mgraphics.redraw(); }
function reset_clip() { clip = 0; peakL = -200.0; peakR = -200.0; mgraphics.redraw(); }

// Click anywhere resets the latched clip flag + peak-hold (premium-EQ meter UX).
function onpointerdown(pe) { reset_clip(); }
function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { reset_clip(); }
//__ONRESIZE__//
""")
