"""LFO waveform display engine for jsui.

Generates JavaScript code that renders a live LFO waveform shape with a
sweeping playhead inside Max's jsui object using mgraphics.

Inlets:
    0 -- Shape index (int 0-4: sine, triangle, square, sawtooth, ramp)
    1 -- Phase position (float 0-1, sweeping playhead)
    2 -- Depth (float 0-1, amplitude scale)
"""

LFO_DISPLAY_INLETS = 3
LFO_DISPLAY_OUTLETS = 0


def lfo_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                   wave_color="0.45, 0.75, 0.65, 1.0",
                   playhead_color="1.0, 1.0, 1.0, 0.8",
                   grid_color="0.2, 0.2, 0.22, 0.5"):
    """Return JavaScript source for an LFO waveform display (Max jsui).

    Draws the current LFO shape (sine, triangle, square, sawtooth, ramp)
    with a vertical playhead line that sweeps across at the current phase.
    Depth scales the waveform amplitude around the center line.

    All color arguments are RGBA strings, e.g. ``"0.45, 0.75, 0.65, 1.0"``.

    Args:
        bg_color: Background color.
        wave_color: Waveform line color.
        playhead_color: Playhead vertical line color.
        grid_color: Center line and border grid color.

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    # Derive a fill color from the wave color
    wc = [s.strip() for s in wave_color.split(",")]
    wave_fill = wc[0] + ", " + wc[1] + ", " + wc[2] + ", 0.12"

    return (
        "// LFO Waveform Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 3;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var shape = 0;   // 0=sine, 1=tri, 2=square, 3=saw, 4=ramp\n"
        "var phase = 0.0; // 0-1 playhead position\n"
        "var depth = 1.0; // 0-1 amplitude scale\n"
        "\n"
        "// --- Constants ---\n"
        "var NUM_POINTS = 128;\n"
        "var PADDING = 4;\n"
        "var SINE = 0, TRI = 1, SQUARE = 2, SAW = 3, RAMP = 4;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_int(v) {\n"
        "    if (inlet === 0) {\n"
        "        shape = Math.max(0, Math.min(4, v));\n"
        "    } else if (inlet === 1) {\n"
        "        phase = Math.max(0, Math.min(1, v));\n"
        "    } else if (inlet === 2) {\n"
        "        depth = Math.max(0, Math.min(1, v));\n"
        "    }\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "function msg_float(v) {\n"
        "    msg_int(v);\n"
        "}\n"
        "\n"
        "// --- Waveform value at normalized position t (0-1) ---\n"
        "function wave_value(t, s) {\n"
        "    if (s === SINE) {\n"
        "        return Math.sin(t * Math.PI * 2);\n"
        "    } else if (s === TRI) {\n"
        "        if (t < 0.25) return t * 4;\n"
        "        if (t < 0.75) return 1 - (t - 0.25) * 4;\n"
        "        return -1 + (t - 0.75) * 4;\n"
        "    } else if (s === SQUARE) {\n"
        "        return t < 0.5 ? 1 : -1;\n"
        "    } else if (s === SAW) {\n"
        "        return 1 - t * 2;\n"
        "    } else if (s === RAMP) {\n"
        "        return -1 + t * 2;\n"
        "    }\n"
        "    return 0;\n"
        "}\n"
        "\n"
        "// --- Paint ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var px = PADDING;\n"
        "    var py = PADDING;\n"
        "    var pw = w - 2 * PADDING;\n"
        "    var ph = h - 2 * PADDING;\n"
        "    var center_y = py + ph * 0.5;\n"
        "\n"
        "    // Background\n"
        "    mgraphics.set_source_rgba(" + bg_color + ");\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Center line\n"
        "    mgraphics.set_source_rgba(" + grid_color + ");\n"
        "    mgraphics.set_line_width(1);\n"
        "    mgraphics.move_to(px, Math.round(center_y) + 0.5);\n"
        "    mgraphics.line_to(px + pw, Math.round(center_y) + 0.5);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Compute waveform points\n"
        "    var xs = [];\n"
        "    var ys = [];\n"
        "    var amp = depth * ph * 0.45;\n"
        "    for (var i = 0; i <= NUM_POINTS; i++) {\n"
        "        var t = i / NUM_POINTS;\n"
        "        var v = wave_value(t, shape);\n"
        "        xs.push(px + t * pw);\n"
        "        ys.push(center_y - v * amp);\n"
        "    }\n"
        "\n"
        "    // Fill between waveform and center\n"
        "    mgraphics.set_source_rgba(" + wave_fill + ");\n"
        "    mgraphics.move_to(xs[0], center_y);\n"
        "    for (var i = 0; i < xs.length; i++) {\n"
        "        mgraphics.line_to(xs[i], ys[i]);\n"
        "    }\n"
        "    mgraphics.line_to(xs[xs.length - 1], center_y);\n"
        "    mgraphics.close_path();\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Waveform stroke\n"
        "    mgraphics.set_source_rgba(" + wave_color + ");\n"
        "    mgraphics.set_line_width(1.5);\n"
        "    mgraphics.move_to(xs[0], ys[0]);\n"
        "    for (var i = 1; i < xs.length; i++) {\n"
        "        mgraphics.line_to(xs[i], ys[i]);\n"
        "    }\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Playhead\n"
        "    var head_x = px + phase * pw;\n"
        "    mgraphics.set_source_rgba(" + playhead_color + ");\n"
        "    mgraphics.set_line_width(1);\n"
        "    mgraphics.move_to(Math.round(head_x) + 0.5, py);\n"
        "    mgraphics.line_to(Math.round(head_x) + 0.5, py + ph);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Dot where playhead meets waveform\n"
        "    var head_v = wave_value(phase, shape);\n"
        "    var head_y = center_y - head_v * amp;\n"
        "    mgraphics.set_source_rgba(" + wave_color + ");\n"
        "    mgraphics.arc(head_x, head_y, 3, 0, Math.PI * 2);\n"
        "    mgraphics.fill();\n"
        "}\n"
    )
