"""Linear-phase EQ display engine with analyzer, HUD, and node editing.

Generates JavaScript (ES5) for Max's jsui object. This display is separate
from the regular parametric EQ engine so the flagship linear-phase product can
own its own visual language, quality badges, empty state, and chip-driven
workflow without regressing the existing Parametric EQ.

Communication uses 3 inlets and 4 outlets.

Inlet 0 messages:
    set_num_bands N
    set_band band_idx freq gain q type enabled slope solo dynamic_enabled dynamic_amount dynamic_current
    set_selected band_idx
    set_analyzer_enabled 0|1
    set_display_range 15
    set_quality_mode 0|1|2
    set_latency_ms float
    set_collision_mode 0|1

Inlet 1:
    sample rate float (typically from dspstate~ outlet 1)

Inlet 2:
    analyzer magnitude list in dB (typically -72..0 dB, log-spaced bins)

Outlet 0:
    selected_band band_idx
    add_band band_idx freq gain q type enabled slope solo
    delete_band band_idx
Outlet 1: band_freq band_idx freq
Outlet 2: band_gain band_idx gain
Outlet 3: band_q band_idx q

Mouse interaction:
    Click empty graph: add the first disabled band at cursor
    Click node: select band
    Ctrl/right-click node: open a context menu for type/slope/listen/dynamic/delete
    Drag node: adjust frequency and gain/Q
    Drag dynamic handle: adjust per-band dynamic range up/down
    Mouse wheel on node: adjust Q
    Alt-click node: disable that band
"""

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)


LINEAR_PHASE_EQ_DISPLAY_INLETS = 3
LINEAR_PHASE_EQ_DISPLAY_OUTLETS = 4


def linear_phase_eq_display_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    composite_color="0.95, 0.97, 1.0, 1.0",
    fill_color="0.42, 0.74, 0.94, 0.10",
    analyzer_fill_color="0.24, 0.84, 0.98, 0.13",
    analyzer_line_color="0.28, 0.88, 1.0, 0.48",
    analyzer_peak_color="0.92, 0.96, 1.0, 0.88",
    grid_color="0.19, 0.21, 0.25, 0.64",
    text_color="0.48, 0.52, 0.58, 1.0",
    zero_line_color="0.34, 0.37, 0.42, 0.94",
    badge_color="0.10, 0.12, 0.15, 0.94",
    badge_border_color="0.25, 0.28, 0.34, 1.0",
    show_dynamic=True,
    show_selection_readout=True,
):
    """Return JavaScript source for the flagship linear-phase EQ display."""
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        composite_color=composite_color,
        fill_color=fill_color,
        analyzer_fill_color=analyzer_fill_color,
        analyzer_line_color=analyzer_line_color,
        analyzer_peak_color=analyzer_peak_color,
        grid_color=grid_color,
        text_color=text_color,
        zero_line_color=zero_line_color,
        badge_color=badge_color,
        badge_border_color=badge_border_color,
        show_dynamic="1" if show_dynamic else "0",
        show_selection_readout="1" if show_selection_readout else "0",
    )


_JS_TEMPLATE = Template("""\
// Linear-Phase EQ Display - generated by m4l-builder
// ES5 compatible for Max jsui

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 3;
outlets = 4;

var BG_COLOR = [$bg_color];
var PANEL_CLR = [$panel_color];
var PLOT_BORDER_CLR = [$plot_border_color];
var COMPOSITE_CLR = [$composite_color];
var FILL_CLR = [$fill_color];
var ANALYZER_FILL_CLR = [$analyzer_fill_color];
var ANALYZER_LINE_CLR = [$analyzer_line_color];
var ANALYZER_PEAK_CLR = [$analyzer_peak_color];
var GRID_CLR = [$grid_color];
var TEXT_CLR = [$text_color];
var ZERO_LINE_CLR = [$zero_line_color];
var BADGE_CLR = [$badge_color];
var BADGE_BORDER_CLR = [$badge_border_color];
var SHOW_DYNAMIC = $show_dynamic;
var SHOW_SELECTION_READOUT = $show_selection_readout;

var BAND_COLORS = [
    [0.92, 0.36, 0.34, 1.0],
    [0.94, 0.62, 0.24, 1.0],
    [0.88, 0.84, 0.28, 1.0],
    [0.36, 0.80, 0.46, 1.0],
    [0.26, 0.84, 0.92, 1.0],
    [0.38, 0.56, 0.92, 1.0],
    [0.66, 0.46, 0.88, 1.0],
    [0.90, 0.42, 0.66, 1.0]
];

var TYPE_PEAK = 0;
var TYPE_LOSHELF = 1;
var TYPE_HISHELF = 2;
var TYPE_LOWCUT = 3;
var TYPE_HIGHCUT = 4;
var TYPE_NOTCH = 5;
var TYPE_BANDPASS = 6;

var TYPE_NAMES = ["Peak", "LShelf", "HShelf", "LCut", "HCut", "Notch", "BPass"];
var QUALITY_NAMES = ["Short", "Medium", "High"];
var ANALYZER_MODE_NAMES = ["Off", "Pre", "Post"];
var SLOPE_NAMES = ["12 dB", "24 dB", "48 dB"];
var RANGE_VALUES = [15.0];

var MIN_FREQ = 20;
var MAX_FREQ = 20000;
var MIN_GAIN = -30;
var MAX_GAIN = 30;
var GRAPH_FLOOR = -180;
var MIN_Q = 0.1;
var MAX_Q = 30.0;
var ANALYZER_MIN_DB = -72.0;
var ANALYZER_MAX_DB = 0.0;
var MAX_BANDS = 8;
var DEFAULT_FREQS = [30.0, 200.0, 1000.0, 5000.0, 3600.0, 7200.0, 12000.0, 18000.0];
var DEFAULT_GAINS = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];
var DEFAULT_QS = [0.707, 1.0, 1.0, 0.707, 1.0, 1.0, 1.0, 0.707];
var DEFAULT_TYPES = [TYPE_LOSHELF, TYPE_PEAK, TYPE_PEAK, TYPE_HISHELF, TYPE_PEAK, TYPE_PEAK, TYPE_PEAK, TYPE_HIGHCUT];
var DEFAULT_SLOPES = [0, 0, 0, 0, 0, 0, 0, 0];
var NUM_POINTS = 768;
var DEFAULT_SR = 48000.0;
var NODE_RADIUS = 9.0;
var NODE_RADIUS_SEL = 12.0;
var DYNAMIC_HANDLE_RADIUS = 6.0;
var DYNAMIC_HIT_RADIUS = 17.0;
var MAX_DYNAMIC_RANGE = 18.0;
var HIT_RADIUS = 22.0;
var LOG_MIN = Math.log(MIN_FREQ);
var LOG_MAX = Math.log(MAX_FREQ);
var LOG_RANGE = LOG_MAX - LOG_MIN;
var REDRAW_INTERVAL_MS = 33;

var MARGIN_LEFT = 16;
var MARGIN_RIGHT = 4;
var MARGIN_TOP = 8;
var MARGIN_BOTTOM = 9;

var sample_rate = DEFAULT_SR;
var analyzer_enabled = 1;
var analyzer_mode = 2;
var display_range = 15.0;
var quality_mode = 1;
var latency_ms = 0.0;
var collision_mode = 1;
var num_bands = MAX_BANDS;
var selected_band = -1;
var hover_band = -1;
var dragging = 0;
var drag_mode = 0;
var curve_dirty = 1;
var drag_start_freq = 0.0;
var drag_start_gain = 0.0;
var drag_start_q = 1.0;
var drag_start_dynamic = 0.0;
var context_menu_open = 0;
var context_menu_mode = 0;
var context_menu_band = -1;
var context_menu_x = 0;
var context_menu_y = 0;
var context_menu_hover = -1;
var last_pointer_press_ms = 0;
var last_pointer_press_x = -1000;
var last_pointer_press_y = -1000;
var suppress_next_click = 0;
var pending_context_click = 0;
var pending_context_x = -1000;
var pending_context_y = -1000;
var pending_context_ms = 0;

var analyzer_display = [];
var analyzer_peaks = [];
var analyzer_input = [];
var last_redraw_ms = 0;
var freq_table = [];
var bands = [];
var band_cache = [];
var band_curve_points = [];
var composite_curve_points = [];
var i;

for (i = 0; i < MAX_BANDS; i++) {
    bands[i] = {
        freq: DEFAULT_FREQS[i],
        gain: DEFAULT_GAINS[i],
        q: DEFAULT_QS[i],
        type: DEFAULT_TYPES[i],
        enabled: 0,
        slope: DEFAULT_SLOPES[i],
        solo: 0,
        dynamic_enabled: 0,
        dynamic_amount: 0.0,
        dynamic_current: 0.0
    };
    band_cache[i] = {
        freq: DEFAULT_FREQS[i],
        gain: DEFAULT_GAINS[i],
        q: DEFAULT_QS[i],
        type: DEFAULT_TYPES[i],
        enabled: 0,
        slope: DEFAULT_SLOPES[i],
        solo: 0,
        dynamic_enabled: 0,
        dynamic_amount: 0.0,
        dynamic_current: 0.0,
        uses_gain: 1,
        node_gain: DEFAULT_GAINS[i],
        coeffs: [1.0, 0.0, 0.0, 1.0, 0.0, 0.0]
    };
    band_curve_points[i] = [];
}

for (i = 0; i < NUM_POINTS; i++) {
    freq_table[i] = Math.exp(LOG_MIN + (i / Math.max(NUM_POINTS - 1, 1)) * LOG_RANGE);
}

function plot_left() { return MARGIN_LEFT; }
function plot_right() { return mgraphics.size[0] - MARGIN_RIGHT; }
function plot_top() { return MARGIN_TOP; }
function plot_bottom() { return mgraphics.size[1] - MARGIN_BOTTOM; }
function plot_w() { return plot_right() - plot_left(); }
function plot_h() { return plot_bottom() - plot_top(); }

function compact_mode() {
    return plot_h() <= 138 || plot_w() <= 620;
}

function circle_path(x, y, radius) {
    mgraphics.new_path();
    mgraphics.arc(x, y, radius, 0, Math.PI * 2.0);
}

function clamp(v, lo, hi) {
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

function safe_log10(v) {
    if (v <= 1.0e-20) v = 1.0e-20;
    return Math.log(v) / Math.log(10);
}

function freq_to_x(f) {
    var norm = (Math.log(clamp(f, MIN_FREQ, MAX_FREQ)) - LOG_MIN) / LOG_RANGE;
    return plot_left() + norm * plot_w();
}

function x_to_freq(x) {
    var norm = (x - plot_left()) / plot_w();
    norm = clamp(norm, 0.0, 1.0);
    return Math.exp(LOG_MIN + norm * LOG_RANGE);
}

function gain_to_y(g) {
    var hi = display_range;
    var lo = -display_range;
    var norm = (clamp(g, lo, hi) - hi) / (lo - hi);
    return plot_top() + norm * plot_h();
}

function graph_db_to_y(g) {
    var hi = display_range;
    var lo = -display_range;
    var span = Math.max(hi - lo, 1.0);
    var overflow;
    if (g < lo) {
        overflow = clamp((lo - g) / span, 0.0, 4.0);
        return plot_bottom() + overflow * plot_h() * 0.6;
    }
    if (g > hi) {
        overflow = clamp((g - hi) / span, 0.0, 2.0);
        return plot_top() - overflow * plot_h() * 0.45;
    }
    return gain_to_y(g);
}

function y_to_gain(y) {
    var norm = (y - plot_top()) / plot_h();
    norm = clamp(norm, 0.0, 1.0);
    var hi = display_range;
    var lo = -display_range;
    return hi + norm * (lo - hi);
}

function q_to_y(q) {
    var norm = (Math.log(clamp(q, MIN_Q, MAX_Q)) - Math.log(MIN_Q))
        / (Math.log(MAX_Q) - Math.log(MIN_Q));
    return plot_bottom() - norm * plot_h();
}

function y_to_q(y) {
    var norm = (plot_bottom() - y) / plot_h();
    norm = clamp(norm, 0.0, 1.0);
    return Math.exp(Math.log(MIN_Q) + norm * (Math.log(MAX_Q) - Math.log(MIN_Q)));
}

function analyzer_db_to_y(db) {
    var clamped = clamp(db, ANALYZER_MIN_DB, ANALYZER_MAX_DB);
    var norm = (clamped - ANALYZER_MIN_DB) / (ANALYZER_MAX_DB - ANALYZER_MIN_DB);
    return plot_bottom() - norm * plot_h();
}

function analyzer_bin_freq(idx, count) {
    var norm = idx / Math.max(count - 1, 1);
    return Math.exp(LOG_MIN + norm * LOG_RANGE);
}

function now_ms() {
    return new Date().getTime();
}

function request_redraw() {
    var now = now_ms();
    if (now - last_redraw_ms < REDRAW_INTERVAL_MS) return;
    last_redraw_ms = now;
    mgraphics.redraw();
}

function update_analyzer_data(values) {
    var attack;
    var incoming;
    var n = values.length;
    var next_value;
    var prev_value;
    var target;
    if (n < 2) {
        analyzer_display = [];
        analyzer_peaks = [];
        analyzer_input = [];
        request_redraw();
        return;
    }
    if (analyzer_display.length !== n) {
        analyzer_display = [];
        analyzer_peaks = [];
        analyzer_input = [];
        for (i = 0; i < n; i++) {
            analyzer_display[i] = ANALYZER_MIN_DB;
            analyzer_peaks[i] = ANALYZER_MIN_DB;
            analyzer_input[i] = ANALYZER_MIN_DB;
        }
    }
    for (i = 0; i < n; i++) {
        incoming = values[i];
        if (incoming !== incoming || incoming === undefined) incoming = ANALYZER_MIN_DB;
        incoming = clamp(incoming, ANALYZER_MIN_DB, ANALYZER_MAX_DB);
        analyzer_input[i] = incoming;
    }
    for (i = 0; i < n; i++) {
        prev_value = analyzer_input[i > 0 ? i - 1 : i];
        next_value = analyzer_input[i < n - 1 ? i + 1 : i];
        target = analyzer_input[i] * 0.58 + prev_value * 0.21 + next_value * 0.21;
        attack = target > analyzer_display[i] ? 0.22 : 0.10;
        analyzer_display[i] = analyzer_display[i] * (1.0 - attack) + target * attack;
        if (analyzer_display[i] > analyzer_peaks[i]) {
            analyzer_peaks[i] = analyzer_display[i];
        } else {
            analyzer_peaks[i] = Math.max(ANALYZER_MIN_DB, analyzer_peaks[i] - 0.18);
        }
    }
    request_redraw();
}

function band_uses_gain(type) {
    return type === TYPE_PEAK || type === TYPE_LOSHELF || type === TYPE_HISHELF;
}

function band_supports_dynamic(type) {
    return SHOW_DYNAMIC && band_uses_gain(type);
}

function band_node_gain(b) {
    if (band_uses_gain(b.type)) return clamp(b.gain, MIN_GAIN, MAX_GAIN);
    return 0.0;
}

function dynamic_handle_gain(cache) {
    return clamp(cache.node_gain + cache.dynamic_amount, MIN_GAIN, MAX_GAIN);
}

function slope_stage_count(slope) {
    if (slope === 2) return 4;
    if (slope === 1) return 2;
    return 1;
}

function find_free_band() {
    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].enabled) return i;
    }
    return -1;
}

function next_enabled_band(preferred_idx) {
    if (preferred_idx >= 0 && preferred_idx < num_bands && band_cache[preferred_idx].enabled) {
        return preferred_idx;
    }
    for (i = 0; i < num_bands; i++) {
        if (band_cache[i].enabled) return i;
    }
    return -1;
}

function delete_band_at(idx) {
    var next_idx;
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) return 0;
    if (!band_cache[idx].enabled) return 0;
    bands[idx].enabled = 0;
    bands[idx].solo = 0;
    bands[idx].dynamic_enabled = 0;
    bands[idx].dynamic_amount = 0.0;
    bands[idx].dynamic_current = 0.0;
    rebuild_band_cache();
    next_idx = next_enabled_band(idx === selected_band ? idx + 1 : selected_band);
    selected_band = next_idx;
    outlet(0, "delete_band", idx);
    outlet(0, "selected_band", next_idx);
    close_context_menu();
    dragging = 0;
    drag_mode = 0;
    mgraphics.redraw();
    return 1;
}

function is_cut_type(type) {
    return type === TYPE_LOWCUT || type === TYPE_HIGHCUT;
}

function close_context_menu() {
    context_menu_open = 0;
    context_menu_mode = 0;
    context_menu_band = -1;
    context_menu_hover = -1;
}

function open_context_menu(idx, x, y) {
    selected_band = idx;
    context_menu_open = 1;
    context_menu_mode = 0;
    context_menu_band = idx;
    context_menu_x = x;
    context_menu_y = y;
    context_menu_hover = -1;
}

function context_menu_items() {
    var band = band_cache[context_menu_band];
    var items;
    if (context_menu_mode === 1) {
        return ["Peak", "Low Shelf", "High Shelf", "Low Cut", "High Cut", "Notch", "Band Pass"];
    }
    if (context_menu_mode === 2) {
        return ["12 dB", "24 dB", "48 dB"];
    }
    items = [
        "Type  " + TYPE_NAMES[band.type],
        "Slope  " + (is_cut_type(band.type) ? SLOPE_NAMES[band.slope] : "--"),
        band.solo ? "Listen  On" : "Listen  Off",
        band.enabled ? "Disable" : "Enable",
        "Delete"
    ];
    if (SHOW_DYNAMIC) {
        items.unshift(
            band_supports_dynamic(band.type)
                ? (band.dynamic_enabled ? "Dynamic  On" : "Make Dynamic")
                : "Dynamic  --"
        );
    }
    return items;
}

function context_dynamic_index() { return SHOW_DYNAMIC ? 0 : -1; }
function context_type_index() { return SHOW_DYNAMIC ? 1 : 0; }
function context_slope_index() { return SHOW_DYNAMIC ? 2 : 1; }
function context_solo_index() { return SHOW_DYNAMIC ? 3 : 2; }
function context_enable_index() { return SHOW_DYNAMIC ? 4 : 3; }
function context_delete_index() { return SHOW_DYNAMIC ? 5 : 4; }

function context_menu_bounds() {
    var items = context_menu_items();
    var menu_w = context_menu_mode === 1 ? 92 : 92;
    var row_h = 14;
    var menu_h = items.length * row_h + 4;
    var x = clamp(context_menu_x, plot_left() + 4, plot_right() - menu_w - 4);
    var y = clamp(context_menu_y, plot_top() + 4, plot_bottom() - menu_h - 4);
    return [x, y, menu_w, menu_h, row_h, items];
}

function context_menu_hit(x, y) {
    var bounds = context_menu_bounds();
    var bx = bounds[0];
    var by = bounds[1];
    var bw = bounds[2];
    var bh = bounds[3];
    var row_h = bounds[4];
    if (x < bx || x > bx + bw || y < by || y > by + bh) return -1;
    return clamp(Math.floor((y - by - 2) / row_h), 0, bounds[5].length - 1);
}

function biquad_coeffs(type, freq, gain, q) {
    var sr = clamp(sample_rate, 22050.0, 384000.0);
    var fc = clamp(freq, MIN_FREQ, Math.min(MAX_FREQ, sr * 0.49));
    var Q = clamp(q, MIN_Q, MAX_Q);
    var w0 = 2.0 * Math.PI * fc / sr;
    var cosw0 = Math.cos(w0);
    var sinw0 = Math.sin(w0);
    var alpha = sinw0 / (2.0 * Q);
    var A = Math.pow(10.0, gain / 40.0);
    var shelf_s = clamp(Q, 0.1, 4.0);
    var shelf_alpha = sinw0 * 0.5 * Math.sqrt((A + 1.0 / A) * (1.0 / shelf_s - 1.0) + 2.0);
    var two_sqrt_A_alpha = 2.0 * Math.sqrt(A) * shelf_alpha;
    var b0, b1, b2, a0, a1, a2;

    switch (type) {
        case TYPE_PEAK:
            b0 = 1.0 + alpha * A;
            b1 = -2.0 * cosw0;
            b2 = 1.0 - alpha * A;
            a0 = 1.0 + alpha / A;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha / A;
            break;

        case TYPE_LOSHELF:
            b0 = A * ((A + 1.0) - (A - 1.0) * cosw0 + two_sqrt_A_alpha);
            b1 = 2.0 * A * ((A - 1.0) - (A + 1.0) * cosw0);
            b2 = A * ((A + 1.0) - (A - 1.0) * cosw0 - two_sqrt_A_alpha);
            a0 = (A + 1.0) + (A - 1.0) * cosw0 + two_sqrt_A_alpha;
            a1 = -2.0 * ((A - 1.0) + (A + 1.0) * cosw0);
            a2 = (A + 1.0) + (A - 1.0) * cosw0 - two_sqrt_A_alpha;
            break;

        case TYPE_HISHELF:
            b0 = A * ((A + 1.0) + (A - 1.0) * cosw0 + two_sqrt_A_alpha);
            b1 = -2.0 * A * ((A - 1.0) + (A + 1.0) * cosw0);
            b2 = A * ((A + 1.0) + (A - 1.0) * cosw0 - two_sqrt_A_alpha);
            a0 = (A + 1.0) - (A - 1.0) * cosw0 + two_sqrt_A_alpha;
            a1 = 2.0 * ((A - 1.0) - (A + 1.0) * cosw0);
            a2 = (A + 1.0) - (A - 1.0) * cosw0 - two_sqrt_A_alpha;
            break;

        case TYPE_LOWCUT:
            b0 = (1.0 + cosw0) * 0.5;
            b1 = -(1.0 + cosw0);
            b2 = (1.0 + cosw0) * 0.5;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_HIGHCUT:
            b0 = (1.0 - cosw0) * 0.5;
            b1 = 1.0 - cosw0;
            b2 = (1.0 - cosw0) * 0.5;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_NOTCH:
            b0 = 1.0;
            b1 = -2.0 * cosw0;
            b2 = 1.0;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        case TYPE_BANDPASS:
            b0 = alpha;
            b1 = 0.0;
            b2 = -alpha;
            a0 = 1.0 + alpha;
            a1 = -2.0 * cosw0;
            a2 = 1.0 - alpha;
            break;

        default:
            return [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
    }

    if (Math.abs(a0) < 1.0e-12) return [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
    return [b0 / a0, b1 / a0, b2 / a0, 1.0, a1 / a0, a2 / a0];
}

function response_db(coeffs, freq) {
    var sr = clamp(sample_rate, 22050.0, 384000.0);
    var fc = clamp(freq, MIN_FREQ, Math.min(MAX_FREQ, sr * 0.49));
    var w = 2.0 * Math.PI * fc / sr;
    var c1 = Math.cos(w);
    var s1 = Math.sin(w);
    var c2 = Math.cos(2.0 * w);
    var s2 = Math.sin(2.0 * w);
    var b0 = coeffs[0];
    var b1 = coeffs[1];
    var b2 = coeffs[2];
    var a0 = coeffs[3];
    var a1 = coeffs[4];
    var a2 = coeffs[5];
    var nr = b0 + b1 * c1 + b2 * c2;
    var ni = -b1 * s1 - b2 * s2;
    var dr = a0 + a1 * c1 + a2 * c2;
    var di = -a1 * s1 - a2 * s2;
    var num = nr * nr + ni * ni;
    var den = dr * dr + di * di;
    var mag = num / Math.max(den, 1.0e-20);
    var db = 10.0 * safe_log10(mag);
    if (db < GRAPH_FLOOR) db = GRAPH_FLOOR;
    if (db > MAX_GAIN) db = MAX_GAIN;
    return db;
}

function band_response_db(cache, freq) {
    var base_db;
    if (!cache.enabled) return 0.0;
    base_db = response_db(cache.coeffs, freq);
    if (cache.type === TYPE_LOWCUT || cache.type === TYPE_HIGHCUT) {
        return base_db * slope_stage_count(cache.slope);
    }
    return base_db;
}

function rebuild_band_cache() {
    for (i = 0; i < MAX_BANDS; i++) {
        band_cache[i].freq = clamp(bands[i].freq, MIN_FREQ, MAX_FREQ);
        band_cache[i].gain = clamp(bands[i].gain, MIN_GAIN, MAX_GAIN);
        band_cache[i].q = clamp(bands[i].q, MIN_Q, MAX_Q);
        band_cache[i].type = Math.floor(bands[i].type);
        band_cache[i].enabled = bands[i].enabled ? 1 : 0;
        band_cache[i].slope = Math.floor(clamp(bands[i].slope, 0, 2));
        band_cache[i].solo = bands[i].solo ? 1 : 0;
        band_cache[i].dynamic_enabled = bands[i].dynamic_enabled ? 1 : 0;
        band_cache[i].dynamic_amount = clamp(bands[i].dynamic_amount, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE);
        band_cache[i].dynamic_current = clamp(bands[i].dynamic_current, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE);
        band_cache[i].uses_gain = band_uses_gain(band_cache[i].type) ? 1 : 0;
        if (!band_supports_dynamic(band_cache[i].type)) {
            band_cache[i].dynamic_enabled = 0;
            band_cache[i].dynamic_amount = 0.0;
            band_cache[i].dynamic_current = 0.0;
        }
        band_cache[i].node_gain = band_node_gain(band_cache[i]);
        if (!band_cache[i].enabled) {
            band_cache[i].coeffs = [1.0, 0.0, 0.0, 1.0, 0.0, 0.0];
        } else if (band_cache[i].uses_gain) {
            band_cache[i].coeffs = biquad_coeffs(
                band_cache[i].type, band_cache[i].freq, band_cache[i].gain, band_cache[i].q
            );
        } else {
            band_cache[i].coeffs = biquad_coeffs(
                band_cache[i].type, band_cache[i].freq, 0.0, band_cache[i].q
            );
        }
    }
    curve_dirty = 1;
}

function enabled_band_count() {
    var count = 0;
    for (i = 0; i < num_bands; i++) {
        if (band_cache[i].enabled) count++;
    }
    return count;
}

var FREQ_LINES = [20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000];
var FREQ_LABELS = ["20", "50", "100", "200", "500", "1k", "2k", "5k", "10k", "20k"];

function gain_grid_step() {
    return 3.0;
}

function gain_grid_values() {
    var vals = [];
    var step = gain_grid_step();
    var g = -display_range;
    while (g <= display_range + 0.0001) {
        vals.push(Math.round(g * 100.0) / 100.0);
        g += step;
    }
    return vals;
}

function current_range_index() {
    return 0;
}

function draw_grid() {
    var gain_lines = gain_grid_values();
    var x, y, label;

    mgraphics.set_line_width(0.5);
    for (i = 0; i < FREQ_LINES.length; i++) {
        x = freq_to_x(FREQ_LINES[i]);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(x, plot_top());
        mgraphics.line_to(x, plot_bottom());
        mgraphics.stroke();

        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.select_font_face("Arial");
        mgraphics.set_font_size(6.1);
        label = FREQ_LABELS[i];
        mgraphics.move_to(x - 6, plot_bottom() + 9);
        mgraphics.show_text(label);
    }

    for (i = 0; i < gain_lines.length; i++) {
        y = gain_to_y(gain_lines[i]);
        mgraphics.set_source_rgba(Math.abs(gain_lines[i]) < 0.0001 ? ZERO_LINE_CLR : GRID_CLR);
        mgraphics.move_to(plot_left(), y);
        mgraphics.line_to(plot_right(), y);
        mgraphics.stroke();

        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.select_font_face("Arial");
        mgraphics.set_font_size(6.1);
        label = Math.abs(gain_lines[i]) < 0.0001 ? "0" : Math.round(gain_lines[i]).toString();
        mgraphics.move_to(2, y + 3);
        mgraphics.show_text(label);
    }
}

function draw_analyzer() {
    var n, x, y, peak_db;
    if (!analyzer_enabled) return;
    n = analyzer_display.length;
    if (n < 2) return;
    peak_db = ANALYZER_MIN_DB;
    for (i = 0; i < n; i++) {
        if (analyzer_display[i] > peak_db) peak_db = analyzer_display[i];
    }
    if (peak_db <= ANALYZER_MIN_DB + 1.0) return;

    mgraphics.set_source_rgba(ANALYZER_FILL_CLR);
    mgraphics.move_to(freq_to_x(analyzer_bin_freq(0, n)), plot_bottom());
    for (i = 0; i < n; i++) {
        x = freq_to_x(analyzer_bin_freq(i, n));
        y = analyzer_db_to_y(analyzer_display[i]);
        mgraphics.line_to(x, y);
    }
    mgraphics.line_to(freq_to_x(analyzer_bin_freq(n - 1, n)), plot_bottom());
    mgraphics.close_path();
    mgraphics.fill();

    mgraphics.set_source_rgba(ANALYZER_LINE_CLR);
    mgraphics.set_line_width(2.0);
    for (i = 0; i < n; i++) {
        x = freq_to_x(analyzer_bin_freq(i, n));
        y = analyzer_db_to_y(analyzer_display[i]);
        if (i === 0) mgraphics.move_to(x, y);
        else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    mgraphics.set_source_rgba(ANALYZER_PEAK_CLR);
    for (i = 0; i < n; i++) {
        x = freq_to_x(analyzer_bin_freq(i, n));
        y = analyzer_db_to_y(analyzer_peaks[i]);
        if (analyzer_peaks[i] > ANALYZER_MIN_DB + 1.0) {
            mgraphics.rectangle(x - 1.0, y - 0.5, 2.0, 2.0);
            mgraphics.fill();
        }
    }
}

function draw_empty_state() {
    var cx = plot_left() + plot_w() * 0.5;
    var cy = plot_top() + plot_h() * 0.5;

    mgraphics.set_source_rgba(0.16, 0.20, 0.25, 0.94);
    circle_path(cx, cy - 9, 13);
    mgraphics.fill_preserve();
    mgraphics.set_source_rgba(0.32, 0.54, 0.74, 0.92);
    mgraphics.set_line_width(1.1);
    mgraphics.stroke();

    mgraphics.set_source_rgba(0.86, 0.92, 0.98, 0.96);
    mgraphics.set_line_width(1.6);
    mgraphics.move_to(cx, cy - 17);
    mgraphics.line_to(cx, cy - 1);
    mgraphics.move_to(cx - 8, cy - 9);
    mgraphics.line_to(cx + 8, cy - 9);
    mgraphics.stroke();

    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(10.5);
    mgraphics.set_source_rgba(0.82, 0.86, 0.92, 0.88);
    mgraphics.move_to(cx - 52, cy + 16);
    mgraphics.show_text("No bands enabled");

    mgraphics.set_font_size(7.2);
    mgraphics.set_source_rgba(0.55, 0.61, 0.68, 0.92);
    mgraphics.move_to(cx - 52, cy + 30);
    mgraphics.show_text("Enable a node or click to place one.");
}

function draw_band_curves() {
    var points;
    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].enabled) continue;
        points = band_curve_points[i];
        if (!points || points.length < 2) continue;
        mgraphics.set_source_rgba(
            BAND_COLORS[i][0],
            BAND_COLORS[i][1],
            BAND_COLORS[i][2],
            selected_band === i ? 0.24 : 0.10
        );
        mgraphics.set_line_width(selected_band === i ? 1.2 : 0.8);
        for (var p = 0; p < points.length; p++) {
            if (p === 0) mgraphics.move_to(points[p][0], points[p][1]);
            else mgraphics.line_to(points[p][0], points[p][1]);
        }
        mgraphics.stroke();
    }
}

function draw_composite_curve() {
    var points = composite_curve_points;
    if (!points || points.length < 2) return;

    mgraphics.set_source_rgba(FILL_CLR);
    mgraphics.move_to(points[0][0], gain_to_y(0.0));
    for (i = 0; i < points.length; i++) {
        mgraphics.line_to(points[i][0], points[i][1]);
    }
    mgraphics.line_to(points[points.length - 1][0], gain_to_y(0.0));
    mgraphics.close_path();
    mgraphics.fill();

    mgraphics.set_source_rgba(COMPOSITE_CLR);
    mgraphics.set_line_width(1.35);
    for (i = 0; i < points.length; i++) {
        if (i === 0) mgraphics.move_to(points[i][0], points[i][1]);
        else mgraphics.line_to(points[i][0], points[i][1]);
    }
    mgraphics.stroke();
}

function label_overlaps(bounds, used) {
    var j, b;
    if (!collision_mode) return 0;
    for (j = 0; j < used.length; j++) {
        b = used[j];
        if (bounds[0] < b[2] && bounds[2] > b[0] && bounds[1] < b[3] && bounds[3] > b[1]) {
            return 1;
        }
    }
    return 0;
}

function draw_nodes() {
    var used_labels = [];
    var compact = compact_mode();
    var x, y, size, radius, color, label, bounds;
    var enabled_alpha, ring_alpha, fill_alpha, text_alpha, cross_alpha;
    var center_alpha, shell_alpha, halo_alpha;
    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i]) continue;
        x = freq_to_x(band_cache[i].freq);
        y = gain_to_y(band_cache[i].uses_gain ? band_cache[i].node_gain : 0.0);
        size = compact
            ? (selected_band === i ? 17.2 : (hover_band === i ? 15.4 : 14.2))
            : (selected_band === i ? 30.0 : (hover_band === i ? 27.0 : 24.0));
        radius = size * 0.5;
        color = BAND_COLORS[i];
        enabled_alpha = band_cache[i].enabled ? 1.0 : 0.36;
        ring_alpha = band_cache[i].enabled ? 0.98 : 0.52;
        fill_alpha = band_cache[i].enabled ? (compact ? 0.94 : 0.98) : (compact ? 0.20 : 0.16);
        text_alpha = band_cache[i].enabled ? 0.96 : 0.54;
        cross_alpha = band_cache[i].enabled ? 0.0 : 0.34;
        center_alpha = band_cache[i].enabled ? (compact ? 0.78 : 0.0) : 0.0;
        shell_alpha = band_cache[i].enabled ? (selected_band === i ? 0.82 : 0.60) : 0.28;
        halo_alpha = band_cache[i].enabled
            ? (selected_band === i ? (compact ? 0.22 : 0.18) : (compact ? 0.14 : 0.12))
            : (selected_band === i ? 0.10 : 0.06);

        if (selected_band === i || hover_band === i) {
            mgraphics.set_source_rgba(
                color[0], color[1], color[2],
                (selected_band === i ? 0.18 : 0.12) * enabled_alpha
            );
            mgraphics.set_line_width(1.0);
            mgraphics.move_to(x, plot_top());
            mgraphics.line_to(x, plot_bottom());
            mgraphics.stroke();
            if (band_cache[i].uses_gain && band_cache[i].enabled) {
                mgraphics.move_to(plot_left(), y);
                mgraphics.line_to(plot_right(), y);
                mgraphics.stroke();
            }

            mgraphics.set_source_rgba(
                color[0], color[1], color[2],
                halo_alpha
            );
            circle_path(x, y, radius + (compact ? 6.8 : 5.5));
            mgraphics.fill();
        }

        mgraphics.set_source_rgba(0.03, 0.04, 0.05, shell_alpha);
        circle_path(x, y, radius + (compact ? 1.9 : 1.2));
        mgraphics.fill();

        mgraphics.set_source_rgba(color[0], color[1], color[2], fill_alpha);
        circle_path(x, y, radius);
        mgraphics.fill();

        mgraphics.set_source_rgba(color[0], color[1], color[2], ring_alpha);
        mgraphics.set_line_width(compact ? (selected_band === i ? 2.5 : 1.9) : (selected_band === i ? 3.6 : 2.8));
        circle_path(x, y, compact ? radius : (radius - 0.8));
        mgraphics.stroke();

        if (!band_cache[i].enabled) {
            mgraphics.set_source_rgba(color[0], color[1], color[2], cross_alpha);
            mgraphics.set_line_width(1.3);
            mgraphics.move_to(x - radius * 0.52, y - radius * 0.52);
            mgraphics.line_to(x + radius * 0.52, y + radius * 0.52);
            mgraphics.move_to(x + radius * 0.52, y - radius * 0.52);
            mgraphics.line_to(x - radius * 0.52, y + radius * 0.52);
            mgraphics.stroke();
        }

        if (center_alpha > 0.0) {
            mgraphics.set_source_rgba(1.0, 1.0, 1.0, center_alpha);
            circle_path(x, y, compact ? 1.9 : 2.3);
            mgraphics.fill();
        }

        if (compact) {
            mgraphics.set_source_rgba(1.0, 1.0, 1.0, band_cache[i].enabled ? 0.88 : 0.42);
            mgraphics.select_font_face("Arial");
            mgraphics.set_font_size(selected_band === i ? 8.8 : 7.8);
            mgraphics.move_to(x + radius + 3.0, y - radius + 1.4);
            mgraphics.show_text("" + (i + 1));
        } else {
            mgraphics.set_source_rgba(0.05, 0.06, 0.08, text_alpha);
            mgraphics.select_font_face("Arial Bold");
            mgraphics.set_font_size(selected_band === i ? 13.0 : 11.4);
            mgraphics.move_to(x - (selected_band === i ? 4.8 : 4.0), y + 5.8);
            mgraphics.show_text("" + (i + 1));
        }

        label = TYPE_NAMES[band_cache[i].type];
        bounds = [x + radius + 8, y + 2, x + radius + 62, y + 14];
        if ((!compact && !label_overlaps(bounds, used_labels)) || (!compact && (selected_band === i || hover_band === i))) {
            used_labels.push(bounds);
            mgraphics.select_font_face("Arial");
            mgraphics.set_font_size(7.0);
            mgraphics.set_source_rgba(
                color[0], color[1], color[2],
                (selected_band === i ? 0.90 : 0.68) * (band_cache[i].enabled ? 1.0 : 0.65)
            );
            mgraphics.move_to(bounds[0], bounds[3]);
            mgraphics.show_text(label);
        }
    }
}

function draw_dynamic_handles() {
    var compact = compact_mode();
    var x, base_y, target_y, live_y, color, alpha;
    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].enabled) continue;
        if (!band_cache[i].dynamic_enabled) continue;
        if (!band_supports_dynamic(band_cache[i].type)) continue;

        x = freq_to_x(band_cache[i].freq);
        base_y = gain_to_y(band_cache[i].node_gain);
        target_y = gain_to_y(dynamic_handle_gain(band_cache[i]));
        live_y = gain_to_y(clamp(band_cache[i].node_gain + band_cache[i].dynamic_current, MIN_GAIN, MAX_GAIN));
        color = BAND_COLORS[i];
        alpha = selected_band === i ? 0.92 : 0.58;

        mgraphics.set_source_rgba(color[0], color[1], color[2], selected_band === i ? 0.38 : 0.24);
        mgraphics.set_line_width(compact ? (selected_band === i ? 1.9 : 1.2) : (selected_band === i ? 2.2 : 1.5));
        mgraphics.move_to(x, base_y);
        mgraphics.line_to(x, target_y);
        mgraphics.stroke();

        mgraphics.set_source_rgba(color[0], color[1], color[2], alpha);
        mgraphics.set_line_width(compact ? (selected_band === i ? 1.8 : 1.2) : 1.6);
        mgraphics.rectangle(
            x - (compact ? 3.8 : 4.5),
            target_y - (compact ? 3.8 : 4.5),
            compact ? 7.6 : 9.0,
            compact ? 7.6 : 9.0
        );
        mgraphics.stroke();

        if (compact) {
            mgraphics.set_source_rgba(color[0], color[1], color[2], selected_band === i ? 0.30 : 0.18);
            mgraphics.rectangle(x - 5.2, target_y - 5.2, 10.4, 10.4);
            mgraphics.fill();
        }

        mgraphics.set_source_rgba(color[0], color[1], color[2], selected_band === i ? 0.94 : 0.74);
        circle_path(x, live_y, compact ? (DYNAMIC_HANDLE_RADIUS - 0.6) : DYNAMIC_HANDLE_RADIUS);
        mgraphics.fill();
    }
}

function ensure_curve_cache() {
    var p, b, freq, x, total, db;
    if (!curve_dirty) return;

    composite_curve_points = [];
    for (b = 0; b < MAX_BANDS; b++) {
        band_curve_points[b] = [];
    }

    for (p = 0; p < NUM_POINTS; p++) {
        freq = freq_table[p];
        x = freq_to_x(freq);
        total = 0.0;

        for (b = 0; b < num_bands; b++) {
            if (!band_cache[b].enabled) continue;
            db = band_response_db(band_cache[b], freq);
            total += db;
            band_curve_points[b].push([x, graph_db_to_y(db)]);
        }

        composite_curve_points.push([x, graph_db_to_y(total)]);
    }

    curve_dirty = 0;
}

function tooltip_band_idx() {
    if (context_menu_open) return -1;
    if (hover_band >= 0 && hover_band < num_bands) return hover_band;
    if (dragging && selected_band >= 0 && selected_band < num_bands) {
        return selected_band;
    }
    return -1;
}

function tooltip_value_text(band) {
    if (band.uses_gain) {
        return format_freq(band.freq)
            + "   "
            + format_gain(band.gain)
            + (band.dynamic_enabled ? "   Dyn " + format_dynamic(band.dynamic_amount) : "")
            + "   Q " + format_q(band.q);
    }
    return format_freq(band.freq) + "   " + SLOPE_NAMES[band.slope] + "   Q " + format_q(band.q);
}

function draw_tooltip() {
    var idx = tooltip_band_idx();
    var band, x, y, w, h, tx, ty;
    if (idx < 0) return;

    band = band_cache[idx];
    x = freq_to_x(band.freq) + 10;
    y = gain_to_y(band.node_gain) - 34;
    w = 122;
    h = 26;

    if (x + w > plot_right() - 2) x = plot_right() - w - 2;
    if (y < plot_top() + 2) y = gain_to_y(band.node_gain) + 10;
    if (y + h > plot_bottom() - 2) y = plot_bottom() - h - 2;

    mgraphics.set_source_rgba(0.05, 0.07, 0.09, 0.96);
    mgraphics.rectangle_rounded(x, y, w, h, 5, 5);
    mgraphics.fill_preserve();
    mgraphics.set_source_rgba(BAND_COLORS[idx][0], BAND_COLORS[idx][1], BAND_COLORS[idx][2], 0.72);
    mgraphics.set_line_width(1.0);
    mgraphics.stroke();

    tx = x + 7;
    ty = y + 10;

    mgraphics.select_font_face("Arial Bold");
    mgraphics.set_font_size(6.8);
    mgraphics.set_source_rgba(0.94, 0.97, 1.0, 0.96);
    mgraphics.move_to(tx, ty);
    mgraphics.show_text("B" + (idx + 1) + "  " + TYPE_NAMES[band.type]);

    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(6.2);
    mgraphics.set_source_rgba(0.72, 0.78, 0.86, 0.96);
    mgraphics.move_to(tx, ty + 10);
    mgraphics.show_text(tooltip_value_text(band));
}

function draw_context_menu() {
    var bounds, x, y, w, h, row_h, items, i, row_y, color, band;
    if (!context_menu_open || context_menu_band < 0 || context_menu_band >= num_bands) return;

    bounds = context_menu_bounds();
    x = bounds[0];
    y = bounds[1];
    w = bounds[2];
    h = bounds[3];
    row_h = bounds[4];
    items = bounds[5];
    band = band_cache[context_menu_band];
    color = BAND_COLORS[context_menu_band];

    mgraphics.set_source_rgba(0.06, 0.08, 0.10, 0.98);
    mgraphics.rectangle_rounded(x, y, w, h, 6, 6);
    mgraphics.fill_preserve();
    mgraphics.set_source_rgba(color[0], color[1], color[2], 0.62);
    mgraphics.set_line_width(1.0);
    mgraphics.stroke();

    for (i = 0; i < items.length; i++) {
        row_y = y + 2 + i * row_h;
        if (i === context_menu_hover) {
            mgraphics.set_source_rgba(color[0], color[1], color[2], 0.24);
            mgraphics.rectangle_rounded(x + 2, row_y, w - 4, row_h - 1, 4, 4);
            mgraphics.fill();
        }

        mgraphics.select_font_face("Arial");
        mgraphics.set_font_size(7);
        mgraphics.set_source_rgba(
            0.92,
            0.95,
            0.99,
            (context_menu_mode === 0 && (
                (SHOW_DYNAMIC && i === context_dynamic_index() && !band_supports_dynamic(band.type)) ||
                (i === context_slope_index() && !is_cut_type(band.type))
            )) ? 0.34 : 0.94
        );
        mgraphics.move_to(x + 7, row_y + 10);
        mgraphics.show_text(items[i]);
    }
}

function draw_badge(x, y, w, h, label, value) {
    mgraphics.set_source_rgba(BADGE_CLR);
    mgraphics.rectangle_rounded(x, y, w, h, 5, 5);
    mgraphics.fill_preserve();
    mgraphics.set_source_rgba(BADGE_BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.stroke();

    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(6);
    mgraphics.set_source_rgba(0.55, 0.60, 0.67, 0.96);
    mgraphics.move_to(x + 6, y + 11);
    mgraphics.show_text(label);

    mgraphics.select_font_face("Arial Bold");
    mgraphics.set_font_size(6.5);
    mgraphics.set_source_rgba(0.95, 0.97, 1.0, 0.96);
    mgraphics.move_to(x + w * 0.48, y + 11);
    mgraphics.show_text(value);
}

function hud_badges() {
    var badge_x = plot_left() + 6;
    var info_y = plot_top() + 5;
    return [
        {key: "quality", x: badge_x, y: info_y, w: 58, h: 14, label: "Q", value: QUALITY_NAMES[quality_mode]},
        {key: "latency", x: badge_x + 62, y: info_y, w: 62, h: 14, label: "LAT", value: latency_ms.toFixed(1) + " ms"},
        {key: "analyzer", x: badge_x + 128, y: info_y, w: 56, h: 14, label: "AN", value: ANALYZER_MODE_NAMES[analyzer_mode]},
        {key: "range", x: badge_x + 188, y: info_y, w: 54, h: 14, label: "RNG", value: display_range.toFixed(0) + " dB"}
    ];
}

function hud_badge_hit(x, y) {
    var badges = hud_badges();
    var badge;
    for (i = 0; i < badges.length; i++) {
        badge = badges[i];
        if (x >= badge.x && x <= badge.x + badge.w && y >= badge.y && y <= badge.y + badge.h) {
            return badge.key;
        }
    }
    return "";
}

function cycle_hud_badge(key, reverse) {
    var idx;
    if (key === "quality") {
        quality_mode = reverse ? (quality_mode + QUALITY_NAMES.length - 1) % QUALITY_NAMES.length
            : (quality_mode + 1) % QUALITY_NAMES.length;
        outlet(0, "hud_quality", quality_mode);
        mgraphics.redraw();
        return 1;
    }
    if (key === "analyzer") {
        analyzer_mode = reverse ? (analyzer_mode + ANALYZER_MODE_NAMES.length - 1) % ANALYZER_MODE_NAMES.length
            : (analyzer_mode + 1) % ANALYZER_MODE_NAMES.length;
        analyzer_enabled = analyzer_mode > 0 ? 1 : 0;
        outlet(0, "hud_analyzer", analyzer_mode);
        mgraphics.redraw();
        return 1;
    }
    if (key === "range") {
        display_range = 15.0;
        curve_dirty = 1;
        outlet(0, "hud_range", 0);
        mgraphics.redraw();
        return 1;
    }
    return 0;
}

function format_freq(freq) {
    if (freq >= 1000.0) return (Math.round(freq / 10.0) / 100.0).toFixed(2) + " kHz";
    return Math.round(freq) + " Hz";
}

function format_gain(gain) {
    var prefix = gain > 0 ? "+" : "";
    return prefix + (Math.round(gain * 10.0) / 10.0).toFixed(1) + " dB";
}

function format_q(q) {
    return (Math.round(q * 100.0) / 100.0).toFixed(2);
}

function format_dynamic(dynamic_amount) {
    var prefix = dynamic_amount > 0 ? "+" : "";
    return prefix + (Math.round(dynamic_amount * 10.0) / 10.0).toFixed(1) + " dB";
}

function draw_hud() {
    var badges = hud_badges();
    var title, subtitle;
    var badge;

    for (i = 0; i < badges.length; i++) {
        badge = badges[i];
        draw_badge(badge.x, badge.y, badge.w, badge.h, badge.label, badge.value);
    }

    if (!SHOW_SELECTION_READOUT) return;

    if (selected_band < 0 || selected_band >= num_bands) {
        mgraphics.select_font_face("Arial");
        mgraphics.set_font_size(6.5);
        mgraphics.set_source_rgba(0.60, 0.65, 0.71, 0.90);
        mgraphics.move_to(plot_right() - 128, plot_top() + 12);
        mgraphics.show_text(enabled_band_count() > 0 ? "Select a node." : "Awaiting first band");
        return;
    }

    title = "Band " + (selected_band + 1) + "  " + TYPE_NAMES[band_cache[selected_band].type];
    subtitle = format_freq(band_cache[selected_band].freq)
        + "   "
        + (band_cache[selected_band].uses_gain ? format_gain(band_cache[selected_band].gain) : SLOPE_NAMES[band_cache[selected_band].slope])
        + "   Q " + format_q(band_cache[selected_band].q)
        + (band_cache[selected_band].dynamic_enabled ? "   Dyn " + format_dynamic(band_cache[selected_band].dynamic_amount) : "")
        + (band_cache[selected_band].enabled ? "" : "   Bypassed");

    mgraphics.select_font_face("Arial Bold");
    mgraphics.set_font_size(8.5);
    mgraphics.set_source_rgba(
        BAND_COLORS[selected_band][0],
        BAND_COLORS[selected_band][1],
        BAND_COLORS[selected_band][2],
        band_cache[selected_band].enabled ? 0.98 : 0.62
    );
    mgraphics.move_to(plot_right() - 170, plot_top() + 12);
    mgraphics.show_text(title);

    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(6.5);
    mgraphics.set_source_rgba(0.76, 0.81, 0.87, 0.94);
    mgraphics.move_to(plot_right() - 170, plot_top() + 22);
    mgraphics.show_text(subtitle);
}

function paint() {
    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, mgraphics.size[0], mgraphics.size[1]);
    mgraphics.fill();

    mgraphics.set_source_rgba(BG_COLOR);
    mgraphics.rectangle(plot_left(), plot_top(), plot_w(), plot_h());
    mgraphics.fill_preserve();
    mgraphics.set_source_rgba(PLOT_BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.stroke();

    draw_grid();
    draw_analyzer();
    if (enabled_band_count() < 1) {
        draw_empty_state();
    } else {
        ensure_curve_cache();
        draw_band_curves();
        draw_composite_curve();
    }
    if (enabled_band_count() >= 1) {
        draw_dynamic_handles();
    }
    if (num_bands > 0) {
        draw_nodes();
        draw_tooltip();
    }
    draw_hud();
    draw_context_menu();
}

function hit_test(x, y) {
    var dx, dy, node_x, node_y;
    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i]) continue;
        node_x = freq_to_x(band_cache[i].freq);
        node_y = gain_to_y(band_cache[i].node_gain);
        dx = x - node_x;
        dy = y - node_y;
        if ((dx * dx + dy * dy) <= (HIT_RADIUS * HIT_RADIUS)) return i;
    }
    return -1;
}

function dynamic_hit_test(x, y) {
    var dx, dy, node_x, node_y, target_gain;
    for (i = 0; i < num_bands; i++) {
        if (!band_cache[i].enabled) continue;
        if (!band_cache[i].dynamic_enabled) continue;
        if (!band_supports_dynamic(band_cache[i].type)) continue;
        node_x = freq_to_x(band_cache[i].freq);
        target_gain = dynamic_handle_gain(band_cache[i]);
        node_y = gain_to_y(target_gain);
        dx = x - node_x;
        dy = y - node_y;
        if ((dx * dx + dy * dy) <= (DYNAMIC_HIT_RADIUS * DYNAMIC_HIT_RADIUS)) return i;
    }
    return -1;
}

function point_in_plot(x, y) {
    return x >= plot_left() && x <= plot_right() && y >= plot_top() && y <= plot_bottom();
}

function create_band_at(x, y) {
    var created_idx;
    var created_freq;
    var created_gain;
    if (!point_in_plot(x, y)) return 0;
    created_idx = find_free_band();
    if (created_idx < 0) return 0;
    created_freq = clamp(x_to_freq(x), MIN_FREQ, MAX_FREQ);
    created_gain = clamp(y_to_gain(y), MIN_GAIN, MAX_GAIN);
    created_gain = Math.round(created_gain * 10.0) / 10.0;
    bands[created_idx].freq = created_freq;
    bands[created_idx].gain = created_gain;
    bands[created_idx].q = 1.0;
    bands[created_idx].type = TYPE_PEAK;
    bands[created_idx].enabled = 1;
    bands[created_idx].slope = 0;
    bands[created_idx].solo = 0;
    bands[created_idx].dynamic_enabled = 0;
    bands[created_idx].dynamic_amount = 0.0;
    bands[created_idx].dynamic_current = 0.0;
    selected_band = created_idx;
    rebuild_band_cache();
    outlet(0, "add_band", created_idx, created_freq, created_gain, 1.0, TYPE_PEAK, 1, 0, 0, 0, 0.0, 0.0);
    outlet(0, "selected_band", created_idx);
    mgraphics.redraw();
    return 1;
}

function set_band(idx, freq, gain, q, type, enabled, slope, solo, dynamic_enabled, dynamic_amount, dynamic_current) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= MAX_BANDS) return;
    bands[idx].freq = freq;
    bands[idx].gain = gain;
    bands[idx].q = q;
    bands[idx].type = Math.floor(type);
    bands[idx].enabled = enabled ? 1 : 0;
    bands[idx].slope = slope === undefined ? 0 : Math.floor(slope);
    bands[idx].solo = solo ? 1 : 0;
    bands[idx].dynamic_enabled = dynamic_enabled ? 1 : 0;
    bands[idx].dynamic_amount = dynamic_amount === undefined ? 0.0 : clamp(dynamic_amount, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE);
    bands[idx].dynamic_current = dynamic_current === undefined ? 0.0 : clamp(dynamic_current, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE);
    if (context_menu_open && context_menu_band === idx && !bands[idx].enabled) {
        close_context_menu();
    }
    rebuild_band_cache();
    mgraphics.redraw();
}

function set_num_bands(n) {
    n = Math.floor(n);
    if (n < 0) n = 0;
    if (n > MAX_BANDS) n = MAX_BANDS;
    num_bands = n;
    if (selected_band >= num_bands) selected_band = -1;
    rebuild_band_cache();
    mgraphics.redraw();
}

function set_selected(idx) {
    idx = Math.floor(idx);
    if (idx < 0 || idx >= num_bands) selected_band = -1;
    else selected_band = idx;
    mgraphics.redraw();
}

function set_analyzer_enabled(v) {
    analyzer_enabled = v ? 1 : 0;
    if (!analyzer_enabled) analyzer_mode = 0;
    else if (analyzer_mode === 0) analyzer_mode = 2;
    mgraphics.redraw();
}

function set_analyzer_mode(v) {
    analyzer_mode = Math.floor(clamp(v, 0, ANALYZER_MODE_NAMES.length - 1));
    analyzer_enabled = analyzer_mode > 0 ? 1 : 0;
    mgraphics.redraw();
}

function set_display_range(v) {
    display_range = 15.0;
    curve_dirty = 1;
    mgraphics.redraw();
}

function set_quality_mode(v) {
    quality_mode = Math.floor(clamp(v, 0, 2));
    mgraphics.redraw();
}

function set_latency_ms(v) {
    latency_ms = Math.max(0.0, v);
    mgraphics.redraw();
}

function set_collision_mode(v) {
    collision_mode = v ? 1 : 0;
    mgraphics.redraw();
}

function list() {
    if (inlet === 2) update_analyzer_data(arrayfromargs(arguments));
}

function msg_float(v) {
    if (inlet === 1) {
        sample_rate = clamp(v, 22050.0, 384000.0);
        rebuild_band_cache();
        mgraphics.redraw();
    }
}

function msg_int(v) {
    if (inlet === 1) msg_float(v);
}

function pointer_context_click(pointerevent, ctrl, but) {
    if (pointerevent) {
        if (pointerevent.contextModifier) return 1;
        if (pointerevent.button !== undefined && pointerevent.button === 2) return 1;
        if (pointerevent.buttons !== undefined && (pointerevent.buttons & 2) !== 0) return 1;
    }
    if (but !== undefined && but !== null) {
        if ((but & 2) !== 0) return 1;
    }
    return ctrl ? 1 : 0;
}

function pointer_option_key(pointerevent, opt) {
    if (pointerevent) {
        if (pointerevent.altKey) return 1;
        if (pointerevent.optionKey) return 1;
    }
    return opt ? 1 : 0;
}

function pointer_shift_key(pointerevent, shift) {
    if (pointerevent && pointerevent.shiftKey) return 1;
    return shift ? 1 : 0;
}

function pointer_command_key(pointerevent, cmd) {
    if (pointerevent && pointerevent.commandKey) return 1;
    return cmd ? 1 : 0;
}

function pointer_x(pointerevent, fallback) {
    if (!pointerevent) return fallback;
    if (pointerevent.x !== undefined) return pointerevent.x;
    if (pointerevent.localX !== undefined) return pointerevent.localX;
    if (pointerevent.offsetX !== undefined) return pointerevent.offsetX;
    if (pointerevent.clientX !== undefined) return pointerevent.clientX;
    return fallback;
}

function pointer_y(pointerevent, fallback) {
    if (!pointerevent) return fallback;
    if (pointerevent.y !== undefined) return pointerevent.y;
    if (pointerevent.localY !== undefined) return pointerevent.localY;
    if (pointerevent.offsetY !== undefined) return pointerevent.offsetY;
    if (pointerevent.clientY !== undefined) return pointerevent.clientY;
    return fallback;
}

function pointer_buttons(pointerevent, fallback) {
    if (!pointerevent) return fallback;
    if (pointerevent.buttons !== undefined) return pointerevent.buttons;
    if (pointerevent.button !== undefined) {
        if (pointerevent.button === 2) return 2;
        return 1;
    }
    return fallback;
}

function note_pointer_press(x, y) {
    last_pointer_press_ms = new Date().getTime();
    last_pointer_press_x = x;
    last_pointer_press_y = y;
    suppress_next_click = 1;
}

function should_ignore_pointer_click(x, y) {
    var now_ms;
    if (!suppress_next_click) return 0;
    now_ms = new Date().getTime();
    if ((now_ms - last_pointer_press_ms) > 300) {
        suppress_next_click = 0;
        return 0;
    }
    if (Math.abs(x - last_pointer_press_x) > 4 || Math.abs(y - last_pointer_press_y) > 4) {
        suppress_next_click = 0;
        return 0;
    }
    suppress_next_click = 0;
    return 1;
}

function note_pending_context_click(x, y) {
    pending_context_click = 1;
    pending_context_x = x;
    pending_context_y = y;
    pending_context_ms = new Date().getTime();
}

function consume_pending_context_click(x, y) {
    var now_ms;
    if (!pending_context_click) return 0;
    now_ms = new Date().getTime();
    if ((now_ms - pending_context_ms) > 300) {
        pending_context_click = 0;
        return 0;
    }
    if (Math.abs(x - pending_context_x) > 4 || Math.abs(y - pending_context_y) > 4) {
        pending_context_click = 0;
        return 0;
    }
    pending_context_click = 0;
    return 1;
}

function handle_press(x, y, but, cmd, shift, opt, ctrl, pointerevent) {
    var badge_hit = hud_badge_hit(x, y);
    var hit = hit_test(x, y);
    var dynamic_hit = dynamic_hit_test(x, y);
    var next_idx;
    var menu_idx;
    var band;
    var context_click = pointer_context_click(pointerevent, ctrl, but);

    if (badge_hit) {
        if (cycle_hud_badge(badge_hit, shift ? 1 : 0)) return;
    }

    if (context_menu_open) {
        menu_idx = context_menu_hit(x, y);
        if (menu_idx >= 0) {
            band = bands[context_menu_band];
            if (context_menu_mode === 1) {
                band.type = menu_idx;
                if (!is_cut_type(band.type)) band.slope = 0;
                rebuild_band_cache();
                outlet(0, "context_type", context_menu_band, menu_idx);
                close_context_menu();
                mgraphics.redraw();
                return;
            }
            if (context_menu_mode === 2) {
                if (is_cut_type(band.type)) {
                    band.slope = menu_idx;
                    rebuild_band_cache();
                    outlet(0, "context_slope", context_menu_band, menu_idx);
                }
                close_context_menu();
                mgraphics.redraw();
                return;
            }
            if (SHOW_DYNAMIC && menu_idx === context_dynamic_index()) {
                if (band_supports_dynamic(band.type)) {
                    band.dynamic_enabled = band.dynamic_enabled ? 0 : 1;
                    if (!band.dynamic_enabled) {
                        band.dynamic_amount = 0.0;
                        band.dynamic_current = 0.0;
                    } else if (Math.abs(band.dynamic_amount) < 0.01) {
                        band.dynamic_amount = band.gain >= 0.0 ? -6.0 : 6.0;
                    }
                    rebuild_band_cache();
                    outlet(0, "context_dynamic", context_menu_band, band.dynamic_enabled, band.dynamic_amount);
                    close_context_menu();
                    mgraphics.redraw();
                }
                return;
            }
            if (menu_idx === context_type_index()) {
                context_menu_mode = 1;
                mgraphics.redraw();
                return;
            }
            if (menu_idx === context_slope_index()) {
                if (is_cut_type(band.type)) {
                    context_menu_mode = 2;
                    mgraphics.redraw();
                }
                return;
            }
            if (menu_idx === context_solo_index()) {
                band.solo = band.solo ? 0 : 1;
                rebuild_band_cache();
                outlet(0, "context_solo", context_menu_band, band.solo);
                close_context_menu();
                mgraphics.redraw();
                return;
            }
            if (menu_idx === context_enable_index()) {
                band.enabled = band.enabled ? 0 : 1;
                if (!band.enabled) {
                    band.solo = 0;
                    band.dynamic_current = 0.0;
                }
                rebuild_band_cache();
                outlet(0, "context_enable", context_menu_band, band.enabled);
                close_context_menu();
                mgraphics.redraw();
                return;
            }
            if (menu_idx === context_delete_index()) {
                delete_band_at(context_menu_band);
                return;
            }
        }
        close_context_menu();
        mgraphics.redraw();
        return;
    }

    if (context_click && (dynamic_hit >= 0 || hit >= 0)) {
        hit = dynamic_hit >= 0 ? dynamic_hit : hit;
        open_context_menu(hit, x, y);
        outlet(0, "selected_band", hit);
        mgraphics.redraw();
        return;
    }

    if (opt && (dynamic_hit >= 0 || hit >= 0)) {
        hit = dynamic_hit >= 0 ? dynamic_hit : hit;
        delete_band_at(hit);
        return;
    }

    if (dynamic_hit >= 0) {
        selected_band = dynamic_hit;
        dragging = 1;
        drag_mode = 2;
        drag_start_dynamic = bands[dynamic_hit].dynamic_amount;
        outlet(0, "selected_band", dynamic_hit);
    } else if (hit >= 0) {
        selected_band = hit;
        dragging = 1;
        drag_mode = 1;
        drag_start_freq = bands[hit].freq;
        drag_start_gain = bands[hit].gain;
        drag_start_q = bands[hit].q;
        outlet(0, "selected_band", hit);
    } else {
        selected_band = -1;
        dragging = 0;
        drag_mode = 0;
    }
    mgraphics.redraw();
}

function handle_double_click(x, y) {
    var hit = hit_test(x, y);
    var dynamic_hit = dynamic_hit_test(x, y);
    if (context_menu_open) {
        close_context_menu();
        mgraphics.redraw();
        return;
    }
    if (dynamic_hit >= 0 || hit >= 0) {
        delete_band_at(dynamic_hit >= 0 ? dynamic_hit : hit);
        return;
    }
    if (create_band_at(x, y)) return;
}

function handle_drag_at(x, y, but, cmd, shift) {
    var b, cache, new_freq, new_gain, new_q, new_dynamic;
    if (but === 0) {
        dragging = 0;
        drag_mode = 0;
        mgraphics.redraw();
        return;
    }
    if (!dragging || selected_band < 0 || selected_band >= num_bands) return;
    b = bands[selected_band];
    cache = band_cache[selected_band];

    if (drag_mode === 2) {
        new_dynamic = y_to_gain(y) - cache.node_gain;
        if (shift) new_dynamic = b.dynamic_amount + (new_dynamic - b.dynamic_amount) * 0.15;
        new_dynamic = Math.round(clamp(new_dynamic, -MAX_DYNAMIC_RANGE, MAX_DYNAMIC_RANGE) * 10.0) / 10.0;
        if (new_dynamic === b.dynamic_amount) return;
        bands[selected_band].dynamic_enabled = 1;
        bands[selected_band].dynamic_amount = new_dynamic;
        rebuild_band_cache();
        outlet(0, "band_dynamic_amount", selected_band, new_dynamic);
        mgraphics.redraw();
        return;
    }

    new_freq = x_to_freq(x);
    new_gain = b.gain;
    new_q = b.q;

    if (cache.uses_gain) {
        new_gain = y_to_gain(y);
        if (cmd) new_gain = drag_start_gain;
        if (shift) new_gain = b.gain + (new_gain - b.gain) * 0.15;
        new_gain = Math.round(clamp(new_gain, MIN_GAIN, MAX_GAIN) * 10.0) / 10.0;
    } else {
        new_q = y_to_q(y);
        if (cmd) new_q = drag_start_q;
        if (shift) new_q = b.q + (new_q - b.q) * 0.15;
        new_q = Math.round(clamp(new_q, MIN_Q, MAX_Q) * 100.0) / 100.0;
    }

    if (shift) new_freq = b.freq + (new_freq - b.freq) * 0.15;
    if (new_freq < 100.0) new_freq = Math.round(new_freq);
    else if (new_freq < 1000.0) new_freq = Math.round(new_freq);
    else new_freq = Math.round(new_freq / 10.0) * 10.0;
    new_freq = clamp(new_freq, MIN_FREQ, MAX_FREQ);

    if (cache.uses_gain && new_freq === b.freq && new_gain === b.gain) return;
    if (!cache.uses_gain && new_freq === b.freq && new_q === b.q) return;

    if (cache.uses_gain) {
        bands[selected_band].gain = new_gain;
    } else {
        bands[selected_band].q = new_q;
    }
    bands[selected_band].freq = new_freq;
    rebuild_band_cache();
    if (cache.uses_gain) outlet(0, "band_drag_gain", selected_band, new_freq, new_gain);
    else outlet(0, "band_drag_q", selected_band, new_freq, new_q);

    mgraphics.redraw();
}

function handle_hover(x, y) {
    var prev = hover_band;
    var prev_menu = context_menu_hover;
    var dynamic_hover;
    if (context_menu_open) {
        context_menu_hover = context_menu_hit(x, y);
        if (context_menu_hover !== prev_menu) mgraphics.redraw();
        return;
    }
    dynamic_hover = dynamic_hit_test(x, y);
    hover_band = dynamic_hover >= 0 ? dynamic_hover : hit_test(x, y);
    if (hover_band !== prev) mgraphics.redraw();
}

function clear_hover_state() {
    if (context_menu_open && context_menu_hover >= 0) {
        context_menu_hover = -1;
        mgraphics.redraw();
        return;
    }
    if (hover_band >= 0) {
        hover_band = -1;
        mgraphics.redraw();
    }
}

function onpointerdown(pointerevent) {
    var x = pointer_x(pointerevent, 0);
    var y = pointer_y(pointerevent, 0);
    var but = pointer_buttons(pointerevent, 1);
    var cmd = pointer_command_key(pointerevent, 0);
    var shift = pointer_shift_key(pointerevent, 0);
    var opt = pointer_option_key(pointerevent, 0);
    var ctrl = pointerevent.ctrlKey ? 1 : 0;
    if (pointer_context_click(pointerevent, ctrl, but)) {
        note_pending_context_click(x, y);
        return;
    }
    note_pointer_press(x, y);
    handle_press(
        x,
        y,
        but,
        cmd,
        shift,
        opt,
        ctrl,
        pointerevent
    );
}

function onpointermove(pointerevent) {
    var buttons = pointer_buttons(pointerevent, 0);
    var x = pointer_x(pointerevent, 0);
    var y = pointer_y(pointerevent, 0);
    if (dragging && ((buttons & 1) !== 0)) {
        handle_drag_at(
            x,
            y,
            buttons,
            pointer_command_key(pointerevent, 0),
            pointer_shift_key(pointerevent, 0)
        );
        return;
    }
    if (dragging && buttons === 0) {
        dragging = 0;
        drag_mode = 0;
    }
    handle_hover(x, y);
}

function onpointerup(pointerevent) {
    var x = pointer_x(pointerevent, 0);
    var y = pointer_y(pointerevent, 0);
    if (dragging) {
        dragging = 0;
        drag_mode = 0;
        mgraphics.redraw();
    } else {
        handle_hover(x, y);
    }
}

function onpointerleave(pointerevent) {
    if (dragging && pointerevent && pointerevent.buttons === 0) {
        dragging = 0;
        drag_mode = 0;
    }
    clear_hover_state();
}

function onclick(x, y, but, cmd, shift, caps, opt, ctrl, pointerevent) {
    if (consume_pending_context_click(x, y)) {
        handle_press(x, y, 2, cmd, shift, opt, 1, pointerevent);
        return;
    }
    if (should_ignore_pointer_click(x, y)) return;
    handle_press(x, y, but, cmd, shift, opt, ctrl, pointerevent);
}

function ondblclick(x, y, but, cmd, shift, caps, opt, ctrl) {
    handle_double_click(x, y);
}

function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    handle_drag_at(x, y, but, cmd, shift);
}

function onidle(x, y, but, cmd, shift, caps, opt, ctrl) {
    handle_hover(x, y);
}

function onidleout(x, y, but, cmd, shift, caps, opt, ctrl) {
    clear_hover_state();
}

function onwheel(x, y, scrollx, scrolly, cmd, shift, caps, opt, ctrl) {
    var target = hover_band >= 0 ? hover_band : selected_band;
    var q, factor;
    if (target < 0 || target >= num_bands) return;
    if (!bands[target].enabled) return;

    q = bands[target].q;
    factor = shift ? 0.02 : 0.08;
    q = q * (1.0 + scrolly * factor);
    q = Math.round(clamp(q, MIN_Q, MAX_Q) * 100.0) / 100.0;
    if (q === bands[target].q) return;
    bands[target].q = q;
    rebuild_band_cache();
    outlet(3, "band_q", target, q);
    mgraphics.redraw();
}

function onresize(w, h) {
    curve_dirty = 1;
    mgraphics.redraw();
}
""")
