"""Loop filter curve — a feedback loop's damping + tilt tone response.

A compact log-frequency magnitude-response readout of how a delay/reverb loop
shapes its repeats tonally: a one-pole DAMP lowpass (darkens each pass) combined
with a TONE tilt (low/high move in opposite directions by ``tilt_db`` around a
``pivot_hz`` pivot). The curve reshapes live as DAMP/TONE move. With
interactive=True the whole panel is a 2-axis pad — horizontal = DAMP amount,
vertical = TONE tilt — emitting on outlet 0 (the proven trail/ballistics idiom).

Mirrors the Echotide gen math: ``damp_c = damp% * damp_scale`` is the one-pole
pole, and the tilt is ``±tilt_db`` at tone ``±100%`` split at ``pivot_hz`` by a
one-pole at the pivot. The DAMP magnitude is exact; the tilt is a faithful
magnitude approximation (low gain below the pivot, high gain above, smooth
crossover) — truthful to what the echoes sound like.

Messages in (inlet 0):
    set_damp <pct>        0..100 loop-damping amount (one-pole LP in the loop)
    set_tone <pct>        -100..100 tilt (>0 brighter, <0 darker)
    set_samplerate <hz>   DSP rate for the bin->Hz + coefficient math

Messages out (outlet 0; interactive=True only, on user drag — no-echo):
    damp <pct>            horizontal drag position (0..100)
    tone <pct>            vertical drag position (-100..100; top = +100)
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)

LOOP_FILTER_CURVE_INLETS = 1
LOOP_FILTER_CURVE_OUTLETS = 1

__all__ = [
    "LOOP_FILTER_CURVE_INLETS",
    "LOOP_FILTER_CURVE_OUTLETS",
    "loop_filter_curve_js",
]


def loop_filter_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    curve_color="0.30, 0.75, 0.95, 1.0",
    fill_color="0.30, 0.75, 0.95, 0.20",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    damp_pct=20.0,
    tone_pct=0.0,
    damp_scale=0.0085,
    pivot_hz=850.0,
    tilt_db=6.0,
    db_hi=9.0,
    db_lo=-24.0,
    interactive=False,
):
    """Return JavaScript source for the loop damping/tilt response display.

    With interactive=True the panel is a 2-axis pad: horizontal position sets
    DAMP (0..100), vertical sets TONE (+100 top .. -100 bottom), emitted as
    ``damp <pct>`` / ``tone <pct>`` on outlet 0 (no-echo: outlet fires only on a
    user gesture; inbound set_* is ignored mid-drag). ``damp_scale``,
    ``pivot_hz`` and ``tilt_db`` mirror the host's loop DSP so the curve is
    truthful.
    """
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        curve_color=curve_color,
        fill_color=fill_color,
        grid_color=grid_color,
        text_color=text_color,
        damp_pct=damp_pct,
        tone_pct=tone_pct,
        damp_scale=damp_scale,
        pivot_hz=pivot_hz,
        tilt_db=tilt_db,
        db_hi=db_hi,
        db_lo=db_lo,
        interactive=1 if interactive else 0,
    )


_JS_TEMPLATE = Template("""\
// Loop Filter Curve Display - generated by m4l-builder
// ES5 compatible; interactive=True turns it into a 2-axis DAMP/TONE pad.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var CURVE_CLR  = [$curve_color];
var FILL_CLR   = [$fill_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];

var damp_pct = $damp_pct;       // 0..100
var tone_pct = $tone_pct;       // -100..100
var DAMP_SCALE = $damp_scale;   // pole = damp_pct * DAMP_SCALE (0..0.85)
var PIVOT_HZ = $pivot_hz;
var TILT_DB = $tilt_db;
var DB_HI = $db_hi, DB_LO = $db_lo;
var samplerate = 44100.0;

var INTERACTIVE = $interactive;
var dragging = 0;

var FMIN = 20.0, FMAX = 20000.0;
var LOG_FMIN = Math.log(FMIN), LOG_FMAX = Math.log(FMAX);

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

function plot_l() { return 6; }
function plot_r() { return mgraphics.size[0] - 6; }
function plot_t() { return 12; }
function plot_b() { return mgraphics.size[1] - 12; }
function plot_w() { var d = plot_r() - plot_l(); return d > 1 ? d : 1; }
function plot_h() { var d = plot_b() - plot_t(); return d > 1 ? d : 1; }

function freq_to_x(f) {
    var t = (Math.log(clamp(f, FMIN, FMAX)) - LOG_FMIN) / (LOG_FMAX - LOG_FMIN);
    return plot_l() + t * plot_w();
}
function db_to_y(db) {
    var t = (DB_HI - clamp(db, DB_LO, DB_HI)) / (DB_HI - DB_LO);
    return plot_t() + t * plot_h();
}

// One-pole magnitude (dB) for a feedback coeff `a`: H(z)=(1-a)/(1-a z^-1),
// DC gain 1. Mirrors `y = x + (y-x)*a` in the loop.
function onepole_mag(f, a) {
    if (a <= 0.0) return 1.0;
    var w = 6.283185307 * f / samplerate;
    var denom = Math.sqrt(1.0 - 2.0 * a * Math.cos(w) + a * a);
    return (1.0 - a) / (denom < 1e-9 ? 1e-9 : denom);
}

// Combined loop tone response (dB) at freq f: the DAMP lowpass + the TONE tilt.
function response_db(f) {
    var a = clamp(damp_pct, 0.0, 100.0) * DAMP_SCALE;     // 0..0.85 pole
    var damp_mag = onepole_mag(f, a);

    // Tilt: a one-pole LP at the pivot splits low/high; low *= lo_g, high *= hi_g
    // with lo_g/hi_g = +/- TILT_DB at tone = +/-100%. tone>0 -> brighter.
    var tg = clamp(tone_pct, -100.0, 100.0) / 100.0;
    var lo_g = Math.pow(10.0, (-tg * TILT_DB) / 20.0);
    var hi_g = Math.pow(10.0, (tg * TILT_DB) / 20.0);
    var tone_c = 1.0 - Math.exp(-6.283185307 * PIVOT_HZ / samplerate);
    var lp_mag = onepole_mag(f, 1.0 - tone_c);            // pivot LP magnitude
    var tilt_mag = lp_mag * lo_g + (1.0 - lp_mag) * hi_g;
    if (tilt_mag < 1e-6) tilt_mag = 1e-6;

    return 20.0 * Math.log(damp_mag * tilt_mag) / Math.LN10;
}

function fmt_sign(v) { return (v > 0 ? "+" : "") + Math.round(v); }

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, y, f, db;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Frequency gridlines (decades) + labels.
    mgraphics.set_line_width(1.0);
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(7.0);
    var decades = [100, 1000, 10000];
    var labels = ["100", "1k", "10k"];
    for (i = 0; i < decades.length; i++) {
        x = freq_to_x(decades[i]);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(x, plot_t()); mgraphics.line_to(x, plot_b()); mgraphics.stroke();
        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.move_to(x + 2, plot_b() - 2); mgraphics.show_text(labels[i]);
    }
    // dB gridlines every 6 dB; the 0 dB line brighter.
    for (db = DB_LO + 6; db <= DB_HI - 0.01; db += 6) {
        y = db_to_y(db);
        if (Math.abs(db) < 0.01) {
            mgraphics.set_source_rgba(GRID_CLR[0], GRID_CLR[1], GRID_CLR[2],
                                      Math.min(1.0, GRID_CLR[3] * 1.8));
        } else {
            mgraphics.set_source_rgba(GRID_CLR);
        }
        mgraphics.move_to(plot_l(), y); mgraphics.line_to(plot_r(), y); mgraphics.stroke();
    }

    // Response curve: fill from the 0 dB line down to the curve, + stroke.
    var N = 160;
    var y0 = db_to_y(0.0);
    mgraphics.set_source_rgba(FILL_CLR);
    mgraphics.move_to(plot_l(), y0);
    for (i = 0; i <= N; i++) {
        var tt = i / N;
        f = Math.exp(LOG_FMIN + tt * (LOG_FMAX - LOG_FMIN));
        mgraphics.line_to(freq_to_x(f), db_to_y(response_db(f)));
    }
    mgraphics.line_to(plot_r(), y0);
    mgraphics.close_path();
    mgraphics.fill();

    mgraphics.set_source_rgba(CURVE_CLR);
    mgraphics.set_line_width(1.8);
    for (i = 0; i <= N; i++) {
        var t2 = i / N;
        f = Math.exp(LOG_FMIN + t2 * (LOG_FMAX - LOG_FMIN));
        x = freq_to_x(f); y = db_to_y(response_db(f));
        if (i === 0) mgraphics.move_to(x, y); else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    // Readout: DAMP / TONE + a hint of the pad axes.
    mgraphics.set_font_size(7.5);
    mgraphics.set_source_rgba(TEXT_CLR);
    mgraphics.move_to(plot_l() + 3, plot_t() + 9);
    mgraphics.show_text("DAMP " + Math.round(damp_pct) + "%   TONE " + fmt_sign(tone_pct) + "%");
}

// ── Message handlers (set_* restyle + redraw; ignored mid-drag) ────────
function set_damp(v) { if (dragging) return; if (isFinite(v)) { damp_pct = v; mgraphics.redraw(); } }
function set_tone(v) { if (dragging) return; if (isFinite(v)) { tone_pct = v; mgraphics.redraw(); } }
function set_samplerate(v) { if (isFinite(v) && v > 0) { samplerate = v; mgraphics.redraw(); } }

// ── Interaction: 2-axis pad — X = DAMP (0..100), Y = TONE (+100 top..-100) ──
// Absolute mapping with the proven v8ui pointer resolver; outlet fires only on a
// user gesture (no-echo). Both axes update together (the trail/X-Y-pad idiom).
function pointer_x(pe, fb) {
    if (!pe) return fb;
    if (pe.x !== undefined) return pe.x;
    if (pe.localX !== undefined) return pe.localX;
    if (pe.offsetX !== undefined) return pe.offsetX;
    if (pe.clientX !== undefined) return pe.clientX;
    return fb;
}
function pointer_y(pe, fb) {
    if (!pe) return fb;
    if (pe.y !== undefined) return pe.y;
    if (pe.localY !== undefined) return pe.localY;
    if (pe.offsetY !== undefined) return pe.offsetY;
    if (pe.clientY !== undefined) return pe.clientY;
    return fb;
}
function pointer_buttons(pe, fb) {
    if (!pe) return fb;
    if (pe.buttons !== undefined) return pe.buttons;
    if (pe.button !== undefined) return pe.button === 2 ? 2 : 1;
    return fb;
}

function apply_drag(x, y) {
    if (isNaN(x) || isNaN(y)) return;
    damp_pct = clamp((x - plot_l()) / plot_w(), 0.0, 1.0) * 100.0;
    tone_pct = (1.0 - 2.0 * clamp((y - plot_t()) / plot_h(), 0.0, 1.0)) * 100.0;
    outlet(0, "damp", damp_pct);
    outlet(0, "tone", tone_pct);
    mgraphics.redraw();
}

function start_drag(x, y) { if (!INTERACTIVE) return; dragging = 1; apply_drag(x, y); }
function drag_to(x, y) { if (dragging) apply_drag(x, y); }
function end_drag() { if (dragging) { dragging = 0; mgraphics.redraw(); } }

function onpointerdown(pe) { start_drag(pointer_x(pe, plot_l()), pointer_y(pe, plot_t())); }
function onpointermove(pe) {
    if (dragging && ((pointer_buttons(pe, 1) & 1) !== 0)) drag_to(pointer_x(pe, plot_l()), pointer_y(pe, plot_t()));
    else if (dragging) end_drag();
}
function onpointerup(pe) { end_drag(); }
function onpointerleave(pe) { end_drag(); }
function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { start_drag(x, y); }
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) { if (but) drag_to(x, y); else end_drag(); }

function onresize(w, h) { mgraphics.redraw(); }
""")
