"""Performance canvas display engine for jsui.

ONE interactive surface: the sliced waveform IS the sequencer view. The
pattern brain (seeds, chop/glitch/vary/drift/fill mutation, locks) lives
here, same as the old lane engine; playback stays in the host's coll +
scheduler clock (js is never in the timing path).

Instead of a separate step lane under the waveform, every step of the
pattern is drawn ON the slice it fires as a stacked SEGMENT rising from
the bottom of that slice's column: a slice hit by steps 3 and 11 shows
two stacked mini-bars. Slices are colored by a position hue ramp across
the sample (amber -> coral -> orchid -> blue), so a segment's color says
which part of the sample it plays. Segment height/brightness = the step's
CHOP level (muted steps stay as dim grabbable slivers), accents wear a
hot cap, locks a bright outline, mutations a tint, ratchets edge ticks,
reversed steps a left chevron. The playing step's segment flashes.

Segments are the drag handles (no dots, no nodes):
    * drag a segment sideways  -> pin that step to the slice under the
      cursor (a step lock; follows the drag live)
    * option-drag              -> direction lock (top half fwd / bottom rev)
    * ctrl-drag                -> pitch lock (vertical, +/-24 st)
    * cmd+option-click         -> gate toggle (mute/unmute lock)
    * shift+option-drag        -> ratchet lock (vertical, 0-3)
    * cmd-click                -> erase that step's slice lock
    * shift+cmd-click          -> clear ALL locks
    * click empty slice area   -> audition that slice (outlet 4)
Hovering names what is under the cursor and shows the gesture legend.

Inlets (identical numbering to slice_pattern_display, so hosts re-point
wires without renumbering):
    0 -- step count            11 -- arp amount
    1 -- slice count           12 -- pitch seed
    2 -- step distance         13 -- direction mode
    3 -- motion mode           14 -- sync messages (see below)
    4 -- jump amount           15 -- vary amount
    5 -- pattern seed          16 -- vary salt
    6 -- chop amount           17 -- drift amount
    7 -- chop seed             18 -- fill amount
    8 -- glitch amount         19 -- form bar
    9 -- glitch seed           20 -- fill active
    10 -- active playhead step 21 -- scale mode

Inlet-14 selectors (unchanged from slice_pattern_display): ``trigger <step>``,
``set/unset/clear``, ``dirset/dirunset/dirclear``, ``pitchset/pitchunset/
pitchclear``, ``gateset/gateunset/gateclear``, ``ratchetset/ratchetunset/
ratchetclear``, ``dumpa/dumpb``, ``dumppattern``.

Waveform named messages (send to inlet 0, selectors — unchanged from
slice_overview EXCEPT the loaded flag, which was a bare number on the old
inlet 0 and is now the selector ``loaded <0|1>``):
    loaded <0|1>            set_sensitivity <0-100>
    set_buffer_name <name>  set_min_spacing <ms>
    set_samplerate <hz>     set_pitch <st>        (stored only, no analyze)
    set_hint <0|1>          set_editable <0|1>    (divider drag on the wave)
    set_mode <0|1>          set_display_bounds <b0 b1 ...>
    set_slices <n>          set_active_index <n>
    analyze                 playhead_ms <ms>

Outlets:
    0 -- lock events (``lock/unlock/clear`` + dir/pitch/gate/ratchet variants)
    1 -- per-slice coll-store row ``k start_ms 0 end_ms dur_ms``
    2 -- PLAYBACK pattern table / ``trigger`` replies (same shapes as
         slice_pattern_display outlet 2)
    3 -- slice count (int)
    4 -- interaction events: ``audition <slice>`` (click empty wave),
         ``bounds <b0 b1 ...>`` (editor-mode divider edits),
         ``<a|b> set ...`` scene export rows
"""

PERFORMANCE_CANVAS_INLETS = 22
PERFORMANCE_CANVAS_OUTLETS = 5

_TEMPLATE = r"""// Performance Canvas - generated by m4l-builder
// ES5 JavaScript for Max jsui mgraphics

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 22;
outlets = 5;

// ---- geometry ----
var PAD = 6;

// ---- waveform state ----
var loaded = 0;
var region_start = 0.0;
var region_end = 1.0;
var playhead = 0.0;
var active_start = 0.0;
var active_end = 0.0;
var recent_hits = [];
var last_hit_center = -1.0;
var BUFFER_NAME = '@BUFNAME@';
var WAVE_POINTS = 256;
// THEME: structural colors default to the baked palette but are overridden at
// runtime by the live.colors theme bus (message 'themebg'/'themefg' R G B A),
// so the canvas tracks the user's Live skin instead of a fixed near-black.
var TH_BG = [@BG@];
var TH_TEXT = [@TEXT@];
function th_bg() { mgraphics.set_source_rgba(TH_BG[0], TH_BG[1], TH_BG[2], TH_BG[3]); }
function th_text() { mgraphics.set_source_rgba(TH_TEXT[0], TH_TEXT[1], TH_TEXT[2], TH_TEXT[3]); }
var waveform_cache = [];
var waveform_ready = 0;
var wave_retry = 0;        // bounded lazy-rebuild budget: buffer~ replace is DEFERRED,
                           // so the buffer can still be empty when 'loaded 1' fires
                           // (waveform stuck blank while audio plays). Retry on redraw
                           // until the buffer reads back, capped so an always-empty
                           // buffer cannot rebuild every frame forever.
var hint = 0;
var HIT_LIMIT = 10;
var sample_rate = 48000.0;
var slice_mode = 0;
var sensitivity = 30.0;
var min_spacing_ms = 80.0;
var pitch_ratio = 1.0;
var slice_boundaries = [];
var editable = 0;
var drag_index = -1;
var manual_edit = 0;
var GRAB_PX = 6;
var MIN_GAP = 0.004;
var RMS_WIN = 512;
var RMS_HOP = 256;

// ---- pattern state ----
var step_count = 16;
var slice_count = 16;
var distance = 1;
var mode = 0;
var jump_amount = 32.0;
var pattern_seed = 11;
var chop_amount = 0.0;
var chop_seed = 37;
var glitch_amount = 0.0;
var glitch_seed = 53;
var playhead_step = -1;
var arp_amount = 0.0;
var pitch_seed = 79;
var dir_mode = 0;
var vary_amount = 0.0;
var vary_salt = 0;
var drift_amount = 0.0;
var fill_amount = 0.0;
var form_bar = 0;
var fill_active = 0;
var scale_mode = 0;
var SCALES = [
    [0.0, 3.0, 7.0, 10.0, 12.0, 15.0, 19.0, 24.0],
    [0.0, 3.0, 5.0, 7.0, 10.0, 12.0, 15.0, 24.0],
    [0.0, 4.0, 7.0, 11.0, 12.0, 16.0, 19.0, 24.0],
    [0.0, 7.0, 12.0, 19.0, 24.0, 12.0, 7.0, 19.0]
];
var locked_steps = {};
var dir_locked_steps = {};
var pitch_locked_steps = {};
var gate_locked_steps = {};
var level_locked_steps = {};   // step -> 0.1..1.25 (vertical drag on a bar)
var ratchet_locked_steps = {};
var prob_locked_steps = {};    // step -> 0..100 trigger chance (shift-drag; absent = 100 = always fires)
var euclid_pulses = 0;         // 0 = off; N = N evenly-spaced hits across step_count (ctrl+shift drag)
var euclid_rot = 0;            // rotate the Euclid pattern under the downbeat
var cond_locked_steps = {};    // step -> trig-condition CODE (cmd+ctrl drag). 0 = OFF (always).
// Trig-condition codes the engine evaluates against the live loop pass + fill:
//   0 OFF | A:B encoded B*10+A (fire when pass%B == A-1) | 1 FILL | 3 FIRST(pass 0)
var COND_CODES  = [0, 21, 22, 31, 41, 42, 43, 81, 1, 3];
var COND_LABELS = ['OFF', '1:2', '2:2', '1:3', '1:4', '2:4', '3:4', '1:8', 'FILL', '1ST'];

// ---- hit-view / shape state ----
var view = 0;              // 0 = overview, 1 = hit inspector
var inspect_k = -1;        // inspected slice
var zoom_cache = [];
var zoom_ready = 0;
var g_attack = 2.0;        // global envelope (mirrors the real params)
var g_decay = 300.0;       // ms
var g_sustain = 100.0;     // %
var g_release = 5.0;       // ms
var g_atk_curve = 0.0;     // -1..1: <0 punchy (convex), >0 soft (concave)
var g_rel_curve = 0.0;     // -1..1: curve of the release tail
var g_lfo_depth = 0.0;     // % tremolo depth (0 = off)
var g_lfo_period = 250.0;  // ms per cycle (host-resolved: synced or free)
var g_lfo_shape = 0;       // 0 sine / 1 tri / 2 saw / 3 sqr
var hv_page = 0;           // hit-view sub-tab: 0 = ENV, 1 = LFO
var shape_ovr = {};        // per-slice pins: {k: [a_ms, d_ms, s_pct, r_ms]}
var drag_shape = 0;        // 1 = attack, 2 = decay/sustain, 3 = release
var shape_dirty = 0;       // audition once on release after a shape drag

// ---- interaction state ----
var drag_step = -1;      // step being gesture-dragged (-1 = none)
var drag_x0 = 0;         // plain-press origin: first movement picks the axis
var drag_y0 = 0;         //   (sideways = MOVE the step, vertical = LOUDNESS)
var drag_kind = 0;       // 1 pin / 2 dir / 3 pitch / 4 gate / 5 ratchet / -1 erase / -3 pitch-erase
var drag_band = 0;       // 1 = wave divider drag (editor instances only)
var hover_on = 0;
var hover_x = -1;
var hover_y = -1;
var seg_x = [];          // per-drawn-segment hit rects (rebuilt every paint)
var seg_y = [];
var seg_w = [];
var seg_h = [];
var seg_step = [];

// ---- slice hue ramp: position in the sample -> color ----
var ACCENT = [0.90, 0.67, 0.28];   // ONE accent — color no longer encodes
                                   // position (the x-axis already does)

function slice_rgb(k) {
    return ACCENT;
}

function clamp(v, lo, hi) {
    if (v < lo) return lo;
    if (v > hi) return hi;
    return v;
}

function inner_w() {
    return mgraphics.size[0] - PAD * 2;
}

function inner_h() {
    return mgraphics.size[1] - PAD * 2;
}

function norm_to_x(v) {
    return PAD + clamp(v, 0.0, 1.0) * inner_w();
}

function x_to_pos(x) {
    var iw = inner_w();
    if (iw <= 0) return 0.0;
    return clamp((x - PAD) / iw, 0.0, 1.0);
}

function norm_from_y(y) {
    return 1.0 - clamp((y - PAD) / Math.max(1, inner_h()), 0.0, 1.0);
}

// ================= waveform side =================

function set_buffer_name(v) {
    BUFFER_NAME = '' + v;
    mgraphics.redraw();
}

function register_hit() {
    var center = clamp((active_start + active_end) * 0.5, 0.0, 1.0);
    if (active_end <= active_start) return;
    if (last_hit_center >= 0.0 && Math.abs(center - last_hit_center) < 0.002) return;
    recent_hits.push(center);
    if (recent_hits.length > HIT_LIMIT) recent_hits.shift();
    last_hit_center = center;
}

function loaded_flag(v) {
    // selector form ('loaded <v>', dispatched from anything()) of the old
    // bare-number inlet-0 flag -- a bare number on inlet 0 is step_count now
    loaded = v > 0 ? 1 : 0;
    playhead = 0.0;
    if (view === 1) exit_hit_view();
    rebuild_waveform_cache();
    // if the buffer was not filled yet, arm the lazy-rebuild retry
    wave_retry = (loaded && !waveform_ready) ? 40 : 0;
    mgraphics.redraw();
}

function rebuild_waveform_cache() {
    waveform_cache = [];
    waveform_ready = 0;
    if (!loaded) return;
    try {
        var source_buffer = new Buffer(BUFFER_NAME);
        var frame_count = source_buffer.framecount();
        var channel_count = source_buffer.channelcount();
        if (!frame_count || frame_count <= 0 || !channel_count || channel_count <= 0) return;
        for (var i = 0; i < WAVE_POINTS; i++) {
            var start_frame = Math.floor((i / WAVE_POINTS) * frame_count);
            var end_frame = Math.floor(((i + 1) / WAVE_POINTS) * frame_count);
            if (end_frame <= start_frame) end_frame = start_frame + 1;
            if (end_frame > frame_count) end_frame = frame_count;
            var stride = Math.max(1, Math.floor((end_frame - start_frame) / 8));
            var peak = 0.0;
            for (var frame = start_frame; frame < end_frame; frame += stride) {
                var sample_sum = 0.0;
                for (var channel = 1; channel <= channel_count; channel++) {
                    var sample_value = source_buffer.peek(channel, frame);
                    if (sample_value < 0.0) sample_value = -sample_value;
                    sample_sum += sample_value;
                }
                sample_sum = sample_sum / channel_count;
                if (sample_sum > peak) peak = sample_sum;
            }
            waveform_cache[i] = clamp(peak, 0.0, 1.0);
        }
        waveform_ready = waveform_cache.length > 0 ? 1 : 0;
    } catch (err) {
        waveform_ready = 0;
    }
}

function nearest_divider(pos) {
    var iw = inner_w();
    var best = -1, bestd = 1e9, i, d;
    for (i = 1; i <= slice_boundaries.length - 2; i++) {
        d = Math.abs(pos - slice_boundaries[i]) * iw;
        if (d < bestd) { bestd = d; best = i; }
    }
    if (best >= 1 && bestd <= GRAB_PX) return best;
    return -1;
}

function add_divider(pos) {
    if (slice_boundaries.length < 2) slice_boundaries = [0.0, 1.0];
    if (pos <= MIN_GAP || pos >= 1.0 - MIN_GAP) return 0;
    if (slice_boundaries.length - 1 >= 64) return 0;
    var i, ins = -1;
    for (i = 0; i < slice_boundaries.length; i++) {
        if (Math.abs(pos - slice_boundaries[i]) < MIN_GAP) return 0;
        if (ins < 0 && slice_boundaries[i] > pos) ins = i;
    }
    if (ins < 0) ins = slice_boundaries.length - 1;
    slice_boundaries.splice(ins, 0, pos);
    return 1;
}

function remove_divider(idx) {
    if (idx >= 1 && idx <= slice_boundaries.length - 2) {
        slice_boundaries.splice(idx, 1);
        return 1;
    }
    return 0;
}

function emit_display_bounds() {
    var args = [4, 'bounds'], i;
    for (i = 0; i < slice_boundaries.length; i++) args.push(slice_boundaries[i]);
    outlet.apply(this, args);
}

function after_edit() {
    manual_edit = 1;
    slice_count = Math.max(1, Math.min(64, slice_boundaries.length - 1));
    emit_display_bounds();
    mgraphics.redraw();
}

function set_editable(v) {
    editable = v > 0 ? 1 : 0;
}

function set_display_bounds() {
    if (arguments.length < 2) return;
    var nb = [], i;
    for (i = 0; i < arguments.length; i++) nb.push(clamp(arguments[i], 0.0, 1.0));
    slice_boundaries = nb;
    slice_count = Math.max(1, Math.min(64, nb.length - 1));
    manual_edit = 1;
    emit_slices();
    mgraphics.redraw();
}

var last_active_k = -1;

function set_active_index(n) {
    if (slice_boundaries.length < 2) return;
    var i = Math.round(n);
    if (i < 0) i = 0;
    if (i > slice_boundaries.length - 2) i = slice_boundaries.length - 2;
    last_active_k = i;
    active_start = slice_boundaries[i];
    active_end = slice_boundaries[i + 1];
    register_hit();
    mgraphics.redraw();
}

function playhead_ms(ms) {
    var fc = buffer_frames();
    if (fc <= 0 || sample_rate <= 0) return;
    var len_ms = (fc / sample_rate) * 1000.0;
    if (len_ms <= 0) return;
    var np = clamp(ms / len_ms, 0.0, 1.0);
    if (Math.abs(np - playhead) < 0.0005) return;
    playhead = np;
    mgraphics.redraw();
}

function set_samplerate(v) {
    if (v > 0) sample_rate = v;
    if (loaded && !manual_edit) analyze();
}

function set_hint(v) {
    hint = Math.max(0, Math.round(v));
    mgraphics.redraw();
}

function set_mode(v) {
    slice_mode = (v === 1 || v === 'grid') ? 1 : 0;
    if (loaded) analyze();
}

function set_slices(v) {
    slice_count = Math.max(1, Math.min(64, Math.round(v)));
    if (loaded) analyze(); else mgraphics.redraw();
}

function set_sensitivity(v) {
    sensitivity = clamp(v, 0.0, 100.0);
    if (loaded && slice_mode === 0) analyze();
}

function set_min_spacing(v) {
    min_spacing_ms = v < 0.0 ? 0.0 : v;
    if (loaded && slice_mode === 0) analyze();
}

function set_pitch(v) {
    // pitch is a trigger-time dur multiply in the host patch; stored only,
    // must NOT analyze (that wiped manual slice edits on every pitch move)
    pitch_ratio = Math.pow(2.0, v / 12.0);
}

function buffer_frames() {
    try {
        var b = new Buffer(BUFFER_NAME);
        var fc = b.framecount();
        return (fc && fc > 0) ? fc : 0;
    } catch (e) {
        return 0;
    }
}

function window_rms(buf, ch_count, start, win, frame_count) {
    var stride = Math.max(1, Math.floor(win / 64));
    var acc = 0.0, n = 0, frame, channel, s;
    for (frame = start; frame < start + win && frame < frame_count; frame += stride) {
        var mono = 0.0;
        for (channel = 1; channel <= ch_count; channel++) {
            s = buf.peek(channel, frame);
            mono += s;
        }
        mono = mono / ch_count;
        acc += mono * mono;
        n++;
    }
    if (n <= 0) return 0.0;
    return Math.sqrt(acc / n);
}

function compute_grid() {
    var n = Math.max(1, slice_count);
    var b = [], i;
    for (i = 0; i <= n; i++) b[i] = i / n;
    return b;
}

function compute_onsets() {
    var frame_count = buffer_frames();
    if (frame_count <= 0) return compute_grid();
    var buf, ch_count;
    try {
        buf = new Buffer(BUFFER_NAME);
        ch_count = buf.channelcount();
    } catch (e) {
        return compute_grid();
    }
    if (!ch_count || ch_count <= 0) ch_count = 1;
    var env = [], w = 0, start;
    for (start = 0; start + RMS_WIN <= frame_count; start += RMS_HOP) {
        env[w] = window_rms(buf, ch_count, start, RMS_WIN, frame_count);
        w++;
    }
    if (env.length < 3) return compute_grid();
    var flux = [], i, d;
    flux[0] = 0.0;
    for (i = 1; i < env.length; i++) {
        d = env[i] - env[i - 1];
        flux[i] = d > 0.0 ? d : 0.0;
    }
    var mult = 3.0 - (sensitivity / 100.0) * 2.5;
    var lwin = 8;
    var floor_thr = 0.0008;
    var min_hops = Math.floor((min_spacing_ms / 1000.0 * sample_rate) / RMS_HOP);
    if (min_hops < 1) min_hops = 1;
    var onsets = [];
    var last_idx = -1000000;
    for (i = 1; i < flux.length - 1; i++) {
        var lo = i - lwin; if (lo < 0) lo = 0;
        var hi = i + lwin; if (hi > flux.length - 1) hi = flux.length - 1;
        var sum = 0.0, c = 0, j;
        for (j = lo; j <= hi; j++) { sum += flux[j]; c++; }
        var local_mean = c > 0 ? sum / c : 0.0;
        var thr = local_mean * mult + floor_thr;
        if (flux[i] > thr && flux[i] >= flux[i - 1] && flux[i] > flux[i + 1]) {
            if (i - last_idx >= min_hops) {
                onsets.push({ pos: (i * RMS_HOP) / frame_count, str: flux[i] });
                last_idx = i;
            }
        }
    }
    if (onsets.length > 63) {
        onsets.sort(function (a, b2) { return b2.str - a.str; });
        onsets = onsets.slice(0, 63);
    }
    onsets.sort(function (a, b2) { return a.pos - b2.pos; });
    var bounds = [0.0];
    for (i = 0; i < onsets.length; i++) {
        var p = clamp(onsets[i].pos, 0.0, 1.0);
        if (p > 0.0005 && p < 0.9995) bounds.push(p);
    }
    bounds.push(1.0);
    return bounds;
}

function emit_slices() {
    var n = slice_boundaries.length - 1;
    if (n < 1) { outlet(3, 1); return; }
    var frame_count = buffer_frames();
    var length_ms = frame_count > 0 ? (frame_count / sample_rate) * 1000.0 : 0.0;
    var k, s_ms, e_ms, dur;
    for (k = 0; k < n; k++) {
        s_ms = slice_boundaries[k] * length_ms;
        e_ms = slice_boundaries[k + 1] * length_ms;
        dur = e_ms - s_ms;
        if (dur < 0.0) dur = 0.0;
        outlet(1, k, s_ms, 0, e_ms, dur);
    }
    outlet(3, n);
}

function analyze() {
    if (!loaded) return;
    if (view === 1) exit_hit_view();
    manual_edit = 0;
    if (slice_mode === 1) slice_boundaries = compute_grid();
    else slice_boundaries = compute_onsets();
    slice_count = Math.max(1, Math.min(64, slice_boundaries.length - 1));
    emit_slices();
    mgraphics.redraw();
}

function slice_from_pos(pos) {
    var i;
    if (slice_boundaries.length > 1) {
        for (i = 0; i < slice_boundaries.length - 1; i++) {
            if (pos >= slice_boundaries[i] && pos < slice_boundaries[i + 1]) return i;
        }
        return slice_boundaries.length - 2;
    }
    var n = Math.max(1, Math.round(slice_count));
    return Math.min(n - 1, Math.floor(pos * n));
}

function slice_edges(k) {
    if (slice_boundaries.length > 1) {
        var i = clamp(Math.round(k), 0, slice_boundaries.length - 2);
        return [slice_boundaries[i], slice_boundaries[i + 1]];
    }
    var n = Math.max(1, Math.round(slice_count));
    var j = clamp(Math.round(k), 0, n - 1);
    return [j / n, (j + 1) / n];
}

// ---- hit shape helpers ----

function slice_pinned(k) {
    return shape_ovr.hasOwnProperty(String(k));
}

function eff_shape(k) {
    if (slice_pinned(k)) return shape_ovr[String(k)];
    return [g_attack, g_decay, g_sustain, g_release];
}

function shape_pack_ad(a, d) {
    return Math.round(clamp(a, 0.5, 200.0) * 10) * 2001 + Math.round(clamp(d, 1.0, 2000.0));
}

function shape_pack_sr(s, r) {
    return Math.round(clamp(s, 0.0, 100.0) * 10) * 2001 + Math.round(clamp(r, 1.0, 2000.0));
}

function lfo_mod_at(t_ms) {
    // per-hit tremolo: phase 0 at the hit (full volume), dips by depth
    if (g_lfo_depth <= 0.5) return 1.0;
    var ph = (t_ms / Math.max(1.0, g_lfo_period)) % 1.0;
    var w;
    if (g_lfo_shape === 1) w = 1.0 - Math.abs(ph * 2.0 - 1.0);
    else if (g_lfo_shape === 2) w = ph;
    else if (g_lfo_shape === 3) w = ph >= 0.5 ? 1.0 : 0.0;
    else w = 0.5 - 0.5 * Math.cos(ph * 6.2832);
    return 1.0 - clamp(g_lfo_depth, 0.0, 100.0) * 0.01 * w;
}

function curve_exp(c) {
    // -1..1 -> exponent (matches the gen~ shaper: exp(c*2), ~0.14..7.4).
    // c>0 -> exp>1 -> pow pulls the ramp down = soft/slow; c<0 -> punchy.
    return Math.exp(clamp(c, -1.0, 1.0) * 2.0);
}

function env_at(t_ms, a, d, s_pct, r, gate_ms) {
    // mirrors the voice VCA: A ramp (attack-curved), D to sustain, hold to the
    // gate (slice end), then R release tail (release-curved).
    var s01 = clamp(s_pct, 0.0, 100.0) * 0.01;
    if (t_ms <= 0.0) return 0.0;
    if (t_ms < a) {
        var la = t_ms / Math.max(0.1, a);
        return Math.pow(la, curve_exp(g_atk_curve));
    }
    var gate_lvl;
    var td = t_ms - a;
    if (t_ms <= gate_ms) {
        if (td < d) return 1.0 - (1.0 - s01) * (td / Math.max(1.0, d));
        return s01;
    }
    // level when the gate closed
    var tg = gate_ms - a;
    if (tg < 0.0) gate_lvl = clamp(gate_ms / Math.max(0.1, a), 0.0, 1.0);
    else if (tg < d) gate_lvl = 1.0 - (1.0 - s01) * (tg / Math.max(1.0, d));
    else gate_lvl = s01;
    var tr = t_ms - gate_ms;
    if (tr >= r) return 0.0;
    var lr = 1.0 - tr / Math.max(1.0, r);   // 1 -> 0 across the release
    return gate_lvl * Math.pow(lr, curve_exp(g_rel_curve));
}

function slice_dur_ms(k) {
    var fc = buffer_frames();
    if (fc <= 0 || sample_rate <= 0) return 0.0;
    var e = slice_edges(k);
    return (e[1] - e[0]) * (fc / sample_rate) * 1000.0;
}

function rebuild_zoom_cache() {
    zoom_cache = [];
    zoom_ready = 0;
    if (!loaded || inspect_k < 0) return;
    try {
        var b = new Buffer(BUFFER_NAME);
        var fc = b.framecount();
        var ch = b.channelcount();
        if (!fc || fc <= 0 || !ch || ch <= 0) return;
        var e = slice_edges(inspect_k);
        var f0 = Math.floor(e[0] * fc);
        var f1 = Math.max(f0 + 1, Math.floor(e[1] * fc));
        for (var i = 0; i < WAVE_POINTS; i++) {
            var sf = f0 + Math.floor((i / WAVE_POINTS) * (f1 - f0));
            var ef = f0 + Math.floor(((i + 1) / WAVE_POINTS) * (f1 - f0));
            if (ef <= sf) ef = sf + 1;
            var stride = Math.max(1, Math.floor((ef - sf) / 8));
            var peak = 0.0;
            for (var fr = sf; fr < ef; fr += stride) {
                var acc = 0.0;
                for (var c = 1; c <= ch; c++) {
                    var sv = b.peek(c, fr);
                    if (sv < 0.0) sv = -sv;
                    acc += sv;
                }
                acc = acc / ch;
                if (acc > peak) peak = acc;
            }
            zoom_cache[i] = clamp(peak, 0.0, 1.0);
        }
        zoom_ready = 1;
    } catch (err) {
        zoom_ready = 0;
    }
}

function enter_hit_view(k) {
    inspect_k = k;
    view = 1;
    rebuild_zoom_cache();
    outlet(4, 'hitview', 1);   // host scripts the real dial row in
    outlet(4, 'hitpage', hv_page);
    mgraphics.redraw();
}

function exit_hit_view() {
    view = 0;
    inspect_k = -1;
    drag_shape = 0;
    outlet(4, 'hitview', 0);
    mgraphics.redraw();
}

function emit_shape_pin(k) {
    var o = shape_ovr[String(k)];
    outlet(0, 'shapecoll', k, o[0], o[1], o[2], o[3]);
    outlet(0, 'shapelock', k, shape_pack_ad(o[0], o[1]), shape_pack_sr(o[2], o[3]));
}

function set_attack(v) {
    g_attack = clamp(v, 0.5, 200.0);
    if (view === 1) mgraphics.redraw();
}

function set_decay(v) {
    g_decay = clamp(v, 1.0, 2000.0);
    if (view === 1) mgraphics.redraw();
}

function set_sustain(v) {
    g_sustain = clamp(v, 0.0, 100.0);
    if (view === 1) mgraphics.redraw();
}

function set_release(v) {
    g_release = clamp(v, 1.0, 2000.0);
    if (view === 1) mgraphics.redraw();
}

function set_attack_curve(v) {
    g_atk_curve = clamp(v, -1.0, 1.0);
    if (view === 1) mgraphics.redraw();
}

function set_release_curve(v) {
    g_rel_curve = clamp(v, -1.0, 1.0);
    if (view === 1) mgraphics.redraw();
}

function set_lfo_depth(v) {
    g_lfo_depth = clamp(v, 0.0, 100.0);
    if (view === 1) mgraphics.redraw();
}

function set_lfo_period(v) {
    if (v > 0) g_lfo_period = v;
    if (view === 1) mgraphics.redraw();
}

function set_lfo_shape(v) {
    g_lfo_shape = clamp(Math.round(v), 0, 3);
    if (view === 1) mgraphics.redraw();
}

function openhit() {
    // host ENV button: open the hit view on the pattern's first slice
    if (!loaded) return;
    enter_hit_view(wrap_index(step_index(0)));
}

// ================= pattern side =================

function wrap_index(idx) {
    var slices = Math.max(1, Math.round(slice_count));
    return ((idx % slices) + slices) % slices;
}

function pseudo(seed, step, salt) {
    var s = Math.max(1, salt);
    return Math.abs((((step + 1) * ((seed % s) + 3)) + (seed * 17) + (step * step * 5)));
}

function normalize_locks() {
    var key;
    for (key in dir_locked_steps) {
        if (!dir_locked_steps.hasOwnProperty(key)) continue;
        dir_locked_steps[key] = Math.round(dir_locked_steps[key]) >= 0 ? 1 : -1;
    }
    for (key in pitch_locked_steps) {
        if (!pitch_locked_steps.hasOwnProperty(key)) continue;
        pitch_locked_steps[key] = clamp(Math.round(pitch_locked_steps[key]), -24, 24);
    }
    for (key in gate_locked_steps) {
        if (!gate_locked_steps.hasOwnProperty(key)) continue;
        gate_locked_steps[key] = Math.round(gate_locked_steps[key]) > 0 ? 1 : 0;
    }
    for (key in ratchet_locked_steps) {
        if (!ratchet_locked_steps.hasOwnProperty(key)) continue;
        ratchet_locked_steps[key] = clamp(Math.round(ratchet_locked_steps[key]), 0, 3);
    }
}

function is_step_locked(step) {
    return locked_steps.hasOwnProperty(String(step));
}

function step_locked_index(step) {
    if (!is_step_locked(step)) return -1;
    return wrap_index(Math.round(locked_steps[String(step)]));
}

function set_step_lock(step, idx) {
    locked_steps[String(step)] = wrap_index(Math.round(idx));
    dump_pattern();
}

function clear_locks() {
    locked_steps = {};
    dump_pattern();
}

function clear_dir_locks() {
    dir_locked_steps = {};
    dump_pattern();
}

function clear_pitch_locks() {
    pitch_locked_steps = {};
    dump_pattern();
}

function clear_level_locks() {
    level_locked_steps = {};
}

function clear_gate_locks() {
    gate_locked_steps = {};
    dump_pattern();
}

function clear_ratchet_locks() {
    ratchet_locked_steps = {};
    dump_pattern();
}

function clear_prob_locks() {
    prob_locked_steps = {};
}

function emit_scene_dump(slot) {
    var visible_steps = Math.max(1, Math.round(step_count));
    var i;
    for (i = 0; i < visible_steps; i++) {
        if (is_step_locked(i)) outlet(4, slot, 'set', i, step_locked_index(i));
        if (is_step_dir_locked(i)) outlet(4, slot, 'dirset', i, step_locked_direction(i));
        if (is_step_pitch_locked(i)) outlet(4, slot, 'pitchset', i, step_locked_pitch(i));
        if (is_step_gate_locked(i)) outlet(4, slot, 'gateset', i, step_locked_gate(i));
        if (is_step_ratchet_locked(i)) outlet(4, slot, 'ratchetset', i, step_locked_ratchet(i));
    }
}

function set_step_unlock(step) {
    if (!is_step_locked(step)) return;
    delete locked_steps[String(step)];
    outlet(0, 'unlock', step);
    dump_pattern();
}

function is_step_dir_locked(step) {
    return dir_locked_steps.hasOwnProperty(String(step));
}

function step_locked_direction(step) {
    if (!is_step_dir_locked(step)) return 0;
    return Math.round(dir_locked_steps[String(step)]) >= 0 ? 1 : -1;
}

function set_step_dir_lock(step, direction) {
    dir_locked_steps[String(step)] = Math.round(direction) >= 0 ? 1 : -1;
    dump_pattern();
}

function set_step_dir_unlock(step) {
    if (!is_step_dir_locked(step)) return;
    delete dir_locked_steps[String(step)];
    outlet(0, 'dirunlock', step);
    dump_pattern();
}

function is_step_pitch_locked(step) {
    return pitch_locked_steps.hasOwnProperty(String(step));
}

function step_locked_pitch(step) {
    if (!is_step_pitch_locked(step)) return 999;
    return clamp(Math.round(pitch_locked_steps[String(step)]), -24, 24);
}

function set_step_pitch_lock(step, semitone) {
    pitch_locked_steps[String(step)] = clamp(Math.round(semitone), -24, 24);
    dump_pattern();
}

function set_step_pitch_unlock(step) {
    if (!is_step_pitch_locked(step)) return;
    delete pitch_locked_steps[String(step)];
    outlet(0, 'pitchunlock', step);
    dump_pattern();
}

function is_step_gate_locked(step) {
    return gate_locked_steps.hasOwnProperty(String(step));
}

function step_locked_gate(step) {
    if (!is_step_gate_locked(step)) return -1;
    return Math.round(gate_locked_steps[String(step)]) > 0 ? 1 : 0;
}

function set_step_gate_lock(step, gate) {
    gate_locked_steps[String(step)] = Math.round(gate) > 0 ? 1 : 0;
    dump_pattern();
}

function is_step_level_locked(step) {
    return level_locked_steps.hasOwnProperty(String(step));
}

function step_locked_level(step) {
    if (!is_step_level_locked(step)) return -1.0;
    return clamp(level_locked_steps[String(step)], 0.1, 1.25);
}

function set_step_level_lock(step, lvl) {
    level_locked_steps[String(step)] = clamp(lvl, 0.1, 1.25);
    dump_pattern();
}

function set_step_level_unlock(step) {
    if (!is_step_level_locked(step)) return;
    delete level_locked_steps[String(step)];
    outlet(0, 'levelunlock', step);
    dump_pattern();
}

function set_step_gate_unlock(step) {
    if (!is_step_gate_locked(step)) return;
    delete gate_locked_steps[String(step)];
    outlet(0, 'gateunlock', step);
    dump_pattern();
}

function is_step_ratchet_locked(step) {
    return ratchet_locked_steps.hasOwnProperty(String(step));
}

function step_locked_ratchet(step) {
    if (!is_step_ratchet_locked(step)) return -1;
    return clamp(Math.round(ratchet_locked_steps[String(step)]), 0, 3);
}

function set_step_ratchet_lock(step, count) {
    ratchet_locked_steps[String(step)] = clamp(Math.round(count), 0, 3);
    dump_pattern();
}

function set_step_ratchet_unlock(step) {
    if (!is_step_ratchet_locked(step)) return;
    delete ratchet_locked_steps[String(step)];
    outlet(0, 'ratchetunlock', step);
    dump_pattern();
}

// ---- per-step trigger PROBABILITY (fills): 0..100. Absent = 100 (always).
// Modeled on the level lock: a dict + a -1 sentinel + dump_pattern on change.
function is_step_prob_locked(step) {
    return prob_locked_steps.hasOwnProperty(String(step));
}

function step_locked_prob(step) {
    if (!is_step_prob_locked(step)) return -1;
    return clamp(Math.round(prob_locked_steps[String(step)]), 0, 100);
}

function set_step_prob_lock(step, pr) {
    prob_locked_steps[String(step)] = clamp(Math.round(pr), 0, 100);
    dump_pattern();
}

function set_step_prob_unlock(step) {
    if (!is_step_prob_locked(step)) return;
    delete prob_locked_steps[String(step)];
    outlet(0, 'probunlock', step);
    dump_pattern();
}

function step_prob(step) {
    var lp = step_locked_prob(step);
    if (lp >= 0) return lp;
    return 100;
}

// ---- per-step TRIG CONDITION (cmd+ctrl drag): a CODE (see COND_CODES). The
// engine decides fire/skip against the live loop pass + fill. 0 = OFF (always).
function is_step_cond_locked(step) {
    return cond_locked_steps.hasOwnProperty(String(step));
}

function step_cond(step) {
    if (!is_step_cond_locked(step)) return 0;
    return Math.round(cond_locked_steps[String(step)]);
}

function set_step_cond_lock(step, code) {
    cond_locked_steps[String(step)] = Math.round(code);
    dump_pattern();
}

function set_step_cond_unlock(step) {
    if (!is_step_cond_locked(step)) return;
    delete cond_locked_steps[String(step)];
    outlet(0, 'condunlock', step);
    dump_pattern();
}

function clear_cond_locks() {
    cond_locked_steps = {};
}

function cond_label(code) {
    var i;
    for (i = 0; i < COND_CODES.length; i++) {
        if (COND_CODES[i] === code) return COND_LABELS[i];
    }
    return '?';
}

// PERSISTENCE PACKING: dir/gate/ratchet are tiny, set-only lanes (no per-step
// unlock gesture — only clear-all touches them), so they share ONE Stored-Only
// host per step. Encode into 0..44 (0 = all unset): dir 0/1/2, gate 0/1/2,
// ratchet 0..4, mixed-radix d + g*3 + r*9. Decoded in the 'dgr' lockrst branch.
function dgr_packed(step) {
    var d = is_step_dir_locked(step) ? (step_locked_direction(step) >= 0 ? 1 : 2) : 0;
    var g = is_step_gate_locked(step) ? (step_locked_gate(step) > 0 ? 2 : 1) : 0;
    var r = is_step_ratchet_locked(step) ? (clamp(Math.round(step_locked_ratchet(step)), 0, 3) + 1) : 0;
    return d + g * 3 + r * 9;
}

function step_base_index(step) {
    var slices = Math.max(1, Math.round(slice_count));
    var dist = Math.round(distance);
    var seed = Math.max(0, Math.round(pattern_seed));
    var rnd = pseudo(seed, step, 23) % slices;
    var base = (step * dist) % slices;
    if (mode <= 0) return base;
    if (mode === 1) return rnd;
    if (mode === 2) {
        return ((step * (((seed % 5) + 1) * dist)) + ((step * step) * ((seed % 3) + 1)) + (seed % slices)) % slices;
    }
    return (base + Math.floor((clamp(jump_amount, 0.0, 100.0) / 100.0) * rnd)) % slices;
}

function step_glitch_level(step) {
    return pseudo(Math.round(glitch_seed), step, 11) % 1000;
}

function vary_roll(step) {
    return pseudo(Math.round(vary_salt), step, 29) % 1000;
}

function drift_roll(step) {
    var bar_seed = Math.round(pattern_seed) + ((Math.round(form_bar) + 1) * 131);
    return pseudo(bar_seed, step, 31) % 1000;
}

function vary_hit(step) {
    return (vary_amount > 0.01) && (vary_roll(step) < vary_amount * 6.0);
}

function drift_hit(step) {
    return (drift_amount > 0.01) && (drift_roll(step) < drift_amount * 4.0);
}

function step_mutated(step) {
    return (vary_hit(step) || drift_hit(step)) ? 1 : 0;
}

function mut_index_shift(step) {
    var shift = 0;
    if (vary_hit(step)) {
        var pv = ((vary_roll(step) * 613) + 89) % 1000;
        var sv = 1 + (pv % 5);
        shift += ((pv % 2) === 1) ? -sv : sv;
    }
    if (drift_hit(step)) {
        var pd = ((drift_roll(step) * 389) + 57) % 1000;
        var sd = 1 + (pd % 3);
        shift += ((pd % 2) === 1) ? -sd : sd;
    }
    return shift;
}

function mut_gate_flip(step) {
    if (vary_hit(step) && ((((vary_roll(step) * 613) + 89) % 1000) % 7) === 0) return 1;
    if (drift_hit(step) && ((((drift_roll(step) * 389) + 57) % 1000) % 9) === 0) return 1;
    return 0;
}

function mut_ratchet_add(step) {
    if (vary_hit(step) && ((((vary_roll(step) * 613) + 89) % 1000) % 11) === 3) return 1;
    if (drift_hit(step) && ((((drift_roll(step) * 389) + 57) % 1000) % 13) === 5) return 1;
    return 0;
}

function fill_zone(step) {
    if (fill_active < 1 || fill_amount <= 0.01) return -1;
    var count = Math.max(1, Math.round(step_count));
    var start = count - Math.max(1, Math.floor(count / 4));
    if (step < start) return -1;
    return (step - start) / Math.max(1, (count - 1) - start);
}

function step_chopped(step) {
    if (chop_amount <= 0.01) return 0;
    return (pseudo(Math.round(chop_seed), step, 19) % 1000) < (chop_amount * 10.0) ? 1 : 0;
}

function step_ratchet_count(step) {
    var locked = step_locked_ratchet(step);
    if (locked >= 0) return locked;
    var fz = fill_zone(step);
    if (fz >= 0) {
        var fr = pseudo(Math.round(glitch_seed), step, 43) % 1000;
        if (fr < fill_amount * 8.0) return 2 + (fr % 2);
    }
    var level = step_glitch_level(step);
    var r = 0;
    if (glitch_amount >= 50.0) {
        if (level < (glitch_amount * 2.2)) r = 3;
        else if (level < (glitch_amount * 5.5)) r = 2;
        else if (level < (glitch_amount * 9.0)) r = 1;
    }
    if (r === 0 && mut_ratchet_add(step)) r = 1;
    return r;
}

function ratchet_direction(step) {
    return (((step + Math.round(glitch_seed)) % 4) < 2) ? 1 : -1;
}

function ratchet_shift(step, ratchet_no) {
    var dir = ratchet_direction(step);
    if (ratchet_no === 0) return dir;
    if (ratchet_no === 1) return dir * -2;
    return dir * 3;
}

function main_glitch_shift(step) {
    var level = step_glitch_level(step);
    var dir = ratchet_direction(step);
    if (glitch_amount < 36.0) return 0;
    if (level < (glitch_amount * 1.2)) return dir;
    if (level < (glitch_amount * 2.1)) return dir * -2;
    if (level < (glitch_amount * 3.0)) return dir * 3;
    return 0;
}

function step_computed_index(step) {
    return wrap_index(step_base_index(step) + main_glitch_shift(step) + mut_index_shift(step));
}

function step_index(step) {
    var locked = step_locked_index(step);
    if (locked >= 0) return locked;
    return step_computed_index(step);
}

function step_direction(step) {
    var locked = step_locked_direction(step);
    if (locked !== 0) return locked;
    if (dir_mode === 0) return 1.0;
    if (dir_mode === 2) return -1.0;
    return (((step + Math.round(pitch_seed)) % 2) === 0) ? 1.0 : -1.0;
}

function ratchet_index(step, ratchet_no) {
    return wrap_index(step_index(step) + ratchet_shift(step, ratchet_no));
}

function arp_index(step) {
    var seed = Math.max(0, Math.round(pitch_seed));
    return Math.abs(((step * ((seed % 5) + 2)) + (seed * 11) + ((step % 3) * 7)) % 8);
}

function arp_semitone(idx) {
    var table = SCALES[clamp(Math.round(scale_mode), 0, 3)];
    return table[clamp(Math.round(idx), 0, 7)];
}

function step_arp(step) {
    var sign = (((step + Math.round(pitch_seed)) % 4) < 2) ? 1.0 : -1.0;
    return arp_semitone(arp_index(step)) * sign * (clamp(arp_amount, 0.0, 100.0) / 100.0);
}

function step_pitch(step) {
    var locked = step_locked_pitch(step);
    if (locked !== 999) return locked;
    var p = step_arp(step);
    var fz = fill_zone(step);
    if (fz >= 0) {
        p = clamp(p + (fz * 12.0 * (clamp(fill_amount, 0.0, 100.0) / 100.0)), -24.0, 24.0);
    }
    return p;
}

function step_level(step) {
    if (step_gate(step) < 1) return 0.0;
    var ll = step_locked_level(step);
    if (ll >= 0.0) return ll;          // hand-set loudness wins
    if (chop_amount <= 0.01) return 1.0;
    var rm = pseudo(Math.round(chop_seed), step, 19) % 1000;
    var r = (rm * 613 + 89) % 1000;
    if (r < chop_amount * 7.0) return 0.45;
    if (r > 999 - chop_amount * 4.0) return 1.25;
    return 1.0;
}

// EUCLID (fills): N evenly-spaced hits across step_count, via the Bresenham
// accumulator (== Bjorklund up to rotation). Returns 1 (hit) / 0 (gap) for a
// step. Off (N<=0) or full (N>=M) -> all hits. Drives the GATE, so probability
// (step_prob) still composes ON TOP of the Euclid rhythm at the engine gate.
function euclid_hit(step) {
    var M = Math.max(1, Math.round(step_count));
    var N = Math.round(euclid_pulses);
    if (N <= 0 || N >= M) return 1;
    var rot = (((Math.round(euclid_rot) % M) + M) % M);
    var idx = ((((step - rot) % M) + M) % M);
    return (Math.floor((idx + 1) * N / M) > Math.floor(idx * N / M)) ? 1 : 0;
}

function step_gate(step) {
    var locked = step_locked_gate(step);
    if (locked >= 0) return locked;
    if (Math.round(euclid_pulses) > 0) return euclid_hit(step);   // Euclid defines the rhythm
    var fz = fill_zone(step);
    if (fz >= 0 && (pseudo(Math.round(chop_seed), step, 41) % 1000) < fill_amount * 9.0) {
        return 1;
    }
    var g = step_chopped(step) ? 0 : 1;
    if (mut_gate_flip(step)) g = 1 - g;
    return g;
}

// ---- gesture application (segments are the handles) ----

function seg_at_point(x, y) {
    var i;
    for (i = seg_x.length - 1; i >= 0; i--) {
        if (x >= seg_x[i] - 2 && x <= seg_x[i] + seg_w[i] + 2 &&
            y >= seg_y[i] - 2 && y <= seg_y[i] + seg_h[i] + 2) {
            return seg_step[i];
        }
    }
    return -1;
}

function step_at_x(x) {
    // Nearest step by horizontal distance to its bar center. A forgiving
    // fallback so a per-step gesture (shift/opt/ctrl/cmd drag) that misses the
    // NARROW bar still snaps to the step whose column it lands in, instead of
    // falling through to the slice-ENV editor. Returns -1 when no steps exist.
    var best = -1, bestd = 1e9, i;
    for (i = 0; i < seg_x.length; i++) {
        var cx = seg_x[i] + seg_w[i] * 0.5;
        var d = Math.abs(cx - x);
        if (d < bestd) { bestd = d; best = seg_step[i]; }
    }
    return best;
}

function apply_gesture(step, x, y) {
    if (drag_kind === 1) {
        var idx = slice_from_pos(x_to_pos(x));
        set_step_lock(step, idx);
        outlet(0, 'lock', step, idx);
    } else if (drag_kind === -1) {
        set_step_unlock(step);
        set_step_level_unlock(step);   // erase reverts the loudness edit too
        set_step_prob_unlock(step);    // ...and restores full trigger chance
        set_step_cond_unlock(step);    // ...and clears the trig condition
    } else if (drag_kind === 6) {
        var lvl6 = clamp(norm_from_y(y) * 1.25, 0.1, 1.25);
        set_step_level_lock(step, lvl6);
        outlet(0, 'levellock', step, lvl6);
    } else if (drag_kind === 2) {
        var direction = (norm_from_y(y) >= 0.5) ? 1 : -1;
        set_step_dir_lock(step, direction);
        outlet(0, 'dgrlock', step, dgr_packed(step));
    } else if (drag_kind === 3) {
        var semitone = clamp(Math.round((norm_from_y(y) * 48.0) - 24.0), -24, 24);
        set_step_pitch_lock(step, semitone);
        outlet(0, 'pitchlock', step, semitone);
    } else if (drag_kind === -3) {
        set_step_pitch_unlock(step);
    } else if (drag_kind === 4) {
        var gate = step_gate(step) > 0 ? 0 : 1;
        set_step_gate_lock(step, gate);
        outlet(0, 'dgrlock', step, dgr_packed(step));
    } else if (drag_kind === 5) {
        var count = clamp(Math.floor(norm_from_y(y) * 4.0), 0, 3);
        set_step_ratchet_lock(step, count);
        outlet(0, 'dgrlock', step, dgr_packed(step));
    } else if (drag_kind === 7) {
        var pr7 = clamp(Math.round(norm_from_y(y) * 100.0), 0, 100);
        set_step_prob_lock(step, pr7);
        outlet(0, 'problock', step, pr7);
    } else if (drag_kind === 8) {
        // EUCLID is GLOBAL: vertical drag sets pulse count 0..step_count. The
        // bars redraw live to the new rhythm; step ignored (any bar starts it).
        euclid_pulses = clamp(Math.round(norm_from_y(y) * Math.max(1, Math.round(step_count))), 0, 32);
        outlet(0, 'euclidset', euclid_pulses);   // persist (Stored-Only host)
        dump_pattern();
    } else if (drag_kind === 9) {
        // TRIG CONDITION: vertical drag picks from COND_CODES (OFF .. 1ST).
        var ci = clamp(Math.round(norm_from_y(y) * (COND_CODES.length - 1)), 0, COND_CODES.length - 1);
        set_step_cond_lock(step, COND_CODES[ci]);
        outlet(0, 'condlock', step, COND_CODES[ci]);
    }
    mgraphics.redraw();
}

var HV_DIALS_H = 52;   // reserved bottom band: label row + the REAL dial row

function hv_frame() {
    var iw = inner_w(), ih = inner_h();
    var top = PAD + 16, bot = PAD + ih - HV_DIALS_H;
    return [top, bot, (top + bot) * 0.5, (bot - top) * 0.5, iw];
}

function hv_span() {
    // time axis: the slice (gate) plus the release tail
    var dur = Math.max(1.0, slice_dur_ms(inspect_k));
    var o = eff_shape(inspect_k);
    return Math.max(dur * 1.1, dur + o[3] * 1.05);
}

function hv_x(t_ms) {
    var f = hv_frame();
    return PAD + clamp(t_ms / Math.max(1.0, hv_span()), 0.0, 1.0) * f[4];
}

function hv_t(x) {
    var f = hv_frame();
    return clamp((x - PAD) / Math.max(1, f[4]), 0.0, 1.0) * hv_span();
}

function hv_env_y(v) {
    var f = hv_frame();
    return f[1] - clamp(v, 0.0, 1.0) * (f[1] - f[0]);
}

function hv_attack_handle() {
    var o = eff_shape(inspect_k);
    return [hv_x(o[0]), hv_env_y(1.0)];
}

function hv_ds_handle() {
    var o = eff_shape(inspect_k);
    return [hv_x(o[0] + o[1]), hv_env_y(o[2] * 0.01)];
}

function hv_rel_handle() {
    var o = eff_shape(inspect_k);
    var dur = Math.max(1.0, slice_dur_ms(inspect_k));
    return [hv_x(dur + o[3]), hv_env_y(0.0)];
}

function hv_atk_curve_node() {
    // sits ON the attack curve at its time-midpoint — grab it to bend
    var o = eff_shape(inspect_k);
    var dur = Math.max(1.0, slice_dur_ms(inspect_k));
    var t = o[0] * 0.5;
    return [hv_x(t), hv_env_y(env_at(t, o[0], o[1], o[2], o[3], dur))];
}

function hv_rel_curve_node() {
    var o = eff_shape(inspect_k);
    var dur = Math.max(1.0, slice_dur_ms(inspect_k));
    var t = dur + o[3] * 0.5;
    return [hv_x(t), hv_env_y(env_at(t, o[0], o[1], o[2], o[3], dur))];
}

function hv_set_shape(a, d, s, r) {
    a = clamp(a, 0.5, 200.0);
    d = clamp(d, 1.0, 2000.0);
    s = clamp(s, 0.0, 100.0);
    r = clamp(r, 1.0, 2000.0);
    if (slice_pinned(inspect_k)) {
        shape_ovr[String(inspect_k)] = [a, d, s, r];
        emit_shape_pin(inspect_k);
    } else {
        // global edit: move the real params; their echo refreshes g_*
        if (a !== g_attack) outlet(4, 'shape', 'attack', a);
        if (d !== g_decay) outlet(4, 'shape', 'decay', d);
        if (s !== g_sustain) outlet(4, 'shape', 'sustain', s);
        if (r !== g_release) outlet(4, 'shape', 'release', r);
        g_attack = a; g_decay = d; g_sustain = s; g_release = r;
    }
    shape_dirty = 1;
    mgraphics.redraw();
}

function curve_from_point(lin, v) {
    // solve c from  v = pow(lin, exp(2c))  so the curve passes through the
    // cursor: exp(2c) = ln(v)/ln(lin) -> c = 0.5*ln( that ). GLOBAL curves.
    lin = clamp(lin, 0.02, 0.98);
    v = clamp(v, 0.02, 0.98);
    var ex = Math.log(v) / Math.log(lin);
    if (ex <= 0.0001) return 0.0;
    return clamp(0.5 * Math.log(ex), -1.0, 1.0);
}

function hv_set_attack_curve(x, y) {
    var o = eff_shape(inspect_k);
    var lt = clamp(hv_t(x) / Math.max(0.1, o[0]), 0.0, 1.0);  // linear attack frac
    var f = hv_frame();
    var v = clamp((f[1] - y) / Math.max(1, f[1] - f[0]), 0.0, 1.0);
    var c = curve_from_point(lt, v);
    if (c !== g_atk_curve) outlet(4, 'shape', 'attackcurve', c);
    g_atk_curve = c;
    shape_dirty = 1;
    mgraphics.redraw();
}

function hv_set_release_curve(x, y) {
    var o = eff_shape(inspect_k);
    var dur = Math.max(1.0, slice_dur_ms(inspect_k));
    var gate_lvl = clamp(o[2] * 0.01, 0.02, 1.0);
    var tr = clamp(hv_t(x) - dur, 0.0, o[3]);
    var lr = clamp(1.0 - tr / Math.max(1.0, o[3]), 0.0, 1.0);   // 1 -> 0
    var f = hv_frame();
    var v = clamp((f[1] - y) / Math.max(1, f[1] - f[0]), 0.0, 1.0) / gate_lvl;
    var c = curve_from_point(lr, v);
    if (c !== g_rel_curve) outlet(4, 'shape', 'releasecurve', c);
    g_rel_curve = c;
    shape_dirty = 1;
    mgraphics.redraw();
}

function hv_click(x, y) {
    var w = mgraphics.size[0];
    if (x < PAD + 40 && y < PAD + 13) { exit_hit_view(); return; }   // BACK
    if (y < PAD + 13 && x > w * 0.5 - 44 && x < w * 0.5 + 44) {      // ENV | LFO
        hv_page = (x < w * 0.5) ? 0 : 1;
        outlet(4, 'hitpage', hv_page);
        mgraphics.redraw();
        return;
    }
    if (x > w - PAD - 44 && y < PAD + 13) {                          // PIN
        if (slice_pinned(inspect_k)) {
            delete shape_ovr[String(inspect_k)];
            outlet(0, 'shapeunlock', inspect_k);
        } else {
            shape_ovr[String(inspect_k)] = [g_attack, g_decay, g_sustain, g_release];
            emit_shape_pin(inspect_k);
        }
        mgraphics.redraw();
        return;
    }
    var ah = hv_attack_handle();
    if (Math.abs(x - ah[0]) < 8 && Math.abs(y - ah[1]) < 10) { drag_shape = 1; return; }
    var dh = hv_ds_handle();
    if (Math.abs(x - dh[0]) < 8 && Math.abs(y - dh[1]) < 10) { drag_shape = 2; return; }
    var rh = hv_rel_handle();
    if (Math.abs(x - rh[0]) < 8 && Math.abs(y - rh[1]) < 10) { drag_shape = 3; return; }
    // curve NODES: a grabbable dot on each segment's midpoint (discoverable).
    var acn = hv_atk_curve_node();
    if (Math.abs(x - acn[0]) < 9 && Math.abs(y - acn[1]) < 9) { drag_shape = 4; hv_set_attack_curve(x, y); return; }
    var rcn = hv_rel_curve_node();
    if (Math.abs(x - rcn[0]) < 9 && Math.abs(y - rcn[1]) < 9) { drag_shape = 5; hv_set_release_curve(x, y); return; }
    // ...or grab anywhere along the attack / release SEGMENT to bend its curve
    // (only if the click sits near the drawn envelope line there).
    var o = eff_shape(inspect_k);
    var dur = Math.max(1.0, slice_dur_ms(inspect_k));
    var t = hv_t(x);
    var env_y = hv_env_y(env_at(t, o[0], o[1], o[2], o[3], dur));
    if (Math.abs(y - env_y) < 16) {   // generous grab: thin diagonal is hard to hit
        if (t > o[0] * 0.12 && t < o[0] * 0.9) { drag_shape = 4; hv_set_attack_curve(x, y); return; }
        if (t > dur + o[3] * 0.12 && t < dur + o[3] * 0.9) { drag_shape = 5; hv_set_release_curve(x, y); return; }
    }
    set_active_index(inspect_k);
    outlet(4, 'audition', inspect_k);
}

function hv_drag(x, y) {
    var o = eff_shape(inspect_k);
    var dur = Math.max(1.0, slice_dur_ms(inspect_k));
    var f = hv_frame();
    if (drag_shape === 1) {
        hv_set_shape(hv_t(x), o[1], o[2], o[3]);
    } else if (drag_shape === 2) {
        var s = clamp((f[1] - y) / Math.max(1, f[1] - f[0]), 0.0, 1.0) * 100.0;
        hv_set_shape(o[0], hv_t(x) - o[0], s, o[3]);
    } else if (drag_shape === 3) {
        hv_set_shape(o[0], o[1], o[2], hv_t(x) - dur);
    } else if (drag_shape === 4) {
        hv_set_attack_curve(x, y);
    } else if (drag_shape === 5) {
        hv_set_release_curve(x, y);
    }
}

function onclick(x, y, but, cmd, shift, capslock, option, ctrl) {
    if (view === 1 && !editable) {
        hv_click(x, y);
        return;
    }
    if (shift && cmd && !option && !ctrl) {
        clear_locks();
        clear_dir_locks();
        clear_pitch_locks();
        clear_gate_locks();
        clear_ratchet_locks();
        clear_level_locks();
        clear_prob_locks();
        clear_cond_locks();
        euclid_pulses = 0;
        outlet(0, 'euclidset', 0);
        outlet(0, 'clear');
        outlet(0, 'dgrclear');
        outlet(0, 'pitchclear');
        outlet(0, 'levelclear');
        outlet(0, 'probclear');
        outlet(0, 'condclear');
        mgraphics.redraw();
        return;
    }
    if (editable) {
        // editor instances: the whole surface is the divider editor
        drag_band = 1;
        var pos = x_to_pos(x);
        var didx = nearest_divider(pos);
        if (option || ctrl) {
            if (remove_divider(didx)) after_edit();
            drag_index = -1;
            return;
        }
        if (didx >= 1) { drag_index = didx; return; }
        if (add_divider(pos)) { drag_index = nearest_divider(pos); after_edit(); }
        return;
    }
    var step = seg_at_point(x, y);
    if (step < 0 && (shift || option || ctrl || cmd)) {
        // A per-step gesture modifier is held but the narrow bar was missed --
        // snap to the nearest step by x so the gesture lands (chance, pitch,
        // dir, erase, cond...) instead of opening the slice-ENV editor.
        step = step_at_x(x);
    }
    if (step >= 0) {
        drag_step = step;
        drag_x0 = x;
        drag_y0 = y;
        if (shift && option && !cmd && !ctrl) drag_kind = 5;
        else if (cmd && option && !ctrl) drag_kind = 4;
        else if (ctrl && shift && !cmd && !option) drag_kind = 8;   // ctrl+shift = EUCLID density (global)
        else if (cmd && ctrl && !shift && !option) drag_kind = 9;   // cmd+ctrl = TRIG CONDITION (per step)
        else if (ctrl) drag_kind = option ? -3 : 3;
        else if (option) drag_kind = 2;
        else if (shift && !option && !cmd && !ctrl) drag_kind = 7;   // shift-drag = CHANCE (per-step probability)
        else drag_kind = cmd ? -1 : 60;   // plain press: axis decides on move
        if (drag_kind !== 60) apply_gesture(step, x, y);
        return;
    }
    var idx = slice_from_pos(x_to_pos(x));
    set_active_index(idx);
    outlet(4, 'audition', idx);
    enter_hit_view(idx);
}

function ondrag(x, y, but, cmd, shift, capslock, option, ctrl) {
    if (but === 0) {
        if (drag_kind === 60 && drag_step >= 0 && view !== 1) {
            drag_kind = 1;                 // plain CLICK (no move) = pin, as before
            apply_gesture(drag_step, x, y);
        }
        if (view === 1 && shape_dirty) {
            shape_dirty = 0;
            set_active_index(inspect_k);
            outlet(4, 'audition', inspect_k);
        }
        drag_step = -1;
        drag_kind = 0;
        drag_index = -1;
        drag_band = 0;
        drag_shape = 0;
        return;
    }
    if (view === 1 && !editable) {
        if (drag_shape > 0) hv_drag(x, y);
        return;
    }
    if (drag_band === 1) {
        if (!editable) return;
        if (drag_index < 1 || drag_index > slice_boundaries.length - 2) return;
        var pos = x_to_pos(x);
        var lo = slice_boundaries[drag_index - 1] + MIN_GAP;
        var hi = slice_boundaries[drag_index + 1] - MIN_GAP;
        if (pos < lo) pos = lo;
        if (pos > hi) pos = hi;
        slice_boundaries[drag_index] = pos;
        after_edit();
        return;
    }
    if (drag_step < 0 || drag_kind === 0 || drag_kind === 4) return;
    if (drag_kind === 60) {
        var pdx = Math.abs(x - drag_x0);
        var pdy = Math.abs(y - drag_y0);
        if (pdx < 3 && pdy < 3) return;    // not moved enough to call the axis
        drag_kind = (pdx >= pdy) ? 1 : 6;
    }
    apply_gesture(drag_step, x, y);
}

function onidle(x, y, but, cmd, shift, capslock, option, ctrl) {
    hover_on = 1;
    hover_x = x;
    hover_y = y;
    mgraphics.redraw();
}

function onidleout(x, y, but, cmd, shift, capslock, option, ctrl) {
    hover_on = 0;
    hover_x = -1;
    hover_y = -1;
    mgraphics.redraw();
}

// ---- message plumbing ----

function msg_int(v) {
    msg_float(v);
}

function dump_pattern() {
    var vis = Math.max(1, Math.round(step_count));
    var i;
    for (i = 0; i < vis; i++) {
        var rc = step_ratchet_count(i);
        outlet(2, i, step_gate(i), step_pitch(i), Math.round(step_direction(i)), 1 + rc,
               step_level(i),
               step_index(i), rc >= 1 ? ratchet_index(i, 0) : -1,
               rc >= 2 ? ratchet_index(i, 1) : -1,
               rc >= 3 ? ratchet_index(i, 2) : -1,
               step_prob(i), step_cond(i));
    }
}

function dumppattern() {
    dump_pattern();
}

function anything() {
    var argv = arrayfromargs(arguments);
    var step;
    if (messagename === 'loaded' && argv.length >= 1) {
        loaded_flag(argv[0]);
        return;
    }
    // THEME BUS: live.colors broadcasts the user's Live skin here (any inlet), so
    // the canvas re-tints on load AND on a light/dark switch. Alpha defaults to 1.
    if (messagename === 'themebg' && argv.length >= 3) {
        TH_BG = [argv[0], argv[1], argv[2], argv.length > 3 ? argv[3] : 1.0];
        mgraphics.redraw();
        return;
    }
    if (messagename === 'themefg' && argv.length >= 3) {
        TH_TEXT = [argv[0], argv[1], argv[2], argv.length > 3 ? argv[3] : 1.0];
        mgraphics.redraw();
        return;
    }
    if (inlet !== 14) return;
    if (messagename === 'trigger' && argv.length >= 1) {
        var vis = Math.max(1, Math.round(step_count));
        var s = Math.round(argv[0]);
        s = ((s % vis) + vis) % vis;
        playhead_step = s;
        var rc = step_ratchet_count(s);
        var h0 = step_index(s);
        var h1 = rc >= 1 ? ratchet_index(s, 0) : -1;
        var h2 = rc >= 2 ? ratchet_index(s, 1) : -1;
        var h3 = rc >= 3 ? ratchet_index(s, 2) : -1;
        outlet(2, 'step', s, step_gate(s), step_pitch(s), step_direction(s), 1 + rc, step_level(s), h0, h1, h2, h3, step_prob(s), step_cond(s));
        mgraphics.redraw();
        return;
    }
    if (messagename === 'clear') {
        clear_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'dirclear') {
        clear_dir_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'pitchclear') {
        clear_pitch_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'gateclear') {
        clear_gate_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'ratchetclear') {
        clear_ratchet_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'levelclear') {
        clear_level_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'probclear') {
        clear_prob_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'condclear') {
        clear_cond_locks();
        mgraphics.redraw();
        return;
    }
    if ((messagename === 'shapesetA' || messagename === 'shapesetB') && argv.length >= 2) {
        // host restore, two packed hosts per slice:
        // A-host = round(a*10)*2001 + round(d); B-host = round(s*10)*2001 + round(r)
        var sk = Math.max(0, Math.round(argv[0]));
        var packed = Math.round(argv[1]);
        var kk = String(sk);
        if (packed >= 0) {
            if (!shape_ovr.hasOwnProperty(kk)) {
                shape_ovr[kk] = [g_attack, g_decay, g_sustain, g_release];
            }
            var hi = Math.floor(packed / 2001) / 10.0;
            var lo = packed % 2001;
            if (messagename === 'shapesetA') {
                shape_ovr[kk][0] = clamp(hi, 0.5, 200.0);
                shape_ovr[kk][1] = clamp(lo, 1.0, 2000.0);
            } else {
                shape_ovr[kk][2] = clamp(hi, 0.0, 100.0);
                shape_ovr[kk][3] = clamp(lo, 1.0, 2000.0);
            }
            outlet(0, 'shapecoll', sk, shape_ovr[kk][0], shape_ovr[kk][1],
                   shape_ovr[kk][2], shape_ovr[kk][3]);
        } else if (messagename === 'shapesetA') {
            delete shape_ovr[kk];
        }
        mgraphics.redraw();
        return;
    }
    if (messagename === 'shapeunset' && argv.length >= 1) {
        var uk = Math.max(0, Math.round(argv[0]));
        delete shape_ovr[String(uk)];
        mgraphics.redraw();
        return;
    }
    if (messagename === 'dumpa') {
        emit_scene_dump('a');
        return;
    }
    if (messagename === 'dumpb') {
        emit_scene_dump('b');
        return;
    }
    if (messagename === 'set' && argv.length >= 2) {
        step = Math.max(0, Math.round(argv[0]));
        if (argv[1] < 0) {
            delete locked_steps[String(step)];
            dump_pattern();
            mgraphics.redraw();
            return;
        }
        set_step_lock(step, argv[1]);
        normalize_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'unset' && argv.length >= 1) {
        step = Math.max(0, Math.round(argv[0]));
        delete locked_steps[String(step)];
        dump_pattern();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'dirset' && argv.length >= 2) {
        step = Math.max(0, Math.round(argv[0]));
        set_step_dir_lock(step, argv[1]);
        normalize_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'dirunset' && argv.length >= 1) {
        step = Math.max(0, Math.round(argv[0]));
        delete dir_locked_steps[String(step)];
        dump_pattern();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'pitchset' && argv.length >= 2) {
        step = Math.max(0, Math.round(argv[0]));
        set_step_pitch_lock(step, argv[1]);
        normalize_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'pitchunset' && argv.length >= 1) {
        step = Math.max(0, Math.round(argv[0]));
        delete pitch_locked_steps[String(step)];
        dump_pattern();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'gateset' && argv.length >= 2) {
        step = Math.max(0, Math.round(argv[0]));
        set_step_gate_lock(step, argv[1]);
        normalize_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'gateunset' && argv.length >= 1) {
        step = Math.max(0, Math.round(argv[0]));
        delete gate_locked_steps[String(step)];
        dump_pattern();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'ratchetset' && argv.length >= 2) {
        step = Math.max(0, Math.round(argv[0]));
        set_step_ratchet_lock(step, argv[1]);
        normalize_locks();
        mgraphics.redraw();
        return;
    }
    if (messagename === 'ratchetunset' && argv.length >= 1) {
        step = Math.max(0, Math.round(argv[0]));
        delete ratchet_locked_steps[String(step)];
        dump_pattern();
        mgraphics.redraw();
        return;
    }
    // --- unified lock-PERSISTENCE restore: the engine's Stored-Only hosts
    // replay one 'lockrst <lane> <step> <val>' per step on load. val <= -50 is
    // the unset sentinel -> nothing to restore (dicts start empty on load).
    // One path for every per-step lane; scene-recall handlers above untouched.
    if (messagename === 'lockrst' && argv.length >= 3) {
        if (argv[2] <= -50) return;
        var ln = argv[0];
        var rst = Math.max(0, Math.round(argv[1]));
        var rv = argv[2];
        if (ln === 'dgr') {
            var pk = Math.round(rv);
            var dd = pk % 3, gg = Math.floor(pk / 3) % 3, rr = Math.floor(pk / 9);
            if (dd === 1) set_step_dir_lock(rst, 1); else if (dd === 2) set_step_dir_lock(rst, -1);
            if (gg === 1) set_step_gate_lock(rst, 0); else if (gg === 2) set_step_gate_lock(rst, 1);
            if (rr >= 1) set_step_ratchet_lock(rst, rr - 1);
        }
        else if (ln === 'pitch') set_step_pitch_lock(rst, rv);
        else if (ln === 'level') set_step_level_lock(rst, rv);
        else if (ln === 'prob') set_step_prob_lock(rst, rv);
        else if (ln === 'cond') set_step_cond_lock(rst, rv);
        mgraphics.redraw();
        return;
    }
    if (messagename === 'euclidval' && argv.length >= 1) {
        euclid_pulses = clamp(Math.round(argv[0]), 0, 32);
        dump_pattern();
        mgraphics.redraw();
        return;
    }
}

function msg_float(v) {
    if (inlet === 0) step_count = clamp(Math.round(v), 1, 32);
    else if (inlet === 1) slice_count = clamp(Math.round(v), 1, 64);
    else if (inlet === 2) distance = clamp(Math.round(v), -8, 8);
    else if (inlet === 3) mode = clamp(Math.round(v), -1, 3);
    else if (inlet === 4) jump_amount = clamp(v, 0.0, 100.0);
    else if (inlet === 5) pattern_seed = Math.max(0, Math.round(v));
    else if (inlet === 6) chop_amount = clamp(v, 0.0, 100.0);
    else if (inlet === 7) chop_seed = Math.max(0, Math.round(v));
    else if (inlet === 8) glitch_amount = clamp(v, 0.0, 100.0);
    else if (inlet === 9) glitch_seed = Math.max(0, Math.round(v));
    else if (inlet === 10) playhead_step = Math.max(-1, Math.round(v));
    else if (inlet === 11) arp_amount = clamp(v, 0.0, 100.0);
    else if (inlet === 12) pitch_seed = Math.max(0, Math.round(v));
    else if (inlet === 13) dir_mode = clamp(Math.round(v), 0, 2);
    else if (inlet === 15) vary_amount = clamp(v, 0.0, 100.0);
    else if (inlet === 16) vary_salt = Math.max(0, Math.round(v));
    else if (inlet === 17) drift_amount = clamp(v, 0.0, 100.0);
    else if (inlet === 18) fill_amount = clamp(v, 0.0, 100.0);
    else if (inlet === 19) form_bar = Math.max(0, Math.round(v));
    else if (inlet === 20) fill_active = (v > 0.5) ? 1 : 0;
    else if (inlet === 21) scale_mode = clamp(Math.round(v), 0, 3);
    normalize_locks();
    if (inlet !== 10) dump_pattern();
    mgraphics.redraw();
}

// ---- painting ----

function draw_waveform(x, y, w, h) {
    var mid = y + h * 0.5;
    var amp = h * 0.40;
    mgraphics.set_source_rgba(@WAVE@);
    mgraphics.set_line_width(1.1);
    if (waveform_ready) {
        for (var i = 0; i < waveform_cache.length; i++) {
            var t = waveform_cache.length <= 1 ? 0.0 : i / (waveform_cache.length - 1);
            var nx = x + t * w;
            var ny = mid - waveform_cache[i] * amp;
            if (i === 0) {
                mgraphics.move_to(nx, ny);
            } else {
                mgraphics.line_to(nx, ny);
            }
        }
        mgraphics.stroke();
        mgraphics.set_source_rgba(@WAVE@);
        for (var j = 0; j < waveform_cache.length; j++) {
            var tt = waveform_cache.length <= 1 ? 0.0 : j / (waveform_cache.length - 1);
            var px = x + tt * w;
            var py = mid + waveform_cache[j] * amp;
            if (j === 0) {
                mgraphics.move_to(px, py);
            } else {
                mgraphics.line_to(px, py);
            }
        }
        mgraphics.stroke();
    }
}

function label_chip(x, y_base, txt) {
    // dark backing chip behind a small label so it reads over segments,
    // flash columns, and the waveform alike
    var tw = mgraphics.text_measure(txt)[0];
    th_bg();
    mgraphics.rectangle_rounded(x - 3, y_base - 8, tw + 6, 11, 3, 3);
    mgraphics.fill();
    th_text();
    mgraphics.move_to(x, y_base);
    mgraphics.show_text(txt);
}

// Always-on step-slot grid so the canvas is never an empty void. Faint vertical
// dividers at each step boundary, tinted from the
// theme fg so it adapts to any skin (light on dark, dark on light). Drawn under
// the waveform + bars so it structures the idle screen without cluttering.
function draw_step_grid() {
    var iw = inner_w();
    var ih = inner_h();
    var n = Math.max(1, Math.round(step_count));
    mgraphics.set_source_rgba(TH_TEXT[0], TH_TEXT[1], TH_TEXT[2], 0.10);
    mgraphics.set_line_width(1.0);
    for (var i = 0; i <= n; i++) {
        var gx = PAD + iw * (i / n);
        mgraphics.move_to(gx, PAD);
        mgraphics.line_to(gx, PAD + ih);
        mgraphics.stroke();
    }
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var iw = inner_w();
    var ih = inner_h();
    var i, k;

    seg_x = []; seg_y = []; seg_w = []; seg_h = []; seg_step = [];

    th_bg();
    mgraphics.rectangle_rounded(0, 0, w, h, 8, 8);
    mgraphics.fill();

    // always-on step grid (idle screen never blank)
    draw_step_grid();

    // quiet midline only -- the slice dividers structure the space
    mgraphics.set_source_rgba(@GRID@);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(PAD, PAD + ih * 0.5);
    mgraphics.line_to(PAD + iw, PAD + ih * 0.5);
    mgraphics.stroke();

    // lazy rebuild: the buffer~ replace is DEFERRED, so 'loaded 1' can arrive before
    // the buffer is fillable. Retry here (redraws keep coming from the playhead)
    // until it reads back, so the waveform appears without any user action.
    if (loaded && !waveform_ready && wave_retry > 0) {
        wave_retry--;
        rebuild_waveform_cache();
        if (waveform_ready) mgraphics.redraw();
    }

    if (!loaded || !waveform_ready) {
        var cx = PAD + iw * 0.5;
        th_text();
        mgraphics.select_font_face('Ableton Sans Medium');
        mgraphics.set_font_size(16);
        var hw = mgraphics.text_measure('DRAG A SAMPLE')[0];
        mgraphics.move_to(cx - hw * 0.5, PAD + ih * 0.5 + 5);
        mgraphics.show_text('DRAG A SAMPLE');
    } else if (view === 1) {
        paint_hit_view();
    } else {
        var slices = Math.max(1, Math.round(slice_count));
        var visible_steps = Math.max(1, Math.round(step_count));
        var dim = (mode < 0) ? 0.42 : 1.0;   // SEQ OFF: pattern dims, wave stays

        // group the steps by the slice they fire
        var by_slice = {}, sidx, key;
        var ord_cx = [], ord_txt = [];   // play-order numerals (drawn post-loop)
        for (i = 0; i < visible_steps; i++) {
            sidx = step_index(i);
            key = String(sidx);
            if (!by_slice[key]) by_slice[key] = [];
            by_slice[key].push(i);
        }

        // pinned-shape badge: a cream cap at the slice's column top
        for (k = 0; k < slices; k++) {
            if (!slice_pinned(k)) continue;
            var edges0 = slice_edges(k);
            var fx = norm_to_x(edges0[0]);
            var fw = Math.max(1, norm_to_x(edges0[1]) - fx);
            mgraphics.set_source_rgba(@GLITCH_RGB@, 0.75);
            mgraphics.rectangle(fx + 1, PAD + 2, Math.max(1, fw - 2), 1.5);
            mgraphics.fill();
        }

        draw_waveform(PAD, PAD, iw, ih);

        // slice dividers: quiet, neutral -- color belongs to the pattern
        if (slice_boundaries.length > 1) {
            for (i = 1; i < slice_boundaries.length - 1; i++) {
                var bdx = norm_to_x(slice_boundaries[i]);
                mgraphics.set_source_rgba(@DIVIDER@);
                mgraphics.set_line_width(0.8);
                mgraphics.move_to(bdx, PAD + 6);
                mgraphics.line_to(bdx, PAD + ih - 4);
                mgraphics.stroke();
            }
        }

        // ---- pattern bars: ONE bar per used slice (height = loudest step).
        // Hovering a slice splits its bar into the individual steps with
        // their ornaments — that's where dragging/re-pinning happens. The
        // always-on view stays glanceable: audio, what's used, how hard.
        var hover_slice = -1;
        if (hover_on) hover_slice = slice_from_pos(x_to_pos(hover_x));
        for (k = 0; k < slices; k++) {
            key = String(k);
            if (!by_slice[key]) continue;
            var hits = by_slice[key];
            var edges = slice_edges(k);
            var sx = norm_to_x(edges[0]);
            var ex = norm_to_x(edges[1]);
            var col_x = sx + 1.5;
            var col_w = Math.max(2, (ex - sx) - 3);
            var m = hits.length;
            var base_y = PAD + ih - 3;
            var split = (k === hover_slice);
            var slot = split ? Math.min(ih * 0.60, (ih * 0.78) / m) : 0;
            // aggregate: loudest live step + lock/mute presence
            var agg_lvl = 0.0, any_lock = 0, all_muted = 1, agg_rc = 0, agg_prob = 100, agg_cond = 0;
            for (i = 0; i < m; i++) {
                var st0 = hits[i];
                var lv0 = step_level(st0);
                if (lv0 > agg_lvl) agg_lvl = lv0;
                if (is_step_locked(st0)) any_lock = 1;
                if (step_gate(st0) > 0) {
                    all_muted = 0;
                    var pb0 = step_prob(st0);
                    if (pb0 < agg_prob) agg_prob = pb0;   // most-chancy live hit represents the column
                    if (agg_cond === 0) agg_cond = step_cond(st0);
                }
            }
            if (!split) {
                var bh = all_muted ? 4
                    : Math.max(6, ih * 0.62 * (0.35 + 0.65 * Math.min(agg_lvl, 1.25) / 1.25));
                var by = base_y - bh;
                var is_playing = 0;
                for (i = 0; i < m; i++) if (hits[i] === playhead_step) is_playing = 1;
                // trigger CHANCE: a step < 100% reads as a fainter (ghostlier)
                // bar — opacity carries probability, height still carries level.
                var pmul = 0.22 + 0.78 * Math.min(agg_prob, 100) / 100.0;
                if (is_playing) mgraphics.set_source_rgba(0.99, 0.97, 0.90, 0.92 * pmul);
                else mgraphics.set_source_rgba(ACCENT[0], ACCENT[1], ACCENT[2],
                    (all_muted ? 0.20 : (0.45 + 0.35 * Math.min(agg_lvl, 1.25) / 1.25)) * pmul * dim);
                mgraphics.rectangle_rounded(col_x, by, col_w, bh, 2, 2);
                mgraphics.fill();
                if (agg_lvl > 1.0) {   // accent cap
                    mgraphics.set_source_rgba(@GLITCH_RGB@, 0.95 * dim);
                    mgraphics.rectangle(col_x, by - 1.5, col_w, 1.5);
                    mgraphics.fill();
                }
                if (any_lock) {        // pinned: cream outline
                    mgraphics.set_source_rgba(@GLITCH_RGB@, 0.9 * dim);
                    mgraphics.set_line_width(1.0);
                    mgraphics.rectangle_rounded(col_x + 0.5, by + 0.5,
                                                Math.max(1, col_w - 1),
                                                Math.max(1, bh - 1), 2, 2);
                    mgraphics.stroke();
                }
                // step-order numeral (user ask): EVERY playing bar gets its
                // number — collected here, chip-drawn after the loop so
                // skinny bars can overflow their column without vanishing.
                // trig-condition marker: a small cyan pip inside the top-left of
                // a conditioned bar (distinct from the centered accent cap).
                if (agg_cond !== 0 && !all_muted) {
                    mgraphics.set_source_rgba(0.35, 0.85, 0.95, 0.92 * dim);
                    mgraphics.rectangle_rounded(col_x + 1.2, by + 1.2, 3, 3, 1, 1);
                    mgraphics.fill();
                }
                if (!all_muted) {
                    ord_cx.push(col_x + col_w * 0.5);
                    ord_txt.push(String(hits[0] + 1) + (m > 1 ? '+' : ''));
                }
                // hit-test rects still map to per-step geometry (clicking an
                // unsplit bar grabs the step that owns that spot)
                var hslot = Math.min(ih * 0.60, (ih * 0.78) / m);
                for (i = 0; i < m; i++) {
                    var sh = Math.max(6, (hslot - 2) * 0.8);
                    seg_x.push(col_x); seg_y.push(base_y - (i * hslot) - sh);
                    seg_w.push(col_w); seg_h.push(sh);
                    seg_step.push(hits[i]);
                }
                continue;
            }
            // ---- hovered slice: split into per-step segments + ornaments ----
            for (i = 0; i < m; i++) {
                var st = hits[i];
                var lvl = step_level(st);
                var gate = step_gate(st);
                var rc = step_ratchet_count(st);
                var seg_hh = gate < 1 ? 4
                    : Math.max(6, (slot - 2) * (0.45 + 0.44 * Math.min(lvl, 1.25)));
                var sy = base_y - (i * slot) - seg_hh;
                var alpha = gate < 1 ? 0.22 : (0.5 + 0.4 * Math.min(lvl, 1.25) / 1.25);
                alpha = alpha * (0.22 + 0.78 * Math.min(step_prob(st), 100) / 100.0);   // CHANCE -> opacity
                if (st === playhead_step) {
                    mgraphics.set_source_rgba(0.99, 0.97, 0.90, 0.92);
                } else {
                    mgraphics.set_source_rgba(ACCENT[0], ACCENT[1], ACCENT[2], alpha * dim);
                }
                mgraphics.rectangle_rounded(col_x, sy, col_w, seg_hh, 2, 2);
                mgraphics.fill();
                if (lvl > 1.0) {
                    mgraphics.set_source_rgba(@GLITCH_RGB@, 0.95 * dim);
                    mgraphics.rectangle(col_x, sy - 1.5, col_w, 1.5);
                    mgraphics.fill();
                }
                if (is_step_locked(st)) {
                    mgraphics.set_source_rgba(@GLITCH_RGB@, 0.9 * dim);
                    mgraphics.set_line_width(1.0);
                    mgraphics.rectangle_rounded(col_x + 0.5, sy + 0.5,
                                                Math.max(1, col_w - 1),
                                                Math.max(1, seg_hh - 1), 2, 2);
                    mgraphics.stroke();
                }
                if (rc > 0 && gate >= 1) {   // ratchet notches (hover only)
                    th_bg();
                    var t2;
                    for (t2 = 0; t2 < rc; t2++) {
                        mgraphics.rectangle(col_x, sy + 3 + t2 * 4, col_w, 1.4);
                        mgraphics.fill();
                    }
                }
                if (step_direction(st) < 0 && gate >= 1) {   // reversed chevron
                    mgraphics.set_source_rgba(@ARP_RGB@, 0.9 * dim);
                    mgraphics.set_line_width(1.0);
                    mgraphics.move_to(col_x + 4.5, sy + 1.5);
                    mgraphics.line_to(col_x + 1.5, sy + seg_hh * 0.5);
                    mgraphics.line_to(col_x + 4.5, sy + seg_hh - 1.5);
                    mgraphics.stroke();
                }
                var sp = step_pitch(st);
                if (Math.abs(sp) > 0.5 && gate >= 1) {   // pitched underline
                    mgraphics.set_source_rgba(@PITCH_RGB@,
                        (0.35 + 0.6 * Math.min(1, Math.abs(sp) / 24.0)) * dim);
                    mgraphics.rectangle(col_x, sy + seg_hh, col_w, 1.2);
                    mgraphics.fill();
                }
                seg_x.push(col_x); seg_y.push(sy);
                seg_w.push(col_w); seg_h.push(seg_hh);
                seg_step.push(st);
            }
        }

        // play-order numerals: every bar numbered. Centered on the column
        // (skinny bars overflow), tiny dark chip for contrast; neighbors
        // that would collide bump to a second row above (greedy 2-row).
        if (ord_cx.length) {
            mgraphics.select_font_face('Ableton Sans Medium');
            mgraphics.set_font_size(5.8);
            var row_end = [-9999, -9999];
            for (i = 0; i < ord_cx.length; i++) {
                var otw = mgraphics.text_measure(ord_txt[i])[0];
                var olx = ord_cx[i] - otw * 0.5;
                if (olx < PAD + 1) olx = PAD + 1;
                if (olx + otw > PAD + iw - 1) olx = PAD + iw - 1 - otw;
                var orow = (olx >= row_end[0] + 3) ? 0
                         : ((olx >= row_end[1] + 3) ? 1
                         : (row_end[0] <= row_end[1] ? 0 : 1));
                var oly = base_y - 2 - orow * 9;
                th_bg();
                mgraphics.rectangle_rounded(olx - 1.5, oly - 6, otw + 3, 8, 2, 2);
                mgraphics.fill();
                mgraphics.set_source_rgba(0.92, 0.90, 0.84, 0.92);
                mgraphics.move_to(olx, oly);
                mgraphics.show_text(ord_txt[i]);
                row_end[orow] = olx + otw;
            }
        }

        // recent hit flashes
        for (i = 0; i < recent_hits.length; i++) {
            var hx = norm_to_x(recent_hits[i]);
            var fade = (i + 1) / recent_hits.length;
            mgraphics.set_source_rgba(0.98, 0.90, 0.62, 0.10 + fade * 0.38);
            mgraphics.set_line_width(1.5 + fade * 2.0);
            mgraphics.move_to(hx, PAD + ih * 0.30);
            mgraphics.line_to(hx, PAD + ih - 4);
            mgraphics.stroke();
        }

        // active slice highlight
        if (active_end > active_start) {
            var asx = norm_to_x(active_start);
            var aex = norm_to_x(active_end);
            mgraphics.set_source_rgba(0.98, 0.90, 0.62, 0.14);
            mgraphics.rectangle(asx, PAD + 2, Math.max(1, aex - asx), ih - 4);
            mgraphics.fill();
            mgraphics.set_source_rgba(0.99, 0.96, 0.86, 0.95);
            mgraphics.set_line_width(1.6);
            mgraphics.move_to(asx, PAD + 3);
            mgraphics.line_to(asx, PAD + ih - 3);
            mgraphics.stroke();
        }

        // EUCLID readout: persistent (top-right) so the gesture-set density is
        // visible without hovering. The bars already redraw to the rhythm.
        if (Math.round(euclid_pulses) > 0) {
            mgraphics.select_font_face('Ableton Sans Medium');
            mgraphics.set_font_size(6.5);
            var etxt = 'EUC ' + Math.round(euclid_pulses) + '/' + Math.max(1, Math.round(step_count));
            var ewi = mgraphics.text_measure(etxt)[0];
            label_chip(PAD + iw - ewi - 4, PAD + 9, etxt);
            mgraphics.set_font_size(8);
        }

        // trig-condition drag: live readout of the code being set on the bar.
        if (drag_kind === 9 && drag_step >= 0) {
            mgraphics.select_font_face('Ableton Sans Medium');
            mgraphics.set_font_size(7);
            label_chip(PAD + 3, PAD + 9, 'COND  ' + cond_label(step_cond(drag_step)));
        }

        // hover feedback
        if (hover_on && !editable) {
            var hstep = seg_at_point(hover_x, hover_y);
            mgraphics.select_font_face('Ableton Sans Medium');
            mgraphics.set_font_size(8);
            if (hstep >= 0) {   // (labels below use chips via label_chip)
                for (i = 0; i < seg_step.length; i++) {
                    if (seg_step[i] !== hstep) continue;
                    mgraphics.set_source_rgba(0.99, 0.96, 0.86, 0.85);
                    mgraphics.set_line_width(1.0);
                    mgraphics.rectangle_rounded(seg_x[i] - 1, seg_y[i] - 1,
                                                seg_w[i] + 2, seg_h[i] + 2, 2, 2);
                    mgraphics.stroke();
                }
                var hsp = step_pitch(hstep);
                var pit = Math.abs(hsp) > 0.5
                    ? '  ' + (hsp > 0 ? '+' : '') + Math.round(hsp) + ' ST' : '';
                var hcond = step_cond(hstep);
                var clab = (hcond !== 0) ? '  [' + cond_label(hcond) + ']' : '';
                label_chip(PAD + 3, PAD + 9, 'STEP ' + (hstep + 1) + ' > SLICE '
                           + (step_index(hstep) + 1) + pit + clab);
                mgraphics.set_font_size(6.5);
                var legA = 'drag: ^v VOL   <> MOVE   sh CHANCE   opt DIR   ctrl PITCH';
                var legB = 'ctrl+sh EUCLID   cmd+ctrl COND   cmd+opt MUTE   sh+opt RATCHET   cmd ERASE';
                var lwA = mgraphics.text_measure(legA)[0];
                var lwB = mgraphics.text_measure(legB)[0];
                label_chip(PAD + (iw - lwA) * 0.5, PAD + ih - 13, legA);
                label_chip(PAD + (iw - lwB) * 0.5, PAD + ih - 5, legB);
                mgraphics.set_font_size(8);
            } else {
                var hidx = slice_from_pos(x_to_pos(hover_x));
                var hedges = slice_edges(hidx);
                var hrgb = slice_rgb(hidx);
                mgraphics.set_source_rgba(hrgb[0], hrgb[1], hrgb[2], 0.75);
                mgraphics.set_line_width(1.0);
                mgraphics.rectangle(norm_to_x(hedges[0]), PAD + 2,
                                    Math.max(1, norm_to_x(hedges[1]) - norm_to_x(hedges[0])),
                                    ih - 4);
                mgraphics.stroke();
                label_chip(PAD + 3, PAD + 9, 'SLICE ' + (hidx + 1) + ' - CLICK TO AUDITION');
            }
        }

        // playhead
        var ph = norm_to_x(playhead);
        mgraphics.set_source_rgba(@PLAYHEAD@);
        mgraphics.set_line_width(1.8);
        mgraphics.move_to(ph, PAD);
        mgraphics.line_to(ph, PAD + ih);
        mgraphics.stroke();

        // labels
        // (slice count readout lives in the SLICE card: SLICES setting + FOUND n)
        // (the HOLD A KEY tutorial hint is retired — Info View covers it)
    }

    mgraphics.set_source_rgba(@GRID@);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle_rounded(0.5, 0.5, w - 1, h - 1, 8, 8);
    mgraphics.stroke();
}

function paint_hit_view() {
    var w = mgraphics.size[0];
    var k = inspect_k;
    var f = hv_frame();
    var top = f[0], bot = f[1], iw = f[4];
    var mid = (top + bot) * 0.5, amp = (bot - top) * 0.5;
    var o = eff_shape(k);
    var dur = Math.max(1.0, slice_dur_ms(k));
    var span = hv_span();
    var rgb = slice_rgb(k);
    var pinned = slice_pinned(k);
    var i, t, ev, px, py;

    // gate line: where the slice (audio) ends and the release takes over
    var gx = hv_x(dur);
    mgraphics.set_source_rgba(0.55, 0.55, 0.58, 0.45);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(gx, top - 2);
    mgraphics.line_to(gx, bot + 2);
    mgraphics.stroke();

    if (zoom_ready) {
        var afrac = dur / span;   // audio occupies the pre-gate part of the axis
        // ghost: the raw slice audio, dim
        mgraphics.set_source_rgba(0.52, 0.64, 0.78, 0.16);
        mgraphics.set_line_width(1.0);
        for (i = 0; i < zoom_cache.length; i++) {
            px = PAD + (i / (zoom_cache.length - 1)) * iw * afrac;
            py = mid - zoom_cache[i] * amp;
            if (i === 0) mgraphics.move_to(px, py); else mgraphics.line_to(px, py);
        }
        mgraphics.stroke();
        for (i = 0; i < zoom_cache.length; i++) {
            px = PAD + (i / (zoom_cache.length - 1)) * iw * afrac;
            py = mid + zoom_cache[i] * amp;
            if (i === 0) mgraphics.move_to(px, py); else mgraphics.line_to(px, py);
        }
        mgraphics.stroke();

        // the shaped hit: peaks * envelope * LFO, in the slice's own hue
        mgraphics.set_source_rgba(rgb[0], rgb[1], rgb[2], 0.88);
        mgraphics.set_line_width(1.2);
        for (i = 0; i < zoom_cache.length; i++) {
            t = (i / (zoom_cache.length - 1)) * dur;
            ev = env_at(t, o[0], o[1], o[2], o[3], dur) * lfo_mod_at(t);
            px = PAD + (i / (zoom_cache.length - 1)) * iw * afrac;
            py = mid - zoom_cache[i] * ev * amp;
            if (i === 0) mgraphics.move_to(px, py); else mgraphics.line_to(px, py);
        }
        mgraphics.stroke();
        for (i = 0; i < zoom_cache.length; i++) {
            t = (i / (zoom_cache.length - 1)) * dur;
            ev = env_at(t, o[0], o[1], o[2], o[3], dur) * lfo_mod_at(t);
            px = PAD + (i / (zoom_cache.length - 1)) * iw * afrac;
            py = mid + zoom_cache[i] * ev * amp;
            if (i === 0) mgraphics.move_to(px, py); else mgraphics.line_to(px, py);
        }
        mgraphics.stroke();
    }

    // envelope outline across the full span (release tail past the gate)
    var flash = (last_active_k === k && playhead_step >= 0);
    var lfo_on = g_lfo_depth > 0.5;
    mgraphics.set_source_rgba(0.99, 0.96, 0.86, lfo_on ? 0.30 : (flash ? 0.95 : 0.65));
    mgraphics.set_line_width(1.2);
    var N = 192;
    for (i = 0; i <= N; i++) {
        t = (i / N) * span;
        ev = env_at(t, o[0], o[1], o[2], o[3], dur);
        px = PAD + (i / N) * iw;
        py = hv_env_y(ev);
        if (i === 0) mgraphics.move_to(px, py); else mgraphics.line_to(px, py);
    }
    mgraphics.stroke();
    if (lfo_on) {   // the tremolo-modulated envelope rides on top, in mint
        mgraphics.set_source_rgba(@PITCH_RGB@, flash ? 0.95 : 0.8);
        mgraphics.set_line_width(1.2);
        for (i = 0; i <= N; i++) {
            t = (i / N) * span;
            ev = env_at(t, o[0], o[1], o[2], o[3], dur) * lfo_mod_at(t);
            px = PAD + (i / N) * iw;
            py = hv_env_y(ev);
            if (i === 0) mgraphics.move_to(px, py); else mgraphics.line_to(px, py);
        }
        mgraphics.stroke();
    }

    // curve NODES: a mint DIAMOND on each segment's midpoint — drag to bend it
    // (a diamond reads as an interactive grip, distinct from the square A/D/S/R
    // handles; the mint matches the curve dials)
    var cns = [hv_atk_curve_node(), hv_rel_curve_node()];
    for (i = 0; i < cns.length; i++) {
        var cnx = cns[i][0], cny = cns[i][1];
        mgraphics.set_source_rgba(@PITCH_RGB@, 0.92);
        mgraphics.move_to(cnx, cny - 3.6);
        mgraphics.line_to(cnx + 3.6, cny);
        mgraphics.line_to(cnx, cny + 3.6);
        mgraphics.line_to(cnx - 3.6, cny);
        mgraphics.close_path();
        mgraphics.fill();
        th_bg();
        mgraphics.move_to(cnx, cny - 1.5);
        mgraphics.line_to(cnx + 1.5, cny);
        mgraphics.line_to(cnx, cny + 1.5);
        mgraphics.line_to(cnx - 1.5, cny);
        mgraphics.close_path();
        mgraphics.fill();
    }

    // handles: square grips (A, D/S, R)
    var hs = [hv_attack_handle(), hv_ds_handle(), hv_rel_handle()];
    for (i = 0; i < hs.length; i++) {
        mgraphics.set_source_rgba(0.99, 0.96, 0.86, 0.95);
        mgraphics.rectangle_rounded(hs[i][0] - 3.5, hs[i][1] - 3.5, 7, 7, 1.5, 1.5);
        mgraphics.fill();
        th_bg();
        mgraphics.rectangle_rounded(hs[i][0] - 1.5, hs[i][1] - 1.5, 3, 3, 1, 1);
        mgraphics.fill();
    }

    // header: BACK / title / ENV|LFO sub-tabs / PIN
    mgraphics.select_font_face('Ableton Sans Medium');
    mgraphics.set_font_size(8);
    mgraphics.set_source_rgba(0.72, 0.74, 0.78, 0.85);
    mgraphics.move_to(PAD + 2, PAD + 9);
    mgraphics.show_text('< BACK');
    mgraphics.set_source_rgba(rgb[0], rgb[1], rgb[2], 0.95);
    mgraphics.move_to(PAD + 46, PAD + 9);
    mgraphics.show_text('SLICE ' + (k + 1));
    // sub-tabs centered: the active one lit
    mgraphics.set_source_rgba(0.99, 0.96, 0.86, hv_page === 0 ? 0.95 : 0.35);
    mgraphics.move_to(w * 0.5 - 36, PAD + 9);
    mgraphics.show_text('ENV');
    mgraphics.set_source_rgba(0.72, 0.74, 0.78, 0.5);
    mgraphics.move_to(w * 0.5 - 8, PAD + 9);
    mgraphics.show_text('|');
    mgraphics.set_source_rgba(@PITCH_RGB@, hv_page === 1 ? 0.95 : 0.35);
    mgraphics.move_to(w * 0.5 + 2, PAD + 9);
    mgraphics.show_text('LFO');
    if (pinned) mgraphics.set_source_rgba(@GLITCH_RGB@, 0.95);
    else mgraphics.set_source_rgba(0.72, 0.74, 0.78, 0.55);
    mgraphics.move_to(w - PAD - 40, PAD + 9);
    mgraphics.show_text(pinned ? 'PINNED' : 'PIN');

    // A / D / S / R letters above the real dial row (the dials sit ON the
    // canvas via scripted overlay; label from here so they stay in sync)
    mgraphics.set_source_rgba(0.72, 0.74, 0.78, 0.8);
    mgraphics.set_font_size(6.5);
    var labels, lxs;
    if (hv_page === 0) {
        labels = ['ATTACK', 'DECAY', 'SUSTAIN', 'RELEASE', 'A.CRV', 'R.CRV'];
        lxs = [6, 54, 102, 150, 203, 245];      // canvas-local label lefts
    } else {
        labels = ['DEPTH', 'SHAPE', 'RATE', 'FREE HZ'];
        lxs = [6, 60, 120, 182];
    }
    for (i = 0; i < labels.length; i++) {
        mgraphics.move_to(PAD + lxs[i], bot + 9);
        mgraphics.show_text(labels[i]);
    }
}

"""


def performance_canvas_js(
    *,
    buffer_name="slicebuf",
    bg_color="0.07, 0.07, 0.08, 1.0",
    grid_color="0.18, 0.18, 0.20, 1.0",
    wave_color="0.52, 0.64, 0.78, 0.40",
    divider_color="0.55, 0.55, 0.58, 0.35",
    playhead_color="0.98, 0.95, 0.82, 0.95",
    text_color="0.72, 0.74, 0.78, 0.90",
    glitch_color="0.97, 0.92, 0.78, 1.0",
    arp_color="0.54, 0.63, 0.76, 1.0",
    pitch_color="0.47, 0.78, 0.67, 1.0",
):
    """Return JavaScript source for the fused performance canvas."""

    def rgb(color):
        return ", ".join(part.strip() for part in color.split(",")[:3])

    return (
        _TEMPLATE
        .replace("@BUFNAME@", buffer_name)
        .replace("@BG@", bg_color)
        .replace("@GRID@", grid_color)
        .replace("@WAVE@", wave_color)
        .replace("@DIVIDER@", divider_color)
        .replace("@PLAYHEAD@", playhead_color)
        .replace("@TEXT@", text_color)
        .replace("@GLITCH_RGB@", rgb(glitch_color))
        .replace("@ARP_RGB@", rgb(arp_color))
        .replace("@PITCH_RGB@", rgb(pitch_color))
    )
