"""Piano roll display engine for jsui.

Generates JavaScript code that renders a note grid display inside Max's jsui
object. Shows notes as colored cells with velocity-based opacity and a
playhead position indicator.

Inlets:
    0 -- Note data: "set row col velocity" messages
    1 -- Step position (int) for playhead

Outlets:
    (none -- display only)
"""

PIANO_ROLL_INLETS = 2
PIANO_ROLL_OUTLETS = 0


def piano_roll_js(*, rows=12, cols=16,
                  bg_color="0.07, 0.07, 0.08, 1.0",
                  note_color="0.45, 0.75, 0.65, 1.0",
                  grid_color="0.2, 0.2, 0.22, 0.5",
                  playhead_color="1.0, 1.0, 1.0, 0.3"):
    """Return JavaScript source for a piano roll display (Max jsui).

    Args:
        rows: Number of pitch rows.
        cols: Number of step columns.
        bg_color: Background color (RGBA string).
        note_color: Note cell color (RGBA string, alpha scaled by velocity).
        grid_color: Grid line color (RGBA string).
        playhead_color: Playhead indicator color (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    # Parse note_color RGB for velocity-based alpha
    nc = [s.strip() for s in note_color.split(",")]
    note_rgb = ", ".join(nc[:3])

    return (
        "// Piano Roll Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 0;\n"
        "\n"
        "// --- Configuration ---\n"
        f"var NUM_ROWS = {rows};\n"
        f"var NUM_COLS = {cols};\n"
        "var PADDING = 1;\n"
        "var playhead_pos = -1;\n"
        "\n"
        "// --- Note grid (rows x cols, values 0-127 velocity) ---\n"
        "var notes = [];\n"
        "var r, c;\n"
        "for (r = 0; r < NUM_ROWS; r++) {\n"
        "    notes[r] = [];\n"
        "    for (c = 0; c < NUM_COLS; c++) {\n"
        "        notes[r][c] = 0;\n"
        "    }\n"
        "}\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_int(v) {\n"
        "    if (inlet === 1) {\n"
        "        playhead_pos = v;\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_float(v) {\n"
        "    msg_int(Math.round(v));\n"
        "}\n"
        "\n"
        "function set(row, col, velocity) {\n"
        "    if (row >= 0 && row < NUM_ROWS && col >= 0 && col < NUM_COLS) {\n"
        "        notes[row][col] = velocity;\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    var cell_w = (w - PADDING) / NUM_COLS;\n"
        "    var cell_h = (h - PADDING) / NUM_ROWS;\n"
        "    var r, c;\n"
        "\n"
        "    // Draw note cells\n"
        "    for (r = 0; r < NUM_ROWS; r++) {\n"
        "        for (c = 0; c < NUM_COLS; c++) {\n"
        "            var vel = notes[r][c];\n"
        "            if (vel > 0) {\n"
        "                var alpha = vel / 127.0;\n"
        f"                mgraphics.set_source_rgba({note_rgb}, alpha);\n"
        "                mgraphics.rectangle(\n"
        "                    PADDING + c * cell_w,\n"
        "                    PADDING + r * cell_h,\n"
        "                    cell_w - PADDING,\n"
        "                    cell_h - PADDING\n"
        "                );\n"
        "                mgraphics.fill();\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "\n"
        "    // Grid lines\n"
        f"    mgraphics.set_source_rgba({grid_color});\n"
        "    mgraphics.set_line_width(0.5);\n"
        "    for (c = 0; c <= NUM_COLS; c++) {\n"
        "        var gx = PADDING + c * cell_w;\n"
        "        mgraphics.move_to(gx, 0);\n"
        "        mgraphics.line_to(gx, h);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "    for (r = 0; r <= NUM_ROWS; r++) {\n"
        "        var gy = PADDING + r * cell_h;\n"
        "        mgraphics.move_to(0, gy);\n"
        "        mgraphics.line_to(w, gy);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // Playhead\n"
        "    if (playhead_pos >= 0 && playhead_pos < NUM_COLS) {\n"
        f"        mgraphics.set_source_rgba({playhead_color});\n"
        "        mgraphics.rectangle(\n"
        "            PADDING + playhead_pos * cell_w,\n"
        "            0, cell_w, h\n"
        "        );\n"
        "        mgraphics.fill();\n"
        "    }\n"
        "}\n"
    )
