"""Resonance bank display engine for jsui.

Renders N vertical bars at resonance frequencies with height proportional
to gain. Bars are colored by gain intensity. Receives a flat list of
[freq, gain, freq, gain, ...] pairs via inlet.

Inlets:
    0 -- Interleaved [freq, gain, ...] list. Freq is Hz (20-20000),
         gain is normalized 0-1.

Outlets:
    (none -- display only)
"""

RESONANCE_BANK_INLETS = 1
RESONANCE_BANK_OUTLETS = 0


def resonance_bank_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                               bar_color="0.45, 0.75, 0.65, 1.0",
                               hot_color="1.0, 0.55, 0.2, 1.0"):
    """Return JavaScript source for a resonance bank display (Max jsui).

    Args:
        bg_color: Background color (RGBA string).
        bar_color: Base bar color at low gain (RGBA string).
        hot_color: Bar color at full gain (RGBA string), interpolated.

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    # Parse color components for interpolation
    bc = [s.strip() for s in bar_color.split(",")]
    hc = [s.strip() for s in hot_color.split(",")]
    bar_r, bar_g, bar_b = bc[0], bc[1], bc[2]
    hot_r, hot_g, hot_b = hc[0], hc[1], hc[2]

    return (
        "// Resonance Bank Display — generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 1;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var freqs = [];\n"
        "var gains = [];\n"
        "var num_bands = 0;\n"
        "\n"
        "// --- Constants ---\n"
        "var MIN_FREQ = 20;\n"
        "var MAX_FREQ = 20000;\n"
        "var PADDING = 4;\n"
        "var BAR_GAP = 1;\n"
        f"var BAR_R = {bar_r};\n"
        f"var BAR_G = {bar_g};\n"
        f"var BAR_B = {bar_b};\n"
        f"var HOT_R = {hot_r};\n"
        f"var HOT_G = {hot_g};\n"
        f"var HOT_B = {hot_b};\n"
        "\n"
        "// --- Input handler ---\n"
        "// Expects interleaved [freq, gain, freq, gain, ...]\n"
        "function msg_list() {\n"
        "    var i;\n"
        "    num_bands = Math.floor(arguments.length / 2);\n"
        "    freqs = [];\n"
        "    gains = [];\n"
        "    for (i = 0; i < num_bands; i++) {\n"
        "        freqs[i] = Math.max(MIN_FREQ, Math.min(MAX_FREQ, arguments[i * 2]));\n"
        "        gains[i] = Math.max(0, Math.min(1, arguments[i * 2 + 1]));\n"
        "    }\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "// --- Helpers ---\n"
        "function freq_to_x(freq, area_x, area_w) {\n"
        "    var log_min = Math.log(MIN_FREQ);\n"
        "    var log_max = Math.log(MAX_FREQ);\n"
        "    var log_f = Math.log(Math.max(MIN_FREQ, freq));\n"
        "    return area_x + ((log_f - log_min) / (log_max - log_min)) * area_w;\n"
        "}\n"
        "\n"
        "function lerp(a, b, t) {\n"
        "    return a + (b - a) * t;\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_x = PADDING;\n"
        "    var area_y = PADDING;\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "    var i;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Frequency axis grid (decade markers)\n"
        "    mgraphics.set_source_rgba(0.2, 0.2, 0.22, 0.35);\n"
        "    mgraphics.set_line_width(0.5);\n"
        "    var decades = [100, 1000, 10000];\n"
        "    var d;\n"
        "    for (d = 0; d < decades.length; d++) {\n"
        "        var gx = freq_to_x(decades[d], area_x, area_w);\n"
        "        mgraphics.move_to(gx, area_y);\n"
        "        mgraphics.line_to(gx, area_y + area_h);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    if (num_bands === 0) {\n"
        "        return;\n"
        "    }\n"
        "\n"
        "    // Determine bar width from number of bands, capped so bars don't overlap\n"
        "    var bar_w = Math.max(1, Math.floor(area_w / num_bands) - BAR_GAP);\n"
        "    if (bar_w > 20) {\n"
        "        bar_w = 20;\n"
        "    }\n"
        "\n"
        "    // Draw bars\n"
        "    for (i = 0; i < num_bands; i++) {\n"
        "        var gain = gains[i];\n"
        "        var bx = freq_to_x(freqs[i], area_x, area_w) - bar_w * 0.5;\n"
        "        var bar_h = gain * area_h;\n"
        "        var by = area_y + area_h - bar_h;\n"
        "\n"
        "        // Interpolate color by gain\n"
        "        var r = lerp(BAR_R, HOT_R, gain);\n"
        "        var g = lerp(BAR_G, HOT_G, gain);\n"
        "        var b = lerp(BAR_B, HOT_B, gain);\n"
        "        mgraphics.set_source_rgba(r, g, b, 0.85);\n"
        "        mgraphics.rectangle(bx, by, bar_w, bar_h);\n"
        "        mgraphics.fill();\n"
        "\n"
        "        // Bright cap at top of bar\n"
        "        if (bar_h > 2) {\n"
        "            mgraphics.set_source_rgba(r, g, b, 1.0);\n"
        "            mgraphics.rectangle(bx, by, bar_w, 2);\n"
        "            mgraphics.fill();\n"
        "        }\n"
        "    }\n"
        "}\n"
    )
