"""Sidechain envelope display engine for jsui.

Generates JavaScript code that renders a sidechain envelope display inside
Max's jsui object using mgraphics. Shows the input level as a vertical filled
bar and a horizontal threshold line.

Inlets:
    0 -- Level (float 0.0-1.0)
    1 -- Threshold (float 0.0-1.0)

Outlets:
    (none -- display only)
"""

SIDECHAIN_DISPLAY_INLETS = 2
SIDECHAIN_DISPLAY_OUTLETS = 0


def sidechain_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                          bar_color="0.45, 0.75, 0.65, 1.0",
                          threshold_color="0.9, 0.5, 0.2, 0.9"):
    """Return JavaScript source for a sidechain envelope display (Max jsui).

    Inlet 0 receives the current level (0.0-1.0). Inlet 1 receives the
    threshold position (0.0-1.0). Draws a vertical bar for level and a
    horizontal line for the threshold.

    Args:
        bg_color: Background color (RGBA string).
        bar_color: Envelope bar color (RGBA string).
        threshold_color: Threshold line color (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    return (
        "// Sidechain Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var level = 0.0;\n"
        "var threshold = 0.75;\n"
        "\n"
        "// --- Constants ---\n"
        "var PADDING = 2;\n"
        "var THRESHOLD_LINE_WIDTH = 1.5;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_float(v) {\n"
        "    if (inlet === 0) {\n"
        "        level = Math.max(0, Math.min(1, v));\n"
        "    } else if (inlet === 1) {\n"
        "        threshold = Math.max(0, Math.min(1, v));\n"
        "    }\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "function msg_int(v) {\n"
        "    msg_float(v);\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_x = PADDING;\n"
        "    var area_y = PADDING;\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Level bar (fills from bottom up)\n"
        "    var bar_h = level * area_h;\n"
        "    var bar_y = area_y + area_h - bar_h;\n"
        f"    mgraphics.set_source_rgba({bar_color});\n"
        "    mgraphics.rectangle(area_x, bar_y, area_w, bar_h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Threshold line (horizontal, position from top = 1 - threshold)\n"
        "    var thresh_y = area_y + (1.0 - threshold) * area_h;\n"
        f"    mgraphics.set_source_rgba({threshold_color});\n"
        "    mgraphics.set_line_width(THRESHOLD_LINE_WIDTH);\n"
        "    mgraphics.move_to(area_x, thresh_y);\n"
        "    mgraphics.line_to(area_x + area_w, thresh_y);\n"
        "    mgraphics.stroke();\n"
        "}\n"
    )
