"""Labels-only overlay for a compiled ``spectroscope~ @sono 1`` spectrogram.

The compiled object renders the scrolling time-frequency raster in native C++
(saturated heat colors). This v8ui sits transparently ON TOP and draws ONLY the
log-frequency axis ticks/labels + a thin frame — no fill, so the raster shows
through. Pair it with ``Device.add_compiled_display(..., overlay_js=...)`` (the
compiled box is added first → behind; this overlay second → in front).

Inlets:
    0 -- bang (redraw); display-only, no data.

Outlets:
    (none)
"""

SONOGRAM_OVERLAY_INLETS = 1
SONOGRAM_OVERLAY_OUTLETS = 0


def sonogram_overlay_js(
    *,
    text_color="0.64, 0.69, 0.76, 0.92",
    frame_color="0.32, 0.36, 0.42, 0.55",
    tick_color="0.70, 0.74, 0.80, 0.30",
    freq_min=20.0,
    freq_max=20000.0,
    labels=(50, 100, 200, 500, 1000, 2000, 5000, 10000),
    fontname="Ableton Sans Medium",
    fontsize=7.0,
) -> str:
    """Return v8ui source for a spectrogram's log-frequency axis overlay.

    Frequency is the VERTICAL axis (low at the bottom), matching
    ``spectroscope~ @sono 1 @logfreq 1``; labels sit in a left margin and ticks
    span the plot. ``labels`` is the set of Hz values to annotate within
    ``[freq_min, freq_max]``. All colors are ``"r, g, b, a"`` strings.
    """
    labels_js = ", ".join(str(float(v)) for v in labels)
    return (
        "// Sonogram overlay - generated by m4l-builder (v8ui, labels only)\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 1;\n"
        "outlets = 0;\n"
        "\n"
        f"var TEXT_CLR = [{text_color}];\n"
        f"var FRAME_CLR = [{frame_color}];\n"
        f"var TICK_CLR = [{tick_color}];\n"
        f"var FREQ_MIN = {float(freq_min)};\n"
        f"var FREQ_MAX = {float(freq_max)};\n"
        f"var FREQ_LABELS = [{labels_js}];\n"
        f'var FONT_NAME = "{fontname}";\n'
        f"var FONT_SIZE = {float(fontsize)};\n"
        "var MARGIN_L = 26;\n"
        "\n"
        "function log_norm(f) {\n"
        "    // 0 at FREQ_MIN .. 1 at FREQ_MAX on a log axis\n"
        "    var lo = Math.log(FREQ_MIN), hi = Math.log(FREQ_MAX);\n"
        "    return (Math.log(f) - lo) / (hi - lo);\n"
        "}\n"
        "\n"
        "function fmt_hz(f) {\n"
        "    if (f >= 1000) {\n"
        "        var k = f / 1000;\n"
        "        return (k === Math.floor(k) ? k.toFixed(0) : k.toFixed(1)) + 'k';\n"
        "    }\n"
        "    return f.toFixed(0);\n"
        "}\n"
        "\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var plot_x = MARGIN_L;\n"
        "    var plot_w = w - MARGIN_L;\n"
        "\n"
        "    // Frequency ticks + labels (freq is the vertical axis, low at bottom).\n"
        "    mgraphics.select_font_face(FONT_NAME);\n"
        "    mgraphics.set_font_size(FONT_SIZE);\n"
        "    mgraphics.set_line_width(1.0);\n"
        "    for (var i = 0; i < FREQ_LABELS.length; i++) {\n"
        "        var f = FREQ_LABELS[i];\n"
        "        if (f < FREQ_MIN || f > FREQ_MAX) continue;\n"
        "        var y = h - log_norm(f) * h;\n"
        "        mgraphics.set_source_rgba(TICK_CLR[0], TICK_CLR[1], TICK_CLR[2], TICK_CLR[3]);\n"
        "        mgraphics.move_to(plot_x, y);\n"
        "        mgraphics.line_to(plot_x + plot_w, y);\n"
        "        mgraphics.stroke();\n"
        "        mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], TEXT_CLR[3]);\n"
        "        var label = fmt_hz(f);\n"
        "        var ty = Math.max(FONT_SIZE, Math.min(h - 2, y + FONT_SIZE * 0.4));\n"
        "        mgraphics.move_to(3, ty);\n"
        "        mgraphics.show_text(label);\n"
        "    }\n"
        "\n"
        "    // Thin frame around the plot region.\n"
        "    mgraphics.set_source_rgba(FRAME_CLR[0], FRAME_CLR[1], FRAME_CLR[2], FRAME_CLR[3]);\n"
        "    mgraphics.set_line_width(1.0);\n"
        "    mgraphics.rectangle(plot_x + 0.5, 0.5, plot_w - 1, h - 1);\n"
        "    mgraphics.stroke();\n"
        "}\n"
        "\n"
        "function bang() { mgraphics.redraw(); }\n"
        "function msg_int(v) { mgraphics.redraw(); }\n"
    )
