"""Spectrum analyzer display engine for jsui.

Generates JavaScript code that renders a real-time spectrum analyzer inside
Max's jsui object using mgraphics (Cairo-based vector graphics). Also provides
a DSP helper that builds a bandpass filter bank to feed frequency data to
the display.

Inlets:
    0 -- List of float magnitudes (dB) for each frequency band
    1 -- Display mode: 0=bars, 1=smooth line, 2=filled (default)
"""

import math

from ..objects import newobj, patchline

SPECTRUM_INLETS = 2
SPECTRUM_OUTLETS = 0


def spectrum_analyzer_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                         bar_color="0.35, 0.60, 0.90, 0.8",
                         peak_color="0.85, 0.88, 0.92, 0.9",
                         grid_color="0.2, 0.2, 0.22, 0.5",
                         text_color="0.5, 0.5, 0.52, 1.0",
                         gradient=True):
    """Return JavaScript source for a spectrum analyzer display (Max jsui).

    The JS code renders incoming FFT/band magnitude data as a real-time
    spectrum display with three visualization modes, peak hold indicators,
    and exponential smoothing for fluid animation.

    Inlet 0 receives a list of floats (magnitude in dB per band).
    Inlet 1 receives an int/float for display mode (0=bars, 1=line, 2=filled).

    All color arguments are RGBA strings, e.g. ``"0.35, 0.60, 0.90, 0.8"``.

    Args:
        bg_color: Background color.
        bar_color: Default bar/line color (used when gradient is False).
        peak_color: Peak hold indicator color.
        grid_color: Grid line color.
        text_color: Axis label color.
        gradient: If True, color bars/line by frequency (blue to red).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    gradient_js = "true" if gradient else "false"

    # Parse the grid_color to derive a brighter version for the 0dB line
    _gc_parts = [s.strip() for s in grid_color.split(",")]
    grid_bright = _gc_parts[0] + ", " + _gc_parts[1] + ", " + _gc_parts[2] + ", 0.8"

    # Parse bar_color to derive a fill-alpha version
    _bc_parts = [s.strip() for s in bar_color.split(",")]
    bar_fill = _bc_parts[0] + ", " + _bc_parts[1] + ", " + _bc_parts[2] + ", 0.3"

    return (
        "// Spectrum Analyzer Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var fft_data = [];\n"
        "var displayed = [];\n"
        "var peaks = [];\n"
        "var mode = 2; // 0=bars, 1=line, 2=filled\n"
        "var USE_GRADIENT = " + gradient_js + ";\n"
        "\n"
        "// --- Constants ---\n"
        "var MIN_FREQ = 20;\n"
        "var MAX_FREQ = 20000;\n"
        "var MIN_DB = -60;\n"
        "var MAX_DB = 0;\n"
        "var DB_RANGE = MAX_DB - MIN_DB;\n"
        "var DECAY = 0.7;\n"
        "var PEAK_DECAY = 0.3; // dB per redraw\n"
        "var MARGIN_LEFT = 28;\n"
        "var MARGIN_RIGHT = 8;\n"
        "var MARGIN_TOP = 6;\n"
        "var MARGIN_BOTTOM = 16;\n"
        "var LOG_MIN = Math.log(MIN_FREQ) / Math.LN10;\n"
        "var LOG_MAX = Math.log(MAX_FREQ) / Math.LN10;\n"
        "var LOG_RANGE = LOG_MAX - LOG_MIN;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function list() {\n"
        "    var args = arrayfromargs(arguments);\n"
        "    if (inlet == 0) {\n"
        "        fft_data = args;\n"
        "        var n = fft_data.length;\n"
        "        // Resize displayed/peaks arrays when data length changes\n"
        "        if (displayed.length != n) {\n"
        "            displayed = [];\n"
        "            peaks = [];\n"
        "            for (var i = 0; i < n; i++) {\n"
        "                displayed.push(MIN_DB);\n"
        "                peaks.push(MIN_DB);\n"
        "            }\n"
        "        }\n"
        "        // Exponential smoothing + peak tracking\n"
        "        for (var i = 0; i < n; i++) {\n"
        "            var incoming = fft_data[i];\n"
        "            // Guard against NaN and out-of-range values\n"
        "            if (incoming != incoming || incoming === undefined) incoming = MIN_DB;\n"
        "            if (incoming < MIN_DB) incoming = MIN_DB;\n"
        "            if (incoming > MAX_DB) incoming = MAX_DB;\n"
        "            displayed[i] = displayed[i] * DECAY + incoming * (1.0 - DECAY);\n"
        "            if (displayed[i] > peaks[i]) {\n"
        "                peaks[i] = displayed[i];\n"
        "            } else {\n"
        "                peaks[i] = peaks[i] - PEAK_DECAY;\n"
        "                if (peaks[i] < MIN_DB) peaks[i] = MIN_DB;\n"
        "            }\n"
        "        }\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_float(v) {\n"
        "    if (inlet == 1) {\n"
        "        mode = Math.round(v);\n"
        "        if (mode < 0) mode = 0;\n"
        "        if (mode > 2) mode = 2;\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_int(v) { msg_float(v); }\n"
        "\n"
        "// --- Mapping helpers ---\n"
        "function freq_to_x(f, plot_x, plot_w) {\n"
        "    var logf = Math.log(Math.max(f, MIN_FREQ)) / Math.LN10;\n"
        "    return plot_x + ((logf - LOG_MIN) / LOG_RANGE) * plot_w;\n"
        "}\n"
        "\n"
        "function db_to_y(db, plot_y, plot_h) {\n"
        "    var clamped = db;\n"
        "    if (clamped < MIN_DB) clamped = MIN_DB;\n"
        "    if (clamped > MAX_DB) clamped = MAX_DB;\n"
        "    return plot_y + (1.0 - (clamped - MIN_DB) / DB_RANGE) * plot_h;\n"
        "}\n"
        "\n"
        "// Map bin index to frequency (logarithmically spaced bins)\n"
        "function bin_freq(i, n) {\n"
        "    var t = i / Math.max(n - 1, 1);\n"
        "    var log_f = LOG_MIN + t * LOG_RANGE;\n"
        "    return Math.pow(10, log_f);\n"
        "}\n"
        "\n"
        "// Frequency-based gradient color (blue -> cyan -> green -> yellow -> red)\n"
        "function freq_color(t) {\n"
        "    var r, g, b;\n"
        "    if (t < 0.25) {\n"
        "        var s = t / 0.25;\n"
        "        r = 0.15; g = 0.35 + 0.4 * s; b = 0.85 - 0.15 * s;\n"
        "    } else if (t < 0.5) {\n"
        "        var s = (t - 0.25) / 0.25;\n"
        "        r = 0.15 + 0.15 * s; g = 0.75 - 0.05 * s; b = 0.7 - 0.4 * s;\n"
        "    } else if (t < 0.75) {\n"
        "        var s = (t - 0.5) / 0.25;\n"
        "        r = 0.3 + 0.55 * s; g = 0.7 + 0.1 * s; b = 0.3 - 0.15 * s;\n"
        "    } else {\n"
        "        var s = (t - 0.75) / 0.25;\n"
        "        r = 0.85 + 0.1 * s; g = 0.8 - 0.55 * s; b = 0.15 - 0.05 * s;\n"
        "    }\n"
        "    return [r, g, b];\n"
        "}\n"
        "\n"
        "// --- Paint ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var plot_x = MARGIN_LEFT;\n"
        "    var plot_y = MARGIN_TOP;\n"
        "    var plot_w = w - MARGIN_LEFT - MARGIN_RIGHT;\n"
        "    var plot_h = h - MARGIN_TOP - MARGIN_BOTTOM;\n"
        "    var n = displayed.length;\n"
        "\n"
        "    // --- Background ---\n"
        "    mgraphics.set_source_rgba(" + bg_color + ");\n"
        "    mgraphics.rectangle_rounded(0, 0, w, h, 4, 4);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // --- dB grid lines ---\n"
        "    mgraphics.set_line_width(1);\n"
        "    var db_lines = [-48, -36, -24, -12, 0];\n"
        "    for (var i = 0; i < db_lines.length; i++) {\n"
        "        var db = db_lines[i];\n"
        "        var y = db_to_y(db, plot_y, plot_h);\n"
        "        if (db == 0) {\n"
        "            mgraphics.set_source_rgba(" + grid_bright + ");\n"
        "        } else {\n"
        "            mgraphics.set_source_rgba(" + grid_color + ");\n"
        "        }\n"
        "        mgraphics.move_to(plot_x, Math.round(y) + 0.5);\n"
        "        mgraphics.line_to(plot_x + plot_w, Math.round(y) + 0.5);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // --- dB labels ---\n"
        "    mgraphics.select_font_face(\"Ableton Sans Medium\");\n"
        "    mgraphics.set_font_size(8);\n"
        "    mgraphics.set_source_rgba(" + text_color + ");\n"
        "    for (var i = 0; i < db_lines.length; i++) {\n"
        "        var db = db_lines[i];\n"
        "        var y = db_to_y(db, plot_y, plot_h);\n"
        "        mgraphics.move_to(2, y + 3);\n"
        "        mgraphics.show_text(db + \"\");\n"
        "    }\n"
        "\n"
        "    // --- Frequency grid lines ---\n"
        "    var freq_grid = [100, 1000, 10000];\n"
        "    mgraphics.set_source_rgba(" + grid_color + ");\n"
        "    mgraphics.set_line_width(1);\n"
        "    for (var i = 0; i < freq_grid.length; i++) {\n"
        "        var x = freq_to_x(freq_grid[i], plot_x, plot_w);\n"
        "        mgraphics.move_to(Math.round(x) + 0.5, plot_y);\n"
        "        mgraphics.line_to(Math.round(x) + 0.5, plot_y + plot_h);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // --- Minor frequency grid ---\n"
        "    var freq_minor = [50, 200, 500, 2000, 5000];\n"
        "    var gc_parts = (\"" + grid_color + "\").split(\",\");\n"
        "    mgraphics.set_source_rgba(\n"
        "        parseFloat(gc_parts[0]),\n"
        "        parseFloat(gc_parts[1]),\n"
        "        parseFloat(gc_parts[2]),\n"
        "        parseFloat(gc_parts[3]) * 0.35\n"
        "    );\n"
        "    for (var i = 0; i < freq_minor.length; i++) {\n"
        "        var x = freq_to_x(freq_minor[i], plot_x, plot_w);\n"
        "        mgraphics.move_to(Math.round(x) + 0.5, plot_y);\n"
        "        mgraphics.line_to(Math.round(x) + 0.5, plot_y + plot_h);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // --- Frequency labels ---\n"
        "    mgraphics.set_font_size(8);\n"
        "    mgraphics.set_source_rgba(" + text_color + ");\n"
        "    var freq_labels = [\n"
        "        [100, \"100\"],\n"
        "        [1000, \"1k\"],\n"
        "        [10000, \"10k\"]\n"
        "    ];\n"
        "    for (var i = 0; i < freq_labels.length; i++) {\n"
        "        var x = freq_to_x(freq_labels[i][0], plot_x, plot_w);\n"
        "        mgraphics.move_to(x - 6, h - 3);\n"
        "        mgraphics.show_text(freq_labels[i][1]);\n"
        "    }\n"
        "\n"
        "    // --- Nothing to draw if no data ---\n"
        "    if (n < 1) return;\n"
        "\n"
        "    // --- Compute x positions and y values for each bin ---\n"
        "    var xs = [];\n"
        "    var ys = [];\n"
        "    var ts = []; // normalized 0..1 for gradient color\n"
        "    for (var i = 0; i < n; i++) {\n"
        "        var f = bin_freq(i, n);\n"
        "        xs.push(freq_to_x(f, plot_x, plot_w));\n"
        "        ys.push(db_to_y(displayed[i], plot_y, plot_h));\n"
        "        ts.push(i / Math.max(n - 1, 1));\n"
        "    }\n"
        "    var bottom_y = plot_y + plot_h;\n"
        "\n"
        "    // --- Draw spectrum based on mode ---\n"
        "    if (mode == 0) {\n"
        "        // === BARS MODE ===\n"
        "        for (var i = 0; i < n; i++) {\n"
        "            var x0, x1;\n"
        "            if (i == 0) {\n"
        "                x0 = xs[0];\n"
        "            } else {\n"
        "                x0 = (xs[i - 1] + xs[i]) / 2;\n"
        "            }\n"
        "            if (i == n - 1) {\n"
        "                x1 = xs[n - 1];\n"
        "            } else {\n"
        "                x1 = (xs[i] + xs[i + 1]) / 2;\n"
        "            }\n"
        "            var bar_gap = 1;\n"
        "            var bx = x0 + bar_gap;\n"
        "            var bw = (x1 - x0) - bar_gap * 2;\n"
        "            if (bw < 1) bw = 1;\n"
        "            var bar_h = bottom_y - ys[i];\n"
        "            if (bar_h < 0) bar_h = 0;\n"
        "\n"
        "            if (USE_GRADIENT) {\n"
        "                var c = freq_color(ts[i]);\n"
        "                mgraphics.set_source_rgba(c[0], c[1], c[2], 0.8);\n"
        "            } else {\n"
        "                mgraphics.set_source_rgba(" + bar_color + ");\n"
        "            }\n"
        "            mgraphics.rectangle(bx, ys[i], bw, bar_h);\n"
        "            mgraphics.fill();\n"
        "        }\n"
        "    } else if (mode == 1) {\n"
        "        // === SMOOTH LINE MODE ===\n"
        "        mgraphics.set_line_width(2);\n"
        "        if (!USE_GRADIENT) {\n"
        "            mgraphics.set_source_rgba(" + bar_color + ");\n"
        "            mgraphics.move_to(xs[0], ys[0]);\n"
        "            for (var i = 1; i < n; i++) {\n"
        "                mgraphics.line_to(xs[i], ys[i]);\n"
        "            }\n"
        "            mgraphics.stroke();\n"
        "        } else {\n"
        "            // Per-segment gradient color\n"
        "            for (var i = 0; i < n - 1; i++) {\n"
        "                var c = freq_color((ts[i] + ts[i + 1]) / 2);\n"
        "                mgraphics.set_source_rgba(c[0], c[1], c[2], 0.9);\n"
        "                mgraphics.set_line_width(2);\n"
        "                mgraphics.move_to(xs[i], ys[i]);\n"
        "                mgraphics.line_to(xs[i + 1], ys[i + 1]);\n"
        "                mgraphics.stroke();\n"
        "            }\n"
        "        }\n"
        "    } else {\n"
        "        // === FILLED MODE (default) ===\n"
        "        if (!USE_GRADIENT) {\n"
        "            // Solid fill\n"
        "            mgraphics.set_source_rgba(" + bar_fill + ");\n"
        "            mgraphics.move_to(xs[0], bottom_y);\n"
        "            for (var i = 0; i < n; i++) {\n"
        "                mgraphics.line_to(xs[i], ys[i]);\n"
        "            }\n"
        "            mgraphics.line_to(xs[n - 1], bottom_y);\n"
        "            mgraphics.close_path();\n"
        "            mgraphics.fill();\n"
        "            // Top edge stroke\n"
        "            mgraphics.set_source_rgba(" + bar_color + ");\n"
        "            mgraphics.set_line_width(2);\n"
        "            mgraphics.move_to(xs[0], ys[0]);\n"
        "            for (var i = 1; i < n; i++) {\n"
        "                mgraphics.line_to(xs[i], ys[i]);\n"
        "            }\n"
        "            mgraphics.stroke();\n"
        "        } else {\n"
        "            // Gradient fill: vertical slices with per-slice color\n"
        "            for (var i = 0; i < n - 1; i++) {\n"
        "                var c = freq_color((ts[i] + ts[i + 1]) / 2);\n"
        "                mgraphics.set_source_rgba(c[0], c[1], c[2], 0.25);\n"
        "                mgraphics.move_to(xs[i], bottom_y);\n"
        "                mgraphics.line_to(xs[i], ys[i]);\n"
        "                mgraphics.line_to(xs[i + 1], ys[i + 1]);\n"
        "                mgraphics.line_to(xs[i + 1], bottom_y);\n"
        "                mgraphics.close_path();\n"
        "                mgraphics.fill();\n"
        "            }\n"
        "            // Gradient stroke along the top edge\n"
        "            for (var i = 0; i < n - 1; i++) {\n"
        "                var c = freq_color((ts[i] + ts[i + 1]) / 2);\n"
        "                mgraphics.set_source_rgba(c[0], c[1], c[2], 0.9);\n"
        "                mgraphics.set_line_width(2);\n"
        "                mgraphics.move_to(xs[i], ys[i]);\n"
        "                mgraphics.line_to(xs[i + 1], ys[i + 1]);\n"
        "                mgraphics.stroke();\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "\n"
        "    // --- Peak hold dots ---\n"
        "    mgraphics.set_source_rgba(" + peak_color + ");\n"
        "    for (var i = 0; i < n; i++) {\n"
        "        var peak_y = db_to_y(peaks[i], plot_y, plot_h);\n"
        "        if (peaks[i] > MIN_DB + 1) {\n"
        "            mgraphics.ellipse(xs[i] - 2, peak_y - 2, 4, 4);\n"
        "            mgraphics.fill();\n"
        "        }\n"
        "    }\n"
        "}\n"
    )


def spectrum_analyzer_dsp(device, jsui_id, source_id, source_outlet=0,
                          num_bands=32, id_prefix="spec",
                          target_inlet=0, min_db=-60.0, max_db=0.0,
                          peak_window=256, q_min=3.0, q_max=22.0):
    """Add a bandpass filter bank + peak detection chain to feed a jsui display.

    Creates logarithmically-spaced reson~ bandpass filters from 20 Hz to 20 kHz,
    each followed by a peakamp~ for level detection. A metro triggers snapshot
    reads via a bang chain, and results are collected into a list via zl.group
    then sent to the jsui.

    Signal flow per band:
        source -> reson~ (bandpass) -> peakamp~ 1024 -> atodb -> clip min_db max_db -> zl.group

    The zl.group fires a complete list of num_bands values to the jsui every
    time it accumulates enough values.

    Args:
        device: The Device instance to add objects to.
        jsui_id: ID of the jsui object to send spectrum data to.
        source_id: ID of the source audio object to tap.
        source_outlet: Outlet index on the source object.
        num_bands: Number of frequency bands (default 32).
        id_prefix: Prefix for generated object IDs.
        target_inlet: Inlet on the destination jsui/listener (default 0).
        min_db: Floor for analyzer values before grouping.
        max_db: Ceiling for analyzer values before grouping.
    """
    p = id_prefix

    # Compute logarithmically-spaced center frequencies from 20 Hz to 20 kHz
    log_min = math.log10(20.0)
    log_max = math.log10(20000.0)
    freqs = []
    for i in range(num_bands):
        t = i / max(num_bands - 1, 1)
        freqs.append(10.0 ** (log_min + t * (log_max - log_min)))

    # zl.group collects num_bands values into a single list
    device.add_newobj(f"{p}_group", f"zl.group {num_bands}",
                      numinlets=2, numoutlets=2, outlettype=["", ""])

    # Connect group output list to jsui inlet 0
    device.add_line(f"{p}_group", 0, jsui_id, target_inlet)

    # Add bandpass + peak detection for each frequency band
    for i in range(num_bands):
        freq = freqs[i]
        # Use a narrower high-frequency analysis band so the graph reads more like a spectrum.
        q = q_min + (i / max(num_bands - 1, 1)) * (q_max - q_min)

        # reson~ bandpass filter: 4 inlets (signal, freq, q, gain), 1 outlet
        reson_id = f"{p}_bp_{i}"
        device.add_newobj(reson_id, f"reson~ {freq:.1f} {q:.1f} 1.",
                          numinlets=4, numoutlets=1,
                          outlettype=["signal"])
        device.add_line(source_id, source_outlet, reson_id, 0)

        # peakamp~ window controls temporal resolution of the analyzer.
        peak_id = f"{p}_peak_{i}"
        device.add_newobj(peak_id, f"peakamp~ {int(peak_window)}",
                          numinlets=1, numoutlets=1,
                          outlettype=["float"])
        device.add_line(reson_id, 0, peak_id, 0)

        # atodb: convert linear amplitude to dB
        db_id = f"{p}_db_{i}"
        device.add_newobj(db_id, "atodb", numinlets=1, numoutlets=1,
                          outlettype=[""])
        device.add_line(peak_id, 0, db_id, 0)

        # clip magnitude to the display range before grouping
        clip_id = f"{p}_clip_{i}"
        device.add_newobj(clip_id, f"clip {min_db:.1f} {max_db:.1f}", numinlets=3, numoutlets=1,
                          outlettype=[""])
        device.add_line(db_id, 0, clip_id, 0)

        # Feed clipped dB value into zl.group
        device.add_line(clip_id, 0, f"{p}_group", 0)
