"""Spectral bin display engine for jsui.

Generates JavaScript code that renders spectral magnitude bins as vertical
bars inside Max's jsui object using mgraphics. A horizontal threshold line
dims bars below it to indicate which frequencies are above the threshold.

Inlets:
    0 -- List of bin magnitudes (float 0.0-1.0 per bin)
    1 -- Threshold (float 0.0-1.0)

Outlets:
    (none -- display only)
"""

SPECTRAL_DISPLAY_INLETS = 2
SPECTRAL_DISPLAY_OUTLETS = 0


def spectral_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                         bar_color="0.35, 0.60, 0.90, 0.8",
                         threshold_color="0.9, 0.5, 0.2, 0.9"):
    """Return JavaScript source for a spectral bin display (Max jsui).

    Inlet 0 receives a list of magnitude floats (0.0-1.0). Inlet 1 receives
    a threshold float (0.0-1.0). Bars below the threshold are drawn at
    reduced opacity.

    Args:
        bg_color: Background color (RGBA string).
        bar_color: Bar color (RGBA string).
        threshold_color: Threshold line color (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    bc = [s.strip() for s in bar_color.split(",")]
    bar_dim = bc[0] + ", " + bc[1] + ", " + bc[2] + ", 0.25"
    bar_cap = bc[0] + ", " + bc[1] + ", " + bc[2] + ", 1.0"
    bar_cap_dim = bc[0] + ", " + bc[1] + ", " + bc[2] + ", 0.4"

    return (
        "// Spectral Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var bins = [];\n"
        "var threshold = 0.5;\n"
        "\n"
        "// --- Constants ---\n"
        "var PADDING = 2;\n"
        "var BAR_GAP = 1;\n"
        "var THRESHOLD_LINE_WIDTH = 1.5;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_list() {\n"
        "    if (inlet === 0) {\n"
        "        bins = arrayfromargs(arguments);\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_float(v) {\n"
        "    if (inlet === 1) {\n"
        "        threshold = Math.max(0, Math.min(1, v));\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_int(v) {\n"
        "    msg_float(v);\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_x = PADDING;\n"
        "    var area_y = PADDING;\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "    var n = bins.length;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Draw each bin as a vertical bar\n"
        "    if (n > 0) {\n"
        "        var bar_w = (area_w - BAR_GAP) / n - BAR_GAP;\n"
        "        if (bar_w < 1) bar_w = 1;\n"
        "        var i;\n"
        "        for (i = 0; i < n; i++) {\n"
        "            var mag = bins[i];\n"
        "            if (mag != mag) mag = 0;\n"
        "            if (mag < 0) mag = 0;\n"
        "            if (mag > 1) mag = 1;\n"
        "            var bar_h = mag * area_h;\n"
        "            var bx = area_x + i * (bar_w + BAR_GAP);\n"
        "            var by = area_y + area_h - bar_h;\n"
        "            if (mag >= threshold) {\n"
        f"                mgraphics.set_source_rgba({bar_color});\n"
        "            } else {\n"
        f"                mgraphics.set_source_rgba({bar_dim});\n"
        "            }\n"
        "            mgraphics.rectangle(bx, by, bar_w, bar_h);\n"
        "            mgraphics.fill();\n"
        "            // Bright cap on top of bar (2px highlight)\n"
        "            if (bar_h > 2) {\n"
        "                if (mag >= threshold) {\n"
        f"                    mgraphics.set_source_rgba({bar_cap});\n"
        "                } else {\n"
        f"                    mgraphics.set_source_rgba({bar_cap_dim});\n"
        "                }\n"
        "                mgraphics.rectangle(bx, by, bar_w, 2);\n"
        "                mgraphics.fill();\n"
        "            }\n"
        "        }\n"
        "    }\n"
        "\n"
        "    // Threshold line (horizontal, position from top = 1 - threshold)\n"
        "    var thresh_y = area_y + (1.0 - threshold) * area_h;\n"
        f"    mgraphics.set_source_rgba({threshold_color});\n"
        "    mgraphics.set_line_width(THRESHOLD_LINE_WIDTH);\n"
        "    mgraphics.move_to(area_x, thresh_y);\n"
        "    mgraphics.line_to(area_x + area_w, thresh_y);\n"
        "    mgraphics.stroke();\n"
        "}\n"
    )
