"""Spectral vocoder display engine for jsui.

Generates JavaScript code that renders carrier and modulator band magnitudes
inside Max's jsui object using mgraphics. Shows two sets of frequency bars
overlaid per band, useful as a real-time companion display for a vocoder.

Inlets:
    0 -- Carrier band magnitudes: list of N floats (0.0-1.0)
    1 -- Modulator band magnitudes: list of N floats (0.0-1.0)

Outlets:
    (none, display only)
"""

SPECTRAL_VOCODER_INLETS = 2
SPECTRAL_VOCODER_OUTLETS = 0


def spectral_vocoder_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                                  carrier_color="0.45, 0.75, 0.65, 0.8",
                                  modulator_color="0.85, 0.45, 0.35, 0.7"):
    """Return JavaScript source for a spectral vocoder band display (Max jsui).

    Inlet 0 sets carrier magnitudes, inlet 1 sets modulator magnitudes. Each
    band draws two bars side by side, carrier on the left half, modulator on
    the right half, so both spectra are readable at a glance.

    Args:
        bg_color: Background color (RGBA string).
        carrier_color: Carrier band bar color (RGBA string).
        modulator_color: Modulator band bar color (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    return (
        "// Spectral Vocoder Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var NUM_BANDS = 16;\n"
        "var carrier_bands = [];\n"
        "var modulator_bands = [];\n"
        "var receiving_modulator = 0;\n"
        "var i;\n"
        "for (i = 0; i < NUM_BANDS; i++) {\n"
        "    carrier_bands[i] = 0.0;\n"
        "    modulator_bands[i] = 0.0;\n"
        "}\n"
        "\n"
        "// --- Constants ---\n"
        "var PADDING = 2;\n"
        "var GAP = 1;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_list() {\n"
        "    var args = arrayfromargs(arguments);\n"
        "    if (inlet === 0) {\n"
        "        NUM_BANDS = args.length;\n"
        "        carrier_bands = [];\n"
        "        var j;\n"
        "        for (j = 0; j < NUM_BANDS; j++) {\n"
        "            carrier_bands[j] = Math.max(0, Math.min(1, args[j]));\n"
        "        }\n"
        "        mgraphics.redraw();\n"
        "    } else if (inlet === 1) {\n"
        "        modulator_bands = [];\n"
        "        var k;\n"
        "        for (k = 0; k < args.length; k++) {\n"
        "            modulator_bands[k] = Math.max(0, Math.min(1, args[k]));\n"
        "        }\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    if (NUM_BANDS === 0) { return; }\n"
        "\n"
        "    var band_w = (area_w - GAP * (NUM_BANDS - 1)) / NUM_BANDS;\n"
        "    var half_w = band_w * 0.5 - 1;\n"
        "\n"
        "    var b;\n"
        "    for (b = 0; b < NUM_BANDS; b++) {\n"
        "        var bx = PADDING + b * (band_w + GAP);\n"
        "        var carrier_h = carrier_bands[b] * area_h;\n"
        "        var mod_val = (b < modulator_bands.length) ? modulator_bands[b] : 0.0;\n"
        "        var mod_h = mod_val * area_h;\n"
        "\n"
        "        // Carrier bar (left half)\n"
        f"        mgraphics.set_source_rgba({carrier_color});\n"
        "        mgraphics.rectangle(bx, PADDING + area_h - carrier_h, half_w, carrier_h);\n"
        "        mgraphics.fill();\n"
        "\n"
        "        // Modulator bar (right half)\n"
        f"        mgraphics.set_source_rgba({modulator_color});\n"
        "        mgraphics.rectangle(bx + half_w + 1, PADDING + area_h - mod_h, half_w, mod_h);\n"
        "        mgraphics.fill();\n"
        "    }\n"
        "}\n"
    )
