"""Step sequencer grid display engine for jsui.

Generates JavaScript code that renders a 16-step sequencer grid inside
Max's jsui object using mgraphics. Each cell shows velocity as fill opacity
and is clickable to toggle the step on or off.

Inlets:
    0 -- Step state: flat list [active, velocity, pitch, active, velocity, pitch, ...]
    1 -- Playhead position (int, 0-based step index)

Outlets:
    0 -- Step index (int)
    1 -- Active state (int 0 or 1)
    2 -- Velocity (float 0.0-1.0)
    3 -- Pitch (int)
"""

STEP_GRID_DISPLAY_INLETS = 2
STEP_GRID_DISPLAY_OUTLETS = 4


def step_grid_display_js(steps=16, *,
                          bg_color="0.07, 0.07, 0.08, 1.0",
                          active_color="0.45, 0.75, 0.65, 1.0",
                          inactive_color="0.18, 0.18, 0.20, 1.0",
                          playhead_color="1.0, 1.0, 1.0, 0.25"):
    """Return JavaScript source for a step sequencer grid display (Max jsui).

    Each step stores active, velocity (0.0-1.0), and pitch. Inlet 0 accepts
    a flat list in groups of three: [active, velocity, pitch, ...]. Inlet 1
    sets the playhead step. Clicking a step toggles it and outputs its state
    on outlets 0-3.

    Args:
        steps: Number of steps (default 16).
        bg_color: Background color (RGBA string).
        active_color: Active step color (RGBA string).
        inactive_color: Inactive step color (RGBA string).
        playhead_color: Playhead highlight color (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    ac = [s.strip() for s in active_color.split(",")]
    active_rgb = ac[0] + ", " + ac[1] + ", " + ac[2]

    return (
        "// Step Grid Display — generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 4;\n"
        "\n"
        "// --- Configuration ---\n"
        f"var NUM_STEPS = {steps};\n"
        "\n"
        "// --- State ---\n"
        "var playhead = -1;\n"
        "var step_active = [];\n"
        "var step_velocity = [];\n"
        "var step_pitch = [];\n"
        "var i;\n"
        "for (i = 0; i < NUM_STEPS; i++) {\n"
        "    step_active.push(0);\n"
        "    step_velocity.push(0.75);\n"
        "    step_pitch.push(60);\n"
        "}\n"
        "\n"
        "// --- Constants ---\n"
        "var PADDING = 2;\n"
        "var GAP = 2;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_list() {\n"
        "    if (inlet === 0) {\n"
        "        var args = arrayfromargs(arguments);\n"
        "        var j;\n"
        "        for (j = 0; j < NUM_STEPS; j++) {\n"
        "            var base = j * 3;\n"
        "            if (base + 2 < args.length) {\n"
        "                step_active[j] = args[base] ? 1 : 0;\n"
        "                step_velocity[j] = Math.max(0, Math.min(1, args[base + 1]));\n"
        "                step_pitch[j] = Math.round(args[base + 2]);\n"
        "            }\n"
        "        }\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_int(v) {\n"
        "    if (inlet === 1) {\n"
        "        playhead = v;\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_float(v) {\n"
        "    msg_int(Math.round(v));\n"
        "}\n"
        "\n"
        "// --- Mouse handling ---\n"
        "function onclick(x, y, but, cmd, shift, capslock, option, ctrl) {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var cell_w = (area_w - GAP * (NUM_STEPS - 1)) / NUM_STEPS;\n"
        "    var step = Math.floor((x - PADDING) / (cell_w + GAP));\n"
        "    if (step < 0) step = 0;\n"
        "    if (step >= NUM_STEPS) step = NUM_STEPS - 1;\n"
        "    step_active[step] = step_active[step] ? 0 : 1;\n"
        "    outlet(0, step);\n"
        "    outlet(1, step_active[step]);\n"
        "    outlet(2, step_velocity[step]);\n"
        "    outlet(3, step_pitch[step]);\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_x = PADDING;\n"
        "    var area_y = PADDING;\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "    var cell_w = (area_w - GAP * (NUM_STEPS - 1)) / NUM_STEPS;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    var j;\n"
        "    for (j = 0; j < NUM_STEPS; j++) {\n"
        "        var cx = area_x + j * (cell_w + GAP);\n"
        "        var cy = area_y;\n"
        "\n"
        "        // Playhead highlight behind cell\n"
        "        if (j === playhead) {\n"
        f"            mgraphics.set_source_rgba({playhead_color});\n"
        "            mgraphics.rectangle(cx, cy, cell_w, area_h);\n"
        "            mgraphics.fill();\n"
        "        }\n"
        "\n"
        "        if (step_active[j]) {\n"
        "            var alpha = 0.35 + step_velocity[j] * 0.65;\n"
        f"            mgraphics.set_source_rgba({active_rgb}, alpha);\n"
        "        } else {\n"
        f"            mgraphics.set_source_rgba({inactive_color});\n"
        "        }\n"
        "        mgraphics.rectangle(cx, cy, cell_w, area_h);\n"
        "        mgraphics.fill();\n"
        "    }\n"
        "}\n"
    )
