"""Compressor/saturator transfer-curve display (Pro-C-style hero graph).

Draws the static transfer function (threshold/ratio/soft knee) on an
in/out-dB plot with a unity reference, gain-reduction shading, a live IO dot
riding the curve, and a right-edge GR bar. Drag vertically to set threshold;
mouse-wheel adjusts ratio. Outlet messages fire only on user gestures
(no-echo rule: inbound ``set_*`` never triggers an outlet).

Messages in (inlet 0):
    set_threshold <db>      -60..0
    set_ratio <r>           1..20
    set_knee <db>           0..24
    set_makeup <db>         display readout only
    io_level <env_db> <gr_db>   live detector level + gain reduction (~30ms)

Messages out (outlet 0):
    threshold <db>          while dragging
    ratio <r>               on wheel
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)

TRANSFER_CURVE_INLETS = 1
TRANSFER_CURVE_OUTLETS = 1

__all__ = ["TRANSFER_CURVE_INLETS", "TRANSFER_CURVE_OUTLETS", "transfer_curve_js"]


def transfer_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    curve_color="0.95, 0.97, 0.99, 0.95",
    unity_color="0.35, 0.38, 0.42, 0.85",
    gr_fill_color="0.95, 0.55, 0.25, 0.16",
    dot_color="0.95, 0.62, 0.28, 1.0",
    gr_bar_color="0.95, 0.55, 0.25, 0.85",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    accent_color="0.95, 0.62, 0.28, 1.0",
    min_db=-60.0,
):
    """Return JavaScript source for the transfer-curve display."""
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        curve_color=curve_color,
        unity_color=unity_color,
        gr_fill_color=gr_fill_color,
        dot_color=dot_color,
        gr_bar_color=gr_bar_color,
        grid_color=grid_color,
        text_color=text_color,
        accent_color=accent_color,
        min_db=min_db,
    )


_JS_TEMPLATE = Template("""\
// Transfer Curve Display - generated by m4l-builder
// ES5 compatible; full pointer handler set for v8ui drags.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR      = [$bg_color];
var PANEL_CLR   = [$panel_color];
var BORDER_CLR  = [$plot_border_color];
var CURVE_CLR   = [$curve_color];
var UNITY_CLR   = [$unity_color];
var GRFILL_CLR  = [$gr_fill_color];
var DOT_CLR     = [$dot_color];
var GRBAR_CLR   = [$gr_bar_color];
var GRID_CLR    = [$grid_color];
var TEXT_CLR    = [$text_color];
var ACCENT_CLR  = [$accent_color];

var MIN_DB = $min_db;
var MAX_DB = 0.0;
var GR_BAR_W = 10;
var MARGIN_L = 24;
var MARGIN_R = 8;
var MARGIN_T = 8;
var MARGIN_B = 16;

var threshold = 0.0;
var ratio = 2.0;
var knee = 6.0;
var makeup = 0.0;
var env_db = MIN_DB;
var gr_db = 0.0;
var dragging = 0;
var hovering = 0;
var drag_start_y = 0;
var drag_start_threshold = 0.0;

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

function plot_l() { return MARGIN_L; }
function plot_r() { return mgraphics.size[0] - MARGIN_R - GR_BAR_W - 6; }
function plot_t() { return MARGIN_T; }
function plot_b() { return mgraphics.size[1] - MARGIN_B; }
function plot_w() { return plot_r() - plot_l(); }
function plot_h() { return plot_b() - plot_t(); }

function in_to_x(db) {
    return plot_l() + ((db - MIN_DB) / (MAX_DB - MIN_DB)) * plot_w();
}
function out_to_y(db) {
    return plot_b() - ((db - MIN_DB) / (MAX_DB - MIN_DB)) * plot_h();
}

// Soft-knee transfer function (same math as the gen~ gain computer).
function transfer_out_db(in_db) {
    var over = in_db - threshold;
    var half = knee * 0.5;
    var gr;
    if (over <= -half) {
        gr = 0.0;
    } else if (over < half && knee > 0.01) {
        var t = over + half;
        gr = (t * t) / (2.0 * knee) * (1.0 / ratio - 1.0);
    } else {
        gr = over * (1.0 / ratio - 1.0);
    }
    return in_db + gr;
}

function format_ratio() {
    return (Math.round(ratio * 10) / 10) + ":1";
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, y, db;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();

    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Grid every 12 dB on both axes.
    mgraphics.set_line_width(1.0);
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(7.5);
    for (db = MIN_DB + 12; db < MAX_DB; db += 12) {
        x = in_to_x(db);
        y = out_to_y(db);
        mgraphics.set_source_rgba(GRID_CLR);
        mgraphics.move_to(x, plot_t());
        mgraphics.line_to(x, plot_b());
        mgraphics.stroke();
        mgraphics.move_to(plot_l(), y);
        mgraphics.line_to(plot_r(), y);
        mgraphics.stroke();
        mgraphics.set_source_rgba(TEXT_CLR);
        mgraphics.move_to(2, y + 2.5);
        mgraphics.show_text("" + Math.round(db));
        mgraphics.move_to(x - 7, h - 5);
        mgraphics.show_text("" + Math.round(db));
    }

    // Unity diagonal.
    mgraphics.set_source_rgba(UNITY_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(in_to_x(MIN_DB), out_to_y(MIN_DB));
    mgraphics.line_to(in_to_x(MAX_DB), out_to_y(MAX_DB));
    mgraphics.stroke();

    // Gain-reduction region: between unity and the transfer curve.
    mgraphics.set_source_rgba(GRFILL_CLR);
    mgraphics.move_to(in_to_x(MIN_DB), out_to_y(MIN_DB));
    for (i = 0; i <= 64; i++) {
        db = MIN_DB + (i / 64) * (MAX_DB - MIN_DB);
        mgraphics.line_to(in_to_x(db), out_to_y(transfer_out_db(db)));
    }
    mgraphics.line_to(in_to_x(MAX_DB), out_to_y(MAX_DB));
    mgraphics.close_path();
    mgraphics.fill();

    // Soft-knee glow: a faint band marks the knee width on the input axis
    // (threshold +/- knee/2) and a soft accent halo glows under the curve
    // segment inside it (the curve strokes on top) — makes the Knee control
    // tangible: subtle for a hard-knee limiter, wide for a soft compressor.
    var half_knee = knee * 0.5;
    if (knee > 0.1) {
        var ka = clamp(threshold - half_knee, MIN_DB, MAX_DB);
        var kb = clamp(threshold + half_knee, MIN_DB, MAX_DB);
        mgraphics.set_source_rgba(ACCENT_CLR[0], ACCENT_CLR[1], ACCENT_CLR[2], 0.07);
        mgraphics.rectangle(in_to_x(ka), plot_t(), in_to_x(kb) - in_to_x(ka), plot_h());
        mgraphics.fill();
        var gp, gw, ga;
        for (gp = 0; gp < 2; gp++) {
            gw = (gp === 0) ? 6.5 : 3.5;
            ga = (gp === 0) ? 0.13 : 0.27;
            mgraphics.set_source_rgba(ACCENT_CLR[0], ACCENT_CLR[1], ACCENT_CLR[2], ga);
            mgraphics.set_line_width(gw);
            for (i = 0; i <= 28; i++) {
                db = ka + (i / 28) * (kb - ka);
                x = in_to_x(db);
                y = out_to_y(transfer_out_db(db));
                if (i === 0) mgraphics.move_to(x, y);
                else mgraphics.line_to(x, y);
            }
            mgraphics.stroke();
        }
    }

    // Transfer curve.
    mgraphics.set_source_rgba(CURVE_CLR);
    mgraphics.set_line_width(dragging || hovering ? 2.2 : 1.7);
    for (i = 0; i <= 96; i++) {
        db = MIN_DB + (i / 96) * (MAX_DB - MIN_DB);
        x = in_to_x(db);
        y = out_to_y(transfer_out_db(db));
        if (i === 0) mgraphics.move_to(x, y);
        else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    // Threshold marker (vertical accent tick on the curve).
    var tx = in_to_x(threshold);
    var ty = out_to_y(transfer_out_db(threshold));
    mgraphics.set_source_rgba(ACCENT_CLR[0], ACCENT_CLR[1], ACCENT_CLR[2], 0.55);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(tx, plot_t());
    mgraphics.line_to(tx, plot_b());
    mgraphics.stroke();

    // Live IO dot riding the curve.
    if (env_db > MIN_DB + 0.5) {
        var dx = in_to_x(clamp(env_db, MIN_DB, MAX_DB));
        var dy = out_to_y(transfer_out_db(clamp(env_db, MIN_DB, MAX_DB)));
        mgraphics.set_source_rgba(DOT_CLR[0], DOT_CLR[1], DOT_CLR[2], 0.25);
        mgraphics.arc(dx, dy, 7.5, 0, Math.PI * 2);
        mgraphics.fill();
        mgraphics.set_source_rgba(DOT_CLR);
        mgraphics.arc(dx, dy, 3.2, 0, Math.PI * 2);
        mgraphics.fill();
    }

    // Right-edge gain-reduction bar (top-down).
    var bar_x = plot_r() + 6;
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(bar_x, plot_t(), GR_BAR_W, plot_h());
    mgraphics.fill();
    var gr_norm = clamp(-gr_db / 24.0, 0.0, 1.0);
    if (gr_norm > 0.005) {
        mgraphics.set_source_rgba(GRBAR_CLR);
        mgraphics.rectangle(bar_x, plot_t(), GR_BAR_W, plot_h() * gr_norm);
        mgraphics.fill();
    }
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(bar_x + 0.5, plot_t() + 0.5, GR_BAR_W - 1, plot_h() - 1);
    mgraphics.stroke();

    // Plot border.
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();

    // Readout (top-left of plot): threshold / ratio / live GR.
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 1.0);
    mgraphics.set_font_size(8.0);
    mgraphics.move_to(plot_l() + 5, plot_t() + 10);
    mgraphics.show_text(Math.round(threshold * 10) / 10 + " dB   " + format_ratio());
    if (gr_db < -0.05) {
        mgraphics.set_source_rgba(ACCENT_CLR);
        mgraphics.move_to(plot_l() + 5, plot_t() + 21);
        mgraphics.show_text("GR " + (Math.round(-gr_db * 10) / 10) + " dB");
    }
}

// ── Messages ─────────────────────────────────────────────────────────
function set_threshold(v) { threshold = clamp(v, MIN_DB, 0.0); mgraphics.redraw(); }
function set_ratio(v)     { ratio = clamp(v, 1.0, 20.0); mgraphics.redraw(); }
function set_knee(v)      { knee = clamp(v, 0.0, 24.0); mgraphics.redraw(); }
function set_makeup(v)    { makeup = v; mgraphics.redraw(); }

function io_level(e, g) {
    env_db = e;
    gr_db = g;
    mgraphics.redraw();
}

// ── Interaction: drag = threshold, wheel = ratio ─────────────────────
function start_drag(y) {
    dragging = 1;
    drag_start_y = y;
    drag_start_threshold = threshold;
}

function drag_to(y, fine) {
    if (!dragging) return;
    var dd = (y - drag_start_y) / plot_h() * (MAX_DB - MIN_DB);
    if (fine) dd *= 0.15;
    threshold = clamp(drag_start_threshold - dd, MIN_DB, 0.0);
    outlet(0, "threshold", Math.round(threshold * 10) / 10);
    mgraphics.redraw();
}

function end_drag() {
    if (!dragging) return;
    dragging = 0;
    mgraphics.redraw();
}

function onpointerdown(pointerevent) { start_drag(pointerevent.screenY !== undefined ? pointerevent.y : pointerevent.y); }
function onpointermove(pointerevent) {
    if (dragging) drag_to(pointerevent.y, pointerevent.shiftKey ? 1 : 0);
    else if (!hovering) { hovering = 1; mgraphics.redraw(); }
}
function onpointerup(pointerevent) { end_drag(); }
function onpointerleave(pointerevent) { hovering = 0; end_drag(); mgraphics.redraw(); }

function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { start_drag(y); }
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but) drag_to(y, shift);
    else end_drag();
}
function onidle(x, y) { if (!hovering) { hovering = 1; mgraphics.redraw(); } }
function onidleout() { hovering = 0; mgraphics.redraw(); }

function onwheel(x, y, scrollx, scrolly, cmd, shift) {
    var step = shift ? 0.05 : 0.2;
    ratio = clamp(ratio + (scrolly > 0 ? step : -step), 1.0, 20.0);
    outlet(0, "ratio", Math.round(ratio * 10) / 10);
    mgraphics.redraw();
}

function onresize(w, h) { mgraphics.redraw(); }
""")
