"""Scrolling transient-shaper history display (input level + bipolar gain).

The signature view for a transient designer: the moment-to-moment gain the
shaper applies scrolls right-to-left as a BIPOLAR trace around a center zero
line — boost (added punch) ignites UP in green, cut (tamed transients/sustain)
hangs DOWN in amber — over a faint scrolling input-level silhouette so gain
events visibly line up with the transients that triggered them. This is the
differentiator over the analog-style transient designers (SPL Transient
Designer / ST4B), which show no live read of what the processor is doing.

Two stacked lanes share the plot:
  * GAIN lane (upper ~62%): bipolar applied gain, +/- ``gain_scale_db`` around a
    center zero line. Above center = boost (green), below = cut (amber).
  * LEVEL lane (lower ~38%): input level as a filled cyan area (``lo_db`` ..
    ``hi_db``) — timing context so a gain spike reads against its transient.

Messages in (inlet 0):
    levels <in_db> <gain_db>   push one frame (input level dB, applied gain dB)
    set_range <lo> <hi>        input-level window in dB (default -48..6)
    set_gain_scale <db>        +/- full-scale of the gain lane (default 12)
    set_seconds <s>            history length in seconds (default 6)
    set_rate <hz>              expected frame rate, sizes the ring (default 30)
    clear                      wipe history

Messages out (outlet 0): none (reserved). Display-only; the inbound ~30 Hz
``levels`` stream drives redraws, so no Task/clock is needed (legacy js
Task.schedule silently no-ops in Live).
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)
from .design_system import design_system_js

TRANSIENT_HISTORY_INLETS = 1
TRANSIENT_HISTORY_OUTLETS = 1

__all__ = [
    "TRANSIENT_HISTORY_INLETS",
    "TRANSIENT_HISTORY_OUTLETS",
    "transient_history_js",
]


def transient_history_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    level_fill_color="0.30, 0.72, 0.92, 0.16",
    level_line_color="0.30, 0.72, 0.92, 0.65",
    boost_color="0.36, 0.86, 0.56, 1.0",
    cut_color="0.96, 0.62, 0.30, 1.0",
    zero_color="0.55, 0.60, 0.68, 0.7",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.58, 0.62, 0.68, 1.0",
    lo_db=-48.0,
    hi_db=6.0,
    gain_scale_db=12.0,
    grid_db=6.0,
    seconds=6.0,
    rate_hz=30.0,
):
    """Return JavaScript source for the scrolling transient-shaper display."""
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return design_system_js() + "\n" + _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        level_fill_color=level_fill_color,
        level_line_color=level_line_color,
        boost_color=boost_color,
        cut_color=cut_color,
        zero_color=zero_color,
        grid_color=grid_color,
        text_color=text_color,
        lo_db=lo_db,
        hi_db=hi_db,
        gain_scale_db=gain_scale_db,
        grid_db=grid_db,
        seconds=seconds,
        rate_hz=rate_hz,
    )


_JS_TEMPLATE = Template("""\
// Transient History Display - generated by m4l-builder
// ES5 compatible; display-only (no gesture outlets).

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var LVL_FILL   = [$level_fill_color];
var LVL_LINE   = [$level_line_color];
var BOOST_CLR  = [$boost_color];
var CUT_CLR    = [$cut_color];
var ZERO_CLR   = [$zero_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];

var lo_db = $lo_db;
var hi_db = $hi_db;
var gain_scale_db = $gain_scale_db;
var grid_db = $grid_db;
var seconds = $seconds;
var rate_hz = $rate_hz;

// Ring buffers (fixed size; resized only by set_seconds/set_rate).
var cap = 0;
var lvl_ring = [];
var gain_ring = [];
var head = 0;     // next write slot
var count = 0;    // valid frames (<= cap)
var flare = 0.0;  // smoothed |gain| glow on the leading edge

function rebuild_ring() {
    cap = Math.round(seconds * rate_hz);
    if (cap < 16) cap = 16;
    if (cap > 1024) cap = 1024;
    lvl_ring = new Array(cap);
    gain_ring = new Array(cap);
    var i;
    for (i = 0; i < cap; i++) { lvl_ring[i] = lo_db; gain_ring[i] = 0.0; }
    head = 0;
    count = 0;
}
rebuild_ring();

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

function plot_l() { return 22; }
function plot_r() { return mgraphics.size[0] - 8; }
function plot_t() { return 6; }
function plot_b() { return mgraphics.size[1] - 6; }
function plot_w() { return plot_r() - plot_l(); }
function plot_h() { return plot_b() - plot_t(); }

// The gain lane (upper 62%) and the level lane (lower 38%) split the plot.
function gain_split() { return plot_t() + plot_h() * 0.62; }
function gain_mid()   { return (plot_t() + gain_split()) * 0.5; }

function gain_to_y(db) {
    // +gain_scale -> lane top, 0 -> lane center, -gain_scale -> lane bottom.
    var top = plot_t() + 2;
    var bot = gain_split() - 2;
    var mid = (top + bot) * 0.5;
    var half = (bot - top) * 0.5;
    var n = clamp(db, -gain_scale_db, gain_scale_db) / gain_scale_db;
    return mid - n * half;
}

function lvl_to_y(db) {
    var top = gain_split() + 2;
    var bot = plot_b();
    var n = (clamp(db, lo_db, hi_db) - lo_db) / (hi_db - lo_db);
    return bot - n * (bot - top);
}

function frame_at(i) {
    // i = 0 is oldest of the valid frames.
    return (head - count + i + cap * 2) % cap;
}

function vgrad(x0, y0, x1, y1, clr, a0, a1) {
    var g = mgraphics.pattern_create_linear(x0, y0, x1, y1);
    g.add_color_stop_rgba(0.0, clr[0], clr[1], clr[2], a0);
    g.add_color_stop_rgba(1.0, clr[0], clr[1], clr[2], a1);
    return g;
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, idx, x, y, gd;

    // Smoothed leading-edge intensity (fast attack / slow release): the live
    // "how hard is it working" read shared by the trace glow + readout.
    var cur_g = (count > 0) ? Math.abs(gain_ring[frame_at(count - 1)]) : 0.0;
    var ft = clamp(cur_g / Math.max(gain_scale_db * 0.6, 1.0), 0.0, 1.0);
    flare = (ft > flare) ? ft : (flare * 0.84 + ft * 0.16);

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    var zy = gain_to_y(0.0);

    // Gain-lane gridlines every grid_db (symmetric around zero), labeled left.
    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(6.5);
    for (gd = grid_db; gd <= gain_scale_db + 0.01; gd += grid_db) {
        var yy = [gain_to_y(gd), gain_to_y(-gd)];
        var lab = ["+" + gd, "-" + gd];
        var k;
        for (k = 0; k < 2; k++) {
            mgraphics.set_source_rgba(GRID_CLR);
            mgraphics.set_line_width(1.0);
            mgraphics.move_to(plot_l(), yy[k]);
            mgraphics.line_to(plot_r(), yy[k]);
            mgraphics.stroke();
            mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.75);
            mgraphics.move_to(1, yy[k] + 2);
            mgraphics.show_text(lab[k]);
        }
    }

    // Center zero line (brighter — the reference the trace pivots around).
    mgraphics.set_source_rgba(ZERO_CLR);
    mgraphics.set_line_width(1.2);
    mgraphics.move_to(plot_l(), zy);
    mgraphics.line_to(plot_r(), zy);
    mgraphics.stroke();

    // Divider between gain lane and level lane.
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(plot_l(), gain_split());
    mgraphics.line_to(plot_r(), gain_split());
    mgraphics.stroke();

    if (count > 1) {
        var px = plot_w() / (cap - 1);
        var x0 = plot_r() - (count - 1) * px;

        // Input-level silhouette (lower lane), faint context.
        mgraphics.set_source(vgrad(0, gain_split(), 0, plot_b(),
                                   LVL_FILL, LVL_FILL[3] * 2.4, LVL_FILL[3] * 0.20));
        mgraphics.move_to(x0, plot_b());
        for (i = 0; i < count; i++) {
            idx = frame_at(i);
            mgraphics.line_to(x0 + i * px, lvl_to_y(lvl_ring[idx]));
        }
        mgraphics.line_to(x0 + (count - 1) * px, plot_b());
        mgraphics.close_path();
        mgraphics.fill();
        mgraphics.set_source_rgba(LVL_LINE);
        mgraphics.set_line_width(1.0);
        for (i = 0; i < count; i++) {
            idx = frame_at(i);
            x = x0 + i * px;
            y = lvl_to_y(lvl_ring[idx]);
            if (i === 0) mgraphics.move_to(x, y);
            else mgraphics.line_to(x, y);
        }
        mgraphics.stroke();

        // Boost fill (gain > 0): from the zero line UP to the trace, green.
        mgraphics.set_source(vgrad(0, gain_to_y(gain_scale_db), 0, zy,
                                   BOOST_CLR, 0.34, 0.05));
        mgraphics.move_to(x0, zy);
        for (i = 0; i < count; i++) {
            idx = frame_at(i);
            gd = gain_ring[idx]; if (gd < 0) gd = 0;
            mgraphics.line_to(x0 + i * px, gain_to_y(gd));
        }
        mgraphics.line_to(x0 + (count - 1) * px, zy);
        mgraphics.close_path();
        mgraphics.fill();

        // Cut fill (gain < 0): from the zero line DOWN to the trace, amber.
        mgraphics.set_source(vgrad(0, zy, 0, gain_to_y(-gain_scale_db),
                                   CUT_CLR, 0.05, 0.34));
        mgraphics.move_to(x0, zy);
        for (i = 0; i < count; i++) {
            idx = frame_at(i);
            gd = gain_ring[idx]; if (gd > 0) gd = 0;
            mgraphics.line_to(x0 + i * px, gain_to_y(gd));
        }
        mgraphics.line_to(x0 + (count - 1) * px, zy);
        mgraphics.close_path();
        mgraphics.fill();

        // Bipolar gain trace: per-segment color (green above zero, amber below).
        mgraphics.set_line_width(1.4);
        for (i = 1; i < count; i++) {
            var a = gain_ring[frame_at(i - 1)];
            var b = gain_ring[frame_at(i)];
            var avg = (a + b) * 0.5;
            if (avg >= 0) mgraphics.set_source_rgba(BOOST_CLR);
            else mgraphics.set_source_rgba(CUT_CLR);
            mgraphics.move_to(x0 + (i - 1) * px, gain_to_y(a));
            mgraphics.line_to(x0 + i * px, gain_to_y(b));
            mgraphics.stroke();
        }

        // Leading-edge glow dot at "now".
        var cx = x0 + (count - 1) * px;
        var cg = gain_ring[frame_at(count - 1)];
        var cy = gain_to_y(cg);
        var dotc = (cg >= 0) ? BOOST_CLR : CUT_CLR;
        if (flare > 0.01) {
            mgraphics.set_source_rgba(dotc[0], dotc[1], dotc[2], 0.18 + 0.22 * flare);
            mgraphics.ellipse(cx - 4.5, cy - 4.5, 9.0, 9.0);
            mgraphics.fill();
        }
        mgraphics.set_source_rgba(dotc[0], dotc[1], dotc[2], 0.95);
        mgraphics.ellipse(cx - 1.8, cy - 1.8, 3.6, 3.6);
        mgraphics.fill();
    }

    // Live gain readout, top-left, colored to the current direction.
    if (count > 0) {
        var g = gain_ring[frame_at(count - 1)];
        if (Math.abs(g) >= 0.05) {
            var rc = (g >= 0) ? BOOST_CLR : CUT_CLR;
            mgraphics.set_source_rgba(rc[0], rc[1], rc[2], 0.95);
            mgraphics.set_font_size(8.5);
            mgraphics.move_to(plot_l() + 6, plot_t() + 12);
            mgraphics.show_text(((g >= 0 ? "+" : "") + g.toFixed(1)) + " dB");
        }
    }

    // Border.
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();
}

// ── Messages ─────────────────────────────────────────────────────────
function levels(in_db, gain_db) {
    // Guard: a per-frame TypeError flood wedges Max's UI thread Live-wide.
    var lv = parseFloat(in_db);
    var gn = parseFloat(gain_db);
    if (!isFinite(lv)) lv = lo_db;
    if (!isFinite(gn)) gn = 0.0;
    lvl_ring[head] = lv;
    gain_ring[head] = gn;
    head = (head + 1) % cap;
    if (count < cap) count += 1;
    mgraphics.redraw();
}

function set_range(lo, hi) {
    lo = parseFloat(lo); hi = parseFloat(hi);
    if (!isFinite(lo) || !isFinite(hi) || hi - lo < 6.0) return;
    lo_db = lo; hi_db = hi;
    mgraphics.redraw();
}

function set_gain_scale(v) {
    v = parseFloat(v);
    if (!isFinite(v) || v < 3.0) return;
    gain_scale_db = v;
    mgraphics.redraw();
}

function set_seconds(s) {
    s = parseFloat(s);
    if (!isFinite(s) || s < 1.0 || s > 30.0) return;
    seconds = s;
    rebuild_ring();
    mgraphics.redraw();
}

function set_rate(hz) {
    hz = parseFloat(hz);
    if (!isFinite(hz) || hz < 5.0 || hz > 120.0) return;
    rate_hz = hz;
    rebuild_ring();
    mgraphics.redraw();
}

function clear() {
    rebuild_ring();
    mgraphics.redraw();
}

function onresize(w, h) { mgraphics.redraw(); }
""")
