"""Value-readout overlay engine — a tiny v8ui that renders a labeled numeric value.

A reusable readout component: a label on top, the formatted value (+ optional
unit) below, on a transparent background so it can float over any compiled
display (``add_compiled_display(..., overlay_js=...)``) or stand alone as a
hover/selection readout. Display-only (no pointer interaction, no CPU gate).

Inlets:
    0 -- ``float``/``int`` sets the value; ``set_value <label> <val> <unit>``
         sets all three; ``set_label <label>`` updates just the label.

Outlets:
    (none)
"""

VALUE_READOUT_INLETS = 1
VALUE_READOUT_OUTLETS = 0


def value_readout_js(
    *,
    label_name: str = "Value",
    unit: str = "",
    label_color: str = "0.64, 0.69, 0.76, 1.0",
    value_color: str = "0.94, 0.92, 0.88, 1.0",
    bg_color: str = "0.0, 0.0, 0.0, 0.0",
    fontname: str = "Ableton Sans Medium",
    fontsize: float = 9.0,
    decimal_places: int = 2,
) -> str:
    """Return v8ui source for a labeled numeric readout.

    The value is set live via ``msg_float`` (value only) or ``set_value label val
    unit`` (all three). Colors are ``"r, g, b, a"`` strings; ``bg_color`` alpha 0
    keeps it transparent (overlay use). ``decimal_places`` fixes the value format.
    """
    return (
        "// Value readout - generated by m4l-builder (v8ui)\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "inlets = 1;\n"
        "outlets = 0;\n"
        f'var label_text = "{label_name}";\n'
        f'var unit_text = "{unit}";\n'
        "var value = 0.0;\n"
        f"var DECIMALS = {int(decimal_places)};\n"
        f"var LABEL_CLR = [{label_color}];\n"
        f"var VALUE_CLR = [{value_color}];\n"
        f"var BG_CLR = [{bg_color}];\n"
        f'var FONT_NAME = "{fontname}";\n'
        f"var FONT_SIZE = {float(fontsize)};\n"
        "function msg_float(v) { value = v; mgraphics.redraw(); }\n"
        "function msg_int(v) { value = v; mgraphics.redraw(); }\n"
        "function set_value(label, val, u) {\n"
        "    label_text = label; value = val; unit_text = u;\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "function set_label(label) { label_text = label; mgraphics.redraw(); }\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    if (BG_CLR[3] > 0.0) {\n"
        "        mgraphics.set_source_rgba(BG_CLR[0], BG_CLR[1], BG_CLR[2], BG_CLR[3]);\n"
        "        mgraphics.rectangle(0, 0, w, h);\n"
        "        mgraphics.fill();\n"
        "    }\n"
        "    mgraphics.select_font_face(FONT_NAME);\n"
        "    // Label (top, dim, slightly smaller).\n"
        "    mgraphics.set_font_size(Math.max(6.0, FONT_SIZE - 2.0));\n"
        "    mgraphics.set_source_rgba(LABEL_CLR[0], LABEL_CLR[1], LABEL_CLR[2], LABEL_CLR[3]);\n"
        "    mgraphics.move_to(3, FONT_SIZE - 1);\n"
        "    mgraphics.show_text(label_text);\n"
        "    // Value + unit (bottom, bright).\n"
        "    mgraphics.set_font_size(FONT_SIZE);\n"
        "    var vstr = value.toFixed(DECIMALS);\n"
        "    if (unit_text.length > 0) { vstr = vstr + ' ' + unit_text; }\n"
        "    mgraphics.set_source_rgba(VALUE_CLR[0], VALUE_CLR[1], VALUE_CLR[2], VALUE_CLR[3]);\n"
        "    mgraphics.move_to(3, h - 3);\n"
        "    mgraphics.show_text(vstr);\n"
        "}\n"
        "function bang() { mgraphics.redraw(); }\n"
    )
