"""Interactive wavetable editor engine for jsui.

Generates JavaScript code that renders an editable waveform inside Max's jsui
object using mgraphics. Click or drag to draw waveform samples. Outputs the
updated sample array when edited.

Inlets:
    0 -- Sample data: list of N floats (-1.0 to 1.0)

Outlets:
    0 -- Updated samples list after editing
"""

WAVETABLE_EDITOR_INLETS = 1
WAVETABLE_EDITOR_OUTLETS = 1


def wavetable_editor_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                         wave_color="0.45, 0.75, 0.65, 1.0",
                         edit_color="1.0, 0.8, 0.3, 1.0"):
    """Return JavaScript source for an interactive wavetable editor (Max jsui).

    Displays a waveform as vertical bars. Click or drag to set sample values
    at each x position. Outputs the full samples array on outlet 0 when edited.

    Args:
        bg_color: Background color (RGBA string).
        wave_color: Default waveform color (RGBA string).
        edit_color: Color for samples being actively edited (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    wc = [s.strip() for s in wave_color.split(",")]
    wave_rgb = wc[0] + ", " + wc[1] + ", " + wc[2]
    wave_line_color = wc[0] + ", " + wc[1] + ", " + wc[2] + ", 0.9"

    return (
        "// Wavetable Editor - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 1;\n"
        "outlets = 1;\n"
        "\n"
        "// --- State ---\n"
        "var NUM_SAMPLES = 64;\n"
        "var samples = [];\n"
        "var is_editing = 0;\n"
        "var last_edited_col = -1;\n"
        "var i;\n"
        "for (i = 0; i < NUM_SAMPLES; i++) {\n"
        "    samples[i] = 0.0;\n"
        "}\n"
        "\n"
        "// --- Constants ---\n"
        "var PADDING = 2;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_list() {\n"
        "    if (inlet === 0) {\n"
        "        var args = arrayfromargs(arguments);\n"
        "        if (args.length > 0) {\n"
        "            NUM_SAMPLES = args.length;\n"
        "            samples = [];\n"
        "            var j;\n"
        "            for (j = 0; j < NUM_SAMPLES; j++) {\n"
        "                samples[j] = Math.max(-1, Math.min(1, args[j]));\n"
        "            }\n"
        "            mgraphics.redraw();\n"
        "        }\n"
        "    }\n"
        "}\n"
        "\n"
        "// --- Shared edit logic ---\n"
        "function edit_at(x, y) {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "    var col = Math.floor((x - PADDING) / area_w * NUM_SAMPLES);\n"
        "    if (col < 0) col = 0;\n"
        "    if (col >= NUM_SAMPLES) col = NUM_SAMPLES - 1;\n"
        "    var mid_y = PADDING + area_h * 0.5;\n"
        "    var val = -((y - mid_y) / (area_h * 0.5));\n"
        "    val = Math.max(-1, Math.min(1, val));\n"
        "    samples[col] = val;\n"
        "    last_edited_col = col;\n"
        "    var out = [];\n"
        "    var k;\n"
        "    for (k = 0; k < NUM_SAMPLES; k++) {\n"
        "        out.push(samples[k]);\n"
        "    }\n"
        "    outlet(0, out);\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "// --- Mouse handling ---\n"
        "function onclick(x, y, but, cmd, shift, capslock, option, ctrl) {\n"
        "    is_editing = 1;\n"
        "    edit_at(x, y);\n"
        "}\n"
        "\n"
        "function ondrag(x, y, but, cmd, shift, capslock, option, ctrl) {\n"
        "    if (but === 0) {\n"
        "        is_editing = 0;\n"
        "        last_edited_col = -1;\n"
        "        return;\n"
        "    }\n"
        "    edit_at(x, y);\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "    var mid_y = PADDING + area_h * 0.5;\n"
        "    var bar_w = area_w / NUM_SAMPLES;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Center line\n"
        f"    mgraphics.set_source_rgba({wave_rgb}, 0.2);\n"
        "    mgraphics.set_line_width(0.5);\n"
        "    mgraphics.move_to(PADDING, mid_y);\n"
        "    mgraphics.line_to(PADDING + area_w, mid_y);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Sample bars\n"
        "    var j;\n"
        "    for (j = 0; j < NUM_SAMPLES; j++) {\n"
        "        var bx = PADDING + j * bar_w;\n"
        "        var val = samples[j];\n"
        "        var bar_h = val * area_h * 0.5;\n"
        "        var by = mid_y - bar_h;\n"
        "        if (j === last_edited_col) {\n"
        f"            mgraphics.set_source_rgba({edit_color});\n"
        "        } else {\n"
        f"            mgraphics.set_source_rgba({wave_color});\n"
        "        }\n"
        "        if (bar_h >= 0) {\n"
        "            mgraphics.rectangle(bx, by, bar_w - 1, bar_h);\n"
        "        } else {\n"
        "            mgraphics.rectangle(bx, mid_y, bar_w - 1, -bar_h);\n"
        "        }\n"
        "        mgraphics.fill();\n"
        "    }\n"
        "\n"
        "    // Waveform line overlay connecting sample centers\n"
        f"    mgraphics.set_source_rgba({wave_line_color});\n"
        "    mgraphics.set_line_width(1.0);\n"
        "    var first_cx = PADDING + 0.5 * bar_w;\n"
        "    var first_val = samples[0];\n"
        "    mgraphics.move_to(first_cx, mid_y - first_val * area_h * 0.5);\n"
        "    for (j = 1; j < NUM_SAMPLES; j++) {\n"
        "        var lx = PADDING + j * bar_w + 0.5 * bar_w;\n"
        "        var lval = samples[j];\n"
        "        mgraphics.line_to(lx, mid_y - lval * area_h * 0.5);\n"
        "    }\n"
        "    mgraphics.stroke();\n"
        "}\n"
    )
