"""Saturator waveshape display (Saturn-style hero graph).

Linear in/out plot (-1..1) of the active transfer character at the current
drive, with a unity reference, harmonic-energy glow under the curve, and a
live IO dot riding the shape at the program level. Drag vertically to set
drive. Outlets fire only on user gestures (no-echo rule).

The shape math mirrors the gen~ core exactly — keep both in sync:
    0 TAPE   tanh(d*x)/tanh(d)
    1 TUBE   asymmetric tanh (positive half driven harder) — DC-blocked in DSP
    2 CLIP   hard clip at 1/d'
    3 FOLD   sine fold sin(d*x*pi/2)
    4 DIODE  asymmetric soft clip (negative half softened, drive-scaled)
    5 WRAP   triangle wavefolder (2/pi * asin(sin(.)))
    6 SOFT   cubic soft-clip 1.5u - 0.5u^3
All 7 are near-unity at drive 0 so the dry/wet null holds. Bias shifts the
operating point into the curve (even harmonics), recentered so bias 0 == raw.

Messages in (inlet 0):
    set_drive <db>          0..36 (drive amount in dB)
    set_character <idx>     0..6
    set_bias <amt>          -1..1 (asymmetry / even harmonics)
    set_mix <pct>           readout only
    io_level <env_lin>      live |input| 0..1 (~30ms)

Messages out (outlet 0):
    drive <db>              while dragging
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)

WAVESHAPE_CURVE_INLETS = 1
WAVESHAPE_CURVE_OUTLETS = 1

__all__ = ["WAVESHAPE_CURVE_INLETS", "WAVESHAPE_CURVE_OUTLETS", "waveshape_curve_js"]


def waveshape_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    curve_color="0.95, 0.97, 0.99, 0.95",
    unity_color="0.35, 0.38, 0.42, 0.85",
    heat_fill_color="0.92, 0.34, 0.20, 0.18",
    dot_color="0.95, 0.45, 0.22, 1.0",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    accent_color="0.95, 0.45, 0.22, 1.0",
):
    """Return JavaScript source for the waveshape display."""
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        curve_color=curve_color,
        unity_color=unity_color,
        heat_fill_color=heat_fill_color,
        dot_color=dot_color,
        grid_color=grid_color,
        text_color=text_color,
        accent_color=accent_color,
    )


_JS_TEMPLATE = Template("""\
// Waveshape Display - generated by m4l-builder
// ES5 compatible; full pointer handler set for v8ui drags.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var CURVE_CLR  = [$curve_color];
var UNITY_CLR  = [$unity_color];
var HEAT_CLR   = [$heat_fill_color];
var DOT_CLR    = [$dot_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];
var ACCENT_CLR = [$accent_color];

var CHAR_NAMES = ["TAPE", "TUBE", "CLIP", "FOLD", "DIODE", "WRAP", "SOFT"];
var NUM_CHARS = 7;

var MARGIN = 10;
var drive_db = 0.0;
var character = 0;
var bias = 0.0;
var mix_pct = 100;
var env_lin = 0.0;
var dragging = 0;
var hovering = 0;
var drag_start_y = 0;
var drag_start_drive = 0.0;

// Dropped-sample waveform: a min/max envelope read from a buffer~. When a
// sample is loaded the hero shows the sample's waveform PLUS its saturated
// version (shape() applied), so the saturation is visible on real audio.
var SAMPLE_COLS = 320;
var sample_loaded = 0;
var sample_name = "";
var smin = [];
var smax = [];

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

// Read a buffer~ into a SAMPLE_COLS-wide min/max envelope (Max-only: new
// Buffer/peek don't exist in the Node harness, so this no-ops there).
function draw_sample(name) {
    if (typeof Buffer === "undefined") return;
    var b = new Buffer("" + name);
    var frames = b.framecount();
    // Not loaded yet (an early/empty read) — leave the prior view untouched
    // rather than wiping it; a later trigger redraws once the file is in.
    if (!frames || frames < 2) { return; }
    var per = Math.floor(frames / SAMPLE_COLS);
    if (per < 1) per = 1;
    smin = []; smax = [];
    var c, k, s, mn, mx, chunk, n;
    for (c = 0; c < SAMPLE_COLS; c++) {
        chunk = b.peek(1, c * per, per < 8192 ? per : 8192);
        mn = 1.0; mx = -1.0;
        n = chunk.length;
        if (n === undefined) { s = chunk; mn = s; mx = s; }
        else { for (k = 0; k < n; k++) { s = chunk[k]; if (s < mn) mn = s; if (s > mx) mx = s; } }
        if (mn > mx) { mn = 0.0; mx = 0.0; }
        smin[c] = clamp(mn, -1.0, 1.0);
        smax[c] = clamp(mx, -1.0, 1.0);
    }
    sample_name = "" + name;
    sample_loaded = 1;
    mgraphics.redraw();
}

function clear_sample() {
    sample_loaded = 0;
    smin = []; smax = [];
    mgraphics.redraw();
}

function plot_l() { return MARGIN + 8; }
function plot_r() { return mgraphics.size[0] - MARGIN; }
function plot_t() { return MARGIN; }
function plot_b() { return mgraphics.size[1] - MARGIN - 4; }
function plot_w() { return plot_r() - plot_l(); }
function plot_h() { return plot_b() - plot_t(); }

function x_of(v) { return plot_l() + ((v + 1.0) * 0.5) * plot_w(); }
function y_of(v) { return plot_b() - ((v + 1.0) * 0.5) * plot_h(); }

function drive_lin() {
    // 0..36 dB mapped to a 1..~8 shaping factor.
    return 0.05 + (drive_db / 36.0) * 8.0;
}

// Mirrors the gen~ core shape(x, d, ch) — keep in sync. Pure/stateless.
function shape_raw(x) {
    var d = drive_lin();
    var v, dn, nf, u, dp;
    if (character === 0) {                       // TAPE
        v = Math.tanh(d * x) / Math.tanh(d);
    } else if (character === 1) {                // TUBE
        dp = x >= 0 ? d * 1.6 : d * 0.9;
        v = clamp(Math.tanh(dp * x) / Math.tanh(d * 1.25), -1.0, 1.0);
    } else if (character === 2) {                // CLIP
        v = clamp(x * (1.0 + (d - 1.0) * 0.6), -1.0, 1.0);
    } else if (character === 3) {                // FOLD
        v = Math.sin(x * d * Math.PI * 0.5);
    } else if (character === 4) {                // DIODE
        dn = clamp((d - 0.05) * 0.125, 0.0, 1.0);
        nf = 1.0 - 0.6 * dn;
        v = x >= 0 ? Math.tanh(d * x) / Math.tanh(d)
                   : Math.tanh(d * nf * x) / Math.tanh(d);
    } else if (character === 5) {                // WRAP
        v = 0.63661977 * Math.asin(Math.sin(x * (1.0 + d * 0.6) * Math.PI * 0.5));
    } else {                                     // SOFT
        dn = clamp((d - 0.05) * 0.125, 0.0, 1.0);
        u = clamp(x * (0.667 + dn * 0.9), -1.0, 1.0);
        v = 1.5 * u - 0.5 * u * u * u;
    }
    return v;
}

// Biased transfer: shift into the curve + recenter (even harmonics). Matches
// the gen's shape(s + b, d, ch) - shape(b, d, ch). bias 0 => exact shape_raw.
function shape(x) {
    var b = clamp(bias, -1.0, 1.0) * 0.5;
    if (b === 0.0) return shape_raw(x);
    return clamp(shape_raw(x + b) - shape_raw(b), -1.0, 1.0);
}

// Draw the dropped sample: its raw waveform envelope (dim) + the SATURATED
// envelope (accent) = shape() applied through the dry/wet mix. Drag drive /
// switch character and the saturated trace reshapes over the real audio.
function draw_sample_waveform() {
    var n = smin.length;
    if (n < 2) return;
    var l = plot_l(), r = plot_r(), t = plot_t(), b = plot_b();
    var w = r - l, cy = (t + b) * 0.5, amp = (b - t) * 0.5 - 1.0;
    var mixf = clamp(mix_pct, 0, 100) * 0.01;
    var c, xx, sv, yy;

    // Center line.
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(l, cy); mgraphics.line_to(r, cy); mgraphics.stroke();

    // Raw sample envelope (dim filled band: max on top, min on bottom).
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.28);
    mgraphics.move_to(l, cy - smax[0] * amp);
    for (c = 0; c < n; c++) { xx = l + (c / (n - 1)) * w; mgraphics.line_to(xx, cy - smax[c] * amp); }
    for (c = n - 1; c >= 0; c--) { xx = l + (c / (n - 1)) * w; mgraphics.line_to(xx, cy - smin[c] * amp); }
    mgraphics.close_path();
    mgraphics.fill();

    // Saturated envelope (accent): top edge (shaped max) then bottom (shaped min).
    mgraphics.set_source_rgba(ACCENT_CLR[0], ACCENT_CLR[1], ACCENT_CLR[2], 0.95);
    mgraphics.set_line_width(1.3);
    for (c = 0; c < n; c++) {
        sv = smax[c]; sv = sv + (shape(sv) - sv) * mixf;
        xx = l + (c / (n - 1)) * w; yy = cy - clamp(sv, -1.0, 1.0) * amp;
        if (c === 0) mgraphics.move_to(xx, yy); else mgraphics.line_to(xx, yy);
    }
    mgraphics.stroke();
    for (c = 0; c < n; c++) {
        sv = smin[c]; sv = sv + (shape(sv) - sv) * mixf;
        xx = l + (c / (n - 1)) * w; yy = cy - clamp(sv, -1.0, 1.0) * amp;
        if (c === 0) mgraphics.move_to(xx, yy); else mgraphics.line_to(xx, yy);
    }
    mgraphics.stroke();

    // Label.
    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.set_font_size(7.5);
    mgraphics.move_to(l + 4, t + 10);
    mgraphics.show_text("SAMPLE  -  dbl-click to clear");
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, y, v;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Quarter grid.
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.set_line_width(1.0);
    for (i = -1; i <= 1; i++) {
        x = x_of(i * 0.5);
        y = y_of(i * 0.5);
        mgraphics.move_to(x, plot_t()); mgraphics.line_to(x, plot_b()); mgraphics.stroke();
        mgraphics.move_to(plot_l(), y); mgraphics.line_to(plot_r(), y); mgraphics.stroke();
    }

    if (sample_loaded) {
        draw_sample_waveform();
    } else {
    // Unity diagonal.
    mgraphics.set_source_rgba(UNITY_CLR);
    mgraphics.move_to(x_of(-1), y_of(-1));
    mgraphics.line_to(x_of(1), y_of(1));
    mgraphics.stroke();

    // Heat fill: area between unity and the shape (the "added harmonics").
    mgraphics.set_source_rgba(HEAT_CLR);
    mgraphics.move_to(x_of(-1), y_of(-1));
    for (i = 0; i <= 96; i++) {
        v = -1.0 + (i / 96) * 2.0;
        mgraphics.line_to(x_of(v), y_of(shape(v)));
    }
    mgraphics.line_to(x_of(1), y_of(1));
    mgraphics.close_path();
    mgraphics.fill();

    // The shape curve.
    mgraphics.set_source_rgba(CURVE_CLR);
    mgraphics.set_line_width(dragging || hovering ? 2.3 : 1.8);
    for (i = 0; i <= 128; i++) {
        v = -1.0 + (i / 128) * 2.0;
        x = x_of(v);
        y = y_of(shape(v));
        if (i === 0) mgraphics.move_to(x, y);
        else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    // Live IO dots (symmetric pair at the program level).
    if (env_lin > 0.003) {
        var e = clamp(env_lin, 0.0, 1.0);
        var dxp = x_of(e), dyp = y_of(shape(e));
        var dxn = x_of(-e), dyn = y_of(shape(-e));
        mgraphics.set_source_rgba(DOT_CLR[0], DOT_CLR[1], DOT_CLR[2], 0.22);
        mgraphics.arc(dxp, dyp, 7.0, 0, Math.PI * 2); mgraphics.fill();
        mgraphics.arc(dxn, dyn, 7.0, 0, Math.PI * 2); mgraphics.fill();
        mgraphics.set_source_rgba(DOT_CLR);
        mgraphics.arc(dxp, dyp, 3.0, 0, Math.PI * 2); mgraphics.fill();
        mgraphics.arc(dxn, dyn, 3.0, 0, Math.PI * 2); mgraphics.fill();
    }
    }

    // Border + readout.
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();

    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(8.0);
    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.move_to(plot_l() + 5, plot_t() + 11);
    mgraphics.show_text(CHAR_NAMES[character] + "  " + (Math.round(drive_db * 10) / 10) + " dB");
    mgraphics.set_source_rgba(TEXT_CLR);
    mgraphics.move_to(plot_l() + 5, plot_t() + 21);
    mgraphics.show_text("MIX " + Math.round(mix_pct) + "%");
}

// ── Messages ─────────────────────────────────────────────────────────
function set_drive(v)     { drive_db = clamp(v, 0.0, 36.0); mgraphics.redraw(); }
function set_character(v) { character = clamp(Math.floor(v), 0, NUM_CHARS - 1); mgraphics.redraw(); }
function set_bias(v)      { bias = clamp(v, -1.0, 1.0); mgraphics.redraw(); }
function set_mix(v)       { mix_pct = clamp(v, 0, 100); mgraphics.redraw(); }
function io_level(e)      { env_lin = e; mgraphics.redraw(); }

// ── Interaction: vertical drag = drive; double-click clears the sample ──
// Robust v8ui pointer resolver (.y/.localY/.offsetY/.clientY); raw .y is
// undefined in Live. Relative feel kept (0.3 dB/px, 0.045 with shift) so
// dragging drive reshapes the saturated overlay over a dropped sample live.
function pointer_y(pe, fb) {
    if (!pe) return fb;
    if (pe.y !== undefined) return pe.y;
    if (pe.localY !== undefined) return pe.localY;
    if (pe.offsetY !== undefined) return pe.offsetY;
    if (pe.clientY !== undefined) return pe.clientY;
    return fb;
}
function pointer_buttons(pe, fb) {
    if (!pe) return fb;
    if (pe.buttons !== undefined) return pe.buttons;
    if (pe.button !== undefined) return pe.button === 2 ? 2 : 1;
    return fb;
}

function start_drag(y) {
    if (isNaN(y)) return;
    dragging = 1;
    drag_start_y = y;
    drag_start_drive = drive_db;
}

function drag_to(y, fine) {
    if (!dragging || isNaN(y)) return;
    // Up = more drive. 1 px = 0.3 dB (0.045 with shift).
    var dd = (drag_start_y - y) * (fine ? 0.045 : 0.3);
    drive_db = clamp(drag_start_drive + dd, 0.0, 36.0);
    outlet(0, "drive", Math.round(drive_db * 10) / 10);
    mgraphics.redraw();
}

function end_drag() {
    if (!dragging) return;
    dragging = 0;
    mgraphics.redraw();
}

function onpointerdown(pe) { start_drag(pointer_y(pe, drag_start_y)); }
function onpointermove(pe) {
    if (dragging && ((pointer_buttons(pe, 1) & 1) !== 0)) {
        drag_to(pointer_y(pe, drag_start_y), pe && pe.shiftKey ? 1 : 0);
        return;
    }
    if (dragging) { end_drag(); return; }
    if (!hovering) { hovering = 1; mgraphics.redraw(); }
}
function onpointerup(pe) { end_drag(); }
function onpointerleave(pe) { hovering = 0; end_drag(); mgraphics.redraw(); }
function ondblclick(x, y, but, cmd, shift, caps, opt, ctrl) { clear_sample(); }

function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { start_drag(y); }
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but) drag_to(y, shift);
    else end_drag();
}
function onidle(x, y) { if (!hovering) { hovering = 1; mgraphics.redraw(); } }
function onidleout() { hovering = 0; mgraphics.redraw(); }
function onresize(w, h) { mgraphics.redraw(); }
""")
