"""Saturator waveshape display (Saturn-style hero graph).

Linear in/out plot (-1..1) of the active transfer character at the current
drive, with a unity reference, harmonic-energy glow under the curve, and a
live IO dot riding the shape at the program level. Drag vertically to set
drive. Outlets fire only on user gestures (no-echo rule).

The shape math mirrors the gen~ core exactly — keep both in sync:
    0 TAPE   tanh(d*x)/tanh(d)
    1 TUBE   asymmetric tanh (positive half driven harder) — DC-blocked in DSP
    2 CLIP   hard clip at 1/d'
    3 FOLD   sine fold sin(d*x*pi/2)
    4 DIODE  asymmetric soft clip (negative half softened, drive-scaled)
    5 WRAP   triangle wavefolder (2/pi * asin(sin(.)))
    6 SOFT   cubic soft-clip 1.5u - 0.5u^3
All 7 are near-unity at drive 0 so the dry/wet null holds. Bias shifts the
operating point into the curve (even harmonics), recentered so bias 0 == raw.

Drop a sample on the hero and ITS waveform becomes the transfer function:
the dropped buffer is read into a 256-point table spanning the whole file,
which is plotted as the input->output curve (the live IO dot rides it) and —
in the gen~ core — is what actually waveshapes the incoming signal (each input
amplitude indexes the table). The SCOPE view still shows the raw scrolling
waveform. Clearing (double-click) returns to the built-in character curves.

Messages in (inlet 0):
    set_drive <db>          0..36 (drive amount in dB)
    set_character <idx>     0..6
    set_bias <amt>          -1..1 (asymmetry / even harmonics)
    set_mix <pct>           readout only
    io_level <env_lin>      live |input| 0..1 (~30ms)
    set_mode <0|1>          0 = curve view, 1 = scope view
    set_dmode <idx>         active color/distortion mode (syncs the swatches)
    set_zmode <z> <v>       set a zone's mode override (0 AUTO, 1..4 = mode+1)
    draw_sample <bufname>   load the dropped buffer as the shaper table
    scope_tick              advance the scope window (patcher metro)

Messages out (outlet 0):
    drive <db>              while dragging
    mode <0|1>              view auto-switch (syncs the rail toggle)
    sample <0|1>            sample loaded / cleared (arms the DSP shaper)
    wt_start <frame>        current wavetable window start (gen~ reads here)
    wt_gain <factor>        per-window normalize gain (gen~ scales the lookup)
    dmode <idx>             color/distortion mode picked from a hero swatch
    zmode_lo/mid/hi <v>     a zone strip cycled (per-third mode override)
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)
from .design_system import design_system_js

WAVESHAPE_CURVE_INLETS = 1
WAVESHAPE_CURVE_OUTLETS = 1

__all__ = ["WAVESHAPE_CURVE_INLETS", "WAVESHAPE_CURVE_OUTLETS", "waveshape_curve_js"]


def waveshape_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    curve_color="0.95, 0.97, 0.99, 0.95",
    unity_color="0.35, 0.38, 0.42, 0.85",
    heat_fill_color="0.92, 0.34, 0.20, 0.18",
    dot_color="0.95, 0.45, 0.22, 1.0",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    accent_color="0.95, 0.45, 0.22, 1.0",
):
    """Return JavaScript source for the waveshape display."""
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return design_system_js() + "\n" + _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        curve_color=curve_color,
        unity_color=unity_color,
        heat_fill_color=heat_fill_color,
        dot_color=dot_color,
        grid_color=grid_color,
        text_color=text_color,
        accent_color=accent_color,
    )


_JS_TEMPLATE = Template("""\
// Waveshape Display - generated by m4l-builder
// ES5 compatible; full pointer handler set for v8ui drags.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var CURVE_CLR  = [$curve_color];
var UNITY_CLR  = [$unity_color];
var HEAT_CLR   = [$heat_fill_color];
var DOT_CLR    = [$dot_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];
var ACCENT_CLR = [$accent_color];

var CHAR_NAMES = ["TAPE", "TUBE", "CLIP", "FOLD", "DIODE", "WRAP", "SOFT"];
var NUM_CHARS = 7;

var MARGIN = 10;
var drive_db = 0.0;
var character = 0;
var character_b = 0;   // it168: morph target character (B)
var morph = 0.0;       // it168: 0..1 crossfade from character A to character B
var bias = 0.0;
var mix_pct = 100;
var env_lin = 0.0;
var dragging = 0;
var hovering = 0;
var drag_start_y = 0;
var drag_start_drive = 0.0;
var drag_start_x = 0;
var drag_start_bias = 0.0;

// Dropped sample as a scrolling OSCILLOSCOPE: a window of the sample's actual
// samples (a line trace, not a min/max blob) plus the SATURATED version
// (shape() applied through the mix) so you watch the distortion on real audio.
// A metro in the patcher advances the window via scope_tick. `mode` (0 =
// transfer curve, 1 = sample scope) is driven by the SCOPE/CURVE rail toggle;
// a fresh drop auto-switches to scope (emitting "mode 1" to sync the toggle).
var WAVE_WIN = 512;        // samples shown at once (a couple of cycles)
var TRIG_SEARCH = 700;     // samples scanned for a rising zero-cross (scope trigger)
var sample_loaded = 0;
var sample_name = "";
var scope_frames = 0;
var scope_pos = 0;
var scope = [];            // current window of samples
var mode = 0;              // 0 = transfer curve, 1 = sample scope
var live_scope = [];       // live OUTPUT waveform window (Phase-4 oscilloscope)
var live_scope_name = "";  // named buffer~ the device records the output into
var live_scope_dry = [];   // live DRY (input) waveform — the before/after ghost
var live_scope_dry_name = "";  // named buffer~ the device records the input into

// The CURRENT wavetable = the WAVE_WIN window at scope_pos (== `scope`): drawn
// as the transfer curve (input -1..1 -> window sample -> output) and applied,
// for the same window, by the gen~ core. It scans the file as scope_pos scrolls
// so the table morphs; the gen~ follows via the wt_start it is sent.
var curve_tbl = [];
var curve_n = 0;

// Self-clocking scan: a repeating Task advances the window from INSIDE the v8ui
// (proven in eq_curve — Task.repeat() runs in Live where a patcher metro auto-
// start and snapshot~ clock both failed to tick this display). schedule() no-ops
// in Live, so use interval+repeat. Absent in the Node harness (guarded).
var scan_task = null;
var scan_running = 0;
var SCAN_MS = 33;
var SCAN_TRAVERSE_SEC = 12;   // scan the WHOLE file in ~this many seconds,
                              // so long samples morph at a usable rate.

// Per-window normalize: scale each window so its peak fills the range, so even
// a quiet slice is a usable full-range wavetable (and visibly distorts). Capped
// so near-silence isn't blown up into noise; the gen~ applies the same wt_gain.
var WT_MAX_GAIN = 8.0;
var WT_MIN_PEAK = 0.02;
var wt_gain_val = 1.0;

// MODES: each is a color THEME (palette) + an extra distortion the gen~ layers
// after the wavetable/character (Ala: "modes that change colors" + "modes that
// further distort it"). The hero recolors per mode; clickable swatches at the
// bottom pick the mode (interactive) and drive the gen~ "dmode" param. Each
// palette is a list of [t, r, g, b] gradient stops across the input axis.
var PALETTES = [
    [[0.00,0.96,0.28,0.32],[0.17,0.97,0.62,0.18],[0.34,0.95,0.88,0.25],
     [0.50,0.42,0.88,0.42],[0.67,0.28,0.78,0.95],[0.84,0.55,0.48,0.97],
     [1.00,0.92,0.42,0.92]],                                   // 0 PRISM (rainbow)
    [[0.00,0.45,0.04,0.02],[0.40,0.93,0.26,0.06],[0.72,0.98,0.62,0.12],
     [1.00,0.99,0.92,0.55]],                                   // 1 FOLD (fire)
    [[0.00,0.05,0.16,0.50],[0.45,0.10,0.55,0.93],[0.78,0.38,0.86,0.98],
     [1.00,0.86,0.98,1.00]],                                   // 2 CRUSH (ice)
    [[0.00,0.95,0.12,0.62],[0.40,0.62,0.10,0.94],[0.72,0.28,0.82,0.55],
     [1.00,0.22,0.94,0.86]],                                   // 3 SHRED (neon)
];
var PALETTE_NAMES = ["PRISM", "FOLD", "CRUSH", "SHRED"];
var dmode = 0;

// ZONES: the input axis is split into thirds (LOW/MID/HIGH). Each zone has its
// own mode override (0 = AUTO = follow the global brush dmode; 1..4 = a specific
// mode +1). Click a zone strip (bottom of the hero) to cycle that third's mode,
// so different PARTS of the wave get different colors + distortion (Ala: "select
// parts of the wave and the color affects that part"). The gen~ mirrors this.
var NUM_ZONES = 3;
var zone_mode = [0, 0, 0];

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

// Effective mode (0..3) of a zone: AUTO follows the global brush.
function zone_eff(z) {
    var v = zone_mode[z];
    return (v === 0) ? dmode : clamp(v - 1, 0, PALETTES.length - 1);
}
function any_zone_painted() {
    var i;
    for (i = 0; i < NUM_ZONES; i++) { if (zone_mode[i] !== 0) return 1; }
    return 0;
}
function set_zmode(z, v) {
    if (z < 0 || z >= NUM_ZONES) return;
    zone_mode[z] = clamp(Math.floor(v), 0, PALETTES.length);
    mgraphics.redraw();
}

// DRAGGABLE zone boundaries (plot-fractions of the input axis). Default thirds;
// drag a divider on the plot to resize which PART of the wave each color/mode
// covers (Ala: "select parts of the wave and the color affects that part"). The
// gen~ reads the same splits as z_split_lo/hi (input amplitude -1..1).
var zone_bound = [1.0 / 3.0, 2.0 / 3.0];
var drag_bound = -1;
var drag_morph = 0;    // it169: dragging the A<->B morph rail at the hero's top edge
function zone_lo_t(z) { return z <= 0 ? 0.0 : zone_bound[z - 1]; }
function zone_hi_t(z) { return z >= NUM_ZONES - 1 ? 1.0 : zone_bound[z]; }
// Param echoes (input -1..1 -> plot fraction). Ignored mid-drag (drag owns it).
function set_z_split_lo(v) {
    if (drag_bound >= 0) return;
    zone_bound[0] = clamp((v + 1.0) * 0.5, 0.04, zone_bound[1] - 0.04);
    mgraphics.redraw();
}
function set_z_split_hi(v) {
    if (drag_bound >= 0) return;
    zone_bound[1] = clamp((v + 1.0) * 0.5, zone_bound[0] + 0.04, 0.96);
    mgraphics.redraw();
}
function bound_x(i) { return plot_l() + zone_bound[i] * plot_w(); }
function bound_hit(px, py) {
    if (isNaN(px) || isNaN(py)) return -1;
    if (py < plot_t() || py > plot_b()) return -1;
    var i;
    for (i = 0; i < 2; i++) { if (Math.abs(px - bound_x(i)) <= 5.0) return i; }
    return -1;
}

// Read WAVE_WIN consecutive samples at the current scroll position. This window
// IS the live wavetable: `scope` (drawn as the oscilloscope) and `curve_tbl`
// (drawn as the transfer curve + interpolated by sample_transfer) are the same
// data, and the gen~ core reads the same window via wt_start. (Max-only: new
// Buffer/peek are absent in the Node harness, so this no-ops there, leaving any
// test-injected `scope`/`curve_tbl` intact.)
function read_window() {
    if (typeof Buffer === "undefined") return;
    var b = new Buffer("" + sample_name);
    var f = b.framecount();
    if (!f || f < 2) return;
    scope_frames = f;
    var count = (f < WAVE_WIN) ? f : WAVE_WIN;
    var start = scope_pos;
    if (start + count > f) start = f - count;
    if (start < 0) start = 0;
    var chunk = b.peek(1, start, count);
    var raw = (chunk.length === undefined) ? [chunk] : chunk;

    // Peak-normalize the window (capped) so quiet slices still fill the table.
    var i, a, pk = 0.0;
    for (i = 0; i < raw.length; i++) { a = raw[i] < 0 ? -raw[i] : raw[i]; if (a > pk) pk = a; }
    wt_gain_val = (pk > WT_MIN_PEAK) ? Math.min(1.0 / pk, WT_MAX_GAIN) : 1.0;
    var norm = [];
    for (i = 0; i < raw.length; i++) norm.push(raw[i] * wt_gain_val);

    scope = norm;
    curve_tbl = norm;
    curve_n = norm.length;
    outlet(0, "wt_gain", wt_gain_val);   // gen applies the same normalize gain
    mgraphics.redraw();
}

// Phase-4 live oscilloscope: the device records its OUTPUT into a named buffer~
// (a parallel tap, no DSP change); the SCOPE view reads a window of it so you
// watch the actual shaped waveform. Shown at TRUE amplitude (no normalize) so a
// driven/clipped output reads hot. (Buffer/peek are Max-only -> no-ops in Node.)
function set_live_scope(name) { live_scope_name = "" + name; }
// The DRY (pre-saturation input) buffer — drawn as a faint ghost behind the wet
// output so the saturation reads as a before/after (Saturn/Rift signature).
function set_live_scope_dry(name) { live_scope_dry_name = "" + name; }
function read_scope_buf(name) {
    if (typeof Buffer === "undefined" || name === "") return [];
    var b = new Buffer(name);
    var f = b.framecount();
    if (!f || f < 2) return [];
    // Read a search window + a display window, then TRIGGER: start the trace at
    // the first rising zero-crossing so the waveform is phase-stable (a free-
    // running ring buffer otherwise scrolls). Falls back to 0 if none is found.
    var want = WAVE_WIN + TRIG_SEARCH;
    var rd = (f < want) ? f : want;
    var chunk = b.peek(1, 0, rd);
    return trigger_slice((chunk.length === undefined) ? [chunk] : chunk);
}
function live_read() { live_scope = read_scope_buf(live_scope_name); }
function live_read_dry() { live_scope_dry = read_scope_buf(live_scope_dry_name); }

// Trigger + slice: find the first rising zero-crossing in the search region and
// return WAVE_WIN samples from there (phase-stable trace); fall back to index 0.
// Pure (no Buffer) so it's unit-testable in the Node harness.
function trigger_slice(raw) {
    var n = raw.length, start = 0, i, lim = n - WAVE_WIN;
    if (n < 2) return raw;
    if (lim < 0) lim = 0;
    if (lim > TRIG_SEARCH) lim = TRIG_SEARCH;
    for (i = 1; i <= lim; i++) {
        if (raw[i - 1] < 0.0 && raw[i] >= 0.0) { start = i; break; }
    }
    var out = [], cnt = (n - start < WAVE_WIN) ? (n - start) : WAVE_WIN;
    for (i = 0; i < cnt; i++) out.push(raw[start + i]);
    return out;
}

// Interpolated transfer lookup: input x in -1..1 -> current-window value
// (mirrors the gen~ peek). Identity when no table so the IO dot still rides.
function sample_transfer(x) {
    var n = curve_n;
    if (n < 2) return x;
    var idx = (clamp(x, -1.0, 1.0) + 1.0) * 0.5 * (n - 1);
    var i0 = Math.floor(idx), fr = idx - i0;
    if (i0 >= n - 1) return curve_tbl[n - 1];
    return curve_tbl[i0] * (1.0 - fr) + curve_tbl[i0 + 1] * fr;
}

// A dropped sample becomes the live wavetable: read the first window, show it
// as the scrolling oscilloscope (the current wave table), arm the DSP shaper
// ("sample 1") and tell the gen~ which window to read ("wt_start 0"). Empty/
// early reads no-op (a later trigger redraws + re-emits).
function draw_sample(name) {
    if (typeof Buffer === "undefined") return;
    var b = new Buffer("" + name);
    var frames = b.framecount();
    if (!frames || frames < 2) { return; }
    sample_name = "" + name;
    scope_frames = frames;
    scope_pos = 0;
    sample_loaded = 1;
    mode = 1;                 // show the oscilloscope (the current wave table)
    outlet(0, "sample", 1);   // arm the gen~ sample shaper
    outlet(0, "mode", 1);     // sync the rail toggle to SCOPE
    outlet(0, "wt_start", 0); // gen reads the same window
    read_window();
    start_scan();             // begin scanning the window (the table morphs)
}

// Advance the wavetable window WHENEVER a sample is loaded — independent of
// which view is showing — so the table scans/morphs and the gen~ follows. Loops
// at the end; emits the new window start to the gen. Called by the repeating
// scan Task (and accepted as a message for completeness).
function scope_tick() {
    if (!sample_loaded) return;
    // Step scales with file length so the whole sample traverses in ~TRAVERSE
    // seconds regardless of size (a fixed step crawls through long files).
    var step = Math.floor(scope_frames / (SCAN_TRAVERSE_SEC * 30));
    if (step < 64) step = 64;
    scope_pos += step;
    if (scope_pos + WAVE_WIN >= scope_frames) scope_pos = 0;
    outlet(0, "wt_start", scope_pos);
    read_window();
}

// Start/stop the self-clocking scan (no-ops in the Node harness: Task absent).
function start_scan() {
    if (typeof Task === "undefined") return;
    if (!scan_task) scan_task = new Task(scope_tick, this);
    if (!scan_running) {
        scan_running = 1;
        scan_task.interval = SCAN_MS;
        scan_task.repeat();
    }
}
function stop_scan() {
    if (scan_task && scan_running) { scan_task.cancel(); scan_running = 0; }
}

function set_mode(m) { mode = (m > 0.5) ? 1 : 0; mgraphics.redraw(); }

function clear_sample() {
    stop_scan();
    sample_loaded = 0;
    mode = 0;
    scope = [];
    curve_tbl = [];
    curve_n = 0;
    outlet(0, "sample", 0);   // disarm the gen~ sample shaper
    outlet(0, "mode", 0);
    mgraphics.redraw();
}

function plot_l() { return MARGIN + 8; }
function plot_r() { return mgraphics.size[0] - MARGIN; }
function plot_t() { return MARGIN; }
function plot_b() { return mgraphics.size[1] - MARGIN - 4; }
function plot_w() { return plot_r() - plot_l(); }
function plot_h() { return plot_b() - plot_t(); }

function x_of(v) { return plot_l() + ((v + 1.0) * 0.5) * plot_w(); }
function y_of(v) { return plot_b() - ((v + 1.0) * 0.5) * plot_h(); }

function drive_lin() {
    // 0..36 dB mapped to a 1..~8 shaping factor.
    return 0.05 + (drive_db / 36.0) * 8.0;
}

// Mirrors the gen~ core shape(x, d, ch) — keep in sync. Pure/stateless.
// `ch` selects the character (defaults to the active `character`) so the morph
// can evaluate both endpoints.
function shape_raw(x, ch) {
    if (ch === undefined) ch = character;
    var d = drive_lin();
    var v, dn, nf, u, dp;
    if (ch === 0) {                              // TAPE
        v = Math.tanh(d * x) / Math.tanh(d);
    } else if (ch === 1) {                       // TUBE
        dp = x >= 0 ? d * 1.6 : d * 0.9;
        v = clamp(Math.tanh(dp * x) / Math.tanh(d * 1.25), -1.0, 1.0);
    } else if (ch === 2) {                       // CLIP
        v = clamp(x * (1.0 + (d - 1.0) * 0.6), -1.0, 1.0);
    } else if (ch === 3) {                       // FOLD
        v = Math.sin(x * d * Math.PI * 0.5);
    } else if (ch === 4) {                       // DIODE
        dn = clamp((d - 0.05) * 0.125, 0.0, 1.0);
        nf = 1.0 - 0.6 * dn;
        v = x >= 0 ? Math.tanh(d * x) / Math.tanh(d)
                   : Math.tanh(d * nf * x) / Math.tanh(d);
    } else if (ch === 5) {                       // WRAP
        v = 0.63661977 * Math.asin(Math.sin(x * (1.0 + d * 0.6) * Math.PI * 0.5));
    } else {                                     // SOFT
        dn = clamp((d - 0.05) * 0.125, 0.0, 1.0);
        u = clamp(x * (0.667 + dn * 0.9), -1.0, 1.0);
        v = 1.5 * u - 0.5 * u * u * u;
    }
    return v;
}

// Biased transfer for character `ch`: shift into the curve + recenter (even
// harmonics). Matches the gen's shape(s + b, d, ch) - shape(b, d, ch).
function shape_ch(x, ch) {
    var b = clamp(bias, -1.0, 1.0) * 0.5;
    if (b === 0.0) return shape_raw(x, ch);
    return clamp(shape_raw(x + b, ch) - shape_raw(b, ch), -1.0, 1.0);
}

// The CHARACTER-MORPH transfer (it168): character A crossfaded to character B by
// `morph` (0..1). morph 0 => pure A (bit-identical to the pre-morph curve), so
// every existing caller (curve, IO dots, sample overlay) morphs automatically.
function shape(x) {
    var a = shape_ch(x, character);
    if (morph <= 0.0 || character_b === character) return a;
    return a + (shape_ch(x, character_b) - a) * morph;
}

// Horizontal gradient across the plot from the ACTIVE mode's palette: the
// wavetable / transfer / character curve is colored by input position, so
// different colors land on different parts of the curve (Ala: "the colors affect
// different parts of the curve" / "rainbow with multiple colors"). One gradient
// source -> one stroke/fill (cheap). Mode 0 = PRISM rainbow.
function palette_grad(a) {
    var p = PALETTES[dmode] || PALETTES[0];
    var g = mgraphics.pattern_create_linear(plot_l(), 0, plot_r(), 0);
    for (var i = 0; i < p.length; i++) {
        g.add_color_stop_rgba(p[i][0], p[i][1], p[i][2], p[i][3], a);
    }
    return g;
}

// Mid color of a palette (for the swatches), as [r,g,b].
function palette_mid(idx) {
    var p = PALETTES[idx] || PALETTES[0];
    var m = p[(p.length / 2) | 0];
    return [m[1], m[2], m[3]];
}

function set_dmode(i) {
    dmode = clamp(Math.floor(i), 0, PALETTES.length - 1);
    mgraphics.redraw();
}

// Gradient with HARD zone boundaries: each input third is colored by its zone's
// effective mode (PRISM spreads the rainbow within the third; other modes use a
// solid theme color). Falls back to the smooth global palette when nothing is
// painted, so the default look is unchanged.
function zone_grad(a) {
    if (!any_zone_painted()) return palette_grad(a);
    var g = mgraphics.pattern_create_linear(plot_l(), 0, plot_r(), 0);
    var z, t0, t1, eff, pal, k, tt, c;
    for (z = 0; z < NUM_ZONES; z++) {
        t0 = zone_lo_t(z); t1 = zone_hi_t(z);
        eff = zone_eff(z);
        if (eff === 0) {
            pal = PALETTES[0];
            for (k = 0; k < pal.length; k++) {
                tt = t0 + pal[k][0] * (t1 - t0);
                g.add_color_stop_rgba(tt, pal[k][1], pal[k][2], pal[k][3], a);
            }
        } else {
            c = palette_mid(eff);
            g.add_color_stop_rgba(t0 + 0.0005, c[0], c[1], c[2], a);
            g.add_color_stop_rgba(t1 - 0.0005, c[0], c[1], c[2], a);
        }
    }
    return g;
}

// Oscilloscope of the CURRENT wavetable: the WAVE_WIN window scanning the file.
// This is exactly the slice the gen~ uses as the transfer function, so watching
// it scroll IS watching the distortion shape morph. Rainbow fill + trace.
function draw_scope() {
    var n = scope.length;
    if (n < 2) return;
    var l = plot_l(), r = plot_r(), t = plot_t(), b = plot_b();
    var w = r - l, cy = (t + b) * 0.5, amp = (b - t) * 0.5 - 1.0;
    var c, xx, yy;

    // Center line.
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(l, cy); mgraphics.line_to(r, cy); mgraphics.stroke();

    // Rainbow fill under the wavetable (low alpha).
    mgraphics.set_source(zone_grad(0.16));
    mgraphics.move_to(l, cy);
    for (c = 0; c < n; c++) {
        xx = l + (c / (n - 1)) * w; yy = cy - clamp(scope[c], -1.0, 1.0) * amp;
        mgraphics.line_to(xx, yy);
    }
    mgraphics.line_to(r, cy);
    mgraphics.close_path();
    mgraphics.fill();

    // The wavetable trace, rainbow-colored by position.
    mgraphics.set_source(zone_grad(0.97));
    mgraphics.set_line_width(1.7);
    for (c = 0; c < n; c++) {
        xx = l + (c / (n - 1)) * w; yy = cy - clamp(scope[c], -1.0, 1.0) * amp;
        if (c === 0) mgraphics.move_to(xx, yy); else mgraphics.line_to(xx, yy);
    }
    mgraphics.stroke();

    // Label.
    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.set_font_size(7.5);
    mgraphics.move_to(l + 4, b - 4);
    mgraphics.show_text("WAVETABLE  -  dbl-click to clear");
}

// Live OUTPUT oscilloscope: the recorded output waveform at TRUE amplitude,
// rainbow-traced over a center line. This is what Heat is actually doing to the
// audio right now (Rift-style) — drive/character/bias visibly reshape it.
function draw_live_scope() {
    var n = live_scope.length;
    if (n < 2) return;
    var l = plot_l(), r = plot_r(), t = plot_t(), b = plot_b();
    var w = r - l, cy = (t + b) * 0.5, amp = (b - t) * 0.5 - 1.0;
    var c, xx, yy;

    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.move_to(l, cy); mgraphics.line_to(r, cy); mgraphics.stroke();

    // DRY (input) ghost trace behind the wet output: a faint neutral line so the
    // saturation reads as a before/after (at drive 0 the two overlap; as Drive
    // climbs the bright output squares/folds away from the calm dry sine).
    var dn = live_scope_dry.length;
    if (dn > 1) {
        mgraphics.set_source_rgba(0.60, 0.65, 0.72, 0.34);
        mgraphics.set_line_width(1.0);
        for (c = 0; c < dn; c++) {
            xx = l + (c / (dn - 1)) * w; yy = cy - clamp(live_scope_dry[c], -1.0, 1.0) * amp;
            if (c === 0) mgraphics.move_to(xx, yy); else mgraphics.line_to(xx, yy);
        }
        mgraphics.stroke();
    }

    mgraphics.set_source(zone_grad(0.14));
    mgraphics.move_to(l, cy);
    for (c = 0; c < n; c++) {
        xx = l + (c / (n - 1)) * w; yy = cy - clamp(live_scope[c], -1.0, 1.0) * amp;
        mgraphics.line_to(xx, yy);
    }
    mgraphics.line_to(r, cy);
    mgraphics.close_path();
    mgraphics.fill();

    mgraphics.set_source(zone_grad(0.97));
    mgraphics.set_line_width(1.6);
    for (c = 0; c < n; c++) {
        xx = l + (c / (n - 1)) * w; yy = cy - clamp(live_scope[c], -1.0, 1.0) * amp;
        if (c === 0) mgraphics.move_to(xx, yy); else mgraphics.line_to(xx, yy);
    }
    mgraphics.stroke();

    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.set_font_size(7.5);
    mgraphics.move_to(l + 4, b - 4);
    mgraphics.show_text((live_scope_dry.length > 1) ? "DRY -> OUTPUT" : "LIVE OUTPUT");
}

// The sample-as-transfer-function: curve_tbl plotted input->output, with the
// unity reference and the live IO dot riding it. This is exactly what the gen~
// core does to the incoming signal (drop a sample -> the wave distorts it).
function draw_sample_transfer() {
    var n = curve_n;
    if (n < 2) return;
    var i, x, y;

    // Unity reference.
    mgraphics.set_source_rgba(UNITY_CLR);
    mgraphics.move_to(x_of(-1), y_of(-1));
    mgraphics.line_to(x_of(1), y_of(1));
    mgraphics.stroke();

    // The sample transfer curve, rainbow-colored by input position.
    mgraphics.set_source(zone_grad(0.97));
    mgraphics.set_line_width(dragging || hovering ? 2.4 : 1.7);
    for (i = 0; i < n; i++) {
        x = plot_l() + (i / (n - 1)) * plot_w();
        y = y_of(clamp(curve_tbl[i], -1.0, 1.0));
        if (i === 0) mgraphics.move_to(x, y); else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    // Live IO: lit reached-segment + glowing dot pair on the sample transfer.
    if (env_lin > 0.003) {
        var e = clamp(env_lin, 0.0, 1.0);
        draw_lit_segment(1, e);
        draw_io_dot(x_of(e), y_of(sample_transfer(e)), e);
        draw_io_dot(x_of(-e), y_of(sample_transfer(-e)), e);
    }

    // Label.
    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.set_font_size(7.5);
    mgraphics.move_to(plot_l() + 4, plot_b() - 4);
    mgraphics.show_text("SAMPLE SHAPER  -  dbl-click to clear");
}

// ── Mode swatches (bottom-right): click one to pick the color theme + extra
// distortion. The active swatch is ringed; clicking emits "dmode <i>".
function swatch_count() { return PALETTES.length; }
function swatch_w() { return 17; }
function swatch_h() { return 9; }
function swatch_gap() { return 3; }
function swatch_y() { return plot_b() - swatch_h() - 3; }
function swatch_x(i) {
    var step = swatch_w() + swatch_gap();
    return plot_r() - (swatch_count() - i) * step - 2;
}

function draw_swatches() {
    var i, sx, sy = swatch_y(), sw = swatch_w(), sh = swatch_h(), c;
    // Active mode name above the row.
    mgraphics.set_source_rgba(TEXT_CLR);
    mgraphics.set_font_size(6.5);
    mgraphics.move_to(swatch_x(0), sy - 3);
    mgraphics.show_text(PALETTE_NAMES[dmode]);
    for (i = 0; i < swatch_count(); i++) {
        sx = swatch_x(i);
        c = palette_mid(i);
        mgraphics.set_source_rgba(c[0], c[1], c[2], (i === dmode) ? 0.95 : 0.45);
        mgraphics.rectangle(sx, sy, sw, sh);
        mgraphics.fill();
        if (i === dmode) {
            mgraphics.set_source_rgba(1.0, 1.0, 1.0, 0.9);
            mgraphics.set_line_width(1.0);
            mgraphics.rectangle(sx + 0.5, sy + 0.5, sw - 1, sh - 1);
            mgraphics.stroke();
        }
    }
}

// Which swatch (if any) is under a point. -1 = none.
function swatch_hit(px, py) {
    if (isNaN(px) || isNaN(py)) return -1;
    var sy = swatch_y(), sh = swatch_h(), sw = swatch_w(), i, sx;
    if (py < sy - 3 || py > sy + sh + 3) return -1;
    for (i = 0; i < swatch_count(); i++) {
        sx = swatch_x(i);
        if (px >= sx - 1 && px <= sx + sw + 1) return i;
    }
    return -1;
}

// Click a swatch -> set the mode locally + drive the gen/param via "dmode".
function pick_mode(idx) {
    dmode = clamp(Math.floor(idx), 0, PALETTES.length - 1);
    outlet(0, "dmode", dmode);
    mgraphics.redraw();
}

// ── Zone strips: a row of three click-to-cycle bars (one per input third) just
// above the swatches. Each shows its zone's effective mode color; clicking
// cycles AUTO -> PRISM -> FOLD -> CRUSH -> SHRED -> AUTO and emits "zmode_*".
var ZONE_MSGS = ["zmode_lo", "zmode_mid", "zmode_hi"];
function zone_strip_h() { return 7; }
function zone_strip_y() { return swatch_y() - zone_strip_h() - 3; }
function zone_x0(z) { return plot_l() + zone_lo_t(z) * plot_w() + 2; }
function zone_x1(z) { return plot_l() + zone_hi_t(z) * plot_w() - 2; }

function draw_zone_strips() {
    var z, x0, x1, sy = zone_strip_y(), sh = zone_strip_h(), eff, c;
    for (z = 0; z < NUM_ZONES; z++) {
        x0 = zone_x0(z); x1 = zone_x1(z);
        eff = zone_eff(z);
        c = palette_mid(eff);
        // AUTO (unpainted) reads dim; a painted zone reads bright.
        mgraphics.set_source_rgba(c[0], c[1], c[2], zone_mode[z] === 0 ? 0.30 : 0.9);
        mgraphics.rectangle(x0, sy, x1 - x0, sh);
        mgraphics.fill();
        if (zone_mode[z] !== 0) {
            mgraphics.set_source_rgba(1.0, 1.0, 1.0, 0.85);
            mgraphics.set_line_width(1.0);
            mgraphics.rectangle(x0 + 0.5, sy + 0.5, x1 - x0 - 1, sh - 1);
            mgraphics.stroke();
        }
    }
}

// Draggable vertical dividers at the zone boundaries on the plot. Drawn with a
// little more presence + grip handles so they read as grab targets (the active
// one brightens while dragging).
function draw_zone_dividers() {
    var i, x, active, t, b;
    t = plot_t(); b = plot_b();
    for (i = 0; i < 2; i++) {
        x = bound_x(i);
        active = (drag_bound === i);
        mgraphics.set_source_rgba(0.92, 0.94, 0.98, active ? 0.85 : 0.34);
        mgraphics.set_line_width(active ? 1.6 : 1.0);
        mgraphics.move_to(x, t); mgraphics.line_to(x, b); mgraphics.stroke();
        // grip handles top + bottom
        mgraphics.set_source_rgba(0.92, 0.94, 0.98, active ? 0.95 : 0.55);
        mgraphics.rectangle(x - 2.0, t, 4.0, 3.0); mgraphics.fill();
        mgraphics.rectangle(x - 2.0, b - 3.0, 4.0, 3.0); mgraphics.fill();
    }
}

function zone_hit(px, py) {
    if (isNaN(px) || isNaN(py)) return -1;
    var sy = zone_strip_y(), sh = zone_strip_h(), z;
    if (py < sy - 2 || py > sy + sh + 2) return -1;
    for (z = 0; z < NUM_ZONES; z++) {
        if (px >= zone_x0(z) - 1 && px <= zone_x1(z) + 1) return z;
    }
    return -1;
}

function cycle_zone(z) {
    if (z < 0 || z >= NUM_ZONES) return;
    zone_mode[z] = (zone_mode[z] + 1) % (PALETTES.length + 1);  // +1 for AUTO
    outlet(0, ZONE_MSGS[z], zone_mode[z]);
    mgraphics.redraw();
}

// A glowing IO dot that IGNITES with the live program level (e = |env| 0..1):
// a radial glow (design-system) + bright core + white-hot center, so the hero
// pulses as the signal drives it. Pure display (rides the io_level stream).
function draw_io_dot(dx, dy, e) {
    ds_node_glow(dx, dy, DOT_CLR, 6.0 + e * 9.0, 0.26 + e * 0.42);
    mgraphics.set_source_rgba(DOT_CLR[0], DOT_CLR[1], DOT_CLR[2], 0.95);
    mgraphics.arc(dx, dy, 2.8, 0, Math.PI * 2); mgraphics.fill();
    mgraphics.set_source_rgba(1.0, 1.0, 1.0, 0.30 + e * 0.5);
    mgraphics.arc(dx, dy, 1.3, 0, Math.PI * 2); mgraphics.fill();
}

// A soft luminous overlay on the portion of the curve the signal is currently
// reaching (-e..+e), so the colored curve lights up brighter with the audio
// (Pro-C "lit segment" feel, kept low-alpha so the palette shows through).
function draw_lit_segment(transfer_is_sample, e) {
    var le = clamp(e, 0.0, 1.0), st, i, lv;
    if (le <= 0.006) return;
    mgraphics.set_source_rgba(1.0, 1.0, 1.0, 0.10 + le * 0.16);
    mgraphics.set_line_width(4.5);
    st = Math.max(2, Math.round(72 * le));
    for (i = 0; i <= st; i++) {
        lv = -le + (i / st) * (2.0 * le);
        if (i === 0) mgraphics.move_to(x_of(lv), y_of(transfer_is_sample ? sample_transfer(lv) : shape(lv)));
        else mgraphics.line_to(x_of(lv), y_of(transfer_is_sample ? sample_transfer(lv) : shape(lv)));
    }
    mgraphics.stroke();
}

// it169: one faint endpoint curve (character `ch`) behind the bright morph blend.
function draw_ghost_curve(ch, a) {
    var i, v;
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], a);
    mgraphics.set_line_width(1.0);
    for (i = 0; i <= 96; i++) {
        v = -1.0 + (i / 96) * 2.0;
        if (i === 0) mgraphics.move_to(x_of(v), y_of(shape_ch(v, ch)));
        else mgraphics.line_to(x_of(v), y_of(shape_ch(v, ch)));
    }
    mgraphics.stroke();
}

// it169: the MORPH rail — a draggable A<->B track at the hero's top edge. The
// handle position is the morph amount (left = pure A, right = pure B). Only shown
// when a distinct character B is selected (else there is nothing to morph to).
function morph_track_y() { return plot_t() + 4; }
function morph_track_x0() { return plot_l() + 14; }
function morph_track_x1() { return plot_r() - 14; }
function morph_handle_x() {
    return morph_track_x0() + morph * (morph_track_x1() - morph_track_x0());
}
function morph_active() { return character_b !== character; }
function draw_morph_track() {
    if (!morph_active()) return;
    var ty = morph_track_y(), x0 = morph_track_x0(), x1 = morph_track_x1();
    mgraphics.set_line_width(2.0);
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.30);
    mgraphics.move_to(x0, ty); mgraphics.line_to(x1, ty); mgraphics.stroke();
    mgraphics.set_font_size(6.0);
    mgraphics.set_source_rgba(TEXT_CLR[0], TEXT_CLR[1], TEXT_CLR[2], 0.55);
    mgraphics.move_to(plot_l() + 2, ty + 2.5); mgraphics.show_text("A");
    mgraphics.move_to(x1 + 4, ty + 2.5); mgraphics.show_text("B");
    var hx = morph_handle_x();
    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.ellipse(hx - 3.0, ty - 3.0, 6.0, 6.0);
    mgraphics.fill();
}
// A press on the top morph rail grabs it (takes the drag instead of the pad).
function morph_strip_hit(px, py) {
    if (!morph_active() || isNaN(px) || isNaN(py)) return 0;
    var ty = morph_track_y();
    return (py >= plot_t() - 3 && py <= ty + 6 &&
            px >= morph_track_x0() - 8 && px <= morph_track_x1() + 8) ? 1 : 0;
}
function apply_morph_x(x) {
    if (isNaN(x)) return;
    var f = clamp((x - morph_track_x0())
                  / Math.max(1.0, morph_track_x1() - morph_track_x0()), 0.0, 1.0);
    morph = f;
    outlet(0, "morph", Math.round(f * 1000) / 10);   // 0..100 (%) for the dial
    mgraphics.redraw();
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, y, v;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Quarter grid.
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.set_line_width(1.0);
    for (i = -1; i <= 1; i++) {
        x = x_of(i * 0.5);
        y = y_of(i * 0.5);
        mgraphics.move_to(x, plot_t()); mgraphics.line_to(x, plot_b()); mgraphics.stroke();
        mgraphics.move_to(plot_l(), y); mgraphics.line_to(plot_r(), y); mgraphics.stroke();
    }
    draw_zone_dividers();

    if (sample_loaded && mode === 1) {
        draw_scope();
    } else if (sample_loaded && curve_n > 1) {
        draw_sample_transfer();
    } else if (mode === 1 && live_scope.length > 1) {
        draw_live_scope();   // SCOPE view, no sample -> the live output waveform
    } else {
    // Unity diagonal.
    mgraphics.set_source_rgba(UNITY_CLR);
    mgraphics.move_to(x_of(-1), y_of(-1));
    mgraphics.line_to(x_of(1), y_of(1));
    mgraphics.stroke();

    // Heat fill: area between unity and the shape, tinted by the active palette.
    mgraphics.set_source(zone_grad(0.16));
    mgraphics.move_to(x_of(-1), y_of(-1));
    for (i = 0; i <= 96; i++) {
        v = -1.0 + (i / 96) * 2.0;
        mgraphics.line_to(x_of(v), y_of(shape(v)));
    }
    mgraphics.line_to(x_of(1), y_of(1));
    mgraphics.close_path();
    mgraphics.fill();

    // it169: when morphing, GHOST the two endpoint character curves (A + B)
    // faintly behind the bright blend, so you SEE the two shapes being crossfaded.
    if (morph > 0.0 && character_b !== character) {
        draw_ghost_curve(character, 0.20);
        draw_ghost_curve(character_b, 0.30);
    }

    // The shape curve, colored by the active palette across the input axis.
    mgraphics.set_source(zone_grad(0.97));
    mgraphics.set_line_width(dragging || hovering ? 2.3 : 1.8);
    for (i = 0; i <= 128; i++) {
        v = -1.0 + (i / 128) * 2.0;
        x = x_of(v);
        y = y_of(shape(v));
        if (i === 0) mgraphics.move_to(x, y);
        else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    // Live IO: the reached portion of the curve lights up + a glowing dot pair
    // ignites at the program level, so the hero pulses with the audio.
    if (env_lin > 0.003) {
        var e = clamp(env_lin, 0.0, 1.0);
        draw_lit_segment(0, e);
        draw_io_dot(x_of(e), y_of(shape(e)), e);
        draw_io_dot(x_of(-e), y_of(shape(-e)), e);
    }
    }

    // Border + readout.
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();

    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(8.0);
    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.move_to(plot_l() + 5, plot_t() + 11);
    var clabel = (morph > 0.0 && character_b !== character)
        ? (CHAR_NAMES[character] + "→" + CHAR_NAMES[character_b]
           + " " + Math.round(morph * 100) + "%")
        : CHAR_NAMES[character];
    mgraphics.show_text(clabel + "  " + (Math.round(drive_db * 10) / 10) + " dB");
    mgraphics.set_source_rgba(TEXT_CLR);
    mgraphics.move_to(plot_l() + 5, plot_t() + 21);
    mgraphics.show_text("MIX " + Math.round(mix_pct) + "%");

    // Zone strips + mode swatches on top of everything (always pickable).
    draw_zone_strips();
    draw_swatches();
    draw_morph_track();   // it169: the A<->B morph rail (top edge)
}

// ── Messages ─────────────────────────────────────────────────────────
function set_drive(v)     { drive_db = clamp(v, 0.0, 36.0); mgraphics.redraw(); }
function set_character(v) { character = clamp(Math.floor(v), 0, NUM_CHARS - 1); mgraphics.redraw(); }
function set_character_b(v) { character_b = clamp(Math.floor(v), 0, NUM_CHARS - 1); mgraphics.redraw(); }
function set_morph(v)    { if (drag_morph) return; morph = clamp(v, 0.0, 100.0) * 0.01; mgraphics.redraw(); }
function set_bias(v)      { bias = clamp(v, -1.0, 1.0); mgraphics.redraw(); }
function set_mix(v)       { mix_pct = clamp(v, 0, 100); mgraphics.redraw(); }
function io_level(e)      {
    env_lin = e;
    // Re-read the live output buffer on this proven 33ms message tick (patcher
    // metros silently fail to tick this display; io_level reliably arrives).
    if (mode === 1 && !sample_loaded && live_scope_name !== "") {
        live_read();
        if (live_scope_dry_name !== "") live_read_dry();
    }
    mgraphics.redraw();
}

// ── Interaction: vertical drag = drive; double-click clears the sample ──
// Robust v8ui pointer resolver (.y/.localY/.offsetY/.clientY); raw .y is
// undefined in Live. Relative feel kept (0.3 dB/px, 0.045 with shift) so
// dragging drive reshapes the saturated overlay over a dropped sample live.
function pointer_y(pe, fb) {
    if (!pe) return fb;
    if (pe.y !== undefined) return pe.y;
    if (pe.localY !== undefined) return pe.localY;
    if (pe.offsetY !== undefined) return pe.offsetY;
    if (pe.clientY !== undefined) return pe.clientY;
    return fb;
}
function pointer_x(pe, fb) {
    if (!pe) return fb;
    if (pe.x !== undefined) return pe.x;
    if (pe.localX !== undefined) return pe.localX;
    if (pe.offsetX !== undefined) return pe.offsetX;
    if (pe.clientX !== undefined) return pe.clientX;
    return fb;
}
function pointer_buttons(pe, fb) {
    if (!pe) return fb;
    if (pe.buttons !== undefined) return pe.buttons;
    if (pe.button !== undefined) return pe.button === 2 ? 2 : 1;
    return fb;
}

function start_drag(x, y) {
    if (isNaN(y)) return;
    dragging = 1;
    drag_bound = -1;
    ds_set_cursor(DS_CUR_GRAB);
    drag_start_y = y;
    drag_start_drive = drive_db;
    drag_start_x = isNaN(x) ? 0 : x;
    drag_start_bias = bias;
}

function drag_to(x, y, fine) {
    if (drag_morph) { apply_morph_x(x); return; }   // the morph rail owns this drag
    if (drag_bound >= 0) {
        // Move a zone boundary -> resize which part of the wave a color/mode
        // covers; emit the split as input amplitude (-1..1) for the gen~.
        if (isNaN(x)) return;
        var f = clamp((x - plot_l()) / Math.max(1.0, plot_w()),
            drag_bound === 0 ? 0.04 : zone_bound[0] + 0.04,
            drag_bound === 0 ? zone_bound[1] - 0.04 : 0.96);
        zone_bound[drag_bound] = f;
        outlet(0, drag_bound === 0 ? "z_split_lo" : "z_split_hi",
            Math.round((f * 2.0 - 1.0) * 1000) / 1000);
        mgraphics.redraw();
        return;
    }
    if (!dragging || isNaN(y)) return;
    // 2-axis pad: vertical = DRIVE (up = more, 0.3 dB/px; 0.045 with shift),
    // horizontal = BIAS (right = more asymmetry/even harmonics, 0.008/px;
    // 0.0015 with shift). A pure vertical drag leaves bias untouched.
    var dd = (drag_start_y - y) * (fine ? 0.045 : 0.3);
    drive_db = clamp(drag_start_drive + dd, 0.0, 36.0);
    outlet(0, "drive", Math.round(drive_db * 10) / 10);
    if (!isNaN(x)) {
        var bd = (x - drag_start_x) * (fine ? 0.0015 : 0.008);
        bias = clamp(drag_start_bias + bd, -1.0, 1.0);
        outlet(0, "bias", Math.round(bias * 100) / 100);
    }
    mgraphics.redraw();
}

function end_drag() {
    if (!dragging && drag_bound < 0 && !drag_morph) return;
    dragging = 0;
    drag_bound = -1;
    drag_morph = 0;
    ds_set_cursor(DS_CUR_ARROW);
    mgraphics.redraw();
}

function onpointerdown(pe) {
    var px = pointer_x(pe, -1), py = pointer_y(pe, -1);
    if (morph_strip_hit(px, py)) {              // the top morph rail grabs the drag
        drag_morph = 1; dragging = 1;
        ds_set_cursor(DS_CUR_GRAB);
        apply_morph_x(px);
        return;
    }
    var sh = swatch_hit(px, py);
    if (sh >= 0) { pick_mode(sh); return; }     // swatch wins over a drive drag
    var zh = zone_hit(px, py);
    if (zh >= 0) { cycle_zone(zh); return; }     // zone strip wins too
    var bh = bound_hit(px, py);                  // a zone divider grabs the drag
    if (bh >= 0) { drag_bound = bh; dragging = 1; ds_set_cursor(DS_CUR_GRAB); mgraphics.redraw(); return; }
    start_drag(pointer_x(pe, drag_start_x), pointer_y(pe, drag_start_y));
}
function onpointermove(pe) {
    if (dragging && ((pointer_buttons(pe, 1) & 1) !== 0)) {
        drag_to(pointer_x(pe, drag_start_x), pointer_y(pe, drag_start_y), pe && pe.shiftKey ? 1 : 0);
        return;
    }
    if (dragging) { end_drag(); return; }
    if (!hovering) { hovering = 1; mgraphics.redraw(); }
    // No hover-hand over the drive/bias pad — only a grab while actively dragging.
}
function onpointerup(pe) { end_drag(); }
function onpointerleave(pe) { hovering = 0; end_drag(); ds_set_cursor(DS_CUR_ARROW); mgraphics.redraw(); }
function ondblclick(x, y, but, cmd, shift, caps, opt, ctrl) {
    // Don't clear when double-clicking the bottom controls (swatches / zone
    // strips) — only an empty-plot double-click clears the sample.
    if (swatch_hit(x, y) >= 0 || zone_hit(x, y) >= 0) return;
    clear_sample();
}

function onclick(x, y, but, cmd, shift, caps, opt, ctrl) {
    var sh = swatch_hit(x, y);
    if (sh >= 0) { pick_mode(sh); return; }
    var zh = zone_hit(x, y);
    if (zh >= 0) { cycle_zone(zh); return; }
    start_drag(x, y);
}
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but) drag_to(x, y, shift);
    else end_drag();
}
function onidle(x, y) { if (!hovering) { hovering = 1; mgraphics.redraw(); } }
function onidleout() { hovering = 0; mgraphics.redraw(); }
function onresize(w, h) { mgraphics.redraw(); }
""")
