"""Saturator waveshape display (Saturn-style hero graph).

Linear in/out plot (-1..1) of the active transfer character at the current
drive, with a unity reference, harmonic-energy glow under the curve, and a
live IO dot riding the shape at the program level. Drag vertically to set
drive. Outlets fire only on user gestures (no-echo rule).

The shape math mirrors the gen~ core exactly — keep both in sync:
    0 TAPE   tanh(d*x)/tanh(d)
    1 TUBE   asymmetric tanh (positive half driven harder) — DC-blocked in DSP
    2 CLIP   hard clip at 1/d'
    3 FOLD   sine fold sin(d*x*pi/2)
    4 DIODE  asymmetric soft clip (negative half softened, drive-scaled)
    5 WRAP   triangle wavefolder (2/pi * asin(sin(.)))
    6 SOFT   cubic soft-clip 1.5u - 0.5u^3
All 7 are near-unity at drive 0 so the dry/wet null holds. Bias shifts the
operating point into the curve (even harmonics), recentered so bias 0 == raw.

Messages in (inlet 0):
    set_drive <db>          0..36 (drive amount in dB)
    set_character <idx>     0..6
    set_bias <amt>          -1..1 (asymmetry / even harmonics)
    set_mix <pct>           readout only
    io_level <env_lin>      live |input| 0..1 (~30ms)

Messages out (outlet 0):
    drive <db>              while dragging
"""

from __future__ import annotations

from string import Template

from ._graph_colors import (
    DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    DEFAULT_GRAPH_PLOT_COLOR,
    resolve_graph_panel_color,
)

WAVESHAPE_CURVE_INLETS = 1
WAVESHAPE_CURVE_OUTLETS = 1

__all__ = ["WAVESHAPE_CURVE_INLETS", "WAVESHAPE_CURVE_OUTLETS", "waveshape_curve_js"]


def waveshape_curve_js(
    *,
    bg_color=DEFAULT_GRAPH_PLOT_COLOR,
    panel_color=None,
    plot_border_color=DEFAULT_GRAPH_PLOT_BORDER_COLOR,
    curve_color="0.95, 0.97, 0.99, 0.95",
    unity_color="0.35, 0.38, 0.42, 0.85",
    heat_fill_color="0.92, 0.34, 0.20, 0.18",
    dot_color="0.95, 0.45, 0.22, 1.0",
    grid_color="0.20, 0.23, 0.27, 0.55",
    text_color="0.55, 0.58, 0.63, 1.0",
    accent_color="0.95, 0.45, 0.22, 1.0",
):
    """Return JavaScript source for the waveshape display."""
    panel_color = resolve_graph_panel_color(bg_color, panel_color)
    return _JS_TEMPLATE.substitute(
        bg_color=bg_color,
        panel_color=panel_color,
        plot_border_color=plot_border_color,
        curve_color=curve_color,
        unity_color=unity_color,
        heat_fill_color=heat_fill_color,
        dot_color=dot_color,
        grid_color=grid_color,
        text_color=text_color,
        accent_color=accent_color,
    )


_JS_TEMPLATE = Template("""\
// Waveshape Display - generated by m4l-builder
// ES5 compatible; full pointer handler set for v8ui drags.

mgraphics.init();
mgraphics.relative_coords = 0;
mgraphics.autofill = 0;

inlets = 1;
outlets = 1;

var BG_CLR     = [$bg_color];
var PANEL_CLR  = [$panel_color];
var BORDER_CLR = [$plot_border_color];
var CURVE_CLR  = [$curve_color];
var UNITY_CLR  = [$unity_color];
var HEAT_CLR   = [$heat_fill_color];
var DOT_CLR    = [$dot_color];
var GRID_CLR   = [$grid_color];
var TEXT_CLR   = [$text_color];
var ACCENT_CLR = [$accent_color];

var CHAR_NAMES = ["TAPE", "TUBE", "CLIP", "FOLD", "DIODE", "WRAP", "SOFT"];
var NUM_CHARS = 7;

var MARGIN = 10;
var drive_db = 0.0;
var character = 0;
var bias = 0.0;
var mix_pct = 100;
var env_lin = 0.0;
var dragging = 0;
var hovering = 0;
var drag_start_y = 0;
var drag_start_drive = 0.0;

function clamp(v, lo, hi) { return v < lo ? lo : (v > hi ? hi : v); }

function plot_l() { return MARGIN + 8; }
function plot_r() { return mgraphics.size[0] - MARGIN; }
function plot_t() { return MARGIN; }
function plot_b() { return mgraphics.size[1] - MARGIN - 4; }
function plot_w() { return plot_r() - plot_l(); }
function plot_h() { return plot_b() - plot_t(); }

function x_of(v) { return plot_l() + ((v + 1.0) * 0.5) * plot_w(); }
function y_of(v) { return plot_b() - ((v + 1.0) * 0.5) * plot_h(); }

function drive_lin() {
    // 0..36 dB mapped to a 1..~8 shaping factor.
    return 0.05 + (drive_db / 36.0) * 8.0;
}

// Mirrors the gen~ core shape(x, d, ch) — keep in sync. Pure/stateless.
function shape_raw(x) {
    var d = drive_lin();
    var v, dn, nf, u, dp;
    if (character === 0) {                       // TAPE
        v = Math.tanh(d * x) / Math.tanh(d);
    } else if (character === 1) {                // TUBE
        dp = x >= 0 ? d * 1.6 : d * 0.9;
        v = clamp(Math.tanh(dp * x) / Math.tanh(d * 1.25), -1.0, 1.0);
    } else if (character === 2) {                // CLIP
        v = clamp(x * (1.0 + (d - 1.0) * 0.6), -1.0, 1.0);
    } else if (character === 3) {                // FOLD
        v = Math.sin(x * d * Math.PI * 0.5);
    } else if (character === 4) {                // DIODE
        dn = clamp((d - 0.05) * 0.125, 0.0, 1.0);
        nf = 1.0 - 0.6 * dn;
        v = x >= 0 ? Math.tanh(d * x) / Math.tanh(d)
                   : Math.tanh(d * nf * x) / Math.tanh(d);
    } else if (character === 5) {                // WRAP
        v = 0.63661977 * Math.asin(Math.sin(x * (1.0 + d * 0.6) * Math.PI * 0.5));
    } else {                                     // SOFT
        dn = clamp((d - 0.05) * 0.125, 0.0, 1.0);
        u = clamp(x * (0.667 + dn * 0.9), -1.0, 1.0);
        v = 1.5 * u - 0.5 * u * u * u;
    }
    return v;
}

// Biased transfer: shift into the curve + recenter (even harmonics). Matches
// the gen's shape(s + b, d, ch) - shape(b, d, ch). bias 0 => exact shape_raw.
function shape(x) {
    var b = clamp(bias, -1.0, 1.0) * 0.5;
    if (b === 0.0) return shape_raw(x);
    return clamp(shape_raw(x + b) - shape_raw(b), -1.0, 1.0);
}

function paint() {
    var w = mgraphics.size[0];
    var h = mgraphics.size[1];
    var i, x, y, v;

    mgraphics.set_source_rgba(PANEL_CLR);
    mgraphics.rectangle(0, 0, w, h);
    mgraphics.fill();
    mgraphics.set_source_rgba(BG_CLR);
    mgraphics.rectangle(plot_l(), plot_t(), plot_w(), plot_h());
    mgraphics.fill();

    // Quarter grid.
    mgraphics.set_source_rgba(GRID_CLR);
    mgraphics.set_line_width(1.0);
    for (i = -1; i <= 1; i++) {
        x = x_of(i * 0.5);
        y = y_of(i * 0.5);
        mgraphics.move_to(x, plot_t()); mgraphics.line_to(x, plot_b()); mgraphics.stroke();
        mgraphics.move_to(plot_l(), y); mgraphics.line_to(plot_r(), y); mgraphics.stroke();
    }

    // Unity diagonal.
    mgraphics.set_source_rgba(UNITY_CLR);
    mgraphics.move_to(x_of(-1), y_of(-1));
    mgraphics.line_to(x_of(1), y_of(1));
    mgraphics.stroke();

    // Heat fill: area between unity and the shape (the "added harmonics").
    mgraphics.set_source_rgba(HEAT_CLR);
    mgraphics.move_to(x_of(-1), y_of(-1));
    for (i = 0; i <= 96; i++) {
        v = -1.0 + (i / 96) * 2.0;
        mgraphics.line_to(x_of(v), y_of(shape(v)));
    }
    mgraphics.line_to(x_of(1), y_of(1));
    mgraphics.close_path();
    mgraphics.fill();

    // The shape curve.
    mgraphics.set_source_rgba(CURVE_CLR);
    mgraphics.set_line_width(dragging || hovering ? 2.3 : 1.8);
    for (i = 0; i <= 128; i++) {
        v = -1.0 + (i / 128) * 2.0;
        x = x_of(v);
        y = y_of(shape(v));
        if (i === 0) mgraphics.move_to(x, y);
        else mgraphics.line_to(x, y);
    }
    mgraphics.stroke();

    // Live IO dots (symmetric pair at the program level).
    if (env_lin > 0.003) {
        var e = clamp(env_lin, 0.0, 1.0);
        var dxp = x_of(e), dyp = y_of(shape(e));
        var dxn = x_of(-e), dyn = y_of(shape(-e));
        mgraphics.set_source_rgba(DOT_CLR[0], DOT_CLR[1], DOT_CLR[2], 0.22);
        mgraphics.arc(dxp, dyp, 7.0, 0, Math.PI * 2); mgraphics.fill();
        mgraphics.arc(dxn, dyn, 7.0, 0, Math.PI * 2); mgraphics.fill();
        mgraphics.set_source_rgba(DOT_CLR);
        mgraphics.arc(dxp, dyp, 3.0, 0, Math.PI * 2); mgraphics.fill();
        mgraphics.arc(dxn, dyn, 3.0, 0, Math.PI * 2); mgraphics.fill();
    }

    // Border + readout.
    mgraphics.set_source_rgba(BORDER_CLR);
    mgraphics.set_line_width(1.0);
    mgraphics.rectangle(plot_l() + 0.5, plot_t() + 0.5, plot_w() - 1, plot_h() - 1);
    mgraphics.stroke();

    mgraphics.select_font_face("Arial");
    mgraphics.set_font_size(8.0);
    mgraphics.set_source_rgba(ACCENT_CLR);
    mgraphics.move_to(plot_l() + 5, plot_t() + 11);
    mgraphics.show_text(CHAR_NAMES[character] + "  " + (Math.round(drive_db * 10) / 10) + " dB");
    mgraphics.set_source_rgba(TEXT_CLR);
    mgraphics.move_to(plot_l() + 5, plot_t() + 21);
    mgraphics.show_text("MIX " + Math.round(mix_pct) + "%");
}

// ── Messages ─────────────────────────────────────────────────────────
function set_drive(v)     { drive_db = clamp(v, 0.0, 36.0); mgraphics.redraw(); }
function set_character(v) { character = clamp(Math.floor(v), 0, NUM_CHARS - 1); mgraphics.redraw(); }
function set_bias(v)      { bias = clamp(v, -1.0, 1.0); mgraphics.redraw(); }
function set_mix(v)       { mix_pct = clamp(v, 0, 100); mgraphics.redraw(); }
function io_level(e)      { env_lin = e; mgraphics.redraw(); }

// ── Interaction: vertical drag = drive ───────────────────────────────
function start_drag(y) {
    dragging = 1;
    drag_start_y = y;
    drag_start_drive = drive_db;
}

function drag_to(y, fine) {
    if (!dragging) return;
    // Up = more drive. 1 px = 0.3 dB (0.045 with shift).
    var dd = (drag_start_y - y) * (fine ? 0.045 : 0.3);
    drive_db = clamp(drag_start_drive + dd, 0.0, 36.0);
    outlet(0, "drive", Math.round(drive_db * 10) / 10);
    mgraphics.redraw();
}

function end_drag() {
    if (!dragging) return;
    dragging = 0;
    mgraphics.redraw();
}

function onpointerdown(pointerevent) { start_drag(pointerevent.y); }
function onpointermove(pointerevent) {
    if (dragging) drag_to(pointerevent.y, pointerevent.shiftKey ? 1 : 0);
    else if (!hovering) { hovering = 1; mgraphics.redraw(); }
}
function onpointerup(pointerevent) { end_drag(); }
function onpointerleave(pointerevent) { hovering = 0; end_drag(); mgraphics.redraw(); }

function onclick(x, y, but, cmd, shift, caps, opt, ctrl) { start_drag(y); }
function ondrag(x, y, but, cmd, shift, caps, opt, ctrl) {
    if (but) drag_to(y, shift);
    else end_drag();
}
function onidle(x, y) { if (!hovering) { hovering = 1; mgraphics.redraw(); } }
function onidleout() { hovering = 0; mgraphics.redraw(); }
function onresize(w, h) { mgraphics.redraw(); }
""")
