"""Wavetable display engine for jsui.

Renders a single cycle of a waveform as a connected line path inside Max's
jsui object. Receives a list of float samples via inlet and draws them.

Inlets:
    0 -- Sample list (floats in range -1.0 to 1.0)

Outlets:
    (none -- display only)
"""

WAVETABLE_DISPLAY_INLETS = 1
WAVETABLE_DISPLAY_OUTLETS = 0


def wavetable_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                          line_color="0.45, 0.75, 0.65, 1.0",
                          fill_color="0.45, 0.75, 0.65, 0.15"):
    """Return JavaScript source for a wavetable display (Max jsui).

    Args:
        bg_color: Background color (RGBA string).
        line_color: Waveform line color (RGBA string).
        fill_color: Fill color under the waveform (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    return (
        "// Wavetable Display — generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 1;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var samples = [];\n"
        "var num_samples = 0;\n"
        "\n"
        "// --- Input handler ---\n"
        "function msg_list() {\n"
        "    var i;\n"
        "    num_samples = arguments.length;\n"
        "    samples = [];\n"
        "    for (i = 0; i < num_samples; i++) {\n"
        "        samples[i] = Math.max(-1, Math.min(1, arguments[i]));\n"
        "    }\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var mid = h * 0.5;\n"
        "    var i, sx, sy;\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Center line\n"
        "    mgraphics.set_source_rgba(0.2, 0.2, 0.22, 0.4);\n"
        "    mgraphics.set_line_width(0.5);\n"
        "    mgraphics.move_to(0, mid);\n"
        "    mgraphics.line_to(w, mid);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    if (num_samples < 2) {\n"
        "        return;\n"
        "    }\n"
        "\n"
        "    // Build path for fill\n"
        f"    mgraphics.set_source_rgba({fill_color});\n"
        "    mgraphics.move_to(0, mid);\n"
        "    for (i = 0; i < num_samples; i++) {\n"
        "        sx = (i / (num_samples - 1)) * w;\n"
        "        sy = mid - samples[i] * mid;\n"
        "        mgraphics.line_to(sx, sy);\n"
        "    }\n"
        "    mgraphics.line_to(w, mid);\n"
        "    mgraphics.close_path();\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Draw waveform line\n"
        f"    mgraphics.set_source_rgba({line_color});\n"
        "    mgraphics.set_line_width(1.5);\n"
        "    sx = 0;\n"
        "    sy = mid - samples[0] * mid;\n"
        "    mgraphics.move_to(sx, sy);\n"
        "    for (i = 1; i < num_samples; i++) {\n"
        "        sx = (i / (num_samples - 1)) * w;\n"
        "        sy = mid - samples[i] * mid;\n"
        "        mgraphics.line_to(sx, sy);\n"
        "    }\n"
        "    mgraphics.stroke();\n"
        "}\n"
    )
