"""Waveform/oscilloscope display engine for jsui.

Generates JavaScript code that renders a scrolling waveform display inside
Max's jsui object using mgraphics (Cairo-based vector graphics).

The display supports three visual modes:
    0: Line trace (single colored waveform line)
    1: Filled (semi-transparent fill from waveform down to center)
    2: Dual/mirrored (butterfly display, positive above / negative below)

Inlets:
    0: list of float samples (waveform data, values -1.0 to 1.0)
    1: float display mode (0=line, 1=filled, 2=dual/mirrored)

DSP feeding:
    Use waveform_display_dsp() to wire a snapshot~ + zl.group chain from
    an audio signal outlet to the jsui inlet 0.
"""

from ..objects import newobj, patchline

WAVEFORM_INLETS = 2
WAVEFORM_OUTLETS = 0


def waveform_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                        line_color="0.45, 0.75, 0.65, 1.0",
                        fill_color="0.45, 0.75, 0.65, 0.2",
                        grid_color="0.15, 0.15, 0.17, 0.8",
                        center_color="0.25, 0.25, 0.27, 0.8",
                        glow_color="0.45, 0.75, 0.65, 0.15"):
    """Return JavaScript source for a waveform/oscilloscope display (Max jsui).

    The JS code draws a scrolling oscilloscope waveform using a circular
    buffer. Incoming list messages on inlet 0 add samples to the buffer;
    the display scrolls as new data arrives. Inlet 1 controls the visual
    mode (0=line, 1=filled, 2=dual/mirrored butterfly).

    Features:
        - Circular buffer for smooth scrolling display
        - Optional subtle grid lines and center line
        - Glow effect (double-draw: thick low-alpha + thin full-alpha)
        - Three display modes: line, filled, dual/mirrored
        - Rounded border frame
        - Graceful handling of empty/partial buffer data

    All color arguments are RGBA strings, e.g. ``"0.45, 0.75, 0.65, 1.0"``.

    Args:
        bg_color: Background fill color.
        line_color: Waveform trace color (full alpha).
        fill_color: Semi-transparent fill color (modes 1 and 2).
        grid_color: Grid line and border color.
        center_color: Center zero line color.
        glow_color: Glow halo color (low alpha, drawn thick behind trace).

    Returns:
        JavaScript source code string (ES5 compatible, Max jsui mgraphics).
    """
    return (
        "// Waveform Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 0;\n"
        "\n"
        "// --- Circular buffer ---\n"
        "var BUFFER_SIZE = 128;\n"
        "var buffer = [];\n"
        "var write_pos = 0;\n"
        "var has_data = false;\n"
        "\n"
        "// Pre-fill buffer with silence\n"
        "for (var _i = 0; _i < BUFFER_SIZE; _i++) { buffer[_i] = 0.0; }\n"
        "\n"
        "// --- Display mode (0=line, 1=filled, 2=dual/mirrored) ---\n"
        "var display_mode = 0;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function list() {\n"
        "    var args = arrayfromargs(arguments);\n"
        "    if (inlet == 0) {\n"
        "        for (var i = 0; i < args.length; i++) {\n"
        "            var s = args[i];\n"
        "            // Clamp to -1..1 for safety\n"
        "            if (s > 1.0) s = 1.0;\n"
        "            if (s < -1.0) s = -1.0;\n"
        "            buffer[write_pos] = s;\n"
        "            write_pos = (write_pos + 1) % BUFFER_SIZE;\n"
        "        }\n"
        "        has_data = true;\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_float(v) {\n"
        "    if (inlet == 1) {\n"
        "        display_mode = Math.floor(Math.max(0, Math.min(2, v)));\n"
        "        mgraphics.redraw();\n"
        "    }\n"
        "}\n"
        "\n"
        "function msg_int(v) { msg_float(v); }\n"
        "\n"
        "// --- Paint ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var cy = h * 0.5;\n"
        "    var amp = h * 0.45;\n"
        "\n"
        "    // --- Background ---\n"
        "    mgraphics.set_source_rgba(" + bg_color + ");\n"
        "    mgraphics.rectangle_rounded(0, 0, w, h, 3, 3);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // --- Grid lines (horizontal at ±0.5, vertical quarters) ---\n"
        "    mgraphics.set_line_width(1);\n"
        "    mgraphics.set_source_rgba(" + grid_color + ");\n"
        "\n"
        "    // Horizontal grid at +0.5\n"
        "    var gy1 = cy - amp * 0.5;\n"
        "    mgraphics.move_to(0, Math.round(gy1) + 0.5);\n"
        "    mgraphics.line_to(w, Math.round(gy1) + 0.5);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Horizontal grid at -0.5\n"
        "    var gy2 = cy + amp * 0.5;\n"
        "    mgraphics.move_to(0, Math.round(gy2) + 0.5);\n"
        "    mgraphics.line_to(w, Math.round(gy2) + 0.5);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Vertical grid at 1/4 and 3/4\n"
        "    var gx1 = Math.round(w * 0.25) + 0.5;\n"
        "    var gx2 = Math.round(w * 0.5) + 0.5;\n"
        "    var gx3 = Math.round(w * 0.75) + 0.5;\n"
        "    mgraphics.move_to(gx1, 0); mgraphics.line_to(gx1, h); mgraphics.stroke();\n"
        "    mgraphics.move_to(gx2, 0); mgraphics.line_to(gx2, h); mgraphics.stroke();\n"
        "    mgraphics.move_to(gx3, 0); mgraphics.line_to(gx3, h); mgraphics.stroke();\n"
        "\n"
        "    // --- Center zero line (slightly brighter) ---\n"
        "    mgraphics.set_source_rgba(" + center_color + ");\n"
        "    mgraphics.move_to(0, Math.round(cy) + 0.5);\n"
        "    mgraphics.line_to(w, Math.round(cy) + 0.5);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // --- Build waveform coordinate arrays ---\n"
        "    var xs = [];\n"
        "    var ys = [];\n"
        "    for (var i = 0; i < BUFFER_SIZE; i++) {\n"
        "        var read_pos = (write_pos + i) % BUFFER_SIZE;\n"
        "        xs[i] = (i / BUFFER_SIZE) * w;\n"
        "        ys[i] = cy - buffer[read_pos] * amp;\n"
        "    }\n"
        "\n"
        "    if (display_mode == 2) {\n"
        "        // --- Mode 2: Dual/mirrored (butterfly) ---\n"
        "        // Positive lobe fill (above center)\n"
        "        mgraphics.set_source_rgba(" + fill_color + ");\n"
        "        mgraphics.move_to(xs[0], cy);\n"
        "        for (var i = 0; i < BUFFER_SIZE; i++) {\n"
        "            var yc = cy - Math.abs(buffer[(write_pos + i) % BUFFER_SIZE]) * amp;\n"
        "            mgraphics.line_to(xs[i], yc);\n"
        "        }\n"
        "        mgraphics.line_to(xs[BUFFER_SIZE - 1], cy);\n"
        "        mgraphics.close_path();\n"
        "        mgraphics.fill();\n"
        "\n"
        "        // Negative lobe fill (below center)\n"
        "        mgraphics.set_source_rgba(" + fill_color + ");\n"
        "        mgraphics.move_to(xs[0], cy);\n"
        "        for (var i = 0; i < BUFFER_SIZE; i++) {\n"
        "            var yc = cy + Math.abs(buffer[(write_pos + i) % BUFFER_SIZE]) * amp;\n"
        "            mgraphics.line_to(xs[i], yc);\n"
        "        }\n"
        "        mgraphics.line_to(xs[BUFFER_SIZE - 1], cy);\n"
        "        mgraphics.close_path();\n"
        "        mgraphics.fill();\n"
        "\n"
        "        // Trace line: positive lobe\n"
        "        mgraphics.set_source_rgba(" + line_color + ");\n"
        "        mgraphics.set_line_width(1.5);\n"
        "        mgraphics.move_to(xs[0], cy - Math.abs(buffer[write_pos % BUFFER_SIZE]) * amp);\n"
        "        for (var i = 1; i < BUFFER_SIZE; i++) {\n"
        "            var yc = cy - Math.abs(buffer[(write_pos + i) % BUFFER_SIZE]) * amp;\n"
        "            mgraphics.line_to(xs[i], yc);\n"
        "        }\n"
        "        mgraphics.stroke();\n"
        "\n"
        "        // Crisp line: negative lobe\n"
        "        mgraphics.move_to(xs[0], cy + Math.abs(buffer[write_pos % BUFFER_SIZE]) * amp);\n"
        "        for (var i = 1; i < BUFFER_SIZE; i++) {\n"
        "            var yc = cy + Math.abs(buffer[(write_pos + i) % BUFFER_SIZE]) * amp;\n"
        "            mgraphics.line_to(xs[i], yc);\n"
        "        }\n"
        "        mgraphics.stroke();\n"
        "\n"
        "    } else if (display_mode == 1) {\n"
        "        // --- Mode 1: Filled (trace + fill to center) ---\n"
        "        mgraphics.set_source_rgba(" + fill_color + ");\n"
        "        mgraphics.move_to(xs[0], cy);\n"
        "        for (var i = 0; i < BUFFER_SIZE; i++) {\n"
        "            mgraphics.line_to(xs[i], ys[i]);\n"
        "        }\n"
        "        mgraphics.line_to(xs[BUFFER_SIZE - 1], cy);\n"
        "        mgraphics.close_path();\n"
        "        mgraphics.fill();\n"
        "\n"
        "        // Trace line\n"
        "        mgraphics.set_source_rgba(" + line_color + ");\n"
        "        mgraphics.set_line_width(1.5);\n"
        "        mgraphics.move_to(xs[0], ys[0]);\n"
        "        for (var i = 1; i < BUFFER_SIZE; i++) {\n"
        "            mgraphics.line_to(xs[i], ys[i]);\n"
        "        }\n"
        "        mgraphics.stroke();\n"
        "\n"
        "    } else {\n"
        "        // --- Mode 0: Line trace only ---\n"
        "        mgraphics.set_source_rgba(" + line_color + ");\n"
        "        mgraphics.set_line_width(1.5);\n"
        "        mgraphics.move_to(xs[0], ys[0]);\n"
        "        for (var i = 1; i < BUFFER_SIZE; i++) {\n"
        "            mgraphics.line_to(xs[i], ys[i]);\n"
        "        }\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // --- Border frame ---\n"
        "    mgraphics.set_source_rgba(" + grid_color + ");\n"
        "    mgraphics.set_line_width(1);\n"
        "    mgraphics.rectangle_rounded(0.5, 0.5, w - 1, h - 1, 3, 3);\n"
        "    mgraphics.stroke();\n"
        "}\n"
    )


def waveform_display_dsp(device, jsui_id, source_id, source_outlet=0,
                         num_samples=16, interval_ms=2, id_prefix="wave"):
    """Add a snapshot~/zl.group chain to capture waveform data for a jsui.

    Wires: source_id[source_outlet] -> snapshot~ -> zl.group -> jsui[0]

    The snapshot~ samples the audio signal at ``interval_ms`` millisecond
    intervals. zl.group accumulates ``num_samples`` values then outputs them
    as a single list, which the jsui waveform display ingests on inlet 0.

    Args:
        device: The Device instance to add objects to.
        jsui_id: ID of the target jsui object.
        source_id: ID of the audio source object.
        source_outlet: Outlet index on the source to tap (default 0).
        num_samples: Samples collected per frame (default 16).
        interval_ms: Snapshot poll interval in ms (default 2 = ~30 fps).
        id_prefix: Prefix for generated object IDs.

    Returns:
        Tuple of (snapshot_id, zlgroup_id) for the created objects.
    """
    snap_id = f"{id_prefix}_snap"
    zlg_id = f"{id_prefix}_zlg"

    # snapshot~ samples the signal at interval_ms milliseconds
    device.add_box(newobj(
        snap_id,
        f"snapshot~ {interval_ms}",
        numinlets=1,
        numoutlets=1,
        outlettype=[""],
        patching_rect=[30, 300, 80, 20],
    ))

    # zl.group collects num_samples floats then outputs as a list
    device.add_box(newobj(
        zlg_id,
        f"zl.group {num_samples}",
        numinlets=2,
        numoutlets=2,
        outlettype=["", ""],
        patching_rect=[30, 330, 90, 20],
    ))

    # Wire: audio source -> snapshot~
    device.add_line(source_id, source_outlet, snap_id, 0)
    # Wire: snapshot~ -> zl.group
    device.add_line(snap_id, 0, zlg_id, 0)
    # Wire: zl.group list output -> jsui inlet 0
    device.add_line(zlg_id, 0, jsui_id, 0)

    return (snap_id, zlg_id)
