"""XY pad control engine for jsui.

Generates JavaScript code that renders an interactive XY pad inside Max's jsui
object using mgraphics. Drag to set X/Y position, outputs normalized 0-1 values.

Inlets:
    0 -- X position (float 0-1)
    1 -- Y position (float 0-1)

Outlets:
    0 -- X value (float 0-1) on interaction
    1 -- Y value (float 0-1) on interaction
"""

XY_PAD_INLETS = 2
XY_PAD_OUTLETS = 2


def xy_pad_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
              dot_color="0.45, 0.75, 0.65, 1.0",
              grid_color="0.2, 0.2, 0.22, 0.5"):
    """Return JavaScript source for an XY pad control (Max jsui).

    Args:
        bg_color: Background color (RGBA string).
        dot_color: Crosshair and dot color (RGBA string).
        grid_color: Grid line color (RGBA string).

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    # Parse dot_color to get RGB for crosshair (with reduced alpha)
    dc = [s.strip() for s in dot_color.split(",")]
    crosshair_color = ", ".join(dc[:3] + ["0.4"])

    return (
        "// XY Pad Control — generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 2;\n"
        "\n"
        "// --- State ---\n"
        "var pos_x = 0.5;\n"
        "var pos_y = 0.5;\n"
        "var is_dragging = 0;\n"
        "\n"
        "// --- Constants ---\n"
        "var DOT_RADIUS = 6;\n"
        "var CROSSHAIR_ALPHA = 0.4;\n"
        "var GRID_DIVISIONS = 4;\n"
        "var PADDING = 2;\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_float(v) {\n"
        "    if (inlet === 0) {\n"
        "        pos_x = Math.max(0, Math.min(1, v));\n"
        "    } else {\n"
        "        pos_y = Math.max(0, Math.min(1, v));\n"
        "    }\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "function msg_int(v) {\n"
        "    msg_float(v);\n"
        "}\n"
        "\n"
        "// --- Mouse handling ---\n"
        "function onclick(x, y, but, cmd, shift, capslock, option, ctrl) {\n"
        "    is_dragging = 1;\n"
        "    update_position(x, y);\n"
        "}\n"
        "\n"
        "function ondrag(x, y, but, cmd, shift, capslock, option, ctrl) {\n"
        "    if (but === 0) {\n"
        "        is_dragging = 0;\n"
        "        return;\n"
        "    }\n"
        "    update_position(x, y);\n"
        "}\n"
        "\n"
        "function update_position(mx, my) {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    pos_x = Math.max(0, Math.min(1, (mx - PADDING) / (w - 2 * PADDING)));\n"
        "    pos_y = Math.max(0, Math.min(1, (my - PADDING) / (h - 2 * PADDING)));\n"
        "    outlet(0, pos_x);\n"
        "    outlet(1, pos_y);\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "// --- Drawing ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "\n"
        "    // Background\n"
        f"    mgraphics.set_source_rgba({bg_color});\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "\n"
        "    // Grid lines\n"
        f"    mgraphics.set_source_rgba({grid_color});\n"
        "    mgraphics.set_line_width(0.5);\n"
        "    var i;\n"
        "    for (i = 1; i < GRID_DIVISIONS; i++) {\n"
        "        var gx = PADDING + (i / GRID_DIVISIONS) * area_w;\n"
        "        mgraphics.move_to(gx, PADDING);\n"
        "        mgraphics.line_to(gx, PADDING + area_h);\n"
        "        mgraphics.stroke();\n"
        "        var gy = PADDING + (i / GRID_DIVISIONS) * area_h;\n"
        "        mgraphics.move_to(PADDING, gy);\n"
        "        mgraphics.line_to(PADDING + area_w, gy);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // Crosshair at current position\n"
        "    var cx = PADDING + pos_x * area_w;\n"
        "    var cy = PADDING + pos_y * area_h;\n"
        "\n"
        f"    mgraphics.set_source_rgba({crosshair_color});\n"
        "    mgraphics.set_line_width(0.5);\n"
        "    mgraphics.move_to(cx, PADDING);\n"
        "    mgraphics.line_to(cx, PADDING + area_h);\n"
        "    mgraphics.stroke();\n"
        "    mgraphics.move_to(PADDING, cy);\n"
        "    mgraphics.line_to(PADDING + area_w, cy);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Dot\n"
        f"    mgraphics.set_source_rgba({dot_color});\n"
        "    mgraphics.arc(cx, cy, DOT_RADIUS, 0, Math.PI * 2);\n"
        "    mgraphics.fill();\n"
        "}\n"
    )
