"""XY pad with fading motion trail engine for jsui.

Generates JavaScript code that renders an XY pad with a 32-point circular
buffer trail that fades from accent color (newest) to transparent (oldest).

Inlets:
    0 -- X position (float 0-1)
    1 -- Y position (float 0-1)
"""

XY_TRAIL_DISPLAY_INLETS = 2
XY_TRAIL_DISPLAY_OUTLETS = 0


def xy_trail_display_js(*, bg_color="0.07, 0.07, 0.08, 1.0",
                        accent_color="0.45, 0.75, 0.65, 1.0",
                        grid_color="0.2, 0.2, 0.22, 0.3"):
    """Return JavaScript source for an XY trail display (Max jsui).

    Draws an XY pad with subtle center grid lines. As X/Y values come in,
    positions are stored in a 32-point circular buffer. The trail is drawn
    with fading opacity -- newest point uses the full accent color, oldest
    fades to transparent. The current position gets a bright filled circle.

    All color arguments are RGBA strings, e.g. ``"0.45, 0.75, 0.65, 1.0"``.

    Args:
        bg_color: Background color.
        accent_color: Trail and current position color (RGBA).
        grid_color: Center crosshair grid color.

    Returns:
        JavaScript source code string (ES5 compatible).
    """
    ac = [s.strip() for s in accent_color.split(",")]
    accent_rgb = ac[0] + ", " + ac[1] + ", " + ac[2]

    return (
        "// XY Trail Display - generated by m4l-builder\n"
        "// ES5 JavaScript for Max jsui mgraphics\n"
        "\n"
        "mgraphics.init();\n"
        "mgraphics.relative_coords = 0;\n"
        "mgraphics.autofill = 0;\n"
        "\n"
        "inlets = 2;\n"
        "outlets = 0;\n"
        "\n"
        "// --- State ---\n"
        "var pos_x = 0.5;\n"
        "var pos_y = 0.5;\n"
        "var TRAIL_SIZE = 32;\n"
        "var trail_x = [];\n"
        "var trail_y = [];\n"
        "var trail_head = 0;\n"
        "var trail_count = 0;\n"
        "\n"
        "// --- Constants ---\n"
        "var PADDING = 4;\n"
        "var DOT_RADIUS = 5;\n"
        "\n"
        "// Initialize trail buffer\n"
        "for (var _i = 0; _i < TRAIL_SIZE; _i++) {\n"
        "    trail_x.push(0.5);\n"
        "    trail_y.push(0.5);\n"
        "}\n"
        "\n"
        "// --- Input handlers ---\n"
        "function msg_float(v) {\n"
        "    if (inlet === 0) {\n"
        "        pos_x = Math.max(0, Math.min(1, v));\n"
        "    } else {\n"
        "        pos_y = Math.max(0, Math.min(1, v));\n"
        "    }\n"
        "    // Push new position into the circular buffer\n"
        "    trail_x[trail_head] = pos_x;\n"
        "    trail_y[trail_head] = pos_y;\n"
        "    trail_head = (trail_head + 1) % TRAIL_SIZE;\n"
        "    if (trail_count < TRAIL_SIZE) trail_count++;\n"
        "    mgraphics.redraw();\n"
        "}\n"
        "\n"
        "function msg_int(v) {\n"
        "    msg_float(v);\n"
        "}\n"
        "\n"
        "// --- Paint ---\n"
        "function paint() {\n"
        "    var w = mgraphics.size[0];\n"
        "    var h = mgraphics.size[1];\n"
        "    var area_x = PADDING;\n"
        "    var area_y = PADDING;\n"
        "    var area_w = w - 2 * PADDING;\n"
        "    var area_h = h - 2 * PADDING;\n"
        "\n"
        "    // Background\n"
        "    mgraphics.set_source_rgba(" + bg_color + ");\n"
        "    mgraphics.rectangle(0, 0, w, h);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Center grid lines\n"
        "    mgraphics.set_source_rgba(" + grid_color + ");\n"
        "    mgraphics.set_line_width(1);\n"
        "    var mid_x = area_x + area_w * 0.5;\n"
        "    var mid_y = area_y + area_h * 0.5;\n"
        "    mgraphics.move_to(Math.round(mid_x) + 0.5, area_y);\n"
        "    mgraphics.line_to(Math.round(mid_x) + 0.5, area_y + area_h);\n"
        "    mgraphics.stroke();\n"
        "    mgraphics.move_to(area_x, Math.round(mid_y) + 0.5);\n"
        "    mgraphics.line_to(area_x + area_w, Math.round(mid_y) + 0.5);\n"
        "    mgraphics.stroke();\n"
        "\n"
        "    // Draw trail (oldest to newest)\n"
        "    if (trail_count < 2) {\n"
        "        // Not enough points for a trail, just draw the dot\n"
        "        var cx = area_x + pos_x * area_w;\n"
        "        var cy = area_y + pos_y * area_h;\n"
        "        mgraphics.set_source_rgba(" + accent_color + ");\n"
        "        mgraphics.arc(cx, cy, DOT_RADIUS, 0, Math.PI * 2);\n"
        "        mgraphics.fill();\n"
        "        return;\n"
        "    }\n"
        "\n"
        "    // Walk from oldest to newest\n"
        "    var n = trail_count;\n"
        "    for (var i = 0; i < n - 1; i++) {\n"
        "        // oldest = 0, newest = n-1\n"
        "        var idx0 = (trail_head - n + i + TRAIL_SIZE) % TRAIL_SIZE;\n"
        "        var idx1 = (trail_head - n + i + 1 + TRAIL_SIZE) % TRAIL_SIZE;\n"
        "        var alpha = (i + 1) / n;\n"
        "        var x0 = area_x + trail_x[idx0] * area_w;\n"
        "        var y0 = area_y + trail_y[idx0] * area_h;\n"
        "        var x1 = area_x + trail_x[idx1] * area_w;\n"
        "        var y1 = area_y + trail_y[idx1] * area_h;\n"
        "\n"
        "        mgraphics.set_source_rgba(" + accent_rgb + ", alpha * 0.7);\n"
        "        mgraphics.set_line_width(1.5 + alpha * 1.5);\n"
        "        mgraphics.move_to(x0, y0);\n"
        "        mgraphics.line_to(x1, y1);\n"
        "        mgraphics.stroke();\n"
        "    }\n"
        "\n"
        "    // Trail dots (fading)\n"
        "    for (var i = 0; i < n; i++) {\n"
        "        var idx = (trail_head - n + i + TRAIL_SIZE) % TRAIL_SIZE;\n"
        "        var alpha = (i + 1) / n;\n"
        "        var tx = area_x + trail_x[idx] * area_w;\n"
        "        var ty = area_y + trail_y[idx] * area_h;\n"
        "        var r = 1.5 + alpha * 1.5;\n"
        "        mgraphics.set_source_rgba(" + accent_rgb + ", alpha * 0.5);\n"
        "        mgraphics.arc(tx, ty, r, 0, Math.PI * 2);\n"
        "        mgraphics.fill();\n"
        "    }\n"
        "\n"
        "    // Current position (bright filled circle)\n"
        "    var cur_x = area_x + pos_x * area_w;\n"
        "    var cur_y = area_y + pos_y * area_h;\n"
        "\n"
        "    // Glow\n"
        "    mgraphics.set_source_rgba(" + accent_rgb + ", 0.15);\n"
        "    mgraphics.arc(cur_x, cur_y, DOT_RADIUS * 2.5, 0, Math.PI * 2);\n"
        "    mgraphics.fill();\n"
        "\n"
        "    // Bright dot\n"
        "    mgraphics.set_source_rgba(" + accent_color + ");\n"
        "    mgraphics.arc(cur_x, cur_y, DOT_RADIUS, 0, Math.PI * 2);\n"
        "    mgraphics.fill();\n"
        "}\n"
    )
