"""Generate docs/palette.md — the one-page index of every reusable kit idea.

The kit IS the reusable library; a device is just a thin script that composes
kit parts. This tool introspects the kit and emits a single browsable palette so
you (and Claude) build NEW devices from proven parts instead of re-deriving
cheap one-offs. Regenerate after adding engines/snippets:

    uv run python tools/build_palette.py
"""

from __future__ import annotations

import ast
import importlib
import inspect
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "m4l_builder"


def _first_line(doc: str | None) -> str:
    """First SENTENCE of the docstring — join the opening paragraph's wrapped
    lines, then cut at the first sentence end (so two-line summaries aren't
    truncated mid-phrase)."""
    if not doc:
        return ""
    para: list[str] = []
    for ln in doc.strip().splitlines():
        s = ln.strip()
        if not s:
            break
        para.append(s)
    text = " ".join(para)
    for i in range(len(text) - 1):
        if text[i] == "." and text[i + 1] == " ":
            return text[:i]
    return text.rstrip(".")


def _module_doc(path: pathlib.Path) -> str:
    try:
        return _first_line(ast.get_docstring(ast.parse(path.read_text())))
    except Exception:
        return ""


def _public_funcs(modname: str) -> list[tuple[str, str]]:
    """(name, one-liner) for functions DEFINED in the module, in source order."""
    mod = importlib.import_module(modname)
    names = getattr(mod, "__all__", None)
    out = []
    members = {n: o for n, o in inspect.getmembers(mod, inspect.isfunction)
               if o.__module__ == modname}
    ordered = names if names else sorted(members)
    for n in ordered:
        obj = members.get(n)
        if obj is None or n.startswith("_"):
            continue
        out.append((n, _first_line(inspect.getdoc(obj))))
    return out


def _fn_table(title: str, blurb: str, modname: str) -> list[str]:
    rows = _public_funcs(modname)
    lines = [f"### {title}", "", blurb, "",
             f"`m4l_builder.{modname.split('.')[-1]}` — {len(rows)} functions", ""]
    for name, one in rows:
        lines.append(f"- **`{name}`** — {one}" if one else f"- **`{name}`**")
    lines.append("")
    return lines


def _dir_table(title: str, blurb: str, subdir: str) -> list[str]:
    folder = SRC / subdir
    mods = sorted(p for p in folder.glob("*.py") if not p.name.startswith("_"))
    lines = [f"### {title}", "", blurb, "",
             f"`m4l_builder.{subdir}/` — {len(mods)} modules", ""]
    for p in mods:
        doc = _module_doc(p)
        lines.append(f"- **`{p.stem}`** — {doc}" if doc else f"- **`{p.stem}`**")
    lines.append("")
    return lines


def main() -> int:
    L: list[str] = [
        "# Kit Palette — reusable ideas on deck", "",
        "_Auto-generated by `tools/build_palette.py`. The kit is the reusable"
        " library; compose devices from these parts. Every entry is a real,"
        " tested building block — no device required._", "",
        "## DSP — the sound", "",
    ]
    L += _fn_table(
        "Character / coloration algorithms",
        "The \"vibe\" algorithms — harvested from shipping devices, each proven"
        " in Live. Self-contained: emit their own state, namespaced by `prefix`,"
        " hoist decls to the top.",
        "m4l_builder.gen_character")
    L += _fn_table(
        "Neutral GenExpr primitives",
        "Clean building blocks — filters, dynamics gain-computers, saturators,"
        " M/S, loudness, oversampling, fractional delay reads.",
        "m4l_builder.gen_snippets")
    L += _fn_table(
        "Stateful GenExpr blocks",
        "Bigger stateful kernels — the viz bus, the LFO cluster, click-free"
        " variable delay.",
        "m4l_builder.gen_stateful")
    L += _dir_table(
        "DSP object emitters",
        "Higher-level DSP that emits Max objects/patchers (not just GenExpr):"
        " delay lines, dynamics, filters, spectral, synthesis, routing.",
        "dsp")

    L += ["## UI — the look", ""]
    L += _dir_table(
        "Display / graph engines",
        "The visual heroes — EQ curves, meters, spectra, waveforms, XY pads,"
        " goniometers, histories. Each returns jsui/v8ui draw code.",
        "engines")

    L += ["## Composition — the frame", "",
          "- **`Surface`** (`surface.py`) — the faceplate layout engine: heroes,"
          " section cards, derived width, the brand-accent bus.",
          "- **`recipes.py`** — composed UI blocks (dial-value cells, settings"
          " sidebar, chip rows, viewport, mapper slots).",
          "- **`theme.py` / `native_sizes.py`** — GRAPHITE/ACCENTS palettes and"
          " the corpus-derived sizing tokens.",
          "- **`engines/lom_mapper.py`** — the Live Object Model mapping kit"
          " (Remote/Mod modes, retargetable param sinks).", ""]

    out = ROOT / "docs" / "palette.md"
    out.write_text("\n".join(L) + "\n")
    n_funcs = sum(1 for line in L if line.startswith("- **`"))
    print(f"palette.md: {n_funcs} entries -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
